<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Introduction to Data – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch02-study-design.html" rel="next">
<link href="../parts/part-i.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1978b12ac2f6ca4f939a81acefe95ae9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/ch01-intro-to-data.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statbench-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatBench Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-case-stents" id="toc-sec-case-stents" class="nav-link active" data-scroll-target="#sec-case-stents"><span class="header-section-number">1.1</span> Case study: Using stents to prevent strokes</a>
  <ul class="collapse">
  <li><a href="#examining-the-data" id="toc-examining-the-data" class="nav-link" data-scroll-target="#examining-the-data"><span class="header-section-number">1.1.1</span> Examining the data</a></li>
  <li><a href="#drawing-conclusions-from-the-data" id="toc-drawing-conclusions-from-the-data" class="nav-link" data-scroll-target="#drawing-conclusions-from-the-data"><span class="header-section-number">1.1.2</span> Drawing conclusions from the data</a></li>
  </ul></li>
  <li><a href="#sec-data-basics" id="toc-sec-data-basics" class="nav-link" data-scroll-target="#sec-data-basics"><span class="header-section-number">1.2</span> Data basics</a>
  <ul class="collapse">
  <li><a href="#sec-observations-variables" id="toc-sec-observations-variables" class="nav-link" data-scroll-target="#sec-observations-variables"><span class="header-section-number">1.2.1</span> Observations, variables, and data matrices</a></li>
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data"><span class="header-section-number">1.2.2</span> Tidy data</a></li>
  <li><a href="#a-larger-dataset-us-counties" id="toc-a-larger-dataset-us-counties" class="nav-link" data-scroll-target="#a-larger-dataset-us-counties"><span class="header-section-number">1.2.3</span> A larger dataset: US counties</a></li>
  </ul></li>
  <li><a href="#sec-variable-types" id="toc-sec-variable-types" class="nav-link" data-scroll-target="#sec-variable-types"><span class="header-section-number">1.3</span> Types of variables</a>
  <ul class="collapse">
  <li><a href="#numerical-variables" id="toc-numerical-variables" class="nav-link" data-scroll-target="#numerical-variables"><span class="header-section-number">1.3.1</span> Numerical variables</a></li>
  <li><a href="#categorical-variables" id="toc-categorical-variables" class="nav-link" data-scroll-target="#categorical-variables"><span class="header-section-number">1.3.2</span> Categorical variables</a></li>
  <li><a href="#variable-type-hierarchy" id="toc-variable-type-hierarchy" class="nav-link" data-scroll-target="#variable-type-hierarchy"><span class="header-section-number">1.3.3</span> Variable type hierarchy</a></li>
  </ul></li>
  <li><a href="#sec-variable-relationships" id="toc-sec-variable-relationships" class="nav-link" data-scroll-target="#sec-variable-relationships"><span class="header-section-number">1.4</span> Relationships between variables</a>
  <ul class="collapse">
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots"><span class="header-section-number">1.4.1</span> Scatterplots</a></li>
  <li><a href="#associated-and-independent-variables" id="toc-associated-and-independent-variables" class="nav-link" data-scroll-target="#associated-and-independent-variables"><span class="header-section-number">1.4.2</span> Associated and independent variables</a></li>
  </ul></li>
  <li><a href="#sec-explanatory-response" id="toc-sec-explanatory-response" class="nav-link" data-scroll-target="#sec-explanatory-response"><span class="header-section-number">1.5</span> Explanatory and response variables</a></li>
  <li><a href="#sec-obs-vs-exp" id="toc-sec-obs-vs-exp" class="nav-link" data-scroll-target="#sec-obs-vs-exp"><span class="header-section-number">1.6</span> Observational studies and experiments</a>
  <ul class="collapse">
  <li><a href="#experiments" id="toc-experiments" class="nav-link" data-scroll-target="#experiments"><span class="header-section-number">1.6.1</span> Experiments</a></li>
  <li><a href="#observational-studies" id="toc-observational-studies" class="nav-link" data-scroll-target="#observational-studies"><span class="header-section-number">1.6.2</span> Observational studies</a></li>
  <li><a href="#the-key-distinction-association-vs.-causation" id="toc-the-key-distinction-association-vs.-causation" class="nav-link" data-scroll-target="#the-key-distinction-association-vs.-causation"><span class="header-section-number">1.6.3</span> The key distinction: association vs.&nbsp;causation</a></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together"><span class="header-section-number">1.6.4</span> Putting it all together</a></li>
  </ul></li>
  <li><a href="#sec-ch01-review" id="toc-sec-ch01-review" class="nav-link" data-scroll-target="#sec-ch01-review"><span class="header-section-number">1.7</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">1.7.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">1.7.2</span> Key terms</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">1.8</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/ch01-intro-to-data.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>Scientists seek to answer questions using rigorous methods and careful observations. These observations — collected from the likes of field notes, surveys, and experiments — form the backbone of a statistical investigation and are called <strong>data</strong>. Statistics is the study of how best to collect, analyze, and draw conclusions from data. In this first chapter, we focus on both the properties of data and on the collection of data. We will introduce the building blocks of statistical thinking: observations, variables, data frames, and the types of questions that statistics can help us answer.</p>
</div>
<section id="sec-case-stents" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-case-stents"><span class="header-section-number">1.1</span> Case study: Using stents to prevent strokes</h2>
<p>In this section we introduce a classic challenge in statistics: evaluating the efficacy of a medical treatment. The terms and ideas introduced here will be revisited throughout the course. For now, the goal is simply to get a sense of the role statistics can play in practice.</p>
<p>A stent is a small mesh tube that is placed inside a narrow or weak artery to assist in patient recovery after cardiac events and reduce the risk of an additional heart attack or death. Many doctors have hoped that there would be similar benefits for patients at risk of stroke. This leads to the principal question the researchers hoped to answer:</p>
<blockquote class="blockquote">
<p>Does the use of stents reduce the risk of stroke?</p>
</blockquote>
<p>The researchers who asked this question conducted an experiment with 451 at-risk patients.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Each volunteer patient was randomly assigned to one of two groups:</p>
<ul>
<li><strong>Treatment group.</strong> Patients in the treatment group received a stent and medical management. The medical management included medications, management of risk factors, and help in lifestyle modification.</li>
<li><strong>Control group.</strong> Patients in the control group received the same medical management as the treatment group, but they did not receive stents.</li>
</ul>
<p>Researchers randomly assigned 224 patients to the treatment group and 227 to the control group. In this study, the control group provides a reference point against which we can measure the medical impact of stents in the treatment group.</p>
<section id="examining-the-data" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="examining-the-data"><span class="header-section-number">1.1.1</span> Examining the data</h3>
<p>Researchers studied the effect of stents at two time points: 30 days after enrollment and 365 days after enrollment. Patient outcomes were recorded as “stroke” or “no event,” representing whether the patient had a stroke during that time period.</p>
<p>It would be difficult to answer the research question by looking at individual patient records one at a time. Instead, we organize the results into a summary table that lets us quickly compare the two groups.</p>
<div id="tbl-stent-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stent-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.1: Descriptive statistics for the stent study.
</figcaption>
<div aria-describedby="tbl-stent-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">30 days: Stroke</th>
<th style="text-align: right;">30 days: No event</th>
<th style="text-align: right;">365 days: Stroke</th>
<th style="text-align: right;">365 days: No event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">191</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">179</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">199</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">378</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="guidedpractice">
<p>Of the 224 patients in the treatment group, 45 had a stroke by the end of the first year. Using these two numbers, compute the proportion of patients in the treatment group who had a stroke by the end of their first year. (Note: answers to all Guided Practice exercises are provided in footnotes!)</p>
<details>
<summary>
Show answer
</summary>
The proportion of the 224 patients who had a stroke within 365 days: <span class="math inline">\(45/224 = 0.20 = 20\%\)</span>.
</details>
</div>
</section>
<section id="drawing-conclusions-from-the-data" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="drawing-conclusions-from-the-data"><span class="header-section-number">1.1.2</span> Drawing conclusions from the data</h3>
<p>We can compute <strong>summary statistics</strong> from <a href="#tbl-stent-summary" class="quarto-xref">Table&nbsp;<span>1.1</span></a> to give us a better idea of how the impact of the stent treatment differed between the two groups.</p>
<div class="definition">
<p>A <strong>summary statistic</strong> is a single number that summarizes data from a sample. Summary statistics condense a large amount of information into a form that is easy to digest and compare.</p>
</div>
<p>For instance, the primary results of the study after one year could be described by two summary statistics: the proportion of people who had a stroke in the treatment and control groups.</p>
<ul>
<li>Proportion who had a stroke in the treatment (stent) group: <span class="math inline">\(45/224 = 0.20 = 20\%\)</span>.</li>
<li>Proportion who had a stroke in the control group: <span class="math inline">\(28/227 = 0.12 = 12\%\)</span>.</li>
</ul>
<p>These two summary statistics are useful in looking for differences between the groups, and we are in for a surprise: an additional 8% of patients in the treatment group had a stroke! This is important for two reasons. First, it is contrary to what doctors expected, which was that stents would <em>reduce</em> the rate of strokes. Second, it leads to a statistical question: do the data show a “real” difference between the groups?</p>
<p>This second question is subtle. Suppose you flip a coin 100 times. While the chance a coin lands heads in any given coin flip is 50%, we probably will not observe exactly 50 heads. This type of variation is part of almost any type of data generating process. It is possible that the 8% difference in the stent study is due to this natural variation. However, the larger the difference we observe (for a particular sample size), the less believable it is that the difference is due to chance. So what we are really asking is the following: if in fact stents have no effect, how unlikely is it that we would observe such a large difference?</p>
<p>While we do not yet have the statistical tools to fully address this question on our own, we can state the conclusion of the published analysis: there was compelling evidence of harm by stents in this study of stroke patients.</p>
<div class="caution">
<p><strong>Be careful about overgeneralizing.</strong> Do not generalize the results of this study to all patients and all stents. This study looked at patients with very specific characteristics who volunteered to be part of the study and who may not be representative of all stroke patients. In addition, there are many types of stents, and this study considered only the self-expanding Wingspan stent (Boston Scientific). However, the study does leave us with an important lesson: we should keep our eyes open for surprises.</p>
</div>
<div class="guidedpractice">
<p>Does this study prove that stents <em>cause</em> strokes? What features of the study design might strengthen or weaken this conclusion?</p>
<details>
<summary>
Show answer
</summary>
Because patients were <em>randomly assigned</em> to treatment and control groups, this is a randomized experiment. Random assignment helps ensure the groups are similar in all respects except the treatment itself. This strengthens the case for a causal conclusion. However, we should still ask: could the difference (20% vs.&nbsp;12%) have arisen by chance alone? We will develop tools to answer this question rigorously later in the course.
</details>
</div>
<div class="original">
<p>This case study highlights a key principle that will guide much of our work in this course: <strong>a single study’s results can be surprising, and statistics gives us the tools to evaluate whether an observed result is real or could be due to random chance</strong>. We will return to this idea again and again as we develop the tools of statistical inference.</p>
</div>
</section>
</section>
<section id="sec-data-basics" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-data-basics"><span class="header-section-number">1.2</span> Data basics</h2>
<p>Effective presentation and description of data is a first step in most analyses. This section introduces one structure for organizing data as well as some terminology that will be used throughout the course.</p>
<section id="sec-observations-variables" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="sec-observations-variables"><span class="header-section-number">1.2.1</span> Observations, variables, and data matrices</h3>
<div class="definition">
<p>An <strong>observation</strong> (also called a <strong>case</strong> or <strong>unit of observation</strong>) is a single entity in a dataset — one person, one county, one transaction. A <strong>variable</strong> is a characteristic that is measured or recorded for each observation. A <strong>data frame</strong> (or <strong>data matrix</strong>) organizes observations as rows and variables as columns. Each cell holds a single value.</p>
</div>
<p>Consider data for 50 randomly sampled loans offered through a peer-to-peer lending company. Each row in the table represents a single loan — that is the observation, or unit of observation. The columns represent characteristics of each loan, and each column is a variable. For example, the first row might represent a loan of $22,000 with an interest rate of 10.90%, where the borrower is based in New Jersey (NJ) and has an income of $59,000.</p>
<div id="tbl-loan50-df" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan50-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.2: Six observations from a loan dataset.
</figcaption>
<div aria-describedby="tbl-loan50-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: right;">loan_amount</th>
<th style="text-align: right;">interest_rate</th>
<th style="text-align: right;">term</th>
<th style="text-align: center;">grade</th>
<th style="text-align: center;">state</th>
<th style="text-align: right;">total_income</th>
<th style="text-align: center;">homeownership</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">22,000</td>
<td style="text-align: right;">10.90</td>
<td style="text-align: right;">60</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">NJ</td>
<td style="text-align: right;">59,000</td>
<td style="text-align: center;">rent</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">6,000</td>
<td style="text-align: right;">9.92</td>
<td style="text-align: right;">36</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">CA</td>
<td style="text-align: right;">60,000</td>
<td style="text-align: center;">rent</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">25,000</td>
<td style="text-align: right;">26.30</td>
<td style="text-align: right;">36</td>
<td style="text-align: center;">E</td>
<td style="text-align: center;">SC</td>
<td style="text-align: right;">75,000</td>
<td style="text-align: center;">mortgage</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">6,000</td>
<td style="text-align: right;">9.92</td>
<td style="text-align: right;">36</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">CA</td>
<td style="text-align: right;">75,000</td>
<td style="text-align: center;">rent</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">25,000</td>
<td style="text-align: right;">9.43</td>
<td style="text-align: right;">60</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">OH</td>
<td style="text-align: right;">254,000</td>
<td style="text-align: center;">mortgage</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6,400</td>
<td style="text-align: right;">9.92</td>
<td style="text-align: right;">36</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">IN</td>
<td style="text-align: right;">67,000</td>
<td style="text-align: center;">mortgage</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In practice, it is especially important to ask clarifying questions to ensure important aspects of the data are understood. For instance, it is always important to be sure we know what each variable means and its units of measurement. <a href="#tbl-loan50-variables" class="quarto-xref">Table&nbsp;<span>1.3</span></a> describes each variable in the loan dataset.</p>
<div id="tbl-loan50-variables" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan50-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.3: Variables and their descriptions for the loan dataset.
</figcaption>
<div aria-describedby="tbl-loan50-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">loan_amount</td>
<td style="text-align: left;">Amount of the loan received, in US dollars.</td>
</tr>
<tr class="even">
<td style="text-align: left;">interest_rate</td>
<td style="text-align: left;">Interest rate on the loan, in an annual percentage.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">term</td>
<td style="text-align: left;">The length of the loan, which is always set as a whole number of months.</td>
</tr>
<tr class="even">
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Loan grade, which takes values A through G and represents the quality of the loan and its likelihood of being repaid.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">state</td>
<td style="text-align: left;">US state where the borrower resides.</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_income</td>
<td style="text-align: left;">Borrower’s total income, including any second income, in US dollars.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">homeownership</td>
<td style="text-align: left;">Indicates whether the person owns, owns but has a mortgage, or rents.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="guidedpractice">
<p>What is the grade of the first loan in <a href="#tbl-loan50-df" class="quarto-xref">Table&nbsp;<span>1.2</span></a>? And what is the homeownership status of the borrower for that first loan?</p>
<details>
<summary>
Show answer
</summary>
The loan’s grade is B, and the borrower rents their residence.
</details>
</div>
</section>
<section id="tidy-data" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="tidy-data"><span class="header-section-number">1.2.2</span> Tidy data</h3>
<p>A data frame where each row is a unique case (observational unit), each column is a variable, and each cell is a single value is commonly referred to as <strong>tidy data</strong>.</p>
<div class="definition">
<p><strong>Tidy data</strong> is a standard way of mapping the meaning of a dataset to its structure. A dataset is tidy when:</p>
<ol type="1">
<li>Each row represents a single observation.</li>
<li>Each column represents a single variable.</li>
<li>Each cell contains a single value.</li>
</ol>
</div>
<p>When recording data, use a tidy data frame unless you have a very good reason to use a different structure. This structure allows new cases to be added as rows or new variables as new columns and facilitates visualization, summarization, and other statistical analyses.</p>
<div class="guidedpractice">
<p>The grades for assignments, quizzes, and exams in a course are often recorded in a gradebook that takes the form of a data frame. How might you organize a course’s grade data using a data frame? Describe the observational units and variables.</p>
<details>
<summary>
Show answer
</summary>
There are multiple strategies that can be followed. One common strategy is to have each student represented by a row, and then add a column for each assignment, quiz, or exam. Under this setup, it is easy to review a single line to understand the grade history of a student. There should also be columns to include student information, such as one column to list student names.
</details>
</div>
</section>
<section id="a-larger-dataset-us-counties" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="a-larger-dataset-us-counties"><span class="header-section-number">1.2.3</span> A larger dataset: US counties</h3>
<p>We consider data for 3,142 counties in the United States, which includes the name of each county, the state where it resides, its population in 2017, the population change from 2010 to 2017, poverty rate, and several additional characteristics.</p>
<div class="guidedpractice">
<p>How might these data be organized in a data frame? What are the observations and variables?</p>
<details>
<summary>
Show answer
</summary>
Each county may be viewed as a case, and there are multiple pieces of information recorded for each case. A table with 3,142 rows and 14 columns could hold these data, where each row represents a county and each column represents a particular piece of information.
</details>
</div>
<div id="tbl-county-df" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-county-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.4: Six observations and six variables from a US county dataset.
</figcaption>
<div aria-describedby="tbl-county-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: left;">state</th>
<th style="text-align: right;">pop2017</th>
<th style="text-align: right;">pop_change</th>
<th style="text-align: right;">unemployment_rate</th>
<th style="text-align: left;">median_edu</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Autauga County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">55,504</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: left;">some_college</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baldwin County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">212,628</td>
<td style="text-align: right;">9.19</td>
<td style="text-align: right;">3.83</td>
<td style="text-align: left;">some_college</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Barbour County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">25,270</td>
<td style="text-align: right;">-6.22</td>
<td style="text-align: right;">6.44</td>
<td style="text-align: left;">hs_diploma</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bibb County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">22,668</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">4.39</td>
<td style="text-align: left;">hs_diploma</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blount County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">58,013</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">4.02</td>
<td style="text-align: left;">hs_diploma</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bullock County</td>
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">10,309</td>
<td style="text-align: right;">-2.28</td>
<td style="text-align: right;">7.72</td>
<td style="text-align: left;">hs_diploma</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-county-variables" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-county-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.5: Variables and their descriptions for the county dataset.
</figcaption>
<div aria-describedby="tbl-county-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">name</td>
<td style="text-align: left;">Name of county.</td>
</tr>
<tr class="even">
<td style="text-align: left;">state</td>
<td style="text-align: left;">Name of state.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pop2000</td>
<td style="text-align: left;">Population in 2000.</td>
</tr>
<tr class="even">
<td style="text-align: left;">pop2010</td>
<td style="text-align: left;">Population in 2010.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pop2017</td>
<td style="text-align: left;">Population in 2017.</td>
</tr>
<tr class="even">
<td style="text-align: left;">pop_change</td>
<td style="text-align: left;">Population change from 2010 to 2017 (in percent).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">poverty</td>
<td style="text-align: left;">Percent of population in poverty in 2017.</td>
</tr>
<tr class="even">
<td style="text-align: left;">homeownership</td>
<td style="text-align: left;">Homeownership rate, 2006–2010.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">multi_unit</td>
<td style="text-align: left;">Percent of housing units that are in multi-unit structures, 2006–2010.</td>
</tr>
<tr class="even">
<td style="text-align: left;">unemployment_rate</td>
<td style="text-align: left;">Unemployment rate in 2017.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">metro</td>
<td style="text-align: left;">Whether the county contains a metropolitan area (yes or no).</td>
</tr>
<tr class="even">
<td style="text-align: left;">median_edu</td>
<td style="text-align: left;">Median education level (2013–2017): below_hs, hs_diploma, some_college, or bachelors.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">per_capita_income</td>
<td style="text-align: left;">Per capita (per person) income (2013–2017).</td>
</tr>
<tr class="even">
<td style="text-align: left;">median_hh_income</td>
<td style="text-align: left;">Median household income.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">smoking_ban</td>
<td style="text-align: left;">Type of county-level smoking ban in place in 2010: none, partial, or comprehensive.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-variable-types" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-variable-types"><span class="header-section-number">1.3</span> Types of variables</h2>
<p>Examine the variables <code>unemployment_rate</code>, <code>pop2017</code>, <code>state</code>, and <code>median_edu</code> in the county dataset. Each of these variables is inherently different from the other three, yet some share certain characteristics. Understanding these distinctions is fundamental to choosing the right analysis tools.</p>
<section id="numerical-variables" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="numerical-variables"><span class="header-section-number">1.3.1</span> Numerical variables</h3>
<div class="definition">
<p>A <strong>numerical variable</strong> (also called a <strong>quantitative variable</strong>) takes on values where arithmetic operations like adding, subtracting, or averaging make sense.</p>
</div>
<p>Consider <code>unemployment_rate</code>, which can take a wide range of numerical values, and it is sensible to add, subtract, or take averages with those values. On the other hand, we would not classify a variable reporting telephone area codes as numerical since the average, sum, and difference of area codes does not have any clear meaning.</p>
<p>Numerical variables can be further subdivided:</p>
<ul>
<li><strong>Continuous variables</strong> can take any value within a range, including decimals. The <code>unemployment_rate</code> is continuous — it could be 3.86%, 4.127%, or any value in between.</li>
<li><strong>Discrete variables</strong> can only take counting values (typically whole numbers: 0, 1, 2, …). The variable <code>pop2017</code> (population count) is discrete — you cannot have 55,504.7 people.</li>
</ul>
<div class="important">
<p><strong>The key test for numerical vs.&nbsp;categorical.</strong> Ask yourself: does it make sense to compute the average of this variable? If you can meaningfully average the values, it is numerical. If averaging does not make sense (as with zip codes or phone numbers), the variable is categorical, even if it happens to be recorded using digits.</p>
</div>
</section>
<section id="categorical-variables" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="categorical-variables"><span class="header-section-number">1.3.2</span> Categorical variables</h3>
<div class="definition">
<p>A <strong>categorical variable</strong> (also called a <strong>qualitative variable</strong>) takes on values that are category names or labels. The possible values of a categorical variable are called its <strong>levels</strong>.</p>
</div>
<p>The variable <code>state</code> can take up to 51 values (after accounting for Washington, DC): Alabama, Alaska, …, and Wyoming. Because the responses themselves are categories, <code>state</code> is a categorical variable, and the possible values (states) are the variable’s levels.</p>
<p>Categorical variables can be further subdivided:</p>
<ul>
<li><strong>Nominal variables</strong> have categories with no natural ordering. The variable <code>state</code> is nominal — there is no inherent reason to rank Alabama above Alaska or Wyoming.</li>
<li><strong>Ordinal variables</strong> have categories with a meaningful order. The variable <code>median_edu</code> takes values <code>below_hs</code>, <code>hs_diploma</code>, <code>some_college</code>, or <code>bachelors</code>. These categories have a natural ordering (less education to more education), making <code>median_edu</code> ordinal.</li>
</ul>
<div class="original">
<p>In most of this course, we will treat categorical variables as nominal (unordered). The distinction between nominal and ordinal becomes more important in advanced courses when special methods are used to take advantage of the ordering.</p>
</div>
</section>
<section id="variable-type-hierarchy" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="variable-type-hierarchy"><span class="header-section-number">1.3.3</span> Variable type hierarchy</h3>
<p>The breakdown of variable types is summarized in the diagram below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-variables" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A tree diagram showing variable types. At the top is 'all variables' which branches into 'numerical' and 'categorical'. Numerical branches into 'discrete' and 'continuous'. Categorical branches into 'ordinal' and 'nominal'.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch01-intro-to-data_files/figure-html/fig-variables-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1.1: Breakdown of variables into their respective types. All variables are either numerical or categorical. Numerical variables are further classified as discrete or continuous. Categorical variables are further classified as ordinal or nominal."><img src="ch01-intro-to-data_files/figure-html/fig-variables-1.png" class="img-fluid figure-img" alt="A tree diagram showing variable types. At the top is 'all variables' which branches into 'numerical' and 'categorical'. Numerical branches into 'discrete' and 'continuous'. Categorical branches into 'ordinal' and 'nominal'." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Breakdown of variables into their respective types. All variables are either numerical or categorical. Numerical variables are further classified as discrete or continuous. Categorical variables are further classified as ordinal or nominal.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="workedexample">
<p>Data were collected about students in a statistics course. Three variables were recorded for each student: number of siblings, student height, and whether the student had previously taken a statistics course. Classify each of the variables as continuous numerical, discrete numerical, or categorical.</p>
<hr>
<p>The number of siblings and student height represent numerical variables. Because the number of siblings is a count, it is discrete. Height varies continuously, so it is a continuous numerical variable. The last variable classifies students into two categories — those who have and those who have not taken a statistics course — which makes this variable categorical.</p>
</div>
<div class="guidedpractice">
<p>An experiment is evaluating the effectiveness of a new drug in treating migraines. A <code>group</code> variable is used to indicate the experiment group for each patient: treatment or control. The <code>num_migraines</code> variable represents the number of migraines the patient experienced during a 3-month period. Classify each variable as either numerical or categorical.</p>
<details>
<summary>
Show answer
</summary>
The <code>group</code> variable can take just one of two group names, making it categorical. The <code>num_migraines</code> variable describes a count of the number of migraines, which is an outcome where basic arithmetic is sensible, which means this is a numerical outcome; more specifically, since it represents a count, <code>num_migraines</code> is a discrete numerical variable.
</details>
</div>
<div class="guidedpractice">
<p>Classify each variable as continuous numerical, discrete numerical, nominal categorical, or ordinal categorical:</p>
<ol type="a">
<li>Number of text messages sent per day</li>
<li>Favorite type of music</li>
<li>Temperature in Fahrenheit</li>
<li>Satisfaction rating (1 = very unsatisfied, …, 5 = very satisfied)</li>
</ol>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li>Discrete numerical — it is a count. b. Nominal categorical — the categories (rock, jazz, classical, etc.) have no natural ordering. c.&nbsp;Continuous numerical — temperature can take any value in a range. d.&nbsp;Ordinal categorical — the numbers have a meaningful order, but the intervals between them may not be equal, and averaging satisfaction ratings is debatable.</li>
</ol>
</details>
</div>
</section>
</section>
<section id="sec-variable-relationships" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-variable-relationships"><span class="header-section-number">1.4</span> Relationships between variables</h2>
<p>Many analyses are motivated by a researcher looking for a relationship between two or more variables. A social scientist might like to answer questions such as:</p>
<blockquote class="blockquote">
<p>Does a higher-than-average increase in county population tend to correspond to counties with higher or lower median household incomes?</p>
</blockquote>
<blockquote class="blockquote">
<p>If homeownership in one county is lower than the national average, will the percent of housing units that are in multi-unit structures in that county tend to be above or below the national average?</p>
</blockquote>
<blockquote class="blockquote">
<p>How much can the median education level explain the median household income for counties in the US?</p>
</blockquote>
<p>To answer these questions, data must be collected, such as the county dataset shown in <a href="#tbl-county-df" class="quarto-xref">Table&nbsp;<span>1.4</span></a>. Examining summary statistics can provide numerical insights about the specifics of each of these questions. Alternatively, graphs can be used to visually explore the data, potentially providing more insight than a summary statistic.</p>
<section id="scatterplots" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="scatterplots"><span class="header-section-number">1.4.1</span> Scatterplots</h3>
<div class="definition">
<p>A <strong>scatterplot</strong> is a graph that displays the relationship between two numerical variables. Each observation is represented by a point, with one variable on the horizontal axis and the other on the vertical axis.</p>
</div>
<p>The figure below displays the relationship between <code>homeownership</code> and <code>multi_unit</code> (the percent of housing units that are in multi-unit structures such as apartments and condos) for US counties. Each point on the plot represents a single county. For instance, one highlighted point corresponds to Chattahoochee County, Georgia, which has 39.4% of housing units in multi-unit structures and a homeownership rate of 31.3%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-county-multi-unit-homeownership" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatterplot with percent of housing units in multi-unit structures on the x-axis and homeownership rate on the y-axis. The points show a clear downward trend from upper-left to lower-right. Chattahoochee County, Georgia is highlighted as an example point.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-county-multi-unit-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch01-intro-to-data_files/figure-html/fig-county-multi-unit-homeownership-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;1.2: A scatterplot of homeownership rate versus the percent of housing units in multi-unit structures for US counties. There is a clear negative trend: as the multi-unit rate increases, homeownership tends to decrease. Chattahoochee County, Georgia is highlighted."><img src="ch01-intro-to-data_files/figure-html/fig-county-multi-unit-homeownership-1.png" class="img-fluid figure-img" alt="A scatterplot with percent of housing units in multi-unit structures on the x-axis and homeownership rate on the y-axis. The points show a clear downward trend from upper-left to lower-right. Chattahoochee County, Georgia is highlighted as an example point." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-county-multi-unit-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: A scatterplot of homeownership rate versus the percent of housing units in multi-unit structures for US counties. There is a clear negative trend: as the multi-unit rate increases, homeownership tends to decrease. Chattahoochee County, Georgia is highlighted.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatterplot suggests a relationship between the two variables: counties with a higher rate of housing units in multi-unit structures tend to have lower homeownership rates. We might brainstorm as to why this relationship exists and investigate each idea to determine which are the most reasonable explanations.</p>
</section>
<section id="associated-and-independent-variables" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="associated-and-independent-variables"><span class="header-section-number">1.4.2</span> Associated and independent variables</h3>
<div class="definition">
<p>When two variables show some connection or pattern with one another, they are called <strong>associated</strong> variables (or <strong>related</strong> variables). If two variables are not associated — there is no evident relationship between them — they are said to be <strong>independent</strong>.</p>
</div>
<p>Because there is a downward trend in the homeownership vs.&nbsp;multi-unit scatterplot — counties with more multi-unit housing are associated with lower homeownership — these variables are said to be <strong>negatively associated</strong>.</p>
<div class="definition">
<p>A <strong>positive association</strong> means that as one variable increases, the other tends to increase as well. A <strong>negative association</strong> means that as one variable increases, the other tends to decrease.</p>
</div>
<div class="workedexample">
<p>Consider the relationship between the percent change in population from 2010 to 2017 and median household income for counties, as shown in the scatterplot below. Are these variables associated?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-county-pop-income" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatterplot with median household income on the x-axis and population change on the y-axis. The points show a positive trend from lower-left to upper-right. Owsley County, Kentucky is highlighted in the lower-left region.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-county-pop-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch01-intro-to-data_files/figure-html/fig-county-pop-income-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;1.3: A scatterplot showing population change against median household income for US counties. There is a positive trend: counties with higher median household income tend to have higher population growth. Owsley County, Kentucky is highlighted."><img src="ch01-intro-to-data_files/figure-html/fig-county-pop-income-1.png" class="img-fluid figure-img" alt="A scatterplot with median household income on the x-axis and population change on the y-axis. The points show a positive trend from lower-left to upper-right. Owsley County, Kentucky is highlighted in the lower-left region." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-county-pop-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: A scatterplot showing population change against median household income for US counties. There is a positive trend: counties with higher median household income tend to have higher population growth. Owsley County, Kentucky is highlighted.
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
<p>The larger the median household income for a county, the higher the population growth observed for the county. While it is not true that every county with a higher median household income has higher population growth, the trend in the plot is evident. Since there is some relationship between the variables, they are associated. Because both variables tend to increase together, this is a positive association.</p>
</div>
<div class="important">
<p><strong>Associated or independent, not both.</strong> A pair of variables are either related in some way (associated) or not (independent). No pair of variables is both associated and independent.</p>
</div>
<div class="guidedpractice">
<p>Examine the variables in the loan dataset, which are described in <a href="#tbl-loan50-variables" class="quarto-xref">Table&nbsp;<span>1.3</span></a>. Create two questions about possible relationships between variables in the loan data that are of interest to you.</p>
<details>
<summary>
Show answer
</summary>
Two example questions: (1) What is the relationship between loan amount and total income? (2) If someone’s income is above the average, will their interest rate tend to be above or below the average?
</details>
</div>
</section>
</section>
<section id="sec-explanatory-response" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-explanatory-response"><span class="header-section-number">1.5</span> Explanatory and response variables</h2>
<p>When we ask questions about the relationship between two variables, we sometimes also want to determine if the change in one variable causes a change in the other. Consider the following rephrasing of an earlier question about the county dataset:</p>
<blockquote class="blockquote">
<p>If there is an increase in the median household income in a county, does this <em>drive</em> an increase in its population?</p>
</blockquote>
<p>In this question, we are asking whether one variable affects another.</p>
<div class="definition">
<p>When we suspect one variable might causally affect another, we label the first variable the <strong>explanatory variable</strong> and the second the <strong>response variable</strong>.</p>
<p><span class="math display">\[\text{explanatory variable} \rightarrow \textit{might affect} \rightarrow \text{response variable}\]</span></p>
<p>We also use the terms explanatory and response to describe variables where the response might be <em>predicted</em> using the explanatory variable, even if there is no causal relationship.</p>
</div>
<p>For many pairs of variables, there is no hypothesized relationship, and these labels would not be applied to either variable.</p>
<div class="workedexample">
<p>In the stent study from <a href="#sec-case-stents" class="quarto-xref"><span>Section 1.1</span></a>, identify the explanatory and response variables.</p>
<hr>
<p>The explanatory variable is the treatment group assignment (stent or control), because this is the factor that the researchers manipulated. The response variable is whether the patient had a stroke, because this is the outcome the researchers measured to evaluate the treatment’s effect.</p>
</div>
<div class="caution">
<p>Labeling one variable as “explanatory” does not guarantee that it <em>causes</em> changes in the response. A formal evaluation of whether one variable causes changes in another requires an experiment. We discuss this distinction further in <a href="#sec-obs-vs-exp" class="quarto-xref"><span>Section 1.6</span></a>.</p>
</div>
<div class="original">
<p>Some disciplines use the terms <strong>independent variable</strong> and <strong>dependent variable</strong> instead of explanatory and response. We avoid this language because the word “independent” has a different technical meaning in statistics — it refers to variables that are not associated. Using “independent” in two different ways can cause confusion.</p>
</div>
<div class="guidedpractice">
<p>A researcher is studying whether hours spent studying for an exam are related to exam scores. Identify the explanatory and response variables.</p>
<details>
<summary>
Show answer
</summary>
The explanatory variable is hours spent studying, because this is the factor that might influence the outcome. The response variable is exam score, because this is the outcome being measured.
</details>
</div>
</section>
<section id="sec-obs-vs-exp" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="sec-obs-vs-exp"><span class="header-section-number">1.6</span> Observational studies and experiments</h2>
<p>There are two primary types of data collection: experiments and observational studies. Understanding the difference is critical, because the type of study determines what conclusions we can draw.</p>
<section id="experiments" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="experiments"><span class="header-section-number">1.6.1</span> Experiments</h3>
<div class="definition">
<p>An <strong>experiment</strong> is a study in which the researcher actively imposes treatments on the subjects in order to observe their responses. When subjects are randomly assigned to treatment groups, the study is called a <strong>randomized experiment</strong>.</p>
</div>
<p>For instance, we may suspect that drinking a high-calorie energy drink will improve performance in a race. To check if there really is a causal relationship between the explanatory variable (whether the runner drank an energy drink or not) and the response variable (the race time), researchers identify a sample of individuals and split them into groups. The individuals in each group are <em>assigned</em> a treatment. Random assignment organizes the participants into groups that are roughly equal on all aspects, thus allowing us to control for any other variables that might affect the outcome (such as fitness level, racing experience, or age).</p>
<p>For example, each runner in the experiment could be randomly assigned — perhaps by flipping a coin — into one of two groups: the first group receives a <strong>placebo</strong> (a fake treatment, in this case a no-calorie drink that looks identical to the energy drink) and the second group receives the high-calorie energy drink.</p>
<div class="definition">
<p>A <strong>placebo</strong> is a fake treatment that is made to look like the real treatment. Placebos are used so that subjects in the control group have the same experience as those in the treatment group (except for the actual treatment), which helps researchers isolate the effect of the treatment itself.</p>
</div>
<p>See the stent case study in <a href="#sec-case-stents" class="quarto-xref"><span>Section 1.1</span></a> for another example of an experiment, though that study did not employ a placebo.</p>
</section>
<section id="observational-studies" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="observational-studies"><span class="header-section-number">1.6.2</span> Observational studies</h3>
<div class="definition">
<p>An <strong>observational study</strong> is a study in which the researcher collects data without interfering with how the data arise. In an observational study, the researcher merely observes what happens naturally.</p>
</div>
<p>Researchers perform observational studies when they collect data via surveys, review medical or company records, or follow a <strong>cohort</strong> (a group of similar individuals) over time to form hypotheses about why certain outcomes might occur. In each of these situations, researchers merely observe the data that arise — they do not assign treatments to subjects.</p>
<div class="workedexample">
<p>A researcher wants to know if smoking causes lung cancer. She follows 10,000 adults over 20 years, recording whether each person smokes and whether they develop lung cancer. Is this an experiment or an observational study?</p>
<hr>
<p>This is an observational study. The researcher did not assign anyone to smoke or not smoke — she simply observed the participants’ behavior and health outcomes. While the study might reveal an association between smoking and lung cancer, it cannot by itself prove causation, because there may be other differences between smokers and non-smokers (such as diet, exercise habits, or genetics) that contribute to the outcome.</p>
</div>
</section>
<section id="the-key-distinction-association-vs.-causation" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" class="anchored" data-anchor-id="the-key-distinction-association-vs.-causation"><span class="header-section-number">1.6.3</span> The key distinction: association vs.&nbsp;causation</h3>
<p>In general, observational studies can provide evidence of a naturally occurring association between variables, but they cannot by themselves show a causal connection. This is because in observational studies, researchers cannot control for all the other variables that might be influencing the outcome.</p>
<div class="important">
<p><strong>Association does not imply causation.</strong></p>
<p>In general, association does not imply causation. An advantage of a randomized experiment is that it is easier to establish causal relationships, because random assignment tends to balance out the effects of other variables across treatment groups. Establishing causation from observational studies requires advanced statistical methods that are beyond the scope of this course. We revisit these ideas when we discuss study design in Chapter 2.</p>
</div>
<div class="workedexample">
<p>Determine whether each of the following is an experiment or an observational study:</p>
<ol type="a">
<li>A pharmaceutical company randomly assigns 200 patients to receive either a new drug or a placebo and measures their cholesterol levels after 6 months.</li>
<li>A university surveys its graduates to determine whether those who participated in study-abroad programs earn higher salaries five years after graduation.</li>
<li>A teacher assigns students in her morning class to use a new learning app and students in her afternoon class to study using traditional methods, then compares exam scores.</li>
</ol>
<hr>
<ol type="a">
<li>This is an experiment — the company randomly assigns patients to treatments.</li>
<li>This is an observational study — the university simply collects data on students who chose (or chose not) to study abroad. The students were not randomly assigned.</li>
<li>This is tricky. The teacher assigns groups, so it might seem like an experiment. However, because students were not randomly assigned (they ended up in morning vs.&nbsp;afternoon classes for their own reasons), this is better described as a quasi-experiment or an observational study. Differences in outcomes could be due to the app, or they could be due to systematic differences between the types of students who take morning vs.&nbsp;afternoon classes.</li>
</ol>
</div>
</section>
<section id="putting-it-all-together" class="level3 original" data-number="1.6.4">
<h3 data-number="1.6.4" class="anchored" data-anchor-id="putting-it-all-together"><span class="header-section-number">1.6.4</span> Putting it all together</h3>
<p>The table below summarizes the key differences between experiments and observational studies.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Experiment</th>
<th style="text-align: left;">Observational Study</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Researcher’s role</strong></td>
<td style="text-align: left;">Assigns treatments</td>
<td style="text-align: left;">Observes what happens naturally</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Random assignment?</strong></td>
<td style="text-align: left;">Yes (in a randomized experiment)</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Can establish causation?</strong></td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Generally no</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Example</strong></td>
<td style="text-align: left;">Randomly assign patients to drug vs.&nbsp;placebo</td>
<td style="text-align: left;">Survey people about their exercise habits and health</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-ch01-review" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="sec-ch01-review"><span class="header-section-number">1.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">1.7.1</span> Summary</h3>
<p>This chapter introduced you to the world of data. Here are the key ideas:</p>
<ul>
<li><strong>Data</strong> are observations collected about the world around us. <strong>Statistics</strong> is the science of collecting, analyzing, and drawing conclusions from data.</li>
<li>A <strong>data frame</strong> organizes data so that each row represents an observation and each column represents a variable. Data organized this way is called <strong>tidy data</strong>.</li>
<li>Variables come in two fundamental types: <strong>numerical</strong> (continuous or discrete) and <strong>categorical</strong> (nominal or ordinal).</li>
<li>When two variables show a pattern together, they are <strong>associated</strong>; if not, they are <strong>independent</strong>. Associations can be <strong>positive</strong> (both increase together) or <strong>negative</strong> (one increases while the other decreases).</li>
<li>The <strong>explanatory variable</strong> is the variable we think might influence the <strong>response variable</strong>.</li>
<li><strong>Experiments</strong> randomly assign subjects to treatments and can establish causation. <strong>Observational studies</strong> merely observe what happens and can identify associations, but generally cannot establish causation.</li>
<li><strong>Association does not imply causation</strong> — this is one of the most important principles in statistics.</li>
</ul>
<p>Many of the ideas from this chapter will be revisited as we move on to doing end-to-end data analyses. In the next chapter, you will learn about how we can design studies to collect the data we need to make conclusions with the desired scope of inference.</p>
</section>
<section id="key-terms" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">1.7.2</span> Key terms</h3>
<p>The following terms were introduced in this chapter. You should be able to define and give an example of each.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Term</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">associated</td>
<td style="text-align: left;">data</td>
<td style="text-align: left;">data frame</td>
</tr>
<tr class="even">
<td style="text-align: left;">case</td>
<td style="text-align: left;">categorical variable</td>
<td style="text-align: left;">cohort</td>
</tr>
<tr class="odd">
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">dependent variable</td>
<td style="text-align: left;">discrete</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiment</td>
<td style="text-align: left;">explanatory variable</td>
<td style="text-align: left;">independent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">level</td>
<td style="text-align: left;">negative association</td>
<td style="text-align: left;">nominal</td>
</tr>
<tr class="even">
<td style="text-align: left;">numerical variable</td>
<td style="text-align: left;">observation</td>
<td style="text-align: left;">observational study</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ordinal</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: left;">positive association</td>
</tr>
<tr class="even">
<td style="text-align: left;">randomized experiment</td>
<td style="text-align: left;">response variable</td>
<td style="text-align: left;">summary statistic</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tidy data</td>
<td style="text-align: left;">unit of observation</td>
<td style="text-align: left;">variable</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="1.8">
<h2 class="exercises anchored" data-number="1.8" data-anchor-id="exercises"><span class="header-section-number">1.8</span> Exercises</h2>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _01-ex-data-hello -->
<ol type="1">
<li><strong>Marvel Cinematic Universe films.</strong> The data frame below contains information on Marvel Cinematic Universe films through the Infinity saga (a movie storyline spanning from Ironman in 2008 to Endgame in 2019). Box office totals are given in millions of US Dollars. How many observations and how many variables does this data frame have?</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Length
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Gross
</div></th>
</tr>
<tr class="even">
<th style="text-align: center;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Title</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Hrs</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mins</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Release Date</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Opening Wknd US</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">US</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">World</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left; width: 10em;">Iron Man</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5/2/2008</td>
<td style="text-align: center;">98.62</td>
<td style="text-align: center;">319.03</td>
<td style="text-align: center;">585.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left; width: 10em;">The Incredible Hulk</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">6/12/2008</td>
<td style="text-align: center;">55.41</td>
<td style="text-align: center;">134.81</td>
<td style="text-align: center;">264.77</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left; width: 10em;">Iron Man 2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5/7/2010</td>
<td style="text-align: center;">128.12</td>
<td style="text-align: center;">312.43</td>
<td style="text-align: center;">623.93</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left; width: 10em;">Thor</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">5/6/2011</td>
<td style="text-align: center;">65.72</td>
<td style="text-align: center;">181.03</td>
<td style="text-align: center;">449.33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left; width: 10em;">Captain America: The First Avenger</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">7/22/2011</td>
<td style="text-align: center;">65.06</td>
<td style="text-align: center;">176.65</td>
<td style="text-align: center;">370.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">...</td>
<td style="text-align: left; width: 10em;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
</tr>
<tr class="odd">
<td style="text-align: center;">23</td>
<td style="text-align: left; width: 10em;">Spiderman: Far from Home</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">7/2/2019</td>
<td style="text-align: center;">92.58</td>
<td style="text-align: center;">390.53</td>
<td style="text-align: center;">1131.93</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="2" type="1">
<li><strong>Cherry Blossom Run.</strong> The data frame below contains information on runners in the 2017 Cherry Blossom Run, which is an annual road race that takes place in Washington, DC. Most runners participate in a 10-mile run while a smaller fraction take part in a 5k run or walk. How many observations and how many variables does this data frame have?</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th colspan="6" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Time
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Bib</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">City / Country</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Net</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Clock</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Pace</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">Hiwot G.</td>
<td style="text-align: left;">F</td>
<td style="text-align: center;">21</td>
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: center;">3217</td>
<td style="text-align: center;">3217</td>
<td style="text-align: center;">321</td>
<td style="text-align: left;">10 Mile</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">Buze D.</td>
<td style="text-align: left;">F</td>
<td style="text-align: center;">22</td>
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: center;">3232</td>
<td style="text-align: center;">3232</td>
<td style="text-align: center;">323</td>
<td style="text-align: left;">10 Mile</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">Gladys K.</td>
<td style="text-align: left;">F</td>
<td style="text-align: center;">31</td>
<td style="text-align: left;">Kenya</td>
<td style="text-align: center;">3276</td>
<td style="text-align: center;">3276</td>
<td style="text-align: center;">327</td>
<td style="text-align: left;">10 Mile</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Mamitu D.</td>
<td style="text-align: left;">F</td>
<td style="text-align: center;">33</td>
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: center;">3285</td>
<td style="text-align: center;">3285</td>
<td style="text-align: center;">328</td>
<td style="text-align: left;">10 Mile</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">Karolina N.</td>
<td style="text-align: left;">F</td>
<td style="text-align: center;">35</td>
<td style="text-align: left;">Poland</td>
<td style="text-align: center;">3288</td>
<td style="text-align: center;">3288</td>
<td style="text-align: center;">328</td>
<td style="text-align: left;">10 Mile</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19961</td>
<td style="text-align: left;">25153</td>
<td style="text-align: left;">Andres E.</td>
<td style="text-align: left;">M</td>
<td style="text-align: center;">33</td>
<td style="text-align: left;">Woodbridge, VA</td>
<td style="text-align: center;">5287</td>
<td style="text-align: center;">5334</td>
<td style="text-align: center;">1700</td>
<td style="text-align: left;">5K</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="3" type="1">
<li><strong>Air pollution and birth outcomes, study components.</strong> Researchers collected data to examine the relationship between air pollutants and preterm births in Southern California. During the study, air pollution levels were measured by air quality monitoring stations. Specifically, levels of carbon monoxide were recorded in parts per million, nitrogen dioxide and ozone in parts per hundred million, and inhalable particulate matter (PM<span class="math inline">\(_{10}\)</span>) in <span class="math inline">\(\mu g/m^3\)</span>. Length of gestation data were collected on 143,196 births between the years 1989 and 1993, and air pollution exposure during gestation was calculated for each birth. The analysis suggested that increased ambient PM<span class="math inline">\(_{10}\)</span> and, to a lesser degree, CO concentrations may be associated with the occurrence of preterm births. <span class="citation" data-cites="Ritz+Yu+Chapa+Fruin:2000">[@Ritz+Yu+Chapa+Fruin:2000]</span></li>
</ol>
<ol type="a">
<li><p>Identify the main research question of the study.</p></li>
<li><p>Who are the subjects in this study, and how many are included?</p></li>
<li><p>What are the variables in the study? Identify each variable as numerical or categorical. If numerical, state whether the variable is discrete or continuous. If categorical, state whether the variable is ordinal.</p></li>
</ol>
<ol start="4" type="1">
<li><strong>Cheaters, study components.</strong> Researchers studying the relationship between honesty, age and self-control conducted an experiment on 160 children between the ages of 5 and 15. Participants reported their age, sex, and whether they were an only child or not. The researchers asked each child to toss a fair coin in private and to record the outcome (white or black) on a paper sheet, and said they would only reward children who report white. <span class="citation" data-cites="Bucciol:2011">[@Bucciol:2011]</span></li>
</ol>
<ol type="a">
<li><p>Identify the main research question of the study.</p></li>
<li><p>Who are the subjects in this study, and how many are included?</p></li>
<li><p>The study’s findings can be summarized as follows: <em>“Half the students were explicitly told not to cheat and the others were not given any explicit instructions. In the no instruction group probability of cheating was found to be uniform across groups based on child’s characteristics. In the group that was explicitly told to not cheat, girls were less likely to cheat, and while rate of cheating didn’t vary by age for boys, it decreased with age for girls.”</em> How many variables were recorded for each subject in the study in order to conclude these findings? State the variables and their types. </p></li>
</ol>
<ol start="5" type="1">
<li><strong>Gamification and statistics, study components.</strong> Gamification is the application of game-design elements and game principles in non-game contexts. In educational settings, gamification is often implemented as educational activities to solve problems by using characteristics of game elements. Researchers investigating the effects of gamification on learning statistics conducted a study where they split college students in a statistics class into four groups: (1) no reading exercises and no gamification, (2) reading exercises but no gamification, (3) gamification but no reading exercises, and (4) gamification and reading exercises. Students in all groups also attended lectures. Students in the class were from two majors: Electrical and Computer Engineering (n = 279) and Business Administration (n = 86). After their assigned learning experience, each student took a final evaluation comprised of 30 multiple choice question and their score was measured as the number of questions they answered correctly. The researchers considered students’ gender, level of studies (first through fourth year) and academic major. Other variables considered were expertise in the English language and use of personal computers and games, both of which were measured on a scale of 1 (beginner) to 5 (proficient). The study found that gamification had a positive effect on student learning compared to traditional teaching methods involving lectures and reading exercises. They also found that the effect was larger for females and Engineering students. <span class="citation" data-cites="Legaki:2020">[@Legaki:2020]</span></li>
</ol>
<ol type="a">
<li><p>Identify the main research question of the study.</p></li>
<li><p>Who were the subjects in this study, and how many were included?</p></li>
<li><p>What are the variables in the study? Identify each variable as numerical or categorical. If numerical, state whether the variable is discrete or continuous. If categorical, state whether the variable is ordinal. </p></li>
</ol>
<ol start="6" type="1">
<li><strong>Stealers, study components.</strong> In a study of the relationship between socio-economic class and unethical behavior, 129 University of California undergraduates at Berkeley were asked to identify themselves as having low or high social-class by comparing themselves to others with the most (least) money, most (least) education, and most (least) respected jobs. They were also presented with a jar of individually wrapped candies and informed that the candies were for children in a nearby laboratory, but that they could take some if they wanted. After completing some unrelated tasks, participants reported the number of candies they had taken. <span class="citation" data-cites="Piff:2012">[@Piff:2012]</span></li>
</ol>
<ol type="a">
<li><p>Identify the main research question of the study.</p></li>
<li><p>Who were the subjects in this study, and how many were included?</p></li>
<li><p>The study found that students who were identified as upper-class took more candy than others. How many variables were recorded for each subject in the study in order to conclude these findings? State the variables and their types.</p></li>
</ol>
<ol start="7" type="1">
<li><strong>Migraine and acupuncture.</strong> A migraine is a particularly painful type of headache, which patients sometimes wish to treat with acupuncture. To determine whether acupuncture relieves migraine pain, researchers conducted a randomized controlled study where 89 individuals who identified as female diagnosed with migraine headaches were randomly assigned to one of two groups: treatment or control. Forty-three (43) patients in the treatment group received acupuncture that is specifically designed to treat migraines. Forty-six (46) patients in the control group received placebo acupuncture (needle insertion at non-acupoint locations). Twenty-four (24) hours after patients received acupuncture, they were asked if they were pain free. Results are summarized in the contingency table below. Also provided is a figure from the original paper displaying the appropriate area (M) versus the inappropriate area (S) used in the treatment of migraine attacks. <span class="citation" data-cites="Allais:2011">[@Allais:2011]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Pain free?
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">Control</td>
<td style="text-align: right; width: 5em;">44</td>
<td style="text-align: right; width: 5em;">2</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">Treatment</td>
<td style="text-align: right; width: 5em;">33</td>
<td style="text-align: right; width: 5em;">10</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What percent of patients in the treatment group were pain free 24 hours after receiving acupuncture?</p></li>
<li><p>What percent were pain free in the control group?</p></li>
<li><p>In which group did a higher percent of patients become pain free 24 hours after receiving acupuncture?</p></li>
<li><p>Your findings so far might suggest that acupuncture is an effective treatment for migraines for all people who suffer from migraines. However this is not the only possible conclusion. What is one other possible explanation for the observed difference between the percentages of patients that are pain free 24 hours after receiving acupuncture in the two groups?</p></li>
<li><p>What are the explanatory and response variables in this study? </p></li>
</ol>
<ol start="8" type="1">
<li><strong>Sinusitis and antibiotics.</strong> Researchers studying the effect of antibiotic treatment for acute sinusitis compared to symptomatic treatments randomly assigned 166 adults diagnosed with acute sinusitis to one of two groups: treatment or control. Study participants received either a 10-day course of amoxicillin (an antibiotic) or a placebo similar in appearance and taste. The placebo consisted of symptomatic treatments such as acetaminophen, nasal decongestants, etc. At the end of the 10-day period, patients were asked if they experienced improvement in symptoms. The distribution of responses is summarized below. <span class="citation" data-cites="Garbutt:2012">[@Garbutt:2012]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Improvement
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">Control</td>
<td style="text-align: right; width: 5em;">16</td>
<td style="text-align: right; width: 5em;">65</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">Treatment</td>
<td style="text-align: right; width: 5em;">19</td>
<td style="text-align: right; width: 5em;">66</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What percent of patients in the treatment group experienced improvement in symptoms?</p></li>
<li><p>What percent experienced improvement in symptoms in the control group?</p></li>
<li><p>In which group did a higher percentage of patients experience improvement in symptoms?</p></li>
<li><p>Your findings so far might suggest a real difference in the effectiveness of antibiotic and placebo treatments for improving symptoms of sinusitis. However this is not the only possible conclusion. What is one other possible explanation for the observed difference between the percentages patients who experienced improvement in symptoms?</p></li>
<li><p>What are the explanatory and response variables in this study?</p></li>
</ol>
<ol start="9" type="1">
<li><strong>Daycare fines, study components.</strong> Researchers tested the deterrence hypothesis which predicts that the introduction of a penalty will reduce the occurrence of the behavior subject to the fine, with the condition that the fine leaves everything else unchanged, by instituting a fine for late pickup at daycare centers. For this study, they worked with 10 volunteer daycare centers that did not originally impose a fine to parents for picking up their kids late. They randomly selected 6 of these daycare centers and instituted a monetary fine (of a considerable amount) for picking up children late and then removed it. In the remaining 4 daycare centers no fine was introduced. The study period was divided into four: before the fine (weeks 1–4), the first 4 weeks with the fine (weeks 5-8), the last 8 weeks with fine (weeks 9–16), and the after fine period (weeks 17-20). Throughout the study, the number of kids who were picked up late was recorded each week for each daycare. The study found that the number of late-coming parents increased discernibly when the fine was introduced, and no reduction occurred after the fine was removed. <span class="citation" data-cites="Gneezy:2000">[@Gneezy:2000]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">center</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">week</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">late_pickups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">study_period</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: left;">test</td>
<td style="text-align: center;">8</td>
<td style="text-align: left;">before fine</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: left;">test</td>
<td style="text-align: center;">8</td>
<td style="text-align: left;">before fine</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: left;">test</td>
<td style="text-align: center;">7</td>
<td style="text-align: left;">before fine</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
<td style="text-align: left;">test</td>
<td style="text-align: center;">6</td>
<td style="text-align: left;">before fine</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">5</td>
<td style="text-align: left;">test</td>
<td style="text-align: center;">8</td>
<td style="text-align: left;">first 4 weeks with fine</td>
</tr>
<tr class="even">
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">20</td>
<td style="text-align: left;">control</td>
<td style="text-align: center;">13</td>
<td style="text-align: left;">after fine</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Is this an observational study or an experiment? Explain your reasoning.</p></li>
<li><p>What are the cases in this study and how many are included?</p></li>
<li><p>What is the response variable in the study and what type of variable is it?</p></li>
<li><p>What are the explanatory variables in the study and what types of variables are they? </p></li>
</ol>
<ol start="10" type="1">
<li><strong>Efficacy of COVID-19 vaccine on adolescents, study components.</strong> Results of a Phase 3 trial announced in March 2021 show that the Pfizer-BioNTech COVID-19 vaccine demonstrated 100% efficacy and robust antibody responses on 12 to 15 years old adolescents with or without prior evidence of SARS-CoV-2 infection. In this trial 2,260 adolescents were randomly assigned to two groups: one group got the vaccine (n = 1,131) and the other got a placebo (n = 1,129). While 18 cases of COVID-19 were observed in the placebo group, none were observed in the vaccine group. <span class="citation" data-cites="Pfizer:2021">[@Pfizer:2021]</span></li>
</ol>
<ol type="a">
<li><p>Is this an observational study or an experiment? Explain your reasoning.</p></li>
<li><p>What are the cases in this study and how many are included?</p></li>
<li><p>What is the response variable in the study and what type of variable is it?</p></li>
<li><p>What are the explanatory variables in the study and what types of variables are they? </p></li>
</ol>
<ol start="11" type="1">
<li><strong>Palmer penguins.</strong> Data were collected on 344 penguins living on three islands (Torgersen, Biscoe, and Dream) in the Palmer Archipelago, Antarctica. In addition to which island each penguin lives on, the data contains information on the species of the penguin (<em>Adelie</em>, <em>Chinstrap</em>, or <em>Gentoo</em>), its bill length, bill depth, and flipper length (measured in millimeters), its body mass (measured in grams), and the sex of the penguin (female or male). <span class="citation" data-cites="palmerpenguins">[@palmerpenguins]</span></li>
</ol>
<ol type="a">
<li>How many cases were included in the data?</li>
<li>How many numerical variables are included in the data? Indicate what they are, and if they are continuous or discrete.</li>
<li>How many categorical variables are included in the data, and what are they? List the corresponding levels (categories) for each.</li>
</ol>
<ol start="12" type="1">
<li><strong>Smoking habits of UK residents.</strong> A survey was conducted to study the smoking habits of 1,691 UK residents. Below is a data frame displaying a portion of the data collected in this survey. A blank cell indicates that data for that variable was not available for a given respondent.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th colspan="6" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
amount
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">marital_status</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">gross_income</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">weekend</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">weekday</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">Married</td>
<td style="text-align: center;">2,600 to 5,200</td>
<td style="text-align: left;">No</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">Divorced</td>
<td style="text-align: center;">10,400 to 15,600</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">69</td>
<td style="text-align: left;">Widowed</td>
<td style="text-align: center;">5,200 to 10,400</td>
<td style="text-align: left;">No</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">Married</td>
<td style="text-align: center;">5,200 to 10,400</td>
<td style="text-align: left;">No</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">31</td>
<td style="text-align: left;">Single</td>
<td style="text-align: center;">10,400 to 15,600</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1691</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">Divorced</td>
<td style="text-align: center;">Above 36,400</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">10</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What does each row of the data frame represent?</p></li>
<li><p>How many participants were included in the survey?</p></li>
<li><p>Indicate whether each variable is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal. </p></li>
</ol>
<ol start="13" type="1">
<li><strong>US Airports.</strong> The visualization below shows the geographical distribution of airports in the contiguous United States and Washington, DC. This visualization was constructed based on a dataset where each observation is an airport.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch01-intro-to-data_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="ch01-intro-to-data_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>List the variables you believe were necessary to create this visualization.</p></li>
<li><p>Indicate whether each variable is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal.</p></li>
</ol>
<ol start="14" type="1">
<li><strong>UN Votes.</strong> The visualization below shows voting patterns in the United States, Canada, and Mexico in the United Nations General Assembly on a variety of issues. Specifically, for a given year between 1946 and 2019, it displays the percentage of roll calls in which the country voted yes for each issue. This visualization was constructed based on a dataset where each observation is a country/year pair.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch01-intro-to-data_files/figure-html/unnamed-chunk-9-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="ch01-intro-to-data_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>List the variables used in creating this visualization.</p></li>
<li><p>Indicate whether each variable is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal. </p></li>
</ol>
<ol start="15" type="1">
<li><strong>UK baby names.</strong> The visualization below shows the number of baby girls born in the United Kingdom (comprised of England &amp; Wales, Northern Ireland, and Scotland) who were given the name “Fiona” over the years.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch01-intro-to-data_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="ch01-intro-to-data_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>List the variables you believe were necessary to create this visualization.</p></li>
<li><p>Indicate whether each variable is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal.</p></li>
</ol>
<ol start="16" type="1">
<li><strong>Shows on Netflix.</strong> The visualization below shows the distribution of ratings of TV shows on Netflix (a streaming entertainment service) based on the decade they were released in and the country they were produced in. In the dataset, each observation is a TV show.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch01-intro-to-data_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="ch01-intro-to-data_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>List the variables you believe were necessary to create this visualization.</p></li>
<li><p>Indicate whether each variable is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal. </p></li>
</ol>
<ol start="17" type="1">
<li><strong>Stanford Open Policing.</strong> The Stanford Open Policing project gathers, analyzes, and releases records from traffic stops by law enforcement agencies across the United States. Their goal is to help researchers, journalists, and policy makers investigate and improve interactions between police and the public. The following is an excerpt from a summary table created based off of the data collected as part of this project. <span class="citation" data-cites="pierson2020large">[@pierson2020large]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Driver
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Car
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">County</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">State</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Race / Ethnicity</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Arrest rate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Stops / year</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Search rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Apache County</td>
<td style="text-align: left;">AZ</td>
<td style="text-align: left;">Black</td>
<td style="text-align: center;">0.016</td>
<td style="text-align: center;">266</td>
<td style="text-align: center;">0.077</td>
</tr>
<tr class="even">
<td style="text-align: left;">Apache County</td>
<td style="text-align: left;">AZ</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: center;">0.018</td>
<td style="text-align: center;">1008</td>
<td style="text-align: center;">0.053</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apache County</td>
<td style="text-align: left;">AZ</td>
<td style="text-align: left;">White</td>
<td style="text-align: center;">0.006</td>
<td style="text-align: center;">6322</td>
<td style="text-align: center;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cochise County</td>
<td style="text-align: left;">AZ</td>
<td style="text-align: left;">Black</td>
<td style="text-align: center;">0.015</td>
<td style="text-align: center;">1169</td>
<td style="text-align: center;">0.047</td>
</tr>
<tr class="odd">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wood County</td>
<td style="text-align: left;">WI</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: center;">0.029</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">0.036</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wood County</td>
<td style="text-align: left;">WI</td>
<td style="text-align: left;">White</td>
<td style="text-align: center;">0.029</td>
<td style="text-align: center;">1157</td>
<td style="text-align: center;">0.033</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What variables were collected on each individual traffic stop in order to create the summary table above?</p></li>
<li><p>State whether each variable is numerical or categorical. If numerical, state whether it is continuous or discrete. If categorical, state whether it is ordinal or not.</p></li>
<li><p>Suppose we wanted to evaluate whether vehicle search rates are different for drivers of different races. In this analysis, which variable would be the response variable and which variable would be the explanatory variable? </p></li>
</ol>
<ol start="18" type="1">
<li><strong>Space launches.</strong> The following summary table shows the number of space launches in the US by the type of launching agency and the outcome of the launch (success or failure).</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
1957 - 1999
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
2000-2018
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Failure</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Success</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Failure</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Success</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Private</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">562</td>
</tr>
<tr class="even">
<td style="text-align: left;">State</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">3751</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">711</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Startup</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">65</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What variables were collected on each launch in order to create to the summary table above?</p></li>
<li><p>State whether each variable is numerical or categorical. If numerical, state whether it is continuous or discrete. If categorical, state whether it is ordinal or not.</p></li>
<li><p>Suppose we wanted to study how the success rate of launches vary between launching agencies and over time. In this analysis, which variable would be the response variable and which variable would be the explanatory variable? </p></li>
</ol>
<ol start="19" type="1">
<li><strong>Pet names.</strong> The city of Seattle, WA has an open data portal that includes pets registered in the city. For each registered pet, we have information on the pet’s name and species. The following visualization plots the proportion of dogs with a given name versus the proportion of cats with the same name. The 20 most common cat and dog names are displayed. The diagonal line on the plot is the <span class="math inline">\(x = y\)</span> line; if a name appeared on this line, the name’s popularity would be exactly the same for dogs and cats.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch01-intro-to-data_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="ch01-intro-to-data_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Are these data collected as part of an experiment or an observational study?</p></li>
<li><p>What is the most common dog name? What is the most common cat name?</p></li>
<li><p>What names are more common for cats than dogs?</p></li>
<li><p>Is the relationship between the two variables positive or negative? What does this mean in context of the data? </p></li>
</ol>
<ol start="20" type="1">
<li><strong>Stressed out in an elevator.</strong> In a study evaluating the relationship between stress and muscle cramps, half the subjects are randomly assigned to be exposed to increased stress by being placed into an elevator that falls rapidly and stops abruptly and the other half are left at no or baseline stress.</li>
</ol>
<ol type="a">
<li><p>What type of study is this?</p></li>
<li><p>Can this study be used to conclude a causal relationship between increased stress and muscle cramps?</p></li>
</ol>
<details class="dataset-sources">
<summary>
Dataset sources
</summary>
<small><a href="http://openintrostat.github.io/openintro/reference/mcu_films.html"><code>mcu_films</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/run17.html"><code>run17</code></a> (cherryblossom) | <a href="http://openintrostat.github.io/openintro/reference/migraine.html"><code>migraine</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/sinusitis.html"><code>sinusitis</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/daycare_fines.html"><code>daycare_fines</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/biontech_adolescents.html"><code>biontech_adolescents</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/smoking.html"><code>smoking</code></a> (openintro) | <a href="http://openintrostat.github.io/airports/reference/usairports.html"><code>usairports</code></a> (airports) | <a href="https://mine-cetinkaya-rundel.github.io/ukbabynames/reference/ukbabynames.html"><code>ukbabynames</code></a> (ukbabynames) | <a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-04-20/readme.md"><code>netflix_titles</code></a> (tidytuesdayR) | <a href="http://openintrostat.github.io/openintro/reference/seattlepets.html"><code>seattlepets</code></a> (openintro)</small>
</details>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Chimowitz MI, Lynn MJ, Derdeyn CP, et al.&nbsp;2011. Stenting versus Aggressive Medical Therapy for Intracranial Arterial Stenosis. <em>New England Journal of Medicine</em> 365:993–1003.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../parts/part-i.html" class="pagination-link" aria-label="Explore">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Explore</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch02-study-design.html" class="pagination-link" aria-label="Data Collection and Study Design">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>