<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Relationships Between Variables – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../parts/part-ii.html" rel="next">
<link href="../chapters/ch04-describing-distributions.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8a91fbd6dc43518bbcbbe5f3fb33f285.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/ch05-relationships.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statbench-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatBench Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-two-categorical" id="toc-sec-two-categorical" class="nav-link active" data-scroll-target="#sec-two-categorical"><span class="header-section-number">6.1</span> Two categorical variables</a>
  <ul class="collapse">
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">6.1.1</span> Contingency tables</a></li>
  <li><a href="#row-and-column-proportions" id="toc-row-and-column-proportions" class="nav-link" data-scroll-target="#row-and-column-proportions"><span class="header-section-number">6.1.2</span> Row and column proportions</a></li>
  <li><a href="#bar-plots-for-two-categorical-variables" id="toc-bar-plots-for-two-categorical-variables" class="nav-link" data-scroll-target="#bar-plots-for-two-categorical-variables"><span class="header-section-number">6.1.3</span> Bar plots for two categorical variables</a></li>
  <li><a href="#mosaic-plots" id="toc-mosaic-plots" class="nav-link" data-scroll-target="#mosaic-plots"><span class="header-section-number">6.1.4</span> Mosaic plots</a></li>
  </ul></li>
  <li><a href="#sec-cat-num" id="toc-sec-cat-num" class="nav-link" data-scroll-target="#sec-cat-num"><span class="header-section-number">6.2</span> One categorical and one numerical variable</a>
  <ul class="collapse">
  <li><a href="#side-by-side-box-plots" id="toc-side-by-side-box-plots" class="nav-link" data-scroll-target="#side-by-side-box-plots"><span class="header-section-number">6.2.1</span> Side-by-side box plots</a></li>
  <li><a href="#faceted-histograms" id="toc-faceted-histograms" class="nav-link" data-scroll-target="#faceted-histograms"><span class="header-section-number">6.2.2</span> Faceted histograms</a></li>
  <li><a href="#ridge-plots" id="toc-ridge-plots" class="nav-link" data-scroll-target="#ridge-plots"><span class="header-section-number">6.2.3</span> Ridge plots</a></li>
  </ul></li>
  <li><a href="#sec-two-numerical" id="toc-sec-two-numerical" class="nav-link" data-scroll-target="#sec-two-numerical"><span class="header-section-number">6.3</span> Two numerical variables</a>
  <ul class="collapse">
  <li><a href="#sec-scatterplots" id="toc-sec-scatterplots" class="nav-link" data-scroll-target="#sec-scatterplots"><span class="header-section-number">6.3.1</span> Scatterplots</a></li>
  <li><a href="#describing-associations" id="toc-describing-associations" class="nav-link" data-scroll-target="#describing-associations"><span class="header-section-number">6.3.2</span> Describing associations</a></li>
  <li><a href="#scatterplots-with-a-third-variable" id="toc-scatterplots-with-a-third-variable" class="nav-link" data-scroll-target="#scatterplots-with-a-third-variable"><span class="header-section-number">6.3.3</span> Scatterplots with a third variable</a></li>
  </ul></li>
  <li><a href="#sec-assoc-cause" id="toc-sec-assoc-cause" class="nav-link" data-scroll-target="#sec-assoc-cause"><span class="header-section-number">6.4</span> Association vs.&nbsp;causation</a>
  <ul class="collapse">
  <li><a href="#when-can-we-infer-causation" id="toc-when-can-we-infer-causation" class="nav-link" data-scroll-target="#when-can-we-infer-causation"><span class="header-section-number">6.4.1</span> When can we infer causation?</a></li>
  </ul></li>
  <li><a href="#sec-ch05-review" id="toc-sec-ch05-review" class="nav-link" data-scroll-target="#sec-ch05-review"><span class="header-section-number">6.5</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.5.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">6.5.2</span> Key terms</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">6.5.3</span> Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/ch05-relationships.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Extended Content.</strong> This chapter extends beyond UWL’s core STAT 145 curriculum. It is included for completeness and for instructors who wish to cover additional topics. Content is in draft form.</p>
</div>
</div>
</div>
<div class="chapterintro">
<p>The preceding chapters focused on exploring one variable at a time. But the most interesting statistical questions involve <strong>relationships between variables</strong>. Does higher education lead to higher income? Is a drug more effective for one group than another? Are two categorical variables associated? This chapter introduces tools for exploring relationships: contingency tables and mosaic plots for two categorical variables, side-by-side box plots and faceted histograms for a categorical and a numerical variable, and scatterplots for two numerical variables. We close with the critical distinction between association and causation.</p>
</div>
<div class="statbench">
<p><strong>StatBench tools for this chapter</strong>: Use the Two-Variable Explorer to create scatterplots, side-by-side box plots, and contingency tables. Upload a CSV dataset and select two variables to explore their relationship interactively.</p>
</div>
<section id="sec-two-categorical" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-two-categorical"><span class="header-section-number">6.1</span> Two categorical variables</h2>
<section id="contingency-tables" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">6.1.1</span> Contingency tables</h3>
<p>When we want to explore the relationship between two categorical variables, we organize the data in a <strong>contingency table</strong> (also called a two-way table or cross-tabulation). Each cell in the table shows the count of observations that belong to a particular combination of categories.</p>
<div class="definition">
<p>A <strong>contingency table</strong> summarizes data for two categorical variables. The rows represent the levels of one variable, the columns represent the levels of the other, and each cell contains the count of observations in that combination. <strong>Row totals</strong> and <strong>column totals</strong> give the marginal distributions.</p>
</div>
<p>Consider a dataset of 10,000 loans. Each loan has a homeownership status (<code>rent</code>, <code>mortgage</code>, or <code>own</code>) and an application type (<code>joint</code> or <code>individual</code>). The contingency table below summarizes these two variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">362</td>
<td style="text-align: right;">950</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">1,495</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">3,496</td>
<td style="text-align: right;">3,839</td>
<td style="text-align: right;">1,170</td>
<td style="text-align: right;">8,505</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>3,858</strong></td>
<td style="text-align: right;"><strong>4,789</strong></td>
<td style="text-align: right;"><strong>1,353</strong></td>
<td style="text-align: right;"><strong>10,000</strong></td>
</tr>
</tbody>
</table>
<p>Each cell represents a count. For example, 3,496 loans were made by individuals who rent their home. The row totals tell us that 1,495 loans were joint applications and 8,505 were individual applications. The column totals tell us the overall distribution of homeownership.</p>
<div class="guidedpractice">
<p>What does the value 950 in the table represent? What does the column total 4,789 represent?</p>
<details>
<summary>
Show answer
</summary>
The value 950 represents the number of loans that were joint applications from borrowers with a mortgage. The column total 4,789 represents the total number of borrowers (both joint and individual) who have a mortgage.
</details>
</div>
</section>
<section id="row-and-column-proportions" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="row-and-column-proportions"><span class="header-section-number">6.1.2</span> Row and column proportions</h3>
<p>Raw counts can be hard to compare when group sizes differ. Instead, we can compute <strong>row proportions</strong> or <strong>column proportions</strong> to see conditional relationships.</p>
<div class="definition">
<p><strong>Row proportions</strong> are computed by dividing each count by its row total. They show how a variable is distributed <em>within each level</em> of the row variable.</p>
<p><strong>Column proportions</strong> are computed by dividing each count by its column total. They show how a variable is distributed <em>within each level</em> of the column variable.</p>
<p>Both row and column proportions are examples of <strong>conditional proportions</strong> — the proportion of observations in one category, conditional on (given) the level of the other variable.</p>
</div>
<p><strong>Row proportions</strong> (each count divided by its row total):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">0.242</td>
<td style="text-align: right;">0.635</td>
<td style="text-align: right;">0.122</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: right;">0.451</td>
<td style="text-align: right;">0.138</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
<p>For example, <span class="math inline">\(3{,}496 / 8{,}505 = 0.411\)</span>, meaning 41.1% of individual applicants rent their home.</p>
<p><strong>Column proportions</strong> (each count divided by its column total):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">0.906</td>
<td style="text-align: right;">0.802</td>
<td style="text-align: right;">0.865</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
<p>The value 0.906 tells us that 90.6% of renters applied individually. This rate is higher than for borrowers with mortgages (80.2%) or who own their home (86.5%). Because these rates vary across the levels of homeownership, there is evidence that application type and homeownership may be <strong>associated</strong>.</p>
<div class="guidedpractice">
<p>What does 0.451 represent in the row proportions table? What does 0.802 represent in the column proportions table?</p>
<details>
<summary>
Show answer
</summary>
0.451 represents the proportion of individual applicants who have a mortgage. 0.802 represents the fraction of applicants with mortgages who applied as individuals.
</details>
</div>
<div class="workedexample">
<p>Data scientists use statistics to build email spam filters. One characteristic examined is email format (HTML or plain text). A contingency table of email format and spam status is shown below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">HTML</th>
<th style="text-align: right;">Text</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Not spam</td>
<td style="text-align: right;">2,568</td>
<td style="text-align: right;">986</td>
<td style="text-align: right;">3,554</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spam</td>
<td style="text-align: right;">158</td>
<td style="text-align: right;">209</td>
<td style="text-align: right;">367</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>2,726</strong></td>
<td style="text-align: right;"><strong>1,195</strong></td>
<td style="text-align: right;"><strong>3,921</strong></td>
</tr>
</tbody>
</table>
<p>Which would be more useful for classifying email: row or column proportions?</p>
<hr>
<p>A data scientist would want to know how the proportion of spam changes depending on email format. This corresponds to <strong>column proportions</strong>: <span class="math inline">\(209/1{,}195 = 17.5\%\)</span> of plain text emails are spam, compared to <span class="math inline">\(158/2{,}726 = 5.8\%\)</span> of HTML emails. Plain text emails are more likely to be spam. Row or column proportions are not equivalent — before computing, consider which variable you want to “condition on” (usually the explanatory variable).</p>
</div>
<div class="guidedpractice">
<p>In the spam example, which variable would you consider the explanatory variable and which the response?</p>
<details>
<summary>
Show answer
</summary>
Email format (HTML vs.&nbsp;text) is the explanatory variable — it is a characteristic of the email that might help explain or predict whether the email is spam. Spam status (spam vs.&nbsp;not spam) is the response variable.
</details>
</div>
</section>
<section id="bar-plots-for-two-categorical-variables" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="bar-plots-for-two-categorical-variables"><span class="header-section-number">6.1.3</span> Bar plots for two categorical variables</h3>
<p>Bar plots can be extended to display the relationship between two categorical variables. There are three common variants:</p>
<div class="definition">
<p>A <strong>stacked bar plot</strong> stacks the bars for the second variable on top of each other within each level of the first variable. It shows both the total count and the breakdown by the second variable.</p>
<p>A <strong>standardized bar plot</strong> (also called a <strong>filled bar plot</strong>) is like a stacked bar plot, but the bars are scaled to the same height (100%). It shows the <em>proportion</em> of each category of the second variable within each level of the first variable.</p>
<p>A <strong>dodged bar plot</strong> (also called a <strong>grouped bar plot</strong>) places bars for the second variable side by side within each level of the first variable. It makes it easy to compare counts across groups.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bar-types-stacked" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three bar plots displaying the relationship between homeownership (rent, mortgage, own) and application type (joint, individual). The stacked bar plot shows total counts with application types stacked. The standardized bar plot shows each bar at 100% height with proportional shading. The dodged bar plot places joint and individual bars side by side for each homeownership category.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bar-types-stacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-bar-types-stacked-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;6.1: Three bar plots showing homeownership and application type: stacked, standardized (filled), and dodged."><img src="ch05-relationships_files/figure-html/fig-bar-types-stacked-1.png" class="img-fluid figure-img" alt="Three bar plots displaying the relationship between homeownership (rent, mortgage, own) and application type (joint, individual). The stacked bar plot shows total counts with application types stacked. The standardized bar plot shows each bar at 100% height with proportional shading. The dodged bar plot places joint and individual bars side by side for each homeownership category." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bar-types-stacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Three bar plots showing homeownership and application type: stacked, standardized (filled), and dodged.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="workedexample">
<p>When is each type of bar plot most useful?</p>
<hr>
<ul>
<li>The <strong>stacked bar plot</strong> is most useful when you want to see both the total count for each group and the breakdown by the second variable. It works well when one variable is clearly the explanatory variable.</li>
<li>The <strong>standardized bar plot</strong> is helpful when comparing proportions across groups, especially when the groups have very different sizes. However, it sacrifices information about the total count.</li>
<li>The <strong>dodged bar plot</strong> makes it easy to compare individual counts directly. It works well for showing both variables without implying one is the explanatory variable. However, it requires more horizontal space and can feel cramped when there are many categories.</li>
</ul>
</div>
</section>
<section id="mosaic-plots" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="mosaic-plots"><span class="header-section-number">6.1.4</span> Mosaic plots</h3>
<p>A <strong>mosaic plot</strong> is a visualization for contingency tables that improves on the standardized bar plot by also encoding the <em>size</em> of each group. In a mosaic plot:</p>
<ul>
<li>The <em>width</em> of each column is proportional to the number of observations in that category of the first variable</li>
<li>The <em>height</em> of each section within a column is proportional to the conditional proportion of the second variable</li>
</ul>
<p>This means the <em>area</em> of each rectangle is proportional to the count in that cell of the contingency table.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mosaic-homeownership" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A mosaic plot with three columns (rent, mortgage, own). The mortgage column is widest, reflecting the largest group. Each column is divided into two sections: individual (top) and joint (bottom). The proportion of joint applications is slightly higher for mortgage holders than for renters or owners.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosaic-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-mosaic-homeownership-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;6.2: A mosaic plot of homeownership and application type. The width of each column reflects the number of borrowers in each homeownership category, and the height of each section reflects the proportion of joint vs.&nbsp;individual applications."><img src="ch05-relationships_files/figure-html/fig-mosaic-homeownership-1.png" class="img-fluid figure-img" alt="A mosaic plot with three columns (rent, mortgage, own). The mortgage column is widest, reflecting the largest group. Each column is divided into two sections: individual (top) and joint (bottom). The proportion of joint applications is slightly higher for mortgage holders than for renters or owners." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosaic-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: A mosaic plot of homeownership and application type. The width of each column reflects the number of borrowers in each homeownership category, and the height of each section reflects the proportion of joint vs.&nbsp;individual applications.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>In the mosaic plot, how can you tell whether homeownership and application type are associated?</p>
<details>
<summary>
Show answer
</summary>
If the variables were not associated, the division between joint and individual would occur at the same height in every column. Since the columns are divided at different heights — mortgage holders have a higher proportion of joint applications than renters or owners — the variables appear to be associated.
</details>
</div>
<div class="important">
<p><strong>Detecting association in a mosaic plot or standardized bar plot.</strong> If the proportional breakdown of the response variable is the <em>same</em> across all levels of the explanatory variable, then the variables are <strong>not</strong> associated. If the breakdown <em>differs</em> across levels, the variables are associated. In a mosaic plot, this means the horizontal dividing lines would be at different heights.</p>
</div>
</section>
</section>
<section id="sec-cat-num" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-cat-num"><span class="header-section-number">6.2</span> One categorical and one numerical variable</h2>
<p>Some of the most interesting investigations involve comparing a numerical variable across groups defined by a categorical variable.</p>
<section id="side-by-side-box-plots" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="side-by-side-box-plots"><span class="header-section-number">6.2.1</span> Side-by-side box plots</h3>
<p><strong>Side-by-side box plots</strong> place a box plot for each group on the same scale, making it easy to compare centers, spreads, and shapes.</p>
<p>Consider comparing median household income for US counties, grouped by whether the county experienced population growth from 2010 to 2017:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-income-popgain-ch05" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two horizontal box plots on the same scale. The gain group has a higher median (about 45,000 dollars) and slightly larger IQR than the no-gain group (median about 40,000 dollars). Both groups have several high-income outlier points.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-income-popgain-ch05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-boxplot-income-popgain-ch05-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;6.3: Side-by-side box plots of median household income by population change status (gain vs.&nbsp;no gain). Counties with population gain have a higher median income."><img src="ch05-relationships_files/figure-html/fig-boxplot-income-popgain-ch05-1.png" class="img-fluid figure-img" alt="Two horizontal box plots on the same scale. The gain group has a higher median (about 45,000 dollars) and slightly larger IQR than the no-gain group (median about 40,000 dollars). Both groups have several high-income outlier points." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-income-popgain-ch05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Side-by-side box plots of median household income by population change status (gain vs.&nbsp;no gain). Counties with population gain have a higher median income.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Using the box plots, compare the income distributions for the two groups. What do you notice about the centers, spreads, and shapes?</p>
<details>
<summary>
Show answer
</summary>
Counties with population gains tend to have higher income (median about $45,000) compared to counties without gains (median about $40,000). The variability is also slightly larger for the gain group, as seen in the wider IQR. Both distributions show slight to moderate right skew, with outliers on the high end.
</details>
</div>
</section>
<section id="faceted-histograms" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="faceted-histograms"><span class="header-section-number">6.2.2</span> Faceted histograms</h3>
<p><strong>Faceting</strong> splits a graphical display into panels based on the levels of a categorical variable. Each panel shows the distribution for one group, using the same scale for easy comparison.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-faceted-histogram-income" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two histograms arranged vertically, sharing the same horizontal axis (median household income). The top panel shows counties with population gain; the bottom panel shows counties with no gain. Both distributions are right skewed and unimodal, with the gain group shifted slightly to the right.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-faceted-histogram-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-faceted-histogram-income-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;6.4: Faceted histograms of median household income, separated into panels for counties with population gain and those with no gain."><img src="ch05-relationships_files/figure-html/fig-faceted-histogram-income-1.png" class="img-fluid figure-img" alt="Two histograms arranged vertically, sharing the same horizontal axis (median household income). The top panel shows counties with population gain; the bottom panel shows counties with no gain. Both distributions are right skewed and unimodal, with the gain group shifted slightly to the right." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-faceted-histogram-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Faceted histograms of median household income, separated into panels for counties with population gain and those with no gain.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Faceting extends naturally to multiple categorical variables. For example, we could split the income data by both population change <em>and</em> whether the county is in a metropolitan area, creating a 2-by-2 grid of histograms.</p>
<div class="workedexample">
<p>What are the advantages of faceted histograms compared to side-by-side box plots?</p>
<hr>
<p>Faceted histograms reveal the full shape of each distribution, including modality (unimodal vs.&nbsp;bimodal), the exact nature of any skewness, and gaps or clusters. Box plots, on the other hand, are more compact and make it easier to compare medians and IQRs at a glance, but they cannot show features like bimodality. The two displays complement each other well.</p>
</div>
</section>
<section id="ridge-plots" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="ridge-plots"><span class="header-section-number">6.2.3</span> Ridge plots</h3>
<div class="original">
<p>A <strong>ridge plot</strong> (also called a joy plot) is a set of overlapping density plots, one for each group, drawn on the same horizontal scale but offset vertically. Ridge plots are useful for comparing the shapes of many distributions at once while maintaining a compact display.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ridge-income" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two overlapping density curves arranged vertically. The curve for counties with population gain is shifted slightly to the right compared to the curve for counties with no gain, indicating higher median incomes in the gain group.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ridge-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-ridge-income-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;6.5: A ridge plot comparing median household income for counties with and without population gain. Each group gets its own smoothed density curve."><img src="ch05-relationships_files/figure-html/fig-ridge-income-1.png" class="img-fluid figure-img" alt="Two overlapping density curves arranged vertically. The curve for counties with population gain is shifted slightly to the right compared to the curve for counties with no gain, indicating higher median incomes in the gain group." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ridge-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: A ridge plot comparing median household income for counties with and without population gain. Each group gets its own smoothed density curve.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="guidedpractice">
<p>What does a ridge plot reveal that side-by-side box plots do not?</p>
<details>
<summary>
Show answer
</summary>
Ridge plots show the full shape of each distribution, including modality and skewness, similar to histograms. Box plots compress all of this shape information into a five-number summary. Ridge plots are especially useful when you want to compare shapes across many groups in a compact space.
</details>
</div>
</section>
</section>
<section id="sec-two-numerical" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-two-numerical"><span class="header-section-number">6.3</span> Two numerical variables</h2>
<section id="sec-scatterplots" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="sec-scatterplots"><span class="header-section-number">6.3.1</span> Scatterplots</h3>
<p>A <strong>scatterplot</strong> displays the relationship between two numerical variables. Each observation is represented as a point, with one variable on the horizontal axis and the other on the vertical axis.</p>
<div class="definition">
<p>A <strong>scatterplot</strong> provides a case-by-case view of data for two numerical variables. Each point represents one observation. The horizontal axis shows the values of one variable and the vertical axis shows the values of the other.</p>
</div>
<p>Consider a dataset of 50 loans, where we plot total income on the horizontal axis and loan amount on the vertical axis:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-loan-income" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatterplot with total income on the horizontal axis (ranging from about 0 to 350,000 dollars) and loan amount on the vertical axis (ranging from about 3,000 to 40,000 dollars). Points show a general upward trend — borrowers with higher incomes tend to take out larger loans — but with considerable scatter.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-loan-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-scatter-loan-income-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6.6: A scatterplot of loan amount versus total income for 50 loans. There is a moderate positive association."><img src="ch05-relationships_files/figure-html/fig-scatter-loan-income-1.png" class="img-fluid figure-img" alt="A scatterplot with total income on the horizontal axis (ranging from about 0 to 350,000 dollars) and loan amount on the vertical axis (ranging from about 3,000 to 40,000 dollars). Points show a general upward trend — borrowers with higher incomes tend to take out larger loans — but with considerable scatter." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-loan-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: A scatterplot of loan amount versus total income for 50 loans. There is a moderate positive association.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>What do scatterplots reveal about the data, and how are they useful?</p>
<details>
<summary>
Show answer
</summary>
Scatterplots are helpful for quickly spotting associations between two numerical variables — whether they tend to increase together, decrease together, or show no pattern. They can also reveal whether the relationship is linear or curved, how strong the association is, and whether there are any unusual points.
</details>
</div>
</section>
<section id="describing-associations" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="describing-associations"><span class="header-section-number">6.3.2</span> Describing associations</h3>
<p>When examining a scatterplot, we describe the association using four characteristics:</p>
<div class="important">
<p><strong>Describing the association between two numerical variables:</strong></p>
<ol type="1">
<li><p><strong>Direction</strong>: Is the association <strong>positive</strong> (both variables tend to increase together) or <strong>negative</strong> (one increases as the other decreases)?</p></li>
<li><p><strong>Form</strong>: Is the relationship approximately <strong>linear</strong> (following a straight-line pattern) or <strong>nonlinear</strong> (curved)?</p></li>
<li><p><strong>Strength</strong>: Is the association <strong>strong</strong> (points closely follow a pattern), <strong>moderate</strong>, or <strong>weak</strong> (points are loosely scattered)?</p></li>
<li><p><strong>Unusual observations</strong>: Are there any <strong>outliers</strong> — points that deviate markedly from the overall pattern?</p></li>
</ol>
</div>
<div class="workedexample">
<p>A scatterplot shows the poverty rate vs.&nbsp;median household income for over 3,000 US counties. How would you describe the association?</p>
<hr>
<p>The association is <strong>negative</strong> (as poverty rate increases, median household income tends to decrease), <strong>nonlinear</strong> (the relationship curves, with income decreasing more steeply at lower poverty rates and leveling off at higher poverty rates), and <strong>moderately strong</strong> (the points follow the curving pattern fairly closely, though there is noticeable scatter). There do not appear to be any extreme outliers, though counties with very high poverty rates or very high incomes stand out somewhat.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-income-poverty" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatterplot with poverty rate on the horizontal axis (ranging from about 0% to 50%) and median household income on the vertical axis (ranging from about 20,000 to over 120,000 dollars). The points show a clear negative, curved relationship. A dashed trend line curves downward from left to right.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-income-poverty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch05-relationships_files/figure-html/fig-scatter-income-poverty-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;6.7: A scatterplot of median household income versus poverty rate for US counties, with a curved trend line. The relationship is negative and nonlinear."><img src="ch05-relationships_files/figure-html/fig-scatter-income-poverty-1.png" class="img-fluid figure-img" alt="A scatterplot with poverty rate on the horizontal axis (ranging from about 0% to 50%) and median household income on the vertical axis (ranging from about 20,000 to over 120,000 dollars). The points show a clear negative, curved relationship. A dashed trend line curves downward from left to right." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-income-poverty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.7: A scatterplot of median household income versus poverty rate for US counties, with a curved trend line. The relationship is negative and nonlinear.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Describe two variables that would have a horseshoe-shaped (<span class="math inline">\(\cap\)</span>) association in a scatterplot.</p>
<details>
<summary>
Show answer
</summary>
Consider a situation where the vertical axis represents something “good” and the horizontal axis represents something that is good only in moderation. For example, health and water consumption: we need some water to survive, but consuming too much becomes dangerous. Athletic performance and practice time is another example — some practice improves performance, but overtraining leads to injury and decline.
</details>
</div>
<div class="workedexample">
<p>For the 50-loan dataset, the scatterplot of total income versus loan amount shows that borrowers with higher incomes tend to take out larger loans. Describe this association.</p>
<hr>
<p>The association is <strong>positive</strong> (higher income is associated with higher loan amounts), approximately <strong>linear</strong> (the general trend follows a straight line, though the pattern is loose), and <strong>weak to moderate</strong> (there is considerable scatter — many borrowers with similar incomes take out very different loan amounts). There are a few borrowers with income above $250,000 who stand out on the right side of the plot.</p>
</div>
</section>
<section id="scatterplots-with-a-third-variable" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="scatterplots-with-a-third-variable"><span class="header-section-number">6.3.3</span> Scatterplots with a third variable</h3>
<p>We can add a third variable to a scatterplot by using color, shape, or size to represent a categorical or numerical variable. For example, in a scatterplot of income vs.&nbsp;poverty rate, we could color the points by whether the county is in a metropolitan area. This technique helps reveal whether the relationship between two numerical variables differs across groups.</p>
</section>
</section>
<section id="sec-assoc-cause" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-assoc-cause"><span class="header-section-number">6.4</span> Association vs.&nbsp;causation</h2>
<div class="original">
<p>Throughout this chapter, we have explored associations between variables. But association is not the same as causation.</p>
</div>
<div class="important">
<p><strong>Association does not imply causation.</strong></p>
<p>When two variables are associated (correlated), it means they tend to vary together — but that does not necessarily mean one <em>causes</em> the other. There may be a <strong>confounding variable</strong> (a third variable) that is related to both, creating the illusion of a direct relationship.</p>
</div>
<div class="workedexample">
<p>A study finds a strong positive association between ice cream sales and drowning deaths. Does eating ice cream cause drowning?</p>
<hr>
<p>Of course not. The association exists because both ice cream sales and drowning are related to a confounding variable: <strong>temperature</strong> (or season). In hot weather, people buy more ice cream <em>and</em> more people go swimming, which increases the risk of drowning. Temperature is the lurking variable that drives both.</p>
</div>
<div class="definition">
<p>A <strong>confounding variable</strong> (also called a <strong>lurking variable</strong>) is a variable that is related to both the explanatory and response variables. Confounding variables can create misleading associations between two variables that have no direct causal relationship.</p>
</div>
<div class="guidedpractice">
<p>A study finds that students who eat breakfast tend to have higher GPAs than students who skip breakfast. Can we conclude that eating breakfast causes higher GPAs?</p>
<details>
<summary>
Show answer
</summary>
Not from this information alone. This is likely an observational study, and there could be confounding variables. For example, students who eat breakfast may come from more supportive home environments, may have better time management skills, or may generally take better care of their health — all of which could independently contribute to higher GPAs. To establish a causal connection, we would need a randomized experiment.
</details>
</div>
<section id="when-can-we-infer-causation" class="level3 original" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="when-can-we-infer-causation"><span class="header-section-number">6.4.1</span> When can we infer causation?</h3>
<p>Establishing a causal relationship between two variables generally requires:</p>
<ol type="1">
<li><p><strong>A randomized experiment</strong>: Randomly assigning subjects to treatment and control groups helps eliminate confounding variables. If a difference is observed between groups, we can more confidently attribute it to the treatment.</p></li>
<li><p><strong>Temporal precedence</strong>: The cause must precede the effect in time.</p></li>
<li><p><strong>Ruling out confounders</strong>: We must be able to argue that no lurking variables explain the observed association.</p></li>
</ol>
<p>In observational studies (where we observe but do not control the variables), we can identify associations but generally cannot draw causal conclusions. This is one of the most important distinctions in statistics.</p>
</section>
<div class="caution">
<p>Be especially skeptical of causal claims from observational data. Media reports often say “X causes Y” when the underlying study only found an association. Always ask: Was this a randomized experiment? Could there be confounding variables?</p>
</div>
</section>
<section id="sec-ch05-review" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-ch05-review"><span class="header-section-number">6.5</span> Chapter review</h2>
<section id="summary" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.5.1</span> Summary</h3>
<p>This chapter introduced tools for exploring relationships between variables. For <strong>two categorical variables</strong>, contingency tables organize counts, row and column proportions reveal conditional relationships, and bar plots (stacked, standardized, dodged) and mosaic plots provide visual comparisons. For <strong>one categorical and one numerical variable</strong>, side-by-side box plots, faceted histograms, and ridge plots compare distributions across groups. For <strong>two numerical variables</strong>, scatterplots reveal the direction, form, strength, and unusual features of an association. We closed with the fundamental principle that <strong>association does not imply causation</strong> — confounding variables can create misleading associations, and establishing causation generally requires a randomized experiment.</p>
</section>
<section id="key-terms" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">6.5.2</span> Key terms</h3>
<ul>
<li>Contingency table, row totals, column totals</li>
<li>Row proportions, column proportions, conditional proportions</li>
<li>Stacked bar plot, standardized (filled) bar plot, dodged bar plot</li>
<li>Mosaic plot</li>
<li>Side-by-side box plot, faceted plot, ridge plot</li>
<li>Scatterplot</li>
<li>Positive association, negative association</li>
<li>Linear, nonlinear</li>
<li>Direction, form, strength (of an association)</li>
<li>Confounding variable (lurking variable)</li>
<li>Association vs.&nbsp;causation</li>
</ul>
</section>
<section id="exercises" class="level3 exercises" data-number="6.5.3">
<h3 class="exercises anchored" data-number="6.5.3" data-anchor-id="exercises"><span class="header-section-number">6.5.3</span> Exercises</h3>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _04-ex-explore-categorical, _05-ex-explore-numerical -->
<ol type="1">
<li><p><strong>Black Lives Matter.</strong> A Washington Post-Schar School poll conducted in the United States in June 2020, among a random national sample of 1,006 adults, asked respondents whether they support or oppose protests following George Floyd’s killing that have taken place in cities across the US. The survey also collected information on the age of the respondents. <span class="citation" data-cites="survey:blmWaPoScar:2020">[@survey:blmWaPoScar:2020]</span> The results are summarized in the stacked bar plot below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch05-relationships_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="ch05-relationships_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Based on the stacked bar plot, do views on the protests and age appear to be associated? Explain your reasoning.</p></li>
<li><p>Conjecture other possible variables that might explain the potential association between these two variables.</p></li>
</ol></li>
</ol>
<!--- MOM ims-04-03
ims_exercise: "4.3"
title: "Black Lives Matter"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 4.3 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

QUESTION TYPE: multipart (numeric + multiple-choice)

========== COMMON CONTROL ==========
loadlibrary("stats")

// Generate a 5 x 5 contingency table: opinion (rows) x age group (cols)
// Opinion: Strongly support, Somewhat support, Somewhat oppose, Strongly oppose, No opinion
// Age: 18-29, 30-39, 40-49, 50-64, 65+
// Pattern: younger groups more supportive, older groups more opposed

// Strongly support row %s by age group (decreasing support with age)
$ss_18 = rand(50, 60)
$ss_30 = rand(38, 48)
$ss_40 = rand(45, 55)
$ss_50 = rand(40, 50)
$ss_65 = rand(36, 46)

// Somewhat support
$sw_18 = rand(22, 30)
$sw_30 = rand(30, 40)
$sw_40 = rand(22, 30)
$sw_50 = rand(25, 33)
$sw_65 = rand(17, 25)

// Strongly oppose (increasing with age)
$so_18 = rand(3, 8)
$so_30 = rand(6, 12)
$so_40 = rand(10, 16)
$so_50 = rand(14, 20)
$so_65 = rand(20, 28)

// Somewhat oppose
$wo_18 = rand(10, 16)
$wo_30 = rand(10, 16)
$wo_40 = rand(7, 13)
$wo_50 = rand(7, 13)
$wo_65 = rand(7, 13)

// No opinion (remainder)
$no_18 = 100 - $ss_18 - $sw_18 - $so_18 - $wo_18
$no_30 = 100 - $ss_30 - $sw_30 - $so_30 - $wo_30
$no_40 = 100 - $ss_40 - $sw_40 - $so_40 - $wo_40
$no_50 = 100 - $ss_50 - $sw_50 - $so_50 - $wo_50
$no_65 = 100 - $ss_65 - $sw_65 - $so_65 - $wo_65

// Part (a): Do views and age appear associated?
$choices_a = array(
  "Yes — the conditional proportions of support and opposition vary across age groups, suggesting association",
  "No — the proportions are roughly the same across all age groups",
  "Cannot determine association from a contingency table",
  "Yes — because both variables are categorical"
)

// Part (b): Which age group has the highest strong opposition?
$choices_b = array("18-29", "30-39", "40-49", "50-64", "65+")
$answer_b = "65+"

// Part (c): Possible confounding variable
$choices_c = array(
  "Geographic region — political views vary by region and are correlated with age demographics",
  "Hair color — it varies by person but has no connection to political views",
  "Favorite food — personal preference unrelated to protest views",
  "Shoe size — a physical characteristic unrelated to opinions"
)

========== QUESTION TEXT ==========
<p>A national survey of adults asked respondents whether they support or oppose recent protests following a high-profile incident. The survey also collected age information. The results (as percentages within each age group) are shown below.</p>


<table class="caption-top" data-quarto-postprocess="true" data-border="1" data-cellpadding="5" style="border-collapse: collapse;">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Opinion</td>
<td data-quarto-table-cell-role="th">18-29</td>
<td data-quarto-table-cell-role="th">30-39</td>
<td data-quarto-table-cell-role="th">40-49</td>
<td data-quarto-table-cell-role="th">50-64</td>
<td data-quarto-table-cell-role="th">65+</td>
</tr>
<tr class="even">
<td>Strongly support</td>
<td>$ss_18%</td>
<td>$ss_30%</td>
<td>$ss_40%</td>
<td>$ss_50%</td>
<td>$ss_65%</td>
</tr>
<tr class="odd">
<td>Somewhat support</td>
<td>$sw_18%</td>
<td>$sw_30%</td>
<td>$sw_40%</td>
<td>$sw_50%</td>
<td>$sw_65%</td>
</tr>
<tr class="even">
<td>Somewhat oppose</td>
<td>$wo_18%</td>
<td>$wo_30%</td>
<td>$wo_40%</td>
<td>$wo_50%</td>
<td>$wo_65%</td>
</tr>
<tr class="odd">
<td>Strongly oppose</td>
<td>$so_18%</td>
<td>$so_30%</td>
<td>$so_40%</td>
<td>$so_50%</td>
<td>$so_65%</td>
</tr>
<tr class="even">
<td>No opinion</td>
<td>$no_18%</td>
<td>$no_30%</td>
<td>$no_40%</td>
<td>$no_50%</td>
<td>$no_65%</td>
</tr>
</tbody>
</table>


<p>(a) Based on the table, do views on the protests and age appear to be associated? Explain.</p>
$answerbox[0]

<p>(b) Which age group has the highest percentage of "Strongly oppose"?</p>
$answerbox[1]

<p>(c) Which of the following could be a confounding variable that might explain the potential association between age and protest views?</p>
$answerbox[2]

========== ANSWER ==========
$displayformat[0] = "radio"
$choices[0] = $choices_a
$answer[0] = $choices_a[0]

$displayformat[1] = "radio"
$choices[1] = $choices_b
$answer[1] = $answer_b

$displayformat[2] = "radio"
$choices[2] = $choices_c
$answer[2] = $choices_c[0]

END MOM --->
<ol start="2" type="1">
<li><p><strong>Raise taxes.</strong> A random sample of registered voters nationally were asked whether they think it’s better to raise taxes on the rich or raise taxes on the poor. The survey also collected information on the political party affiliation of the respondents. <span class="citation" data-cites="survey:raiseTaxes:2015">[@survey:raiseTaxes:2015]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch05-relationships_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="ch05-relationships_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Based on the stacked bar plot shown above, do views on raising taxes and political affiliation appear to be associated? Explain your reasoning.</p></li>
<li><p>Conjecture other possible variables that might explain the potential association between these two variables.</p></li>
</ol></li>
</ol>
<!--- MOM ims-04-04
ims_exercise: "4.4"
title: "Raise taxes"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 4.4 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

QUESTION TYPE: multipart (numeric + multiple-choice)

========== COMMON CONTROL ==========
loadlibrary("stats")

// Generate a 3x3 contingency table: tax opinion x party affiliation
// Row: opinion (Raise taxes on rich, Raise taxes on poor, Not sure)
// Col: party (Democrat, Republican, Independent)
// Pattern: Democrats overwhelmingly favor taxing rich; Republicans more split

$n = rand(800, 1200)

// Party proportions
$p_dem = rrand(0.30, 0.40, 0.01)
$p_rep = rrand(0.28, 0.38, 0.01)
$p_ind = round(1 - $p_dem - $p_rep, 2)

$n_dem = round($p_dem * $n)
$n_rep = round($p_rep * $n)
$n_ind = $n - $n_dem - $n_rep

// Within Democrat: high support for taxing rich
$dem_rich_pct = rand(85, 95)
$dem_poor_pct = rand(2, 6)
$dem_unsure_pct = 100 - $dem_rich_pct - $dem_poor_pct
$dem_rich = round($dem_rich_pct / 100 * $n_dem)
$dem_poor = round($dem_poor_pct / 100 * $n_dem)
$dem_unsure = $n_dem - $dem_rich - $dem_poor

// Within Republican: more split
$rep_rich_pct = rand(40, 55)
$rep_poor_pct = rand(6, 14)
$rep_unsure_pct = 100 - $rep_rich_pct - $rep_poor_pct
$rep_rich = round($rep_rich_pct / 100 * $n_rep)
$rep_poor = round($rep_poor_pct / 100 * $n_rep)
$rep_unsure = $n_rep - $rep_rich - $rep_poor

// Within Independent: moderate
$ind_rich_pct = rand(42, 56)
$ind_poor_pct = rand(8, 15)
$ind_unsure_pct = 100 - $ind_rich_pct - $ind_poor_pct
$ind_rich = round($ind_rich_pct / 100 * $n_ind)
$ind_poor = round($ind_poor_pct / 100 * $n_ind)
$ind_unsure = $n_ind - $ind_rich - $ind_poor

// Totals
$tot_rich = $dem_rich + $rep_rich + $ind_rich
$tot_poor = $dem_poor + $rep_poor + $ind_poor
$tot_unsure = $dem_unsure + $rep_unsure + $ind_unsure

// Answers
// (a) % of Democrats who favor taxing the rich
$pct_dem_rich = round($dem_rich / $n_dem * 100, 1)
// (b) % of Republicans who favor taxing the rich
$pct_rep_rich = round($rep_rich / $n_rep * 100, 1)
// (c) % of Independents who favor taxing the rich
$pct_ind_rich = round($ind_rich / $n_ind * 100, 1)

// (d) Association question
$choices_d = array(
  "Yes — the conditional proportions vary substantially across political parties, suggesting the variables are associated",
  "No — the proportions are approximately the same across all three parties",
  "Cannot be determined from a contingency table",
  "Yes — because both variables are categorical, they must be associated"
)

// (e) Possible confounding variable
$choices_e = array(
  "Income level — it may be associated with both party affiliation and views on taxation",
  "Favorite color — it is unrelated to tax policy preferences",
  "Height — a physical characteristic unrelated to political views",
  "Number of pets — not clearly connected to tax opinions"
)

$abstolerance = 0.5

========== QUESTION TEXT ==========
<p>A random sample of $n registered voters were asked whether it is better to raise taxes on the rich or raise taxes on the poor. The survey also collected party affiliation. Results are shown below.</p>


<table class="caption-top" data-quarto-postprocess="true" data-border="1" data-cellpadding="5" style="border-collapse: collapse;">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Opinion</td>
<td data-quarto-table-cell-role="th">Democrat</td>
<td data-quarto-table-cell-role="th">Republican</td>
<td data-quarto-table-cell-role="th">Independent</td>
<td data-quarto-table-cell-role="th">Total</td>
</tr>
<tr class="even">
<td>Raise taxes on the rich</td>
<td>$dem_rich</td>
<td>$rep_rich</td>
<td>$ind_rich</td>
<td>$tot_rich</td>
</tr>
<tr class="odd">
<td>Raise taxes on the poor</td>
<td>$dem_poor</td>
<td>$rep_poor</td>
<td>$ind_poor</td>
<td>$tot_poor</td>
</tr>
<tr class="even">
<td>Not sure</td>
<td>$dem_unsure</td>
<td>$rep_unsure</td>
<td>$ind_unsure</td>
<td>$tot_unsure</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>$n_dem</td>
<td>$n_rep</td>
<td>$n_ind</td>
<td>$n</td>
</tr>
</tbody>
</table>


<p>(a) What percent of Democrats favor raising taxes on the rich? $answerbox[0]</p>
<p>(b) What percent of Republicans favor raising taxes on the rich? $answerbox[1]</p>
<p>(c) What percent of Independents favor raising taxes on the rich? $answerbox[2]</p>
<p>(d) Based on the table, do views on raising taxes and political affiliation appear to be associated?</p>
$answerbox[3]
<p>(e) Which of the following could be a confounding variable?</p>
$answerbox[4]

========== ANSWER ==========
$answer[0] = $pct_dem_rich
$answer[1] = $pct_rep_rich
$answer[2] = $pct_ind_rich

$displayformat[3] = "radio"
$choices[3] = $choices_d
$answer[3] = $choices_d[0]

$displayformat[4] = "radio"
$choices[4] = $choices_e
$answer[4] = $choices_e[0]

END MOM --->
<ol start="3" type="1">
<li><p><strong>Meat consumption and life expectancy.</strong> In data collected for <span class="citation" data-cites="You:2022">@You:2022</span>, total meat intake is associated with life expectancy (at birth) in 175 countries. Meat intake is measured in kg per capita per year (averaged over 2011 to 2013). The two ridge plots show an association between income and meat consumption (higher income countries tend to eat more meat) and an association between income and life expectancy (higher income countries have higher life expectancy).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch05-relationships_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="ch05-relationships_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Do the graphs above demonstrate that meat consumption and life expectancy are associated? That is, can you tell if countries with low meat consumption have low life expectancy? Explain.</p></li>
<li><p>Let’s assume that you had a plot comparing meat consumption and life expectancy, and they <em>do</em> seem associated. Your friend says that the plot shows that high meat consumption leads to a longer life. You correctly say, no, we can’t tell if there is a causal realtionship because the relationship is confounded by income level. Explain what you mean.</p></li>
<li><p>How can you investigate the relationship between meat consumption and life expectancy in the presence of confounding variables (like income)?</p></li>
</ol></li>
</ol>
<!--- MOM ims-04-07
ims_exercise: "4.7"
title: "Meat consumption and life expectancy"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 4.7 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

QUESTION TYPE: multipart (multiple-choice, conceptual about confounding)

========== COMMON CONTROL ==========
loadlibrary("stats")

// Present summary data about 3 income groups: meat consumption and life expectancy
// Both increase with income, creating confounding
$lo_meat = rand(15, 30)
$mid_meat = rand(35, 55)
$hi_meat = rand(60, 90)

$lo_life = rrand(55, 65, 0.1)
$mid_life = rrand(68, 74, 0.1)
$hi_life = rrand(76, 83, 0.1)

// Part (a): Can we conclude association between meat and life expectancy from this data?
$choices_a = array(
  "No — the data show that both meat consumption and life expectancy are associated with income, but we cannot directly compare meat consumption to life expectancy from these summaries alone",
  "Yes — because both variables increase with income, meat consumption must cause longer life",
  "Yes — the data clearly show that eating more meat leads to living longer",
  "No — because the sample sizes are too small"
)

// Part (b): Friend says high meat consumption leads to longer life. Why is this wrong?
$choices_b = array(
  "Income is a confounding variable — wealthier countries tend to both eat more meat and have higher life expectancy due to better healthcare, sanitation, etc.",
  "The data are wrong because meat consumption cannot affect life expectancy",
  "The sample is biased because only wealthy countries were included",
  "Correlation always equals causation, so the friend is actually correct"
)

// Part (c): How to investigate in the presence of confounding?
$choices_c = array(
  "Compare meat consumption and life expectancy within countries of similar income levels (stratify by the confounding variable)",
  "Ignore income and just look at the overall correlation",
  "Only study countries with high income",
  "Remove all confounding variables from the dataset"
)

========== QUESTION TEXT ==========
<p>Researchers studied meat consumption and life expectancy across 175 countries, grouped by income level. The summary data are shown below.</p>


<table class="caption-top" data-quarto-postprocess="true" data-border="1" data-cellpadding="5" style="border-collapse: collapse;">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Income Level</td>
<td data-quarto-table-cell-role="th">Avg. Meat Consumption (kg/capita/yr)</td>
<td data-quarto-table-cell-role="th">Avg. Life Expectancy (years)</td>
</tr>
<tr class="even">
<td>Low income</td>
<td>$lo_meat</td>
<td>$lo_life</td>
</tr>
<tr class="odd">
<td>Middle income</td>
<td>$mid_meat</td>
<td>$mid_life</td>
</tr>
<tr class="even">
<td>High income</td>
<td>$hi_meat</td>
<td>$hi_life</td>
</tr>
</tbody>
</table>


<p>(a) Can we conclude from this table that meat consumption and life expectancy are directly associated (i.e., that countries eating more meat have higher life expectancy)?</p>
$answerbox[0]

<p>(b) Suppose you had data showing a positive correlation between meat consumption and life expectancy. A friend says this proves that eating more meat leads to a longer life. Why is this reasoning flawed?</p>
$answerbox[1]

<p>(c) How could you investigate the relationship between meat consumption and life expectancy in the presence of the confounding variable (income)?</p>
$answerbox[2]

========== ANSWER ==========
$displayformat[0] = "radio"
$choices[0] = $choices_a
$answer[0] = $choices_a[0]

$displayformat[1] = "radio"
$choices[1] = $choices_b
$answer[1] = $choices_b[0]

$displayformat[2] = "radio"
$choices[2] = $choices_c
$answer[2] = $choices_c[0]

END MOM --->
<ol start="4" type="1">
<li><p><strong>On-time arrivals.</strong> Consider all of the flights out of New York City in 2013 that flew into Puerto Rico (BQN), Los Angeles (LAX), or San Francisco (SFO) on the following two airlines: JetBlue (B6) or United Airlines (UA). Below are the tabulated counts for the number of flights <code>delayed</code> and <code>on time</code> for each airline into each city.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">dest</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">carrier</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">status</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">271</td>
</tr>
<tr class="even">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="even">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">151</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">670</td>
</tr>
<tr class="even">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">999</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">2368</td>
</tr>
<tr class="even">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">3402</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">405</td>
</tr>
<tr class="even">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">615</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">2694</td>
</tr>
<tr class="even">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">4034</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What percent of all JetBlue flights were delayed? What percent of all United Airlines flights were delayed? (Note, the overall delay proportions are typically what would be reported and associated with an airline.)</p></li>
<li><p>For each of the three airports, find the percent of delayed flights for each of JetBlue and United (you should have 6 numbers).</p></li>
<li><p>United has a higher proportion of delayed flights for each of the three cities, yet JetBlue has a higher proportion of delayed flights overall. Explain, using the data counts provided, how the seeming paradox could happen.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p></li>
</ol></li>
</ol>
<!--- MOM ims-04-09
ims_exercise: "4.9"
title: "On-time arrivals"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 4.9 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

QUESTION TYPE: multipart (number for each part)

========== COMMON CONTROL ==========
loadlibrary("stats")

// Simpson's paradox: two airlines, three destinations
// Airline A has worse overall delay rate but better rate at each airport
// Key: Airline A flies mostly to the hard airport; Airline B flies mostly to easy airports

// Destination 1 (hard airport — high delay rate)
$d1_delay_rate_A = rrand(0.43, 0.48, 0.01)
$d1_delay_rate_B = rrand(0.49, 0.55, 0.01)
$d1_nA = rand(600, 900)
$d1_nB = rand(50, 120)
$d1_delA = round($d1_delay_rate_A * $d1_nA)
$d1_onA = $d1_nA - $d1_delA
$d1_delB = round($d1_delay_rate_B * $d1_nB)
$d1_onB = $d1_nB - $d1_delB

// Destination 2 (medium airport)
$d2_delay_rate_A = rrand(0.37, 0.42, 0.01)
$d2_delay_rate_B = rrand(0.43, 0.48, 0.01)
$d2_nA = rand(200, 400)
$d2_nB = rand(400, 700)
$d2_delA = round($d2_delay_rate_A * $d2_nA)
$d2_onA = $d2_nA - $d2_delA
$d2_delB = round($d2_delay_rate_B * $d2_nB)
$d2_onB = $d2_nB - $d2_delB

// Destination 3 (easy airport — low delay rate)
$d3_delay_rate_A = rrand(0.30, 0.37, 0.01)
$d3_delay_rate_B = rrand(0.38, 0.43, 0.01)
$d3_nA = rand(50, 150)
$d3_nB = rand(500, 800)
$d3_delA = round($d3_delay_rate_A * $d3_nA)
$d3_onA = $d3_nA - $d3_delA
$d3_delB = round($d3_delay_rate_B * $d3_nB)
$d3_onB = $d3_nB - $d3_delB

// Overall totals
$tot_delA = $d1_delA + $d2_delA + $d3_delA
$tot_nA = $d1_nA + $d2_nA + $d3_nA
$tot_onA = $tot_nA - $tot_delA

$tot_delB = $d1_delB + $d2_delB + $d3_delB
$tot_nB = $d1_nB + $d2_nB + $d3_nB
$tot_onB = $tot_nB - $tot_delB

// Part (a): overall % delayed for each airline
$pct_delA = round($tot_delA / $tot_nA * 100, 1)
$pct_delB = round($tot_delB / $tot_nB * 100, 1)

// Part (b): % delayed at each destination for each airline
$pct_d1_A = round($d1_delA / $d1_nA * 100, 1)
$pct_d1_B = round($d1_delB / $d1_nB * 100, 1)
$pct_d2_A = round($d2_delA / $d2_nA * 100, 1)
$pct_d2_B = round($d2_delB / $d2_nB * 100, 1)
$pct_d3_A = round($d3_delA / $d3_nA * 100, 1)
$pct_d3_B = round($d3_delB / $d3_nB * 100, 1)

$abstolerance = 0.5

========== QUESTION TEXT ==========
<p>Consider all flights from a city to three destinations (Airport 1, Airport 2, Airport 3) on two airlines: Airline A and Airline B. The table below shows the number of delayed and on-time flights.</p>


<table class="caption-top" data-quarto-postprocess="true" data-border="1" data-cellpadding="5" style="border-collapse: collapse;">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Destination</td>
<td data-quarto-table-cell-role="th">Airline</td>
<td data-quarto-table-cell-role="th">Delayed</td>
<td data-quarto-table-cell-role="th">On time</td>
<td data-quarto-table-cell-role="th">Total</td>
</tr>
<tr class="even">
<td rowspan="2">Airport 1</td>
<td>A</td>
<td>$d1_delA</td>
<td>$d1_onA</td>
<td>$d1_nA</td>
</tr>
<tr class="odd">
<td>B</td>
<td>$d1_delB</td>
<td>$d1_onB</td>
<td>$d1_nB</td>
</tr>
<tr class="even">
<td rowspan="2">Airport 2</td>
<td>A</td>
<td>$d2_delA</td>
<td>$d2_onA</td>
<td>$d2_nA</td>
</tr>
<tr class="odd">
<td>B</td>
<td>$d2_delB</td>
<td>$d2_onB</td>
<td>$d2_nB</td>
</tr>
<tr class="even">
<td rowspan="2">Airport 3</td>
<td>A</td>
<td>$d3_delA</td>
<td>$d3_onA</td>
<td>$d3_nA</td>
</tr>
<tr class="odd">
<td>B</td>
<td>$d3_delB</td>
<td>$d3_onB</td>
<td>$d3_nB</td>
</tr>
</tbody>
</table>


<p>(a) What percent of <b>all</b> Airline A flights were delayed? $answerbox[0]</p>
<p>(b) What percent of <b>all</b> Airline B flights were delayed? $answerbox[1]</p>
<p>(c) For Airport 1, what percent of Airline A flights were delayed? $answerbox[2]</p>
<p>(d) For Airport 1, what percent of Airline B flights were delayed? $answerbox[3]</p>
<p>(e) For Airport 2, what percent of Airline A flights were delayed? $answerbox[4]</p>
<p>(f) For Airport 2, what percent of Airline B flights were delayed? $answerbox[5]</p>
<p>(g) For Airport 3, what percent of Airline A flights were delayed? $answerbox[6]</p>
<p>(h) For Airport 3, what percent of Airline B flights were delayed? $answerbox[7]</p>

========== ANSWER ==========
$answer[0] = $pct_delA
$answer[1] = $pct_delB
$answer[2] = $pct_d1_A
$answer[3] = $pct_d1_B
$answer[4] = $pct_d2_A
$answer[5] = $pct_d2_B
$answer[6] = $pct_d3_A
$answer[7] = $pct_d3_B

END MOM --->
<ol start="5" type="1">
<li><p><strong>US House of Representatives.</strong> The US House of Representatives is dominated by two political parties: Democrats and Republicans. Democrats are thought to be the more liberal party and Republicans are considered to be the more conservative party. However, within each party there is an internal spectrum of liberal to conservative. For example, conservative Democrats and liberal Republicans would be labeled moderate. Consider an election where the only change in membership is that the most conservative Democrats are replaced by a set of liberal Republicans who are more liberal than the incumbent Republicans but more conservative than the Democrats they replaced.</p>
<ol type="a">
<li><p>After the election, is the Democratic wing of the House more conservative or more liberal? Explain.</p></li>
<li><p>After the election, is the Republican wing of the House more conservative or more liberal? Explain.</p></li>
<li><p>After the election, is the overall House membership more conservative or more liberal? Explain.</p></li>
<li><p>In what settings would you report the outcome of the change in House membership to be more conservative? And in what settings would you report the outcome of the change in House membership to be more liberal?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p></li>
</ol></li>
</ol>
<!--- MOM ims-04-10
ims_exercise: "4.10"
title: "US House of Representatives"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 4.10 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

QUESTION TYPE: multipart (multiple-choice, Simpson's paradox thought experiment)

========== COMMON CONTROL ==========
loadlibrary("stats")

// Simpson's paradox thought experiment:
// Some members of Party A (the most conservative ones) are replaced by
// members of Party B who are more liberal than existing Party B members
// but more conservative than the Party A members they replaced.

$party_pool = array(
  array("Democrats", "Republicans", "conservative", "liberal"),
  array("Party A", "Party B", "conservative", "liberal"),
  array("the Blue Party", "the Red Party", "right-leaning", "left-leaning")
)
$pidx = rand(0, count($party_pool)-1)
$partyA = $party_pool[$pidx][0]
$partyB = $party_pool[$pidx][1]
$dirA = $party_pool[$pidx][2]
$dirB = $party_pool[$pidx][3]

// Part (a): After the change, is Party A (e.g., Democrats) more liberal or conservative?
$choices_a = array(
  "More $dirB — because the most $dirA members of $partyA were removed, shifting the remaining membership toward the $dirB end",
  "More $dirA — because losing members always makes a party more $dirA",
  "No change — the composition of $partyA is not affected",
  "Cannot be determined from this information"
)

// Part (b): After the change, is Party B (e.g., Republicans) more liberal or conservative?
$choices_b = array(
  "More $dirB — because the new members added to $partyB are more $dirB than the existing $partyB members",
  "More $dirA — because gaining new members always makes a party more $dirA",
  "No change — adding members does not affect the party's ideological center",
  "Cannot be determined from this information"
)

// Part (c): Is the overall body more liberal or conservative?
$choices_c = array(
  "More $dirA — because the new $partyB members who replaced the old $partyA members are more $dirA than those they replaced, shifting the overall body in the $dirA direction",
  "More $dirB — because both individual parties became more $dirB",
  "No change — gains and losses cancel out",
  "Cannot be determined from this information"
)

// Part (d): Simpson's paradox identification
$choices_d = array(
  "This is an example of Simpson's paradox: each subgroup ($partyA and $partyB individually) shifted in one direction ($dirB), but the overall body shifted in the opposite direction ($dirA)",
  "This is an example of confirmation bias",
  "This is an example of selection bias",
  "This is not a paradox — the results are completely consistent"
)

========== QUESTION TEXT ==========
<p>A legislative body is composed of two parties: $partyA and $partyB. $partyA is generally considered more $dirB and $partyB more $dirA, but within each party there is a spectrum.</p>

<p>Consider an election where the only change is: the most $dirA members of $partyA are replaced by new $partyB members who are more $dirB than the existing $partyB members but more $dirA than the $partyA members they replaced.</p>

<p>(a) After the election, is $partyA more $dirA or more $dirB?</p>
$answerbox[0]

<p>(b) After the election, is $partyB more $dirA or more $dirB?</p>
$answerbox[1]

<p>(c) After the election, is the <b>overall</b> legislative body more $dirA or more $dirB?</p>
$answerbox[2]

<p>(d) What statistical phenomenon does this illustrate?</p>
$answerbox[3]

========== ANSWER ==========
$displayformat[0] = "radio"
$choices[0] = $choices_a
$answer[0] = $choices_a[0]

$displayformat[1] = "radio"
$choices[1] = $choices_b
$answer[1] = $choices_b[0]

$displayformat[2] = "radio"
$choices[2] = $choices_c
$answer[2] = $choices_c[0]

$displayformat[3] = "radio"
$choices[3] = $choices_d
$answer[3] = $choices_d[0]

END MOM --->
<ol start="6" type="1">
<li><p><strong>Mammal life spans.</strong> Data were collected on life spans (in years) and gestation lengths (in days) for 62 mammals. A scatterplot of life span versus length of gestation is shown below.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="citation" data-cites="Allison+Cicchetti:1975">[@Allison+Cicchetti:1975]</span></p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.5, -0.02, 0.43]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="questions" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ol type="a">
<li><p>What type of an association is apparent between life span and length of gestation?</p></li>
<li><p>What type of an association would you expect to see if the axes of the plot were reversed, i.e., if we plotted length of gestation versus life span?</p></li>
<li><p>Are life span and length of gestation independent? Explain your reasoning.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 43.0%;justify-content: flex-start;">
<div class="cell" data-layout-align="right">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-right">
<figure class="figure">
<p><a href="ch05-relationships_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="ch05-relationships_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-right figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div></li>
</ol>
<!--- MOM ims-05-01
ims_exercise: "5.1"
title: "Mammal life spans"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.1 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate a scatterplot with a positive, roughly linear association
// (mimicking life span vs gestation)
$n = rand(40, 70)
$x = array()
$y = array()
for ($i = 0; $i < $n; $i++) {
  $x[$i] = round(rand(15, 600))
  $y[$i] = round(0.03 * $x[$i] + normrand(0, 3, 1, 1)[0] + rand(1, 8), 1)
  if ($y[$i] < 0.5) { $y[$i] = round(rrand(0.5, 3.0, 0.1), 1); }
}

$scatter = scatterplot($x, $y)

// Correlation to confirm direction
$reg = linreg($x, $y)
$r = round($reg[0], 3)

// Association type
$assoc_type = ($r > 0) ? "Positive" : "Negative"

$assoc_choices = array("Positive", "Negative", "No association")
$yn_choices = array("Yes", "No")

// === Question Text ===
// <p>Data were collected on two numerical variables for $n observations.
// A scatterplot of Variable Y versus Variable X is shown below.</p>
//
// $scatter
//
// <p><b>(a)</b> What type of association is apparent between X and Y?</p>
// $answerbox[0]
//
// <p><b>(b)</b> If we reversed the axes (plotted X versus Y), would the
// type of association change?</p>
// $answerbox[1]
//
// <p><b>(c)</b> Based on the scatterplot, do X and Y appear to be independent?</p>
// $answerbox[2]

// === Answer ===
$answer[0] = $assoc_type
$displayformat[0] = "radio"
$answerformat[0] = "list"
$questions[0] = $assoc_choices

$answer[1] = "No"
$displayformat[1] = "radio"
$answerformat[1] = "list"
$questions[1] = array("Yes", "No")

$answer[2] = "No"
$displayformat[2] = "radio"
$answerformat[2] = "list"
$questions[2] = $yn_choices
$showanswer[2] = "Because there is an apparent association, the variables are not independent."

END MOM --->
<ol start="7" type="1">
<li><p><strong>Associations.</strong> Indicate which of the plots show (a) a positive association, (b) a negative association, or (c) no association. Also determine if the positive and negative associations are linear or nonlinear. Each part may refer to more than one plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch05-relationships_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="ch05-relationships_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div></li>
</ol>
<!--- MOM ims-05-02
ims_exercise: "5.2"
title: "Associations"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.2 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate four scatterplots: positive linear, no association, positive curved, negative linear
$n = 80

// Plot 1: Positive linear
$x1 = array()
$y1 = array()
for ($i = 0; $i < $n; $i++) {
  $x1[$i] = rrand(0, 10, 0.1)
  $y1[$i] = round(2.5 * $x1[$i] + normrand(0, 5, 1, 1)[0], 1)
}
$plot1 = scatterplot($x1, $y1)

// Plot 2: No association
$x2 = array()
$y2 = array()
for ($i = 0; $i < $n; $i++) {
  $x2[$i] = rrand(0, 10, 0.1)
  $y2[$i] = round(normrand(0, 15, 1, 1)[0], 1)
}
$plot2 = scatterplot($x2, $y2)

// Plot 3: Positive curved (quadratic)
$x3 = array()
$y3 = array()
for ($i = 0; $i < $n; $i++) {
  $x3[$i] = rrand(0, 10, 0.1)
  $y3[$i] = round($x3[$i] * $x3[$i] + normrand(0, 4, 1, 1)[0], 1)
}
$plot3 = scatterplot($x3, $y3)

// Plot 4: Negative linear
$x4 = array()
$y4 = array()
for ($i = 0; $i < $n; $i++) {
  $x4[$i] = rrand(0, 10, 0.1)
  $y4[$i] = round(-3 * $x4[$i] + 30 + normrand(0, 5, 1, 1)[0], 1)
}
$plot4 = scatterplot($x4, $y4)

$assoc_choices = array("Positive linear", "Positive nonlinear", "Negative linear", "Negative nonlinear", "No association")

// === Question Text ===
// <p>Examine each of the four scatterplots below and identify the type of
// association shown.</p>
//
// <p><b>Plot (1):</b></p>
// $plot1
// <p>Association: $answerbox[0]</p>
//
// <p><b>Plot (2):</b></p>
// $plot2
// <p>Association: $answerbox[1]</p>
//
// <p><b>Plot (3):</b></p>
// $plot3
// <p>Association: $answerbox[2]</p>
//
// <p><b>Plot (4):</b></p>
// $plot4
// <p>Association: $answerbox[3]</p>

// === Answer ===
$answer[0] = "Positive linear"
$displayformat[0] = "radio"
$answerformat[0] = "list"
$questions[0] = $assoc_choices

$answer[1] = "No association"
$displayformat[1] = "radio"
$answerformat[1] = "list"
$questions[1] = $assoc_choices

$answer[2] = "Positive nonlinear"
$displayformat[2] = "radio"
$answerformat[2] = "list"
$questions[2] = $assoc_choices

$answer[3] = "Negative linear"
$displayformat[3] = "radio"
$answerformat[3] = "list"
$questions[3] = $assoc_choices

END MOM --->
<ol start="8" type="1">
<li><strong>Reproducing bacteria.</strong> Suppose that there is only sufficient space and nutrients to support one million bacterial cells in a petri dish. You place a few bacterial cells in this petri dish, allow them to reproduce freely, and record the number of bacterial cells in the dish over time. Sketch a plot representing the relationship between number of bacterial cells and time.</li>
</ol>
<!--- MOM ims-05-03
ims_exercise: "5.3"
title: "Reproducing bacteria"
type: multiple_choice
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.3 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
$capacity = randfrom(500000, 1000000, 2000000, 5000000)
$cap_display = number_format($capacity)

// === Question Text ===
// <p>Suppose there is only sufficient space and nutrients to support
// $cap_display bacterial cells in a petri dish. You place a few bacterial
// cells in the dish, allow them to reproduce freely, and track the
// number of cells over time.</p>
//
// <p>Which of the following best describes the expected shape of the
// relationship between the number of bacterial cells and time?</p>
// $answerbox

// === Answer ===
$answer = "S-shaped (logistic) — slow growth initially, rapid exponential growth in the middle, then leveling off near the carrying capacity"
$displayformat = "radio"
$answerformat = "list"
$questions = array("S-shaped (logistic) — slow growth initially, rapid exponential growth in the middle, then leveling off near the carrying capacity", "Linear — the number of bacteria increases at a constant rate over time", "Exponential — the number of bacteria increases faster and faster without bound", "Decreasing — the bacteria die off over time as resources deplete")
$showanswer = "Bacteria grow exponentially at first, but as they approach the carrying capacity of the dish, growth slows and the population levels off, producing an S-shaped (logistic) curve."

END MOM --->
<ol start="9" type="1">
<li><strong>Office productivity.</strong> Office productivity is relatively low when the employees feel no stress about their work or job security. However, high levels of stress can also lead to reduced employee productivity. Sketch a plot to represent the relationship between stress and productivity.</li>
</ol>
<!--- MOM ims-05-04
ims_exercise: "5.4"
title: "Office productivity"
type: multiple_choice
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.4 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Conceptual question: low stress = low productivity, high stress = low productivity,
// moderate stress = peak productivity => inverted U (nonlinear)

// === Question Text ===
// <p>Office productivity is relatively low when employees feel no stress about
// their work or job security. However, high levels of stress can also lead to
// reduced employee productivity.</p>
//
// <p>Which of the following best describes the expected shape of the relationship
// between stress level and productivity?</p>
// $answerbox

// === Answer ===
$answer = "An inverted U-shape (nonlinear) — productivity increases with moderate stress but decreases at high stress"
$displayformat = "radio"
$answerformat = "list"
$questions = array("An inverted U-shape (nonlinear) — productivity increases with moderate stress but decreases at high stress", "A positive linear relationship — more stress always leads to more productivity", "A negative linear relationship — more stress always leads to less productivity", "No association — stress and productivity are unrelated")
$showanswer = "Since both very low and very high stress lead to low productivity, while moderate stress leads to peak productivity, the relationship forms an inverted U-shape (also known as the Yerkes–Dodson curve). This is a nonlinear association."

END MOM --->
<ol start="10" type="1">
<li><strong>Oscar winners.</strong> The first Oscar awards for best actor and best actress were given out in 1929. The histograms below show the age distribution for all of the best actor and best actress winners from 1929 to 2019. Summary statistics for these distributions are also provided. Compare the distributions of ages of best actor and actress winners.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></li>
</ol>
<pre><code>:::: {layout="[-0.05, 0.6, 0.35]"}

:::{#plot}




::: {.cell}
::: {.cell-output-display}
![](ch05-relationships_files/figure-html/unnamed-chunk-8-1.png){width=1500}
:::
:::




:::
:::{#table}




::: {.cell}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Best actor &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 43.8 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 8.8 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 92 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Best actress &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 36.2 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 11.9 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 92 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::




:::
::::</code></pre>
<!--- MOM ims-05-20
ims_exercise: "5.20"
title: "Oscar winners"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.20 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate two groups resembling Oscar-winner age distributions
// Group A (like Best Actor): right-skewed, centered higher
$nA = rand(80, 100)
$groupA = normrand(44, 9, $nA, 0, 1, 1)

// Group B (like Best Actress): right-skewed, centered lower, more spread
$nB = rand(80, 100)
$groupB = normrand(35, 10, $nB, 0, 1, 1)

$meanA = round(mean($groupA), 1)
$sdA = round(stdev($groupA), 1)
$medA = median($groupA)
$meanB = round(mean($groupB), 1)
$sdB = round(stdev($groupB), 1)
$medB = median($groupB)

$bp = boxplot($groupA, $groupB, labels=array("Group A", "Group B"))

$compare_choices = array("Group A has a higher center (mean and median) than Group B", "Group B has a higher center (mean and median) than Group A", "Both groups have approximately the same center")
$spread_choices = array("Group A has more variability than Group B", "Group B has more variability than Group A", "Both groups have approximately the same variability")
$shape_choices = array("Both are approximately symmetric", "Both are right skewed", "Group A is symmetric and Group B is right skewed", "Group A is right skewed and Group B is symmetric")

// === Question Text ===
// <p>The comparative box plots below show the age distributions for two groups
// of award winners ($nA in Group A and $nB in Group B).</p>
//
// $bp
//
// <p>Summary statistics:</p>
// <table border="1" cellpadding="4">
// <tr><th></th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Group A</td><td>$meanA</td><td>$sdA</td><td>$nA</td></tr>
// <tr><td>Group B</td><td>$meanB</td><td>$sdB</td><td>$nB</td></tr>
// </table>
//
// <p><b>(a)</b> Compare the centers of the two distributions:</p>
// $answerbox[0]
//
// <p><b>(b)</b> Compare the variability of the two distributions:</p>
// $answerbox[1]
//
// <p><b>(c)</b> What is the approximate median age for Group A?</p>
// $answerbox[2]
//
// <p><b>(d)</b> What is the approximate median age for Group B?</p>
// $answerbox[3]

// === Answer ===
$answer[0] = "Group A has a higher center (mean and median) than Group B"
$displayformat[0] = "radio"
$answerformat[0] = "list"
$questions[0] = $compare_choices

$answer[1] = "Group B has more variability than Group A"
$displayformat[1] = "radio"
$answerformat[1] = "list"
$questions[1] = $spread_choices

$answer[2] = $medA
$abstolerance[2] = 2

$answer[3] = $medB
$abstolerance[3] = 2

END MOM --->
<ol start="11" type="1">
<li><strong>NYC marathon winners.</strong> The histogram and box plots below show the distribution of finishing times for male and female (combined) winners of the New York City Marathon between 1970 and 2023.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch05-relationships_files/figure-html/unnamed-chunk-10-1.png){width=2100}
:::
:::





a.  What features of the distribution are apparent in the histogram and not the box plot?
    What features are apparent in the box plot but not in the histogram?

b.  What may be the reason for the bimodal distribution?
    Explain.

c.  Compare the distribution of marathon times for men and women based on the box plot shown below.





::: {.cell}
::: {.cell-output-display}
![](ch05-relationships_files/figure-html/unnamed-chunk-11-1.png){width=95%}
:::
:::





d.  The time series plot shown below is another way to look at these data. Describe what is visible in this plot but not in the others.





::: {.cell}
::: {.cell-output-display}
![](ch05-relationships_files/figure-html/unnamed-chunk-12-1.png){width=95%}
:::
:::</code></pre>
<!--- MOM ims-05-26
ims_exercise: "5.26"
title: "NYC marathon winners"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 5.26 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate bimodal race-time data (two groups: faster group A, slower group B)
$nA = rand(45, 55)
$nB = rand(45, 55)
$mu_A = rrand(2.10, 2.25, 0.01)
$mu_B = rrand(2.40, 2.60, 0.01)
$groupA = normrand($mu_A, 0.08, $nA, 2)
$groupB = normrand($mu_B, 0.10, $nB, 2)

// Combined data (bimodal)
$combined = array_merge($groupA, $groupB)
$ntotal = $nA + $nB

$histo = histogram($combined, "Finishing time (hours)")
$bp_combined = boxplot($combined, "All winners")
$bp_compare = boxplot($groupA, $groupB, labels=array("Group A", "Group B"))

$medA = round(median($groupA), 2)
$medB = round(median($groupB), 2)

$tf_choices = array("True", "False")

// === Question Text ===
// <p>The histogram and box plot below show the distribution of finishing times
// for $ntotal race winners (combined from two divisions).</p>
//
// $histo
// $bp_combined
//
// <p><b>(a)</b> True or False: The histogram reveals a bimodal (two-peaked)
// distribution.</p>
// $answerbox[0]
//
// <p><b>(b)</b> True or False: The bimodal shape is clearly visible in the
// box plot.</p>
// $answerbox[1]
//
// <p><b>(c)</b> What might explain the bimodal distribution?</p>
// $answerbox[2]
//
// <p>The comparative box plots below separate the data by division:</p>
// $bp_compare
//
// <p><b>(d)</b> What is the approximate median finishing time for Group A?</p>
// $answerbox[3]
//
// <p><b>(e)</b> What is the approximate median finishing time for Group B?</p>
// $answerbox[4]

// === Answer ===
$answer[0] = "True"
$displayformat[0] = "radio"
$answerformat[0] = "list"
$questions[0] = $tf_choices

$answer[1] = "False"
$displayformat[1] = "radio"
$answerformat[1] = "list"
$questions[1] = $tf_choices
$showanswer[1] = "Box plots cannot reveal bimodality — they only summarize the five-number summary."

$answer[2] = "The data combines two distinct groups (divisions) with different typical finishing times"
$displayformat[2] = "radio"
$answerformat[2] = "list"
$questions[2] = array("The data combines two distinct groups (divisions) with different typical finishing times", "There were two separate races held on different days", "The timing equipment was miscalibrated partway through", "Some runners took a break during the race")

$answer[3] = $medA
$abstolerance[3] = 0.05

$answer[4] = $medB
$abstolerance[4] = 0.05

END MOM --->


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The <code>flights</code> data used in this exercise can be found in the <a href="https://github.com/tidyverse/nycflights13"><strong>nycflights13</strong></a> R package.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The conundrum is known as Simpson’s Paradox and is explored in <span class="quarto-unresolved-ref">?sec-data-applications</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The conundrum is known as Simpson’s Paradox and is explored in <span class="quarto-unresolved-ref">?sec-data-applications</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <a href="http://openintrostat.github.io/openintro/reference/mammals.html"><code>mammals</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The <a href="http://openintrostat.github.io/openintro/reference/oscars.html"><code>oscars</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The <a href="http://openintrostat.github.io/openintro/reference/nyc_marathon.html"><code>nyc_marathon</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch04-describing-distributions.html" class="pagination-link" aria-label="Describing Distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../parts/part-ii.html" class="pagination-link" aria-label="Simulate">
        <span class="nav-page-text">Simulate</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>