<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Confidence Intervals for Means – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch12-hypothesis-tests-means.html" rel="next">
<link href="../chapters/ch10-normal-approximation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8516382779693841795b18304a02d14e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Traditional Inference</a></li><li class="breadcrumb-item"><a href="../chapters/ch11-ci-for-means.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data and Exploration</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation-Based Inference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Traditional Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Power and Study Design</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-vi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical Inference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-vii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing Groups</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-viii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling and Regression</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/simkit-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">SimKit Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-t-dist" id="toc-sec-t-dist" class="nav-link active" data-scroll-target="#sec-t-dist"><span class="header-section-number">12.1</span> The <span class="math inline">\(t\)</span>-distribution</a>
  <ul class="collapse">
  <li><a href="#why-not-the-normal-distribution" id="toc-why-not-the-normal-distribution" class="nav-link" data-scroll-target="#why-not-the-normal-distribution"><span class="header-section-number">12.1.1</span> Why not the normal distribution?</a></li>
  <li><a href="#properties-of-the-t-distribution" id="toc-properties-of-the-t-distribution" class="nav-link" data-scroll-target="#properties-of-the-t-distribution"><span class="header-section-number">12.1.2</span> Properties of the <span class="math inline">\(t\)</span>-distribution</a></li>
  <li><a href="#critical-values-from-the-t-distribution" id="toc-critical-values-from-the-t-distribution" class="nav-link" data-scroll-target="#critical-values-from-the-t-distribution"><span class="header-section-number">12.1.3</span> Critical values from the <span class="math inline">\(t\)</span>-distribution</a></li>
  </ul></li>
  <li><a href="#sec-one-sample-t-ci" id="toc-sec-one-sample-t-ci" class="nav-link" data-scroll-target="#sec-one-sample-t-ci"><span class="header-section-number">12.2</span> One-sample <span class="math inline">\(t\)</span> confidence interval</a>
  <ul class="collapse">
  <li><a href="#the-setup" id="toc-the-setup" class="nav-link" data-scroll-target="#the-setup"><span class="header-section-number">12.2.1</span> The setup</a></li>
  <li><a href="#checking-conditions" id="toc-checking-conditions" class="nav-link" data-scroll-target="#checking-conditions"><span class="header-section-number">12.2.2</span> Checking conditions</a></li>
  <li><a href="#worked-example-mercury-levels-in-rissos-dolphins" id="toc-worked-example-mercury-levels-in-rissos-dolphins" class="nav-link" data-scroll-target="#worked-example-mercury-levels-in-rissos-dolphins"><span class="header-section-number">12.2.3</span> Worked example: Mercury levels in Risso’s dolphins</a></li>
  </ul></li>
  <li><a href="#sec-two-sample-t-ci" id="toc-sec-two-sample-t-ci" class="nav-link" data-scroll-target="#sec-two-sample-t-ci"><span class="header-section-number">12.3</span> Two-sample <span class="math inline">\(t\)</span> confidence interval</a>
  <ul class="collapse">
  <li><a href="#the-setup-1" id="toc-the-setup-1" class="nav-link" data-scroll-target="#the-setup-1"><span class="header-section-number">12.3.1</span> The setup</a></li>
  <li><a href="#worked-example-embryonic-stem-cells-and-heart-function" id="toc-worked-example-embryonic-stem-cells-and-heart-function" class="nav-link" data-scroll-target="#worked-example-embryonic-stem-cells-and-heart-function"><span class="header-section-number">12.3.2</span> Worked example: Embryonic stem cells and heart function</a></li>
  </ul></li>
  <li><a href="#sec-paired-ci" id="toc-sec-paired-ci" class="nav-link" data-scroll-target="#sec-paired-ci"><span class="header-section-number">12.4</span> Paired data confidence interval</a>
  <ul class="collapse">
  <li><a href="#what-makes-data-paired" id="toc-what-makes-data-paired" class="nav-link" data-scroll-target="#what-makes-data-paired"><span class="header-section-number">12.4.1</span> What makes data “paired”?</a></li>
  <li><a href="#the-key-idea-analyze-the-differences" id="toc-the-key-idea-analyze-the-differences" class="nav-link" data-scroll-target="#the-key-idea-analyze-the-differences"><span class="header-section-number">12.4.2</span> The key idea: analyze the differences</a></li>
  <li><a href="#worked-example-textbook-prices" id="toc-worked-example-textbook-prices" class="nav-link" data-scroll-target="#worked-example-textbook-prices"><span class="header-section-number">12.4.3</span> Worked example: Textbook prices</a></li>
  <li><a href="#why-not-use-a-two-sample-t-interval-for-paired-data" id="toc-why-not-use-a-two-sample-t-interval-for-paired-data" class="nav-link" data-scroll-target="#why-not-use-a-two-sample-t-interval-for-paired-data"><span class="header-section-number">12.4.4</span> Why not use a two-sample <span class="math inline">\(t\)</span> interval for paired data?</a></li>
  </ul></li>
  <li><a href="#sec-t-vs-bootstrap" id="toc-sec-t-vs-bootstrap" class="nav-link" data-scroll-target="#sec-t-vs-bootstrap"><span class="header-section-number">12.5</span> Connecting <span class="math inline">\(t\)</span>-based and bootstrap confidence intervals</a></li>
  <li><a href="#sec-ch11-review" id="toc-sec-ch11-review" class="nav-link" data-scroll-target="#sec-ch11-review"><span class="header-section-number">12.6</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">12.6.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">12.6.2</span> Key terms</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">12.6.3</span> Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Traditional Inference</a></li><li class="breadcrumb-item"><a href="../chapters/ch11-ci-for-means.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>In Chapter 8, we used bootstrapping to construct confidence intervals – a flexible, simulation-based approach that works well in many settings. In Chapter 10, we saw that sampling distributions are often well approximated by the normal distribution. For means, however, we encounter a complication: the population standard deviation <span class="math inline">\(\sigma\)</span> is almost never known, and estimating it with the sample standard deviation <span class="math inline">\(s\)</span> introduces extra uncertainty. To account for this, we use a slightly different bell-shaped distribution called the <strong><span class="math inline">\(t\)</span>-distribution</strong>. In this chapter, we develop <span class="math inline">\(t\)</span>-based confidence intervals for one mean, the difference between two independent means, and the mean of paired differences.</p>
</div>
<div class="simkit">
<p><strong>SimKit tools for this chapter</strong>: Use the <strong><span class="math inline">\(t\)</span>-Distribution Explorer</strong> to compare the <span class="math inline">\(t\)</span>-distribution to the standard normal at various degrees of freedom.</p>
<p><a href="https://datascienceuwl.github.io/simkit/explore/t/" target="_blank">Launch t-Distribution Explorer</a></p>
</div>
<section id="sec-t-dist" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="sec-t-dist"><span class="header-section-number">12.1</span> The <span class="math inline">\(t\)</span>-distribution</h2>
<section id="why-not-the-normal-distribution" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="why-not-the-normal-distribution"><span class="header-section-number">12.1.1</span> Why not the normal distribution?</h3>
<p>In Chapter 10, we used the normal distribution to model sampling distributions. For proportions, this works well because the standard error formula <span class="math inline">\(SE = \sqrt{\hat{p}(1 - \hat{p})/n}\)</span> depends only on the sample proportion and the sample size – both of which are known. For means, the standard error is <span class="math inline">\(SE = \sigma / \sqrt{n}\)</span>, which depends on <span class="math inline">\(\sigma\)</span>, the population standard deviation. Since we rarely know <span class="math inline">\(\sigma\)</span>, we estimate it using the sample standard deviation <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[SE \approx \frac{s}{\sqrt{n}}\]</span></p>
<p>This substitution introduces additional uncertainty, especially in small samples. When <span class="math inline">\(n\)</span> is small, <span class="math inline">\(s\)</span> can be a poor estimate of <span class="math inline">\(\sigma\)</span>, and the normal model underestimates how variable the statistic really is. The <span class="math inline">\(t\)</span>-distribution corrects for this.</p>
</section>
<section id="properties-of-the-t-distribution" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="properties-of-the-t-distribution"><span class="header-section-number">12.1.2</span> Properties of the <span class="math inline">\(t\)</span>-distribution</h3>
<div class="definition">
<p>The <strong><span class="math inline">\(t\)</span>-distribution</strong> is a bell-shaped, symmetric distribution that is similar to the normal distribution but has <strong>heavier tails</strong> (more probability in the extremes). The exact shape of the <span class="math inline">\(t\)</span>-distribution depends on a parameter called the <strong>degrees of freedom (df)</strong>.</p>
<ul>
<li>When <span class="math inline">\(df\)</span> is small, the <span class="math inline">\(t\)</span>-distribution has noticeably heavier tails than the normal – extreme values are more likely.</li>
<li>As <span class="math inline">\(df\)</span> increases, the <span class="math inline">\(t\)</span>-distribution approaches the standard normal distribution.</li>
<li>For <span class="math inline">\(df \geq 30\)</span>, the <span class="math inline">\(t\)</span>-distribution is nearly indistinguishable from the normal.</li>
</ul>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/placeholder.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Three distributions plotted on the same axes: the standard normal distribution N(0,1), a t-distribution with df = 5, and a t-distribution with df = 15. All are centered at 0 and bell-shaped, but the t-distributions have heavier tails, especially when df is small."><img src="images/placeholder.png" class="img-fluid figure-img" alt="Three overlapping bell-shaped curves centered at zero. The standard normal curve is the tallest and has the thinnest tails. The t-distribution with 15 degrees of freedom is slightly shorter with slightly heavier tails. The t-distribution with 5 degrees of freedom is the shortest with the heaviest tails."></a></p>
<figcaption>Three distributions plotted on the same axes: the standard normal distribution <span class="math inline">\(N(0,1)\)</span>, a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 5\)</span>, and a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 15\)</span>. All are centered at 0 and bell-shaped, but the <span class="math inline">\(t\)</span>-distributions have heavier tails, especially when <span class="math inline">\(df\)</span> is small.</figcaption>
</figure>
</div>
<div class="important">
<p><strong>Why heavier tails matter.</strong> Heavier tails mean that extreme values (large <span class="math inline">\(t\)</span>-scores) are more probable under the <span class="math inline">\(t\)</span>-distribution than under the normal distribution. In practice, this leads to <strong>wider confidence intervals</strong> when sample sizes are small – exactly the extra caution we need when <span class="math inline">\(\sigma\)</span> is estimated by <span class="math inline">\(s\)</span>.</p>
</div>
<div class="guidedpractice">
<p>How does the <span class="math inline">\(t\)</span>-distribution compare to the normal distribution when <span class="math inline">\(df = 2\)</span>? When <span class="math inline">\(df = 100\)</span>?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
</section>
<section id="critical-values-from-the-t-distribution" class="level3" data-number="12.1.3">
<h3 data-number="12.1.3" class="anchored" data-anchor-id="critical-values-from-the-t-distribution"><span class="header-section-number">12.1.3</span> Critical values from the <span class="math inline">\(t\)</span>-distribution</h3>
<p>Just as we use <span class="math inline">\(z^*\)</span> for the normal distribution, we use <span class="math inline">\(t^*_{df}\)</span> for the <span class="math inline">\(t\)</span>-distribution. Because the <span class="math inline">\(t\)</span>-distribution has heavier tails, <span class="math inline">\(t^*\)</span> values are larger than the corresponding <span class="math inline">\(z^*\)</span> values (especially for small <span class="math inline">\(df\)</span>).</p>
<p><strong>Selected critical values for 95% confidence intervals:</strong></p>
<table class="table-striped caption-top table">
<caption>Critical values <span class="math inline">\(t^*_{df}\)</span> for a 95% confidence interval. As <span class="math inline">\(df\)</span> increases, <span class="math inline">\(t^*\)</span> approaches <span class="math inline">\(z^* = 1.96\)</span>.</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(df\)</span></th>
<th><span class="math inline">\(t^*_{df}\)</span> (95% CI)</th>
<th><span class="math inline">\(z^*\)</span> (for comparison)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>2.571</td>
<td>1.960</td>
</tr>
<tr class="even">
<td>10</td>
<td>2.228</td>
<td>1.960</td>
</tr>
<tr class="odd">
<td>20</td>
<td>2.086</td>
<td>1.960</td>
</tr>
<tr class="even">
<td>30</td>
<td>2.042</td>
<td>1.960</td>
</tr>
<tr class="odd">
<td>50</td>
<td>2.009</td>
<td>1.960</td>
</tr>
<tr class="even">
<td>100</td>
<td>1.984</td>
<td>1.960</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\infty\)</span></td>
<td>1.960</td>
<td>1.960</td>
</tr>
</tbody>
</table>
<div class="guidedpractice">
<p>Why is the critical value <span class="math inline">\(t^*_5 = 2.571\)</span> so much larger than <span class="math inline">\(z^* = 1.96\)</span>?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
</section>
</section>
<section id="sec-one-sample-t-ci" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="sec-one-sample-t-ci"><span class="header-section-number">12.2</span> One-sample <span class="math inline">\(t\)</span> confidence interval</h2>
<section id="the-setup" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="the-setup"><span class="header-section-number">12.2.1</span> The setup</h3>
<p>We want to estimate the population mean <span class="math inline">\(\mu\)</span> based on a single sample. The point estimate is the sample mean <span class="math inline">\(\bar{x}\)</span>, and the standard error is <span class="math inline">\(SE = s / \sqrt{n}\)</span>.</p>
<div class="important">
<p><strong>One-sample <span class="math inline">\(t\)</span> confidence interval for <span class="math inline">\(\mu\)</span>.</strong></p>
<p><span class="math display">\[\bar{x} \pm t^*_{df} \times \frac{s}{\sqrt{n}}\]</span></p>
<p>where <span class="math inline">\(df = n - 1\)</span>.</p>
<p><strong>Conditions:</strong></p>
<ol type="1">
<li><strong>Independence.</strong> The observations are independent (e.g., from a random sample).</li>
<li><strong>Normality / sample size.</strong> Either the population distribution is approximately normal, or the sample size is large enough (<span class="math inline">\(n \geq 30\)</span>). For smaller samples, check for strong skewness or extreme outliers.</li>
</ol>
</div>
</section>
<section id="checking-conditions" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="checking-conditions"><span class="header-section-number">12.2.2</span> Checking conditions</h3>
<p>The normality condition is about the shape of the <strong>population</strong>, not the sample. In practice:</p>
<ul>
<li>If <span class="math inline">\(n &lt; 30\)</span>: Check a histogram or dotplot of the sample data. If there is no strong skewness and no extreme outliers, the <span class="math inline">\(t\)</span>-methods are reasonable.</li>
<li>If <span class="math inline">\(n \geq 30\)</span>: The Central Limit Theorem ensures that <span class="math inline">\(\bar{x}\)</span> is approximately normal, even if the population is moderately skewed. However, be cautious with extreme outliers, which can distort <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(s\)</span>.</li>
</ul>
<div class="caution">
<p><strong>Outliers and the <span class="math inline">\(t\)</span>-test.</strong> The sample mean <span class="math inline">\(\bar{x}\)</span> and sample standard deviation <span class="math inline">\(s\)</span> are sensitive to outliers. A single extreme observation can substantially shift <span class="math inline">\(\bar{x}\)</span> and inflate <span class="math inline">\(s\)</span>, leading to misleading confidence intervals. When outliers are present, consider whether they represent data errors. If the outliers are genuine, a bootstrap confidence interval (Chapter 8) may be more reliable.</p>
</div>
</section>
<section id="worked-example-mercury-levels-in-rissos-dolphins" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="worked-example-mercury-levels-in-rissos-dolphins"><span class="header-section-number">12.2.3</span> Worked example: Mercury levels in Risso’s dolphins</h3>
<div class="workedexample">
<p>Researchers measured mercury concentrations (in <span class="math inline">\(\mu\)</span>g/g) in the muscle tissue of 19 Risso’s dolphins from the Adriatic Sea. The sample mean was <span class="math inline">\(\bar{x} = 4.4\)</span> <span class="math inline">\(\mu\)</span>g/g and the sample standard deviation was <span class="math inline">\(s = 2.3\)</span> <span class="math inline">\(\mu\)</span>g/g. Construct a 95% confidence interval for the mean mercury level in the population of Risso’s dolphins.</p>
<hr>
<p><strong>Check conditions.</strong></p>
<ol type="1">
<li><em>Independence.</em> The dolphins were sampled from different locations, so it is reasonable to treat the measurements as independent.</li>
<li><em>Normality.</em> With <span class="math inline">\(n = 19\)</span>, we need to check for strong skewness or outliers. Suppose a histogram of the data shows a roughly symmetric distribution with no extreme outliers. The condition is satisfied.</li>
</ol>
<p><strong>Compute the interval.</strong> With <span class="math inline">\(df = 19 - 1 = 18\)</span>, the critical value for a 95% CI is <span class="math inline">\(t^*_{18} = 2.101\)</span>.</p>
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{2.3}{\sqrt{19}} = \frac{2.3}{4.359} = 0.528\]</span></p>
<p><span class="math display">\[\bar{x} \pm t^*_{18} \times SE = 4.4 \pm 2.101 \times 0.528 = 4.4 \pm 1.109 = (3.29, 5.51)\]</span></p>
<p>We are 95% confident that the mean mercury concentration in Risso’s dolphins is between 3.29 and 5.51 <span class="math inline">\(\mu\)</span>g/g.</p>
</div>
<div class="guidedpractice">
<p>A sample of 35 UW-La Crosse students reported their weekly study hours. The sample mean is <span class="math inline">\(\bar{x} = 15.2\)</span> hours and <span class="math inline">\(s = 6.8\)</span> hours. Construct a 90% confidence interval for the mean weekly study hours of all UW-La Crosse students. (Use <span class="math inline">\(t^*_{34} = 1.691\)</span> for a 90% CI.)<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
</section>
</section>
<section id="sec-two-sample-t-ci" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="sec-two-sample-t-ci"><span class="header-section-number">12.3</span> Two-sample <span class="math inline">\(t\)</span> confidence interval</h2>
<section id="the-setup-1" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="the-setup-1"><span class="header-section-number">12.3.1</span> The setup</h3>
<p>When comparing the means of two independent groups, we estimate the difference <span class="math inline">\(\mu_1 - \mu_2\)</span> using <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>.</p>
<div class="important">
<p><strong>Two-sample <span class="math inline">\(t\)</span> confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span>.</strong></p>
<p><span class="math display">\[(\bar{x}_1 - \bar{x}_2) \pm t^*_{df} \times \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\]</span></p>
<p><strong>Degrees of freedom:</strong> The exact formula for <span class="math inline">\(df\)</span> is complex and typically computed by software. A conservative (safe) approximation is:</p>
<p><span class="math display">\[df = \min(n_1 - 1,\ n_2 - 1)\]</span></p>
<p><strong>Conditions:</strong></p>
<ol type="1">
<li><strong>Independence (extended).</strong> Observations are independent within each group <em>and</em> between groups (e.g., from two independent random samples or a randomized experiment).</li>
<li><strong>Normality / sample size.</strong> Each group’s data should be approximately normal or have <span class="math inline">\(n \geq 30\)</span>. Check each group separately for strong skewness or extreme outliers.</li>
</ol>
</div>
</section>
<section id="worked-example-embryonic-stem-cells-and-heart-function" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="worked-example-embryonic-stem-cells-and-heart-function"><span class="header-section-number">12.3.2</span> Worked example: Embryonic stem cells and heart function</h3>
<div class="workedexample">
<p>Researchers studied whether embryonic stem cell (ESC) treatment improves heart function in sheep after a heart attack. Nine sheep received the ESC treatment and nine were in the control group. The change in pumping capacity was measured:</p>
<table class="table-striped caption-top table">
<caption>Summary statistics for the stem cell study.</caption>
<thead>
<tr class="header">
<th>Group</th>
<th><span class="math inline">\(n\)</span></th>
<th><span class="math inline">\(\bar{x}\)</span></th>
<th><span class="math inline">\(s\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ESC</td>
<td>9</td>
<td>3.50</td>
<td>5.17</td>
</tr>
<tr class="even">
<td>Control</td>
<td>9</td>
<td><span class="math inline">\(-4.33\)</span></td>
<td>2.76</td>
</tr>
</tbody>
</table>
<p>Construct a 95% confidence interval for the difference in mean change in pumping capacity, <span class="math inline">\(\mu_{ESC} - \mu_{Control}\)</span>.</p>
<hr>
<p><strong>Check conditions.</strong></p>
<ol type="1">
<li><em>Independence.</em> The sheep were randomly assigned to groups, so independence within and between groups is satisfied.</li>
<li><em>Normality.</em> With <span class="math inline">\(n = 9\)</span> per group (small samples), we check histograms. Suppose they show no extreme outliers in either group. The condition is reasonably met.</li>
</ol>
<p><strong>Compute the interval.</strong></p>
<p><span class="math display">\[SE = \sqrt{\frac{5.17^2}{9} + \frac{2.76^2}{9}} = \sqrt{\frac{26.73}{9} + \frac{7.62}{9}} = \sqrt{2.970 + 0.847} = \sqrt{3.817} = 1.954\]</span></p>
<p>Using <span class="math inline">\(df = \min(9-1, 9-1) = 8\)</span>, the critical value for a 95% CI is <span class="math inline">\(t^*_8 = 2.306\)</span>.</p>
<p><span class="math display">\[\text{Point estimate} = 3.50 - (-4.33) = 7.83\]</span></p>
<p><span class="math display">\[7.83 \pm 2.306 \times 1.954 = 7.83 \pm 4.506 = (3.32, 12.34)\]</span></p>
<p>We are 95% confident that the ESC treatment increases heart pumping capacity by between 3.32% and 12.34% compared to the control. Because the interval is entirely above zero, we have evidence that the ESC treatment improves heart function. Since this was a randomized experiment, we can attribute the improvement to the treatment.</p>
</div>
<div class="guidedpractice">
<p>Researchers collected birth weight data from a random sample of 1,000 US births. Nonsmoker mothers (<span class="math inline">\(n = 867\)</span>) had babies with <span class="math inline">\(\bar{x}_n = 7.27\)</span> lbs (<span class="math inline">\(s_n = 1.23\)</span>), and smoker mothers (<span class="math inline">\(n = 114\)</span>) had babies with <span class="math inline">\(\bar{x}_s = 6.68\)</span> lbs (<span class="math inline">\(s_s = 1.60\)</span>). Is there evidence that babies born to nonsmoker mothers weigh more on average? Compute a 95% confidence interval for the difference <span class="math inline">\(\mu_n - \mu_s\)</span>.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</div>
</section>
</section>
<section id="sec-paired-ci" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="sec-paired-ci"><span class="header-section-number">12.4</span> Paired data confidence interval</h2>
<section id="what-makes-data-paired" class="level3" data-number="12.4.1">
<h3 data-number="12.4.1" class="anchored" data-anchor-id="what-makes-data-paired"><span class="header-section-number">12.4.1</span> What makes data “paired”?</h3>
<p>Sometimes two measurements are made on the same individual (e.g., before and after a treatment) or on naturally matched pairs (e.g., the same textbook priced at two stores). In these cases, the two groups are <strong>not independent</strong> – they are <strong>paired</strong>.</p>
<div class="definition">
<p><strong>Paired data.</strong> Two sets of observations are <strong>paired</strong> if each observation in one set has a special correspondence or connection with exactly one observation in the other set. Common examples include:</p>
<ul>
<li>Before/after measurements on the same individual</li>
<li>Two treatments applied to the same subject (e.g., tires on the same car)</li>
<li>Matched pairs in an experiment (e.g., twins assigned to different treatments)</li>
<li>The same item measured under two conditions (e.g., textbook prices at two stores)</li>
</ul>
</div>
<table class="table-striped caption-top table">
<caption>Examples of paired designs.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Observational unit</th>
<th>Comparison groups</th>
<th>Measurement</th>
<th>Value of interest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Car</td>
<td>Smooth Turn vs.&nbsp;Quick Spin</td>
<td>Tire tread after 1,000 miles</td>
<td>Difference in tread</td>
</tr>
<tr class="even">
<td>Textbook</td>
<td>UCLA Bookstore vs.&nbsp;Amazon</td>
<td>Price of new textbook</td>
<td>Difference in price</td>
</tr>
<tr class="odd">
<td>Individual</td>
<td>Pre-course vs.&nbsp;Post-course</td>
<td>Exam score</td>
<td>Difference in score</td>
</tr>
</tbody>
</table>
</section>
<section id="the-key-idea-analyze-the-differences" class="level3" data-number="12.4.2">
<h3 data-number="12.4.2" class="anchored" data-anchor-id="the-key-idea-analyze-the-differences"><span class="header-section-number">12.4.2</span> The key idea: analyze the differences</h3>
<p>The key to working with paired data is simple: <strong>compute the difference for each pair, then analyze those differences as a single sample.</strong> This converts a two-sample problem into a one-sample problem.</p>
<div class="important">
<p><strong>Paired <span class="math inline">\(t\)</span> confidence interval for <span class="math inline">\(\mu_{diff}\)</span>.</strong></p>
<p>For paired data, compute the difference <span class="math inline">\(d_i = x_{1,i} - x_{2,i}\)</span> for each pair. Then the confidence interval for the mean difference <span class="math inline">\(\mu_{diff}\)</span> is:</p>
<p><span class="math display">\[\bar{x}_{diff} \pm t^*_{df} \times \frac{s_{diff}}{\sqrt{n_{diff}}}\]</span></p>
<p>where <span class="math inline">\(\bar{x}_{diff}\)</span> is the sample mean of the differences, <span class="math inline">\(s_{diff}\)</span> is the sample standard deviation of the differences, <span class="math inline">\(n_{diff}\)</span> is the number of pairs, and <span class="math inline">\(df = n_{diff} - 1\)</span>.</p>
<p><strong>Conditions:</strong></p>
<ol type="1">
<li><strong>Independence of pairs.</strong> The pairs themselves are independent (e.g., different cars, different textbooks).</li>
<li><strong>Normality of differences.</strong> The distribution of the <em>differences</em> should be approximately normal, or the number of pairs should be large (<span class="math inline">\(n_{diff} \geq 30\)</span>). Check for extreme outliers.</li>
</ol>
</div>
</section>
<section id="worked-example-textbook-prices" class="level3" data-number="12.4.3">
<h3 data-number="12.4.3" class="anchored" data-anchor-id="worked-example-textbook-prices"><span class="header-section-number">12.4.3</span> Worked example: Textbook prices</h3>
<div class="workedexample">
<p>Researchers sampled 68 UCLA courses and compared textbook prices at the UCLA Bookstore to prices on Amazon. Summary statistics for the price differences (UCLA <span class="math inline">\(-\)</span> Amazon) are:</p>
<table class="table-striped caption-top table">
<caption>Summary statistics for the 68 price differences.</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(n_{diff}\)</span></th>
<th><span class="math inline">\(\bar{x}_{diff}\)</span></th>
<th><span class="math inline">\(s_{diff}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>68</td>
<td>$3.58</td>
<td>$13.42</td>
</tr>
</tbody>
</table>
<p>Construct a 95% confidence interval for the mean price difference.</p>
<hr>
<p><strong>Check conditions.</strong></p>
<ol type="1">
<li><em>Independence of pairs.</em> The textbooks were randomly sampled, so the pairs are independent.</li>
<li><em>Normality of differences.</em> With <span class="math inline">\(n_{diff} = 68\)</span>, the CLT ensures the sampling distribution of <span class="math inline">\(\bar{x}_{diff}\)</span> is approximately normal. Though the distribution of individual differences is right-skewed, the large sample size and absence of extreme outliers make the <span class="math inline">\(t\)</span>-methods reasonable.</li>
</ol>
<p><strong>Compute the interval.</strong></p>
<p><span class="math display">\[SE = \frac{s_{diff}}{\sqrt{n_{diff}}} = \frac{13.42}{\sqrt{68}} = \frac{13.42}{8.246} = 1.628\]</span></p>
<p>With <span class="math inline">\(df = 68 - 1 = 67\)</span>, the critical value for a 95% CI is <span class="math inline">\(t^*_{67} \approx 2.00\)</span>.</p>
<p><span class="math display">\[3.58 \pm 2.00 \times 1.628 = 3.58 \pm 3.256 = (0.32, 6.84)\]</span></p>
<p>We are 95% confident that UCLA Bookstore prices are, on average, between $0.32 and $6.84 higher than Amazon prices for UCLA course books.</p>
</div>
<div class="guidedpractice">
<p>A fitness program enrolled 25 participants and measured their resting heart rates before and after 8 weeks of training. The mean difference (before <span class="math inline">\(-\)</span> after) was <span class="math inline">\(\bar{x}_{diff} = 4.2\)</span> beats per minute with <span class="math inline">\(s_{diff} = 6.1\)</span> bpm. Construct a 90% confidence interval for the mean decrease in resting heart rate. (Use <span class="math inline">\(t^*_{24} = 1.711\)</span>.)<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
</section>
<section id="why-not-use-a-two-sample-t-interval-for-paired-data" class="level3" data-number="12.4.4">
<h3 data-number="12.4.4" class="anchored" data-anchor-id="why-not-use-a-two-sample-t-interval-for-paired-data"><span class="header-section-number">12.4.4</span> Why not use a two-sample <span class="math inline">\(t\)</span> interval for paired data?</h3>
<div class="caution">
<p><strong>Never use a two-sample procedure for paired data.</strong> A two-sample <span class="math inline">\(t\)</span> interval treats the two groups as independent, which they are not. Ignoring the pairing throws away valuable information about the within-pair relationship and typically produces a wider (less precise) confidence interval. Always compute the differences first and then use the one-sample (paired) <span class="math inline">\(t\)</span> procedure.</p>
</div>
</section>
</section>
<section id="sec-t-vs-bootstrap" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="sec-t-vs-bootstrap"><span class="header-section-number">12.5</span> Connecting <span class="math inline">\(t\)</span>-based and bootstrap confidence intervals</h2>
<div class="original">
<p>The <span class="math inline">\(t\)</span>-based confidence intervals in this chapter and the bootstrap confidence intervals from Chapter 8 are answering the same question: “What is a plausible range for the population parameter?” When conditions are met, they give similar results.</p>
<p><strong>When do they agree?</strong></p>
<ul>
<li>Large samples with no extreme outliers: the <span class="math inline">\(t\)</span>-interval and bootstrap interval will be nearly identical.</li>
<li>Moderate samples from approximately normal populations: close agreement.</li>
</ul>
<p><strong>When might they differ?</strong></p>
<ul>
<li>Small samples from skewed populations: the bootstrap can capture asymmetry in the sampling distribution, while the <span class="math inline">\(t\)</span>-interval is always symmetric around <span class="math inline">\(\bar{x}\)</span>.</li>
<li>Presence of outliers: the bootstrap is somewhat more robust because it does not rely on <span class="math inline">\(s\)</span> being a good estimate of <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<p><strong>Which should you use?</strong></p>
<ul>
<li>If conditions are met, the <span class="math inline">\(t\)</span>-interval is simpler to compute and has well-understood properties.</li>
<li>If conditions are questionable (small sample, skewness, outliers), prefer the bootstrap.</li>
<li>In practice, reporting both and noting any discrepancies is informative.</li>
</ul>
</div>
</section>
<section id="sec-ch11-review" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="sec-ch11-review"><span class="header-section-number">12.6</span> Chapter review</h2>
<section id="summary" class="level3" data-number="12.6.1">
<h3 data-number="12.6.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">12.6.1</span> Summary</h3>
<p>This chapter developed formula-based confidence intervals for means using the <span class="math inline">\(t\)</span>-distribution.</p>
<ul>
<li>The <strong><span class="math inline">\(t\)</span>-distribution</strong> accounts for the extra uncertainty from estimating <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>. It has heavier tails than the normal distribution, especially for small degrees of freedom.</li>
<li><strong>One-sample <span class="math inline">\(t\)</span> CI</strong>: <span class="math inline">\(\bar{x} \pm t^*_{n-1} \times \frac{s}{\sqrt{n}}\)</span>. Requires independent observations and approximate normality (or large <span class="math inline">\(n\)</span>).</li>
<li><strong>Two-sample <span class="math inline">\(t\)</span> CI</strong>: <span class="math inline">\((\bar{x}_1 - \bar{x}_2) \pm t^*_{df} \times \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\)</span>. Requires independence within and between groups, and approximate normality or large samples in each group.</li>
<li><strong>Paired <span class="math inline">\(t\)</span> CI</strong>: Compute differences for each pair, then apply the one-sample <span class="math inline">\(t\)</span> CI to the differences: <span class="math inline">\(\bar{x}_{diff} \pm t^*_{n_{diff}-1} \times \frac{s_{diff}}{\sqrt{n_{diff}}}\)</span>.</li>
<li>Always check conditions before using <span class="math inline">\(t\)</span>-methods: independence, normality/sample size, and absence of extreme outliers.</li>
<li>When conditions are met, <span class="math inline">\(t\)</span>-based and bootstrap confidence intervals give similar results. When conditions are questionable, the bootstrap may be more reliable.</li>
</ul>
</section>
<section id="key-terms" class="level3" data-number="12.6.2">
<h3 data-number="12.6.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">12.6.2</span> Key terms</h3>
<p><span class="math inline">\(t\)</span>-distribution, degrees of freedom (<span class="math inline">\(df\)</span>), critical value (<span class="math inline">\(t^*\)</span>), one-sample <span class="math inline">\(t\)</span> confidence interval, two-sample <span class="math inline">\(t\)</span> confidence interval, paired data, paired <span class="math inline">\(t\)</span> confidence interval, standard error of the mean, independence condition, normality condition.</p>
</section>
<section id="exercises" class="level3 exercises" data-number="12.6.3">
<h3 class="exercises anchored" data-number="12.6.3" data-anchor-id="exercises"><span class="header-section-number">12.6.3</span> Exercises</h3>
<p>Exercises for this chapter are under development.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>When <span class="math inline">\(df = 2\)</span>, the <span class="math inline">\(t\)</span>-distribution has very heavy tails – values far from 0 are much more likely than under the normal curve. When <span class="math inline">\(df = 100\)</span>, the <span class="math inline">\(t\)</span>-distribution is nearly identical to the standard normal. In general, the <span class="math inline">\(t\)</span>-distribution becomes more like the normal as degrees of freedom increase.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>With only <span class="math inline">\(df = 5\)</span>, there is substantial uncertainty in estimating <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>. The <span class="math inline">\(t\)</span>-distribution accounts for this by having heavier tails, which pushes the critical values further from zero. This results in a wider confidence interval, reflecting the greater uncertainty.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>First check conditions: the sample is a random sample (independence), and <span class="math inline">\(n = 35 \geq 30\)</span> (normality via CLT). Then <span class="math inline">\(SE = 6.8/\sqrt{35} = 1.149\)</span>. The 90% CI is <span class="math inline">\(15.2 \pm 1.691 \times 1.149 = 15.2 \pm 1.943 = (13.26, 17.14)\)</span>. We are 90% confident the mean weekly study hours for all UW-La Crosse students is between 13.26 and 17.14 hours.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The point estimate is <span class="math inline">\(7.27 - 6.68 = 0.59\)</span> lbs. The SE is <span class="math inline">\(\sqrt{1.23^2/867 + 1.60^2/114} = \sqrt{0.001745 + 0.02246} = \sqrt{0.02420} = 0.156\)</span>. Using <span class="math inline">\(df = \min(866, 113) = 113\)</span> and <span class="math inline">\(t^*_{113} \approx 1.981\)</span>, the CI is <span class="math inline">\(0.59 \pm 1.981 \times 0.156 = 0.59 \pm 0.309 = (0.28, 0.90)\)</span>. We are 95% confident that babies born to nonsmoker mothers weigh between 0.28 and 0.90 lbs more on average than babies born to smoker mothers.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>First check conditions: pairs (individuals) were randomly selected (independence), and with <span class="math inline">\(n = 25\)</span> and no extreme outliers reported, the normality condition is reasonable. Then <span class="math inline">\(SE = 6.1/\sqrt{25} = 6.1/5 = 1.22\)</span>. The 90% CI is <span class="math inline">\(4.2 \pm 1.711 \times 1.22 = 4.2 \pm 2.09 = (2.11, 6.29)\)</span>. We are 90% confident the training program reduces resting heart rate by between 2.11 and 6.29 bpm on average.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch10-normal-approximation.html" class="pagination-link" aria-label="Normal Approximation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch12-hypothesis-tests-means.html" class="pagination-link" aria-label="Hypothesis Tests for Means">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>