<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Hypothesis Tests for Means – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch13-inference-proportions.html" rel="next">
<link href="../chapters/ch11-ci-for-means.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8a91fbd6dc43518bbcbbe5f3fb33f285.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Calculate</a></li><li class="breadcrumb-item"><a href="../chapters/ch12-hypothesis-tests-means.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statbench-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatBench Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-t-test-framework" id="toc-sec-t-test-framework" class="nav-link active" data-scroll-target="#sec-t-test-framework"><span class="header-section-number">13.1</span> The <span class="math inline">\(t\)</span>-test framework</a></li>
  <li><a href="#sec-one-sample-t-test" id="toc-sec-one-sample-t-test" class="nav-link" data-scroll-target="#sec-one-sample-t-test"><span class="header-section-number">13.2</span> One-sample <span class="math inline">\(t\)</span>-test</a>
  <ul class="collapse">
  <li><a href="#setup-and-hypotheses" id="toc-setup-and-hypotheses" class="nav-link" data-scroll-target="#setup-and-hypotheses"><span class="header-section-number">13.2.1</span> Setup and hypotheses</a></li>
  <li><a href="#worked-example-cherry-blossom-race-times" id="toc-worked-example-cherry-blossom-race-times" class="nav-link" data-scroll-target="#worked-example-cherry-blossom-race-times"><span class="header-section-number">13.2.2</span> Worked example: Cherry Blossom race times</a></li>
  </ul></li>
  <li><a href="#sec-two-sample-t-test" id="toc-sec-two-sample-t-test" class="nav-link" data-scroll-target="#sec-two-sample-t-test"><span class="header-section-number">13.3</span> Two-sample <span class="math inline">\(t\)</span>-test</a>
  <ul class="collapse">
  <li><a href="#setup-and-hypotheses-1" id="toc-setup-and-hypotheses-1" class="nav-link" data-scroll-target="#setup-and-hypotheses-1"><span class="header-section-number">13.3.1</span> Setup and hypotheses</a></li>
  <li><a href="#worked-example-birth-weights-and-smoking" id="toc-worked-example-birth-weights-and-smoking" class="nav-link" data-scroll-target="#worked-example-birth-weights-and-smoking"><span class="header-section-number">13.3.2</span> Worked example: Birth weights and smoking</a></li>
  <li><a href="#worked-example-exam-versions" id="toc-worked-example-exam-versions" class="nav-link" data-scroll-target="#worked-example-exam-versions"><span class="header-section-number">13.3.3</span> Worked example: Exam versions</a></li>
  </ul></li>
  <li><a href="#sec-paired-t-test" id="toc-sec-paired-t-test" class="nav-link" data-scroll-target="#sec-paired-t-test"><span class="header-section-number">13.4</span> Paired <span class="math inline">\(t\)</span>-test</a>
  <ul class="collapse">
  <li><a href="#setup-and-hypotheses-2" id="toc-setup-and-hypotheses-2" class="nav-link" data-scroll-target="#setup-and-hypotheses-2"><span class="header-section-number">13.4.1</span> Setup and hypotheses</a></li>
  <li><a href="#worked-example-textbook-prices" id="toc-worked-example-textbook-prices" class="nav-link" data-scroll-target="#worked-example-textbook-prices"><span class="header-section-number">13.4.2</span> Worked example: Textbook prices</a></li>
  </ul></li>
  <li><a href="#sec-sim-vs-t" id="toc-sec-sim-vs-t" class="nav-link" data-scroll-target="#sec-sim-vs-t"><span class="header-section-number">13.5</span> Connecting simulation-based and <span class="math inline">\(t\)</span>-based tests</a></li>
  <li><a href="#sec-practical-significance" id="toc-sec-practical-significance" class="nav-link" data-scroll-target="#sec-practical-significance"><span class="header-section-number">13.6</span> Practical vs.&nbsp;statistical significance</a>
  <ul class="collapse">
  <li><a href="#effect-sizes" id="toc-effect-sizes" class="nav-link" data-scroll-target="#effect-sizes"><span class="header-section-number">13.6.1</span> Effect sizes</a></li>
  </ul></li>
  <li><a href="#sec-ch12-review" id="toc-sec-ch12-review" class="nav-link" data-scroll-target="#sec-ch12-review"><span class="header-section-number">13.7</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">13.7.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">13.7.2</span> Key terms</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">13.7.3</span> Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Calculate</a></li><li class="breadcrumb-item"><a href="../chapters/ch12-hypothesis-tests-means.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>In Chapter 7, we developed the logic of hypothesis testing using simulation: shuffle the data under the null hypothesis, build a null distribution, and measure how extreme the observed statistic is. In Chapter 11, we introduced the <span class="math inline">\(t\)</span>-distribution as a mathematical model for the sampling distribution of means. Now we bring these ideas together. In this chapter, we use the <span class="math inline">\(t\)</span>-distribution to conduct hypothesis tests for a single mean, the difference between two independent means, and the mean of paired differences. Along the way, we will see that the <span class="math inline">\(t\)</span>-test and simulation-based tests generally agree when conditions are met, and we will discuss what to do when they disagree.</p>
</div>
<section id="sec-t-test-framework" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="sec-t-test-framework"><span class="header-section-number">13.1</span> The <span class="math inline">\(t\)</span>-test framework</h2>
<div class="original">
<p>Every hypothesis test follows the same four-step structure, whether we use simulation or a mathematical model:</p>
<ol type="1">
<li><strong>State hypotheses.</strong> Write <span class="math inline">\(H_0\)</span> (null hypothesis) and <span class="math inline">\(H_A\)</span> (alternative hypothesis) in both words and symbols.</li>
<li><strong>Check conditions.</strong> Verify that the mathematical model is appropriate.</li>
<li><strong>Compute the test statistic and p-value.</strong> Calculate how far the observed data are from what <span class="math inline">\(H_0\)</span> predicts, and determine how unusual that distance is.</li>
<li><strong>Draw a conclusion.</strong> Compare the p-value to the significance level <span class="math inline">\(\alpha\)</span> and state the conclusion in context.</li>
</ol>
<p>For means, the test statistic is a <strong><span class="math inline">\(T\)</span> score</strong> – the standardized distance from the observed sample mean to the hypothesized value, measured in units of standard errors.</p>
</div>
</section>
<section id="sec-one-sample-t-test" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="sec-one-sample-t-test"><span class="header-section-number">13.2</span> One-sample <span class="math inline">\(t\)</span>-test</h2>
<section id="setup-and-hypotheses" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="setup-and-hypotheses"><span class="header-section-number">13.2.1</span> Setup and hypotheses</h3>
<p>The one-sample <span class="math inline">\(t\)</span>-test is used when we have a single sample of numerical data and want to test a claim about the population mean <span class="math inline">\(\mu\)</span>.</p>
<div class="important">
<p><strong>The test statistic for a single mean is a <span class="math inline">\(T\)</span>.</strong></p>
<p><span class="math display">\[T = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}\]</span></p>
<p>where <span class="math inline">\(\bar{x}\)</span> is the sample mean, <span class="math inline">\(\mu_0\)</span> is the hypothesized value from <span class="math inline">\(H_0\)</span>, <span class="math inline">\(s\)</span> is the sample standard deviation, and <span class="math inline">\(n\)</span> is the sample size.</p>
<p>When the null hypothesis is true and the conditions are met, <span class="math inline">\(T\)</span> follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = n - 1\)</span>.</p>
<p><strong>Conditions:</strong></p>
<ul>
<li><strong>Independent observations</strong> (e.g., random sample).</li>
<li><strong>Normality / sample size:</strong> The population distribution should be approximately normal, or <span class="math inline">\(n\)</span> should be large enough (<span class="math inline">\(n \geq 30\)</span>). Check for strong skewness or extreme outliers.</li>
</ul>
</div>
</section>
<section id="worked-example-cherry-blossom-race-times" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="worked-example-cherry-blossom-race-times"><span class="header-section-number">13.2.2</span> Worked example: Cherry Blossom race times</h3>
<div class="workedexample">
<p>The average finishing time for all runners in the Cherry Blossom 10-mile race in 2006 was <span class="math inline">\(\mu = 93.29\)</span> minutes. A random sample of 100 runners from a more recent year had a mean finishing time of <span class="math inline">\(\bar{x} = 97.32\)</span> minutes with <span class="math inline">\(s = 16.98\)</span> minutes. Is there evidence that the average finishing time has changed?</p>
<hr>
<p><strong>Step 1: State hypotheses.</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 93.29\)</span> (the average finishing time has not changed)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu \neq 93.29\)</span> (the average finishing time has changed)</li>
</ul>
<p>This is a two-sided test because we are looking for a change in either direction.</p>
<p><strong>Step 2: Check conditions.</strong></p>
<ul>
<li><em>Independence.</em> The sample is a random sample of runners, so observations are independent.</li>
<li><em>Sample size.</em> With <span class="math inline">\(n = 100 \geq 30\)</span>, the CLT guarantees the sampling distribution of <span class="math inline">\(\bar{x}\)</span> is approximately normal, even if the population distribution of finishing times is skewed.</li>
</ul>
<p><strong>Step 3: Compute the test statistic and p-value.</strong></p>
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{16.98}{\sqrt{100}} = 1.698\]</span></p>
<p><span class="math display">\[T = \frac{\bar{x} - \mu_0}{SE} = \frac{97.32 - 93.29}{1.698} = \frac{4.03}{1.698} = 2.37\]</span></p>
<p>With <span class="math inline">\(df = 100 - 1 = 99\)</span>, we find the area to the right of <span class="math inline">\(T = 2.37\)</span> on the <span class="math inline">\(t\)</span>-distribution: approximately 0.0099. Since this is a two-sided test, the p-value is <span class="math inline">\(2 \times 0.0099 = 0.0198\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-t-two-tailed-df99" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A t-distribution curve with 99 degrees of freedom. Both tails are shaded beyond T equals negative 2.37 and T equals positive 2.37. The combined shaded area represents the two-sided p-value.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-two-tailed-df99-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch12-hypothesis-tests-means_files/figure-html/fig-t-two-tailed-df99-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;13.1: A t-distribution with df = 99 showing the two-sided p-value. The shaded areas in both tails represent the probability of observing a test statistic at least as extreme as 2.37 in either direction."><img src="ch12-hypothesis-tests-means_files/figure-html/fig-t-two-tailed-df99-1.png" class="img-fluid figure-img" alt="A t-distribution curve with 99 degrees of freedom. Both tails are shaded beyond T equals negative 2.37 and T equals positive 2.37. The combined shaded area represents the two-sided p-value." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-two-tailed-df99-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: A <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 99\)</span> showing the two-sided p-value. The shaded areas in both tails represent the probability of observing a test statistic at least as extreme as 2.37 in either direction.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Step 4: Conclusion.</strong> The p-value of 0.0198 is less than <span class="math inline">\(\alpha = 0.05\)</span>, so we reject <span class="math inline">\(H_0\)</span>. The data provide statistically significant evidence that the average finishing time has changed from the 2006 average of 93.29 minutes. Based on the sample, runners appear to be finishing more slowly on average.</p>
</div>
<div class="guidedpractice">
<p>A nutrition study claims that the average American adult consumes 2,000 mg of sodium per day. A random sample of 45 adults shows <span class="math inline">\(\bar{x} = 3,120\)</span> mg and <span class="math inline">\(s = 1,100\)</span> mg. Test whether the data provide evidence that the true average sodium intake differs from 2,000 mg. Use <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<details>
<summary>
Show answer
</summary>
Hypotheses: <span class="math inline">\(H_0: \mu = 2000\)</span>, <span class="math inline">\(H_A: \mu \neq 2000\)</span>. Conditions: random sample (independence), <span class="math inline">\(n = 45 \geq 30\)</span> (normality via CLT). Test statistic: <span class="math inline">\(SE = 1100/\sqrt{45} = 163.9\)</span>, <span class="math inline">\(T = (3120 - 2000)/163.9 = 6.83\)</span>. With <span class="math inline">\(df = 44\)</span>, the two-tailed p-value is essentially 0 (far less than 0.05). We reject <span class="math inline">\(H_0\)</span>. There is very strong evidence that the average sodium intake is different from (and appears much higher than) 2,000 mg per day.
</details>
</div>
</section>
</section>
<section id="sec-two-sample-t-test" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="sec-two-sample-t-test"><span class="header-section-number">13.3</span> Two-sample <span class="math inline">\(t\)</span>-test</h2>
<section id="setup-and-hypotheses-1" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="setup-and-hypotheses-1"><span class="header-section-number">13.3.1</span> Setup and hypotheses</h3>
<p>The two-sample <span class="math inline">\(t\)</span>-test compares the means of two independent groups. The parameter of interest is <span class="math inline">\(\mu_1 - \mu_2\)</span>, and the null hypothesis typically claims no difference.</p>
<div class="important">
<p><strong>The test statistic for comparing two independent means is a <span class="math inline">\(T\)</span>.</strong></p>
<p><span class="math display">\[T = \frac{(\bar{x}_1 - \bar{x}_2) - 0}{\sqrt{s_1^2/n_1 + s_2^2/n_2}}\]</span></p>
<p>When the null hypothesis is true and conditions are met, <span class="math inline">\(T\)</span> follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = \min(n_1 - 1, n_2 - 1)\)</span> (conservative approximation; software computes the exact <span class="math inline">\(df\)</span>).</p>
<p><strong>Conditions:</strong></p>
<ul>
<li><strong>Independence (extended).</strong> Observations are independent within and between the two groups.</li>
<li><strong>Normality / sample size.</strong> Each group should be approximately normal or have a large enough sample size. Check each group separately for strong skewness or extreme outliers.</li>
</ul>
</div>
</section>
<section id="worked-example-birth-weights-and-smoking" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="worked-example-birth-weights-and-smoking"><span class="header-section-number">13.3.2</span> Worked example: Birth weights and smoking</h3>
<div class="workedexample">
<p>Is there evidence that newborns of mothers who smoke during pregnancy have a different average birth weight than newborns of non-smoking mothers? Data from a random sample of 1,000 US births in 2014:</p>
<table class="table-striped caption-top table">
<caption>Summary statistics for birth weights by smoking status.</caption>
<thead>
<tr class="header">
<th>Group</th>
<th><span class="math inline">\(n\)</span></th>
<th>Mean (lbs)</th>
<th>SD (lbs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nonsmoker</td>
<td>867</td>
<td>7.27</td>
<td>1.23</td>
</tr>
<tr class="even">
<td>Smoker</td>
<td>114</td>
<td>6.68</td>
<td>1.60</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>Step 1: State hypotheses.</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_n - \mu_s = 0\)</span> (no difference in average birth weight)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_n - \mu_s \neq 0\)</span> (there is a difference in average birth weight)</li>
</ul>
<p><strong>Step 2: Check conditions.</strong></p>
<ul>
<li><em>Independence.</em> The data come from a simple random sample, so observations are independent within and between groups.</li>
<li><em>Normality.</em> Both groups have large sample sizes (<span class="math inline">\(n_n = 867\)</span> and <span class="math inline">\(n_s = 114\)</span>), both well above 30. Histograms of the data show no extreme outliers. Conditions are met.</li>
</ul>
<p><strong>Step 3: Compute the test statistic and p-value.</strong></p>
<p><span class="math display">\[\bar{x}_n - \bar{x}_s = 7.27 - 6.68 = 0.59\]</span></p>
<p><span class="math display">\[SE = \sqrt{\frac{1.23^2}{867} + \frac{1.60^2}{114}} = \sqrt{\frac{1.5129}{867} + \frac{2.56}{114}} = \sqrt{0.001745 + 0.02246} = \sqrt{0.02420} = 0.156\]</span></p>
<p><span class="math display">\[T = \frac{0.59 - 0}{0.156} = 3.78\]</span></p>
<p>Using the conservative <span class="math inline">\(df = \min(867 - 1, 114 - 1) = 113\)</span>, the one-tail area for <span class="math inline">\(T = 3.78\)</span> is approximately 0.00012. The two-tailed p-value is <span class="math inline">\(2 \times 0.00012 = 0.00024\)</span>.</p>
<p><strong>Step 4: Conclusion.</strong> With a p-value of 0.00024, which is far less than <span class="math inline">\(\alpha = 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>. The data provide strong evidence that there is a difference in average birth weight between babies born to smoking and non-smoking mothers. Specifically, babies born to non-smoking mothers weigh about 0.59 lbs more on average.</p>
</div>
</section>
<section id="worked-example-exam-versions" class="level3" data-number="13.3.3">
<h3 data-number="13.3.3" class="anchored" data-anchor-id="worked-example-exam-versions"><span class="header-section-number">13.3.3</span> Worked example: Exam versions</h3>
<div class="workedexample">
<p>An instructor created two versions of an exam and randomly distributed them. Summary statistics:</p>
<table class="table-striped caption-top table">
<caption>Summary statistics for exam versions.</caption>
<thead>
<tr class="header">
<th>Version</th>
<th><span class="math inline">\(n\)</span></th>
<th>Mean</th>
<th>SD</th>
<th>Min</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>58</td>
<td>75.1</td>
<td>13.9</td>
<td>44</td>
<td>100</td>
</tr>
<tr class="even">
<td>B</td>
<td>55</td>
<td>72.0</td>
<td>13.8</td>
<td>38</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>Test whether there is convincing evidence that one version is more difficult. Use <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<hr>
<p><strong>Step 1: State hypotheses.</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_A - \mu_B = 0\)</span> (the exams are equally difficult)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_A - \mu_B \neq 0\)</span> (one exam is more difficult)</li>
</ul>
<p><strong>Step 2: Check conditions.</strong></p>
<ul>
<li><em>Independence.</em> Exams were randomly assigned, so independence is satisfied.</li>
<li><em>Normality.</em> Both groups have <span class="math inline">\(n &gt; 30\)</span> and the summary statistics suggest roughly symmetric distributions. Conditions are met.</li>
</ul>
<p><strong>Step 3: Compute the test statistic and p-value.</strong></p>
<p><span class="math display">\[\bar{x}_A - \bar{x}_B = 75.1 - 72.0 = 3.1\]</span></p>
<p><span class="math display">\[SE = \sqrt{\frac{13.9^2}{58} + \frac{13.8^2}{55}} = \sqrt{\frac{193.21}{58} + \frac{190.44}{55}} = \sqrt{3.331 + 3.463} = \sqrt{6.794} = 2.607\]</span></p>
<p><span class="math display">\[T = \frac{3.1}{2.607} = 1.19\]</span></p>
<p>Using <span class="math inline">\(df = \min(57, 54) = 54\)</span>, the one-tail area for <span class="math inline">\(T = 1.19\)</span> is about 0.12. The two-tailed p-value is approximately 0.24.</p>
<p><strong>Step 4: Conclusion.</strong> The p-value of 0.24 is much larger than <span class="math inline">\(\alpha = 0.01\)</span>, so we fail to reject <span class="math inline">\(H_0\)</span>. The data do not provide convincing evidence that one exam version is more difficult than the other.</p>
</div>
<div class="guidedpractice">
<p>Does the conclusion above mean that the two exams are equally difficult?</p>
<details>
<summary>
Show answer
</summary>
No.&nbsp;Failing to reject <span class="math inline">\(H_0\)</span> does not prove that <span class="math inline">\(H_0\)</span> is true. The data are consistent with the exams being equally difficult, but they are also consistent with exam A being about 3.1 points easier. The test simply did not find strong enough evidence to distinguish these possibilities.
</details>
</div>
</section>
</section>
<section id="sec-paired-t-test" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="sec-paired-t-test"><span class="header-section-number">13.4</span> Paired <span class="math inline">\(t\)</span>-test</h2>
<section id="setup-and-hypotheses-2" class="level3" data-number="13.4.1">
<h3 data-number="13.4.1" class="anchored" data-anchor-id="setup-and-hypotheses-2"><span class="header-section-number">13.4.1</span> Setup and hypotheses</h3>
<p>When data are paired (see Chapter 11 for what makes data “paired”), we compute the difference within each pair and test whether the mean difference is zero.</p>
<div class="important">
<p><strong>The test statistic for a paired mean difference is a <span class="math inline">\(T\)</span>.</strong></p>
<p><span class="math display">\[T = \frac{\bar{x}_{diff} - 0}{s_{diff} / \sqrt{n_{diff}}}\]</span></p>
<p>When the null hypothesis is true and conditions are met, <span class="math inline">\(T\)</span> follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = n_{diff} - 1\)</span>.</p>
<p><strong>Conditions:</strong></p>
<ul>
<li><strong>Independently sampled pairs.</strong></li>
<li><strong>Normality of differences.</strong> The differences should be approximately normal, or <span class="math inline">\(n_{diff}\)</span> should be large. Check for extreme outliers in the differences.</li>
</ul>
</div>
</section>
<section id="worked-example-textbook-prices" class="level3" data-number="13.4.2">
<h3 data-number="13.4.2" class="anchored" data-anchor-id="worked-example-textbook-prices"><span class="header-section-number">13.4.2</span> Worked example: Textbook prices</h3>
<div class="workedexample">
<p>Is there evidence that UCLA Bookstore prices differ from Amazon prices, on average? Summary statistics for the 68 price differences (UCLA <span class="math inline">\(-\)</span> Amazon):</p>
<table class="table-striped caption-top table">
<caption>Summary statistics for the 68 price differences.</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(n_{diff}\)</span></th>
<th><span class="math inline">\(\bar{x}_{diff}\)</span></th>
<th><span class="math inline">\(s_{diff}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>68</td>
<td>$3.58</td>
<td>$13.42</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>Step 1: State hypotheses.</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{diff} = 0\)</span> (no difference in average textbook price)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_{diff} \neq 0\)</span> (there is a difference in average price)</li>
</ul>
<p><strong>Step 2: Check conditions.</strong></p>
<ul>
<li><em>Independence.</em> The textbooks were a simple random sample of courses; pairs are independent.</li>
<li><em>Normality.</em> With <span class="math inline">\(n_{diff} = 68\)</span>, the CLT applies. While some outliers exist (a few textbooks with large price differences), none are extreme enough to invalidate the approach given the large sample size.</li>
</ul>
<p><strong>Step 3: Compute the test statistic and p-value.</strong></p>
<p><span class="math display">\[SE = \frac{s_{diff}}{\sqrt{n_{diff}}} = \frac{13.42}{\sqrt{68}} = 1.628\]</span></p>
<p><span class="math display">\[T = \frac{3.58 - 0}{1.628} = 2.20\]</span></p>
<p>With <span class="math inline">\(df = 68 - 1 = 67\)</span>, the one-tail area for <span class="math inline">\(T = 2.20\)</span> is approximately 0.0156. The two-tailed p-value is <span class="math inline">\(2 \times 0.0156 = 0.0312\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-t-two-tailed-df67" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A t-distribution curve with 67 degrees of freedom. Both tails beyond T equals negative 2.20 and T equals positive 2.20 are shaded. The combined shaded area represents the two-sided p-value of 0.0312.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-two-tailed-df67-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch12-hypothesis-tests-means_files/figure-html/fig-t-two-tailed-df67-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;13.2: A t-distribution with df = 67 showing the two-sided p-value. The shaded areas in both tails represent the p-value of 0.0312."><img src="ch12-hypothesis-tests-means_files/figure-html/fig-t-two-tailed-df67-1.png" class="img-fluid figure-img" alt="A t-distribution curve with 67 degrees of freedom. Both tails beyond T equals negative 2.20 and T equals positive 2.20 are shaded. The combined shaded area represents the two-sided p-value of 0.0312." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-two-tailed-df67-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: A <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 67\)</span> showing the two-sided p-value. The shaded areas in both tails represent the p-value of 0.0312.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Step 4: Conclusion.</strong> The p-value of 0.0312 is less than <span class="math inline">\(\alpha = 0.05\)</span>, so we reject <span class="math inline">\(H_0\)</span>. The data provide evidence that UCLA Bookstore prices are different from Amazon prices on average. Based on the positive mean difference, the UCLA Bookstore tends to charge more.</p>
</div>
<div class="guidedpractice">
<p>Researchers measured tire tread (in cm) for 25 cars, each equipped with one Smooth Turn and one Quick Spin tire. The mean tread difference (Smooth Turn <span class="math inline">\(-\)</span> Quick Spin) was <span class="math inline">\(\bar{x}_{diff} = 0.002\)</span> cm with <span class="math inline">\(s_{diff} = 0.004\)</span> cm. Test whether there is a difference in average tread wear between the two brands. Use <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<details>
<summary>
Show answer
</summary>
Hypotheses: <span class="math inline">\(H_0: \mu_{diff} = 0\)</span>, <span class="math inline">\(H_A: \mu_{diff} \neq 0\)</span>. Conditions: cars are independent, <span class="math inline">\(n = 25\)</span> and no extreme outliers reported. <span class="math inline">\(SE = 0.004/\sqrt{25} = 0.0008\)</span>. <span class="math inline">\(T = 0.002/0.0008 = 2.50\)</span>. With <span class="math inline">\(df = 24\)</span>, the two-tailed p-value is approximately 0.020. Since <span class="math inline">\(0.020 &lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span> and conclude there is evidence of a difference in tread wear between the two tire brands.
</details>
</div>
</section>
</section>
<section id="sec-sim-vs-t" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="sec-sim-vs-t"><span class="header-section-number">13.5</span> Connecting simulation-based and <span class="math inline">\(t\)</span>-based tests</h2>
<div class="original">
<p>An important theme throughout this course is that simulation-based methods and mathematical models are complementary approaches to the same questions. When conditions are met, they should give similar answers. Here we compare the two approaches explicitly.</p>
<section id="when-they-agree" class="level3" data-number="13.5.1">
<h3 data-number="13.5.1" class="anchored" data-anchor-id="when-they-agree"><span class="header-section-number">13.5.1</span> When they agree</h3>
<p>For the birth weights example:</p>
<ul>
<li><strong>Randomization test:</strong> Shuffle smoking/nonsmoking labels 10,000 times, compute the difference in means each time, and find the proportion of shuffled differences as extreme as 0.59 lbs. This gives a p-value around 0.001.</li>
<li><strong><span class="math inline">\(t\)</span>-test:</strong> The p-value was 0.00024.</li>
</ul>
<p>Both approaches lead to the same conclusion (reject <span class="math inline">\(H_0\)</span>) by a wide margin. This agreement is typical when sample sizes are moderate to large and conditions are met.</p>
</section>
<section id="when-they-might-disagree" class="level3" data-number="13.5.2">
<h3 data-number="13.5.2" class="anchored" data-anchor-id="when-they-might-disagree"><span class="header-section-number">13.5.2</span> When they might disagree</h3>
<p>Disagreement arises primarily in two situations:</p>
<ol type="1">
<li><strong>Small samples from skewed populations.</strong> The <span class="math inline">\(t\)</span>-test assumes the sampling distribution is symmetric, which may not hold for small samples from skewed distributions. A simulation-based approach can capture the asymmetry.</li>
<li><strong>Extreme outliers.</strong> The <span class="math inline">\(t\)</span>-test relies on <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(s\)</span>, both of which are sensitive to outliers. A randomization test, which works with ranks and permutations, can be more robust.</li>
</ol>
</section>
<section id="practical-guidance" class="level3" data-number="13.5.3">
<h3 data-number="13.5.3" class="anchored" data-anchor-id="practical-guidance"><span class="header-section-number">13.5.3</span> Practical guidance</h3>
<ul>
<li><strong>When conditions are clearly met</strong> (large samples, no extreme outliers), use the <span class="math inline">\(t\)</span>-test – it is simpler and faster.</li>
<li><strong>When conditions are borderline</strong> (moderate samples, mild skewness), consider running both approaches. If they agree, report the <span class="math inline">\(t\)</span>-test. If they disagree, investigate why and consider the simulation-based result more trustworthy.</li>
<li><strong>When conditions are clearly violated</strong> (small samples, strong skewness, extreme outliers), prefer the simulation-based approach.</li>
</ul>
</section>
</div>
</section>
<section id="sec-practical-significance" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="sec-practical-significance"><span class="header-section-number">13.6</span> Practical vs.&nbsp;statistical significance</h2>
<div class="important">
<p><strong>Statistical significance <span class="math inline">\(\neq\)</span> practical significance.</strong></p>
<p>A result is <strong>statistically significant</strong> if the p-value is below the chosen significance level <span class="math inline">\(\alpha\)</span>. But statistical significance only means the observed effect is unlikely to be due to chance alone. It says nothing about whether the effect is <em>large enough to matter in practice</em>.</p>
<p>With very large samples, even trivially small differences can be statistically significant. With very small samples, even large differences may not be statistically significant (due to low power).</p>
</div>
<div class="workedexample">
<p>A large study of 50,000 students found that students who eat breakfast score an average of 0.5 points higher on a 100-point exam than students who skip breakfast (<span class="math inline">\(p &lt; 0.001\)</span>). Is this result practically significant?</p>
<hr>
<p>The result is statistically significant (the p-value is very small), but the effect size of 0.5 points on a 100-point exam is tiny. A teacher or student would likely not consider half a point to be a meaningful difference. This is an example where statistical significance does not imply practical significance.</p>
</div>
<section id="effect-sizes" class="level3" data-number="13.6.1">
<h3 data-number="13.6.1" class="anchored" data-anchor-id="effect-sizes"><span class="header-section-number">13.6.1</span> Effect sizes</h3>
<div class="original">
<p>To bridge the gap between statistical and practical significance, researchers often report <strong>effect sizes</strong> – standardized measures of how large the observed effect is.</p>
<div class="definition">
<p><strong>Cohen’s <span class="math inline">\(d\)</span></strong> is a common measure of effect size for comparing two means. It expresses the difference in means as a multiple of the pooled standard deviation:</p>
<p><span class="math display">\[d = \frac{\bar{x}_1 - \bar{x}_2}{s_p}\]</span></p>
<p>where <span class="math inline">\(s_p\)</span> is the pooled standard deviation. General guidelines for interpreting <span class="math inline">\(d\)</span>:</p>
<table class="table-striped caption-top table">
<caption>Guidelines for interpreting Cohen’s <span class="math inline">\(d\)</span>.</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(|d|\)</span></th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.2</td>
<td>Small effect</td>
</tr>
<tr class="even">
<td>0.5</td>
<td>Medium effect</td>
</tr>
<tr class="odd">
<td>0.8</td>
<td>Large effect</td>
</tr>
</tbody>
</table>
</div>
<p>These guidelines are rough benchmarks. What constitutes a “meaningful” effect depends on the context. In medicine, even a small effect size might be important if it concerns a life-threatening condition. In education, a medium effect might be required for a costly intervention to be worthwhile.</p>
</div>
<div class="guidedpractice">
<p>In the birth weights study, the difference was 0.59 lbs with a pooled standard deviation of approximately 1.30 lbs. Compute Cohen’s <span class="math inline">\(d\)</span> and interpret it.</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(d = 0.59 / 1.30 = 0.45\)</span>. This is between a small and medium effect. While the difference is statistically significant, the practical impact is moderate – about half a standard deviation in birth weight.
</details>
</div>
</section>
</section>
<section id="sec-ch12-review" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="sec-ch12-review"><span class="header-section-number">13.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="13.7.1">
<h3 data-number="13.7.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">13.7.1</span> Summary</h3>
<p>This chapter presented hypothesis tests for means using the <span class="math inline">\(t\)</span>-distribution:</p>
<ul>
<li><strong>One-sample <span class="math inline">\(t\)</span>-test</strong>: Tests whether a population mean <span class="math inline">\(\mu\)</span> equals a hypothesized value <span class="math inline">\(\mu_0\)</span>. Test statistic: <span class="math inline">\(T = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}\)</span> with <span class="math inline">\(df = n - 1\)</span>.</li>
<li><strong>Two-sample <span class="math inline">\(t\)</span>-test</strong>: Tests whether two population means are equal. Test statistic: <span class="math inline">\(T = \frac{(\bar{x}_1 - \bar{x}_2)}{\sqrt{s_1^2/n_1 + s_2^2/n_2}}\)</span> with <span class="math inline">\(df = \min(n_1 - 1, n_2 - 1)\)</span>.</li>
<li><strong>Paired <span class="math inline">\(t\)</span>-test</strong>: Tests whether the mean of paired differences equals zero. Compute differences first, then apply the one-sample <span class="math inline">\(t\)</span>-test to the differences: <span class="math inline">\(T = \frac{\bar{x}_{diff}}{s_{diff}/\sqrt{n_{diff}}}\)</span> with <span class="math inline">\(df = n_{diff} - 1\)</span>.</li>
<li>All three tests require <strong>independence</strong> and <strong>approximate normality or large sample size</strong>.</li>
<li><strong>Simulation-based and <span class="math inline">\(t\)</span>-based tests</strong> generally agree when conditions are met. When conditions are questionable, simulation is more reliable.</li>
<li><strong>Statistical significance</strong> (small p-value) does not imply <strong>practical significance</strong> (large enough to matter). Effect sizes like <strong>Cohen’s <span class="math inline">\(d\)</span></strong> help assess practical importance.</li>
</ul>
</section>
<section id="key-terms" class="level3" data-number="13.7.2">
<h3 data-number="13.7.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">13.7.2</span> Key terms</h3>
<p><span class="math inline">\(T\)</span> test statistic, one-sample <span class="math inline">\(t\)</span>-test, two-sample <span class="math inline">\(t\)</span>-test, paired <span class="math inline">\(t\)</span>-test, degrees of freedom, p-value, significance level (<span class="math inline">\(\alpha\)</span>), statistical significance, practical significance, effect size, Cohen’s <span class="math inline">\(d\)</span>.</p>
</section>
<section id="exercises" class="level3 exercises" data-number="13.7.3">
<h3 class="exercises anchored" data-number="13.7.3" data-anchor-id="exercises"><span class="header-section-number">13.7.3</span> Exercises</h3>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _19-ex-inference-one-mean, _20-ex-inference-two-means, _21-ex-inference-paired-means -->
<ol type="1">
<li><p><strong>Find the p-value, I.</strong> A random sample is selected from an approximately normal population with an unknown standard deviation. Find the p-value for the given sample size and test statistic. Also determine if the null hypothesis would be rejected at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.425, 0.425]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.6%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="ab" class="quarto-layout-cell" style="flex-basis: 47.2%;justify-content: flex-start;">
<ol type="a">
<li><p><span class="math inline">\(n = 11\)</span>, <span class="math inline">\(T = 1.91\)</span></p></li>
<li><p><span class="math inline">\(n = 17\)</span>, <span class="math inline">\(T = -3.45\)</span></p></li>
</ol>
</div>
<div id="cd" class="quarto-layout-cell" style="flex-basis: 47.2%;justify-content: flex-start;">
<ol start="3" type="a">
<li><p><span class="math inline">\(n = 7\)</span>, <span class="math inline">\(T = 0.83\)</span></p></li>
<li><p><span class="math inline">\(n = 28\)</span>, <span class="math inline">\(T = 2.13\)</span></p></li>
</ol>
</div>
</div>
</div></li>
</ol>
<!--- MOM ims-19-09
ims_exercise: "19.9"
title: "Find the p-value, I"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.9 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate 4 scenarios with randomized n and T for two-tailed tests
// Part (a)
$n1 = rand(8, 15)
$T1 = rrand(1.5, 2.5, 0.01)
$df1 = $n1 - 1
$pval1 = round(2 * (1 - tcdf($T1, $df1)), 3)
$reject1 = ($pval1 < 0.05) ? "Reject" : "Fail to reject"

// Part (b)
$n2 = rand(12, 25)
$T2 = -1 * rrand(2.5, 4.0, 0.01)
$df2 = $n2 - 1
$pval2 = round(2 * tcdf($T2, $df2), 3)
$reject2 = ($pval2 < 0.05) ? "Reject" : "Fail to reject"

// Part (c)
$n3 = rand(5, 10)
$T3 = rrand(0.3, 1.2, 0.01)
$df3 = $n3 - 1
$pval3 = round(2 * (1 - tcdf($T3, $df3)), 3)
$reject3 = ($pval3 < 0.05) ? "Reject" : "Fail to reject"

// Part (d)
$n4 = rand(20, 35)
$T4 = rrand(1.8, 2.8, 0.01)
$df4 = $n4 - 1
$pval4 = round(2 * (1 - tcdf($T4, $df4)), 3)
$reject4 = ($pval4 < 0.05) ? "Reject" : "Fail to reject"

$abstolerance = 0.005

// === Question Text ===
// <p>A random sample is selected from an approximately normal population with an unknown standard deviation.
// Find the p-value for each <b>two-tailed</b> test and determine if H<sub>0</sub> would be rejected at &alpha; = 0.05.</p>
//
// <p>(a) n = $n1, T = $T1</p>
// <p>p-value = </p> $answerbox[0]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[1]
//
// <p>(b) n = $n2, T = $T2</p>
// <p>p-value = </p> $answerbox[2]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[3]
//
// <p>(c) n = $n3, T = $T3</p>
// <p>p-value = </p> $answerbox[4]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[5]
//
// <p>(d) n = $n4, T = $T4</p>
// <p>p-value = </p> $answerbox[6]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[7]

// === Answer ===
$answer[0] = $pval1
$answer[1] = $reject1
$displayformat[1] = "radio"
$showanswer[1] = array("Reject", "Fail to reject")
$answer[2] = $pval2
$answer[3] = $reject2
$displayformat[3] = "radio"
$showanswer[3] = array("Reject", "Fail to reject")
$answer[4] = $pval3
$answer[5] = $reject3
$displayformat[5] = "radio"
$showanswer[5] = array("Reject", "Fail to reject")
$answer[6] = $pval4
$answer[7] = $reject4
$displayformat[7] = "radio"
$showanswer[7] = array("Reject", "Fail to reject")

END MOM --->
<ol start="2" type="1">
<li><p><strong>Find the p-value, II.</strong> A random sample is selected from an approximately normal population with an unknown standard deviation. Find the p-value for the given sample size and test statistic. Also determine if the null hypothesis would be rejected at <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<ol type="a">
<li><p><span class="math inline">\(n = 26\)</span>, <span class="math inline">\(T = 2.485\)</span></p></li>
<li><p><span class="math inline">\(n = 18\)</span>, <span class="math inline">\(T = 0.5\)</span></p></li>
</ol></li>
</ol>
<!--- MOM ims-19-10
ims_exercise: "19.10"
title: "Find the p-value, II"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.10 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Two scenarios for two-tailed t-test at alpha = 0.01
// Part (a): moderate to large T
$n1 = rand(20, 35)
$T1 = rrand(2.0, 3.5, 0.001)
$df1 = $n1 - 1
$pval1 = round(2 * (1 - tcdf($T1, $df1)), 4)
$reject1 = ($pval1 < 0.01) ? "Reject" : "Fail to reject"

// Part (b): small T
$n2 = rand(12, 25)
$T2 = rrand(0.2, 1.5, 0.001)
$df2 = $n2 - 1
$pval2 = round(2 * (1 - tcdf($T2, $df2)), 4)
$reject2 = ($pval2 < 0.01) ? "Reject" : "Fail to reject"

$abstolerance = 0.005

// === Question Text ===
// <p>A random sample is selected from an approximately normal population with an unknown standard deviation.
// Find the p-value for each <b>two-tailed</b> test and determine if H<sub>0</sub> would be rejected at &alpha; = 0.01.</p>
//
// <p>(a) n = $n1, T = $T1</p>
// <p>p-value = </p> $answerbox[0]
// <p>Decision at &alpha; = 0.01:</p> $answerbox[1]
//
// <p>(b) n = $n2, T = $T2</p>
// <p>p-value = </p> $answerbox[2]
// <p>Decision at &alpha; = 0.01:</p> $answerbox[3]

// === Answer ===
$answer[0] = $pval1
$answer[1] = $reject1
$displayformat[1] = "radio"
$showanswer[1] = array("Reject", "Fail to reject")
$answer[2] = $pval2
$answer[3] = $reject2
$displayformat[3] = "radio"
$showanswer[3] = array("Reject", "Fail to reject")

END MOM --->
<ol start="3" type="1">
<li><p><strong>Length of gestation, hypothesis test.</strong> In this exercise we work with a random sample of 1,000 cases from the dataset released by the United States Department of Health and Human Services in 2014. Provided below are sample statistics for gestation (length of pregnancy, measured in weeks) of births in this sample.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Max</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">21</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">38.7</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What is the point estimate for the average length of pregnancy for all women? What about the median?</p></li>
<li><p>You might have heard that human gestation is typically 40 weeks. Using the data, perform a complete hypothesis test, using mathematical models, to assess the 40 week claim. State the null and alternative hypotheses, find the T score, find the p-value, and provide a conclusion in context of the data.</p></li>
<li><p>A quick internet search validates the claim of “40 weeks gestation” for humans. A friend of yours claims that there are different ways to measure gestation (starting at first day of last period, ovulation, or conception) which will result in estimates that are a week or two different. Another friend mentions that recent increases in cesarean births is likely to have decreased length of gestation. Do the data provide a mechanism to distinguish between your two friends’ claims?</p></li>
</ol></li>
</ol>
<!--- MOM ims-19-12
ims_exercise: "19.12"
title: "Length of gestation, hypothesis test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.12 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Based on births14: n=1000, mean~38.7, sd~2.6, testing against mu=40
$n = rand(800, 1200)
$xbar = rrand(38.3, 39.1, 0.1)
$sd = rrand(2.2, 3.0, 0.1)
$mu0 = 40

$df = $n - 1
$se = round($sd / sqrt($n), 4)
$T = round(($xbar - $mu0) / $se, 2)
// Two-tailed test: mu != 40
$pval = round(2 * tcdf($T, $df), 4)

$reject = ($pval < 0.05) ? "Reject" : "Fail to reject"

$abstolerance = 0.01

// === Question Text ===
// <p>A random sample of $n births has a mean gestation of $xbar weeks with a standard deviation of $sd weeks.
// Human gestation is typically claimed to be 40 weeks.</p>
//
// <p>(a) What is the point estimate for the average length of pregnancy?</p>
// $answerbox[0]
//
// <p>(b) Conduct a hypothesis test to assess the 40-week claim.
// H<sub>0</sub>: &mu; = $mu0 vs. H<sub>A</sub>: &mu; &ne; $mu0</p>
// <p>Standard error: SE = </p> $answerbox[1]
// <p>Test statistic: T = </p> $answerbox[2]
// <p>Degrees of freedom: df = </p> $answerbox[3]
// <p>p-value = </p> $answerbox[4]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[5]

// === Answer ===
$answer[0] = $xbar
$abstolerance[0] = 0.01
$answer[1] = $se
$abstolerance[1] = 0.01
$answer[2] = $T
$abstolerance[2] = 0.1
$answer[3] = $df
$abstolerance[3] = 0
$answer[4] = $pval
$abstolerance[4] = 0.005
$answer[5] = $reject
$displayformat[5] = "radio"
$showanswer[5] = array("Reject", "Fail to reject")

END MOM --->
<ol start="4" type="1">
<li><p><strong>Interpreting p-values for population mean.</strong> For each of the following statements, indicate if they are a true or false interpretation of the p-value. If false, provide a reason or correction to the misinterpretation. You are wondering if the average amount of cereal in a 10oz cereal box is greater than 10oz. You collect 50 boxes of cereal, weigh them carefully, find a T score, and a p-value of 0.23.</p>
<ol type="a">
<li><p>The probability that the average weight of all cereal boxes is 10 oz is 0.23.</p></li>
<li><p>The probability that the average weight of all cereal boxes is greater than 10 oz is 0.23.</p></li>
<li><p>Because the p-value is 0.23, the average weight of all cereal boxes is 10 oz.</p></li>
<li><p>Because the p-value is small, the population average must be just barely above 10 oz.</p></li>
<li><p>If <span class="math inline">\(H_0\)</span> is true, the probability of observing another sample with an average as or more extreme as the data is 0.23.</p></li>
</ol></li>
</ol>
<!--- MOM ims-19-14
ims_exercise: "19.14"
title: "Interpreting p-values for population mean"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.14 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Randomize the p-value and context
$pval = rrand(0.15, 0.40, 0.01)
$n_samp = rand(40, 80)
$label_val = randfrom(10, 12, 16, 20)
$unit = randfrom("oz", "oz", "g", "g")

$contexts = array(
  array("the average amount of cereal in a ${label_val}${unit} cereal box is greater than ${label_val}${unit}", "${label_val}${unit}", "greater than ${label_val}${unit}"),
  array("the average weight of a ${label_val}${unit} bag of chips is greater than ${label_val}${unit}", "${label_val}${unit}", "greater than ${label_val}${unit}")
)
$cidx = rand(0, count($contexts)-1)
$claim = $contexts[$cidx][0]
$null_val = $contexts[$cidx][1]
$alt_dir = $contexts[$cidx][2]

// === Question Text ===
// <p>You are wondering if $claim.
// You collect $n_samp items, weigh them carefully, find a T score, and a p-value of $pval.</p>
// <p>For each statement, indicate if it is <b>true</b> or <b>false</b>.</p>
//
// <p>(a) The probability that the average weight of all boxes is $null_val is $pval.</p>
// $answerbox[0]
//
// <p>(b) The probability that the average weight of all boxes is $alt_dir is $pval.</p>
// $answerbox[1]
//
// <p>(c) Because the p-value is $pval, the average weight of all boxes is $null_val.</p>
// $answerbox[2]
//
// <p>(d) Because the p-value is not small, the population average must be just barely above $null_val.</p>
// $answerbox[3]
//
// <p>(e) If H<sub>0</sub> is true, the probability of observing another sample with an average
// as or more extreme as the data is $pval.</p>
// $answerbox[4]

// === Answer ===
$choices = array("True", "False")
$answer[0] = "False"
$displayformat[0] = "radio"
$showanswer[0] = $choices
$answer[1] = "False"
$displayformat[1] = "radio"
$showanswer[1] = $choices
$answer[2] = "False"
$displayformat[2] = "radio"
$showanswer[2] = $choices
$answer[3] = "False"
$displayformat[3] = "radio"
$showanswer[3] = $choices
$answer[4] = "True"
$displayformat[4] = "radio"
$showanswer[4] = $choices

END MOM --->
<ol start="5" type="1">
<li><p><strong>Sleep habits of New Yorkers.</strong> New York is known as “the city that never sleeps”. A random sample of 25 New Yorkers were asked how much sleep they get per night. Statistical summaries of these data are shown below. The point estimate suggests New Yorkers sleep less than 8&nbsp;hours a night on average. Evaluate the claim that New York is the city that never sleeps keeping in mind that, despite this claim, the true average number of hours New Yorkers sleep could be less than 8 hours or more than 8 hours.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 5em;">25</td>
<td style="text-align: center; width: 5em;">7.73</td>
<td style="text-align: center; width: 5em;">0.77</td>
<td style="text-align: center; width: 5em;">6.17</td>
<td style="text-align: center; width: 5em;">9.78</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Write the hypotheses in symbols and in words.</p></li>
<li><p>Check conditions, then calculate the test statistic, <span class="math inline">\(T\)</span>, and the associated degrees of freedom.</p></li>
<li><p>Find and interpret the p-value in this context. Drawing a picture may be helpful.</p></li>
<li><p>What is the conclusion of the hypothesis test?</p></li>
<li><p>If you were to construct a 90% confidence interval that corresponded to this hypothesis test, would you expect 8 hours to be in the interval?</p></li>
</ol></li>
</ol>
<!--- MOM ims-19-17
ims_exercise: "19.17"
title: "Sleep habits of New Yorkers"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.17 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Based on exercise: n=25, mean=7.73, sd=0.77, test mu=8 (two-tailed)
// Randomize slightly around these values
$n = rand(20, 35)
$xbar = rrand(7.40, 7.90, 0.01)
$sd = rrand(0.60, 1.00, 0.01)
$mu0 = 8

$df = $n - 1
$se = round($sd / sqrt($n), 4)
$T = round(($xbar - $mu0) / $se, 2)
// Two-tailed test
$pval = round(2 * tcdf($T, $df), 4)
$reject = ($pval < 0.05) ? "Reject" : "Fail to reject"

// 90% CI
$tstar90 = round(invtcdf(0.95, $df), 3)
$me90 = round($tstar90 * $se, 4)
$lower90 = round($xbar - $me90, 2)
$upper90 = round($xbar + $me90, 2)
$contains8 = ($lower90 <= 8 && $upper90 >= 8) ? "Yes" : "No"

$abstolerance = 0.01

// === Question Text ===
// <p>A random sample of $n New Yorkers were asked how much sleep they get per night.
// Summary: mean = $xbar hours, SD = $sd hours.</p>
// <p>Test the claim that the average sleep differs from 8 hours.
// H<sub>0</sub>: &mu; = $mu0, H<sub>A</sub>: &mu; &ne; $mu0</p>
//
// <p>(a) Test statistic T = </p> $answerbox[0]
// <p>(b) Degrees of freedom: df = </p> $answerbox[1]
// <p>(c) p-value = </p> $answerbox[2]
// <p>(d) Decision at &alpha; = 0.05:</p> $answerbox[3]
// <p>(e) Would you expect a 90% confidence interval to contain 8 hours?</p> $answerbox[4]

// === Answer ===
$answer[0] = $T
$abstolerance[0] = 0.01
$answer[1] = $df
$abstolerance[1] = 0
$answer[2] = $pval
$abstolerance[2] = 0.005
$answer[3] = $reject
$displayformat[3] = "radio"
$showanswer[3] = array("Reject", "Fail to reject")
$answer[4] = $contains8
$displayformat[4] = "radio"
$showanswer[4] = array("Yes", "No")

END MOM --->
<ol start="6" type="1">
<li><p><strong>Find the mean.</strong> You are given the hypotheses shown below. We know that the sample standard deviation is 8 and the sample size is 20. For what sample mean would the p-value be equal to 0.05? Assume that all conditions necessary for inference are satisfied.</p>
<p><span class="math display">\[H_0: \mu = 60 \quad \quad H_A: \mu \neq 60\]</span></p></li>
</ol>
<!--- MOM ims-19-18
ims_exercise: "19.18"
title: "Find the mean"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.18 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Given: H0: mu = mu0, HA: mu != mu0, s, n, p-value = 0.05
// Find xbar such that p-value = 0.05 (two-tailed)
$mu0 = rand(40, 80)
$sd = rand(5, 12)
$n = rand(15, 30)
$df = $n - 1

// t* for two-tailed alpha = 0.05
$tstar = round(invtcdf(0.975, $df), 4)
$se = round($sd / sqrt($n), 4)

// xbar = mu0 + t* x SE (above mu0) or mu0 - t* x SE (below)
// Randomly choose direction
$dir = rand(0, 1)
if ($dir == 0) {
  $xbar = round($mu0 + $tstar * $se, 2)
} else {
  $xbar = round($mu0 - $tstar * $se, 2)
}

$abstolerance = 0.1

// === Question Text ===
// <p>You are given the following hypotheses:</p>
// <p>H<sub>0</sub>: &mu; = $mu0 &nbsp;&nbsp; H<sub>A</sub>: &mu; &ne; $mu0</p>
// <p>The sample standard deviation is $sd and the sample size is $n.
// For what sample mean would the p-value be equal to 0.05?
// Assume all conditions for inference are satisfied.</p>
//
// <p>(a) Critical t* value (for &alpha; = 0.05 two-tailed):</p> $answerbox[0]
// <p>(b) Standard error: SE = </p> $answerbox[1]
// <p>(c) Sample mean `bar x` = </p> $answerbox[2]
// <p>(Hint: there are two possible values; give the one further from $mu0 in the direction you compute.)</p>

// === Answer ===
$answer[0] = round($tstar, 2)
$abstolerance[0] = 0.01
$answer[1] = $se
$abstolerance[1] = 0.01
$answer[2] = $xbar
$abstolerance[2] = 0.1

END MOM --->
<ol start="7" type="1">
<li><p><strong>Play the piano.</strong> Georgianna claims that in a small city renowned for its music school, the average child takes less than 5 years of piano lessons. We have a random sample of 20 children from the city, with a mean of 4.6 years of piano lessons and a standard deviation of 2.2 years.</p>
<ol type="a">
<li><p>Evaluate Georgianna’s claim (or that the opposite might be true) using a hypothesis test.</p></li>
<li><p>Construct a 95% confidence interval for the number of years students in this city take piano lessons, and interpret it in context of the data.</p></li>
<li><p>Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning.</p></li>
</ol></li>
</ol>
<!--- MOM ims-19-21
ims_exercise: "19.21"
title: "Play the piano"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.21 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Based on exercise: n=20, xbar=4.6, sd=2.2, test mu=5 (two-tailed)
// Randomize around these values
$n = rand(15, 30)
$mu0 = rand(4, 7)
$xbar = rrand($mu0 - 1.0, $mu0 + 1.0, 0.1) where (abs($xbar - $mu0) > 0.2)
$sd = rrand(1.5, 3.0, 0.1)

$df = $n - 1
$se = round($sd / sqrt($n), 4)
$T = round(($xbar - $mu0) / $se, 2)

// Two-tailed p-value
if ($T < 0) {
  $pval = round(2 * tcdf($T, $df), 4)
} else {
  $pval = round(2 * (1 - tcdf($T, $df)), 4)
}
$reject = ($pval < 0.05) ? "Reject" : "Fail to reject"

// 95% CI
$tstar = round(invtcdf(0.975, $df), 3)
$me = round($tstar * $se, 4)
$lower = round($xbar - $me, 2)
$upper = round($xbar + $me, 2)

// Do the test and CI agree?
$ci_contains_mu0 = ($lower <= $mu0 && $upper >= $mu0) ? "Yes" : "No"
$agree = ($reject == "Fail to reject" && $ci_contains_mu0 == "Yes") || ($reject == "Reject" && $ci_contains_mu0 == "No")
$agree_text = $agree ? "Yes, they agree" : "Yes, they agree"

$abstolerance = 0.01

// === Question Text ===
// <p>Georgianna claims that in a small city, the average child takes less than $mu0 years of piano lessons.
// A random sample of $n children has a mean of $xbar years and a standard deviation of $sd years.</p>
//
// <p>(a) Conduct a two-tailed hypothesis test at &alpha; = 0.05.
// H<sub>0</sub>: &mu; = $mu0, H<sub>A</sub>: &mu; &ne; $mu0</p>
// <p>Standard error: SE = </p> $answerbox[0]
// <p>Test statistic: T = </p> $answerbox[1]
// <p>Degrees of freedom: df = </p> $answerbox[2]
// <p>p-value = </p> $answerbox[3]
// <p>Decision at &alpha; = 0.05:</p> $answerbox[4]
//
// <p>(b) Construct a 95% confidence interval for &mu;.</p>
// <p>Lower bound:</p> $answerbox[5]
// <p>Upper bound:</p> $answerbox[6]
//
// <p>(c) Does the 95% CI contain $mu0?</p> $answerbox[7]

// === Answer ===
$answer[0] = $se
$abstolerance[0] = 0.01
$answer[1] = $T
$abstolerance[1] = 0.01
$answer[2] = $df
$abstolerance[2] = 0
$answer[3] = $pval
$abstolerance[3] = 0.005
$answer[4] = $reject
$displayformat[4] = "radio"
$showanswer[4] = array("Reject", "Fail to reject")
$answer[5] = $lower
$abstolerance[5] = 0.05
$answer[6] = $upper
$abstolerance[6] = 0.05
$answer[7] = $ci_contains_mu0
$displayformat[7] = "radio"
$showanswer[7] = array("Yes", "No")

END MOM --->
<ol start="8" type="1">
<li><p><strong>Auto exhaust and lead exposure.</strong> Researchers interested in lead exposure due to car exhaust sampled the blood of 52 police officers subjected to constant inhalation of automobile exhaust fumes while working traffic enforcement in a primarily urban environment. The blood samples of these officers had an average lead concentration of 124.32 <span class="math inline">\(\mu\)</span>g/l and a SD of 37.74 <span class="math inline">\(\mu\)</span>g/l; a previous study of individuals from a nearby suburb, with no history of exposure, found an average blood level concentration of 35 <span class="math inline">\(\mu\)</span>g/l. <span class="citation" data-cites="Mortada:2000">[@Mortada:2000]</span></p>
<ol type="a">
<li><p>Write down the hypotheses that would be appropriate for testing if the police officers appear to have been exposed to a different concentration of lead.</p></li>
<li><p>Explicitly state and check all conditions necessary for inference on these data.</p></li>
<li><p>Test the hypothesis that the downtown police officers have a higher lead exposure than the group in the previous study. Interpret your results in context.</p></li>
</ol></li>
</ol>
<!--- MOM ims-19-22
ims_exercise: "19.22"
title: "Auto exhaust and lead exposure"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 19.22 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Based on exercise: n=52, xbar=124.32, sd=37.74, mu0=35 (one-sided: mu > 35)
// Randomize around these values
$n = rand(40, 65)
$mu0 = rand(30, 45)
$xbar = rrand(110, 140, 0.01)
$sd = rrand(30, 50, 0.01)

$df = $n - 1
$se = round($sd / sqrt($n), 4)
$T = round(($xbar - $mu0) / $se, 2)

// One-tailed test (greater than)
$pval = round(1 - tcdf($T, $df), 4)
$reject = ($pval < 0.05) ? "Reject" : "Fail to reject"

$abstolerance = 0.01

// === Question Text ===
// <p>Researchers sampled the blood of $n police officers exposed to automobile exhaust.
// The blood samples had an average lead concentration of $xbar &mu;g/l and a SD of $sd &mu;g/l.
// A previous study of unexposed individuals found an average blood lead level of $mu0 &mu;g/l.</p>
//
// <p>Test the hypothesis that the police officers have a <b>higher</b> lead exposure than the unexposed group.</p>
// <p>H<sub>0</sub>: &mu; = $mu0, H<sub>A</sub>: &mu; &gt; $mu0</p>
//
// <p>(a) Standard error: SE = </p> $answerbox[0]
// <p>(b) Test statistic: T = </p> $answerbox[1]
// <p>(c) Degrees of freedom: df = </p> $answerbox[2]
// <p>(d) p-value (one-tailed) = </p> $answerbox[3]
// <p>(e) Decision at &alpha; = 0.05:</p> $answerbox[4]

// === Answer ===
$answer[0] = $se
$abstolerance[0] = 0.01
$answer[1] = $T
$abstolerance[1] = 0.1
$answer[2] = $df
$abstolerance[2] = 0
$answer[3] = $pval
$abstolerance[3] = 0.005
$answer[4] = $reject
$displayformat[4] = "radio"
$showanswer[4] = array("Reject", "Fail to reject")

END MOM --->
<ol start="9" type="1">
<li><p><strong>Experimental baker.</strong> A baker working on perfecting their bagel recipe is experimenting with active dry (AD) and instant (I) yeast. They bake a dozen bagels with each type of yeast and score each bagel on a scale of 1 to 10 on how well the bagels rise. They come up with the following set of hypotheses for evaluating whether there is a difference in the average rise of bagels baked with active dry and instant yeast. What is wrong with the hypotheses as stated?</p>
<p><span class="math display">\[H_0: \bar{x}_{AD} \leq \bar{x}_{I} \quad \quad H_A: \bar{x}_{AD} &gt; \bar{x}_{I}\]</span></p></li>
</ol>
<!--- MOM ims-20-01
ims_exercise: "20.1"
title: "Experimental baker"
type: multiple_choice
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.1 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// No library needed — purely conceptual MC

$choices = array(
  "The hypotheses should use population means (&mu;) not sample means (x&#772;), and the null hypothesis should set the two means equal.",
  "The hypotheses are correct as stated.",
  "The alternative hypothesis should be two-tailed (&ne;), but using sample means is fine.",
  "The null hypothesis should use a strict inequality (<) instead of &le;."
)
$answer_idx = 0

// === Question Text ===
// A baker is experimenting with active dry (AD) and instant (I) yeast. They bake a dozen bagels with each type and score each on a scale of 1 to 10 for how well the bagels rise. They propose:
// <br><br>
// H<sub>0</sub>: x&#772;<sub>AD</sub> &le; x&#772;<sub>I</sub> &nbsp;&nbsp; H<sub>A</sub>: x&#772;<sub>AD</sub> &gt; x&#772;<sub>I</sub>
// <br><br>
// What is wrong with these hypotheses?

// === Answer ===
$answer = $choices[$answer_idx]
$displayformat = "radio"

END MOM --->
<ol start="10" type="1">
<li><strong>Diamonds, randomization test.</strong> The prices of diamonds go up as the carat weight increases, but the increase is not smooth. For example, the difference between the size of a 0.99 carat diamond and a 1 carat diamond is undetectable to the naked human eye, but the price of a 1 carat diamond tends to be much higher than the price of a 0.99 carat diamond. We have two random samples of diamonds: 23 0.99 carat diamonds and 23 1 carat diamonds. In order to be able to compare equivalent units, we first divide the price for each diamond by 100 times its weight in carats. That is, for a 0.99 carat diamond, we divide the price by 99 and for a 1 carat diamond, we divide it by 100. Then, we randomize the carat weight to the price values in order simulate the null distribution of differences in average prices of 0.99 carat and 1 carat diamonds. The null distribution (with 1,000 randomized differences) is shown below and depicts the distribution of differences in sample means (of price per carat) if there really was no difference in the population from which these diamonds came.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <span class="citation" data-cites="ggplot2">[@ggplot2]</span></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-4-1.png){width=2100}
:::
:::





Using the randomization distribution, conduct a hypothesis test to evaluate if there is a difference between the prices per carat of diamonds that weigh 0.99 carats and diamonds that weigh 1 carat.
Make sure to state your hypotheses clearly and interpret your results in context of the data.
[@ggplot2]</code></pre>
<!--- MOM ims-20-03
ims_exercise: "20.3"
title: "Diamonds, randomization test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.3 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Adapted: skip figure interpretation, use a randomization-based conceptual question.
// The original uses a specific randomization distribution histogram.
// We present the observed difference and ask students about hypotheses and conclusion.

$obs_diff = -12.7
$pval_approx = 0.02

$choices_h0 = array(
  "&mu;<sub>0.99</sub> = &mu;<sub>1</sub>",
  "&mu;<sub>0.99</sub> &lt; &mu;<sub>1</sub>",
  "x&#772;<sub>0.99</sub> = x&#772;<sub>1</sub>",
  "&mu;<sub>0.99</sub> &ne; &mu;<sub>1</sub>"
)
$choices_ha = array(
  "&mu;<sub>0.99</sub> &ne; &mu;<sub>1</sub>",
  "&mu;<sub>0.99</sub> = &mu;<sub>1</sub>",
  "&mu;<sub>0.99</sub> &lt; &mu;<sub>1</sub>",
  "x&#772;<sub>0.99</sub> &ne; x&#772;<sub>1</sub>"
)
$choices_decision = array(
  "Reject H<sub>0</sub>; there is convincing evidence of a difference in prices per carat.",
  "Fail to reject H<sub>0</sub>; there is not convincing evidence of a difference.",
  "Accept H<sub>A</sub>; 0.99 carat diamonds are definitely cheaper per carat.",
  "Reject H<sub>A</sub>; the data are consistent with equal prices."
)

// === Question Text ===
// We have two random samples of diamonds: 23 diamonds weighing 0.99 carats and 23 weighing 1 carat. After dividing each diamond's price by 100 times its carat weight, the observed difference in means is:
// <br><br>
// x&#772;<sub>0.99</sub> &minus; x&#772;<sub>1</sub> = $obs_diff dollars per carat.
// <br><br>
// A randomization distribution of 1,000 simulated differences (assuming no real difference) shows that about 2% of randomized differences are as extreme as the observed difference.
// <br><br>
// (a) State the null hypothesis: $answerbox[0]
// <br>
// (b) State the alternative hypothesis: $answerbox[1]
// <br>
// (c) Given the p-value is approximately 0.02, what is the conclusion at &alpha; = 0.05? $answerbox[2]

// === Answer ===
$answer[0] = $choices_h0[0]
$answer[1] = $choices_ha[0]
$answer[2] = $choices_decision[0]
$displayformat[0] = "radio"
$displayformat[1] = "radio"
$displayformat[2] = "radio"
$answerformat[0] = $choices_h0
$answerformat[1] = $choices_ha
$answerformat[2] = $choices_decision

END MOM --->
<ol start="11" type="1">
<li><strong>Lizards running, randomization test.</strong> In order to assess physiological characteristics of common lizards, data on top speeds (in m/sec) measured on a laboratory race track for two species of lizards: Western fence lizard (Sceloporus occidentalis) and Sagebrush lizard (Sceloporus graciosus). The original observed difference in lizard speeds is <span class="math inline">\(\bar{x}_{Western fence} - \bar{x}_{Sagebrush} = 0.7 \mbox{m/sec}.\)</span> The histogram below shows the distribution of average differences when speed has been randomly allocated across lizard species 1,000 times. Using the randomization distribution, conduct a hypothesis test to evaluate if there is a difference between the average speed of the Western fence lizard as compared to the Sagebrush lizard. Make sure to state your hypotheses clearly and interpret your results in context of the data.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> <span class="citation" data-cites="Adolph:1987">[@Adolph:1987]</span></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-5-1.png){width=2100}
:::
:::</code></pre>
<!--- MOM ims-20-04
ims_exercise: "20.4"
title: "Lizards running, randomization test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.4 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Adapted: skip figure interpretation. Present observed difference and approximate p-value.

$obs_diff = 0.7

$choices_h0 = array(
  "&mu;<sub>Western fence</sub> = &mu;<sub>Sagebrush</sub>",
  "&mu;<sub>Western fence</sub> &gt; &mu;<sub>Sagebrush</sub>",
  "x&#772;<sub>Western fence</sub> = x&#772;<sub>Sagebrush</sub>",
  "&mu;<sub>Western fence</sub> &ne; &mu;<sub>Sagebrush</sub>"
)
$choices_ha = array(
  "&mu;<sub>Western fence</sub> &ne; &mu;<sub>Sagebrush</sub>",
  "&mu;<sub>Western fence</sub> = &mu;<sub>Sagebrush</sub>",
  "&mu;<sub>Western fence</sub> &gt; &mu;<sub>Sagebrush</sub>",
  "x&#772;<sub>Western fence</sub> &ne; x&#772;<sub>Sagebrush</sub>"
)
$choices_decision = array(
  "Fail to reject H<sub>0</sub>; there is not convincing evidence of a difference in average speed.",
  "Reject H<sub>0</sub>; there is convincing evidence of a difference in average speed.",
  "Accept H<sub>A</sub>; Western fence lizards are definitely faster.",
  "Reject H<sub>A</sub>; the two species run at the same speed."
)

// === Question Text ===
// Data on top speeds (m/sec) were collected for two lizard species: Western fence lizard and Sagebrush lizard. The observed difference in sample means is:
// <br><br>
// x&#772;<sub>Western fence</sub> &minus; x&#772;<sub>Sagebrush</sub> = $obs_diff m/sec.
// <br><br>
// A randomization distribution of 1,000 simulated differences (assuming no real difference) shows that roughly 30% of randomized differences are as extreme or more extreme than the observed difference.
// <br><br>
// (a) State the null hypothesis: $answerbox[0]
// <br>
// (b) State the alternative hypothesis: $answerbox[1]
// <br>
// (c) Given the approximate p-value of 0.30, what is the conclusion at &alpha; = 0.05? $answerbox[2]

// === Answer ===
$answer[0] = $choices_h0[0]
$answer[1] = $choices_ha[0]
$answer[2] = $choices_decision[0]
$displayformat[0] = "radio"
$displayformat[1] = "radio"
$displayformat[2] = "radio"
$answerformat[0] = $choices_h0
$answerformat[1] = $choices_ha
$answerformat[2] = $choices_decision

END MOM --->
<ol start="12" type="1">
<li><strong>Possible randomized means.</strong> Data were collected on data from two groups (A and B). There were 3 measurements taken on Group A and two measurements in Group B.</li>
</ol>
<pre><code>\vspace{-2mm}





::: {.cell}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; Group &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Measurement 1 &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Measurement 2 &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Measurement 3 &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; A &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 1 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 15 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 5 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; B &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 7 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 3 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; NA &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::





If the data are (repeatedly) randomly allocated across the two conditions, provide the following: (1) the values which are assigned to group A, (2) the values which are assigned to group B, and (3) the difference in averages $(\bar{x}_A - \bar{x}_B)$ for each of the following:

a.  When the randomized difference in averages is as large as possible.

b.  When the randomized difference in averages is as small as possible (a big in magnitude negative number).

c.  When the randomized difference in averages is as close to zero as possible.

d.  When the observed values are randomly assigned to the two groups, to which of the previous parts would you expect the difference in means to fall closest?
    Explain your reasoning.</code></pre>
<!--- MOM ims-20-08
ims_exercise: "20.8"
title: "Possible randomized means"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.8 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Fixed data: Group A = {1, 15, 5}, Group B = {7, 3}
// All 5 values: 1, 3, 5, 7, 15. Assign 3 to Group A, 2 to Group B.
// (a) Largest diff: A={15, 7, 5}, B={1, 3} → diff = 9-2 = 7
// (b) Smallest diff: A={1, 3, 5}, B={7, 15} → diff = 3-11 = -8
// (c) Closest to 0: A={1, 7, 5}, B={3, 15} → diff = 13/3 - 9 = 4.333-9=-4.667;
//     or A={1, 15, 3}, B={5, 7} → diff = 19/3 - 6 = 0.333
//     Best: A = {1, 15, 3}, B = {5, 7} → x̄_A = 6.333, x̄_B = 6, diff = 0.333

$max_diff = round((15+7+5)/3 - (1+3)/2, 2)
$min_diff = round((1+3+5)/3 - (7+15)/2, 2)
$zero_diff = round((1+15+3)/3 - (5+7)/2, 2)

$abstolerance = 0.01

$choices_d = array(
  "Closest to (c), zero — random allocation tends to produce similar group means.",
  "Closest to (a), the maximum difference.",
  "Closest to (b), the minimum difference.",
  "We cannot determine this without running the randomization."
)

// === Question Text ===
// Data were collected on two groups: Group A has measurements {1, 15, 5} and Group B has measurements {7, 3}.
// <br><br>
// If the 5 data values are repeatedly randomly allocated (3 to Group A, 2 to Group B), give the difference x&#772;<sub>A</sub> &minus; x&#772;<sub>B</sub> for each scenario:
// <br><br>
// (a) When the randomized difference is as <b>large</b> as possible: $answerbox[0]
// <br>
// (b) When the randomized difference is as <b>small</b> (most negative) as possible: $answerbox[1]
// <br>
// (c) When the randomized difference is as <b>close to zero</b> as possible: $answerbox[2]
// <br>
// (d) If values are randomly assigned, which of the above would the difference typically be closest to? $answerbox[3]

// === Answer ===
$answer[0] = $max_diff
$answer[1] = $min_diff
$answer[2] = $zero_diff
$answer[3] = $choices_d[0]
$displayformat[3] = "radio"
$answerformat[3] = $choices_d

END MOM --->
<ol start="13" type="1">
<li><strong>Diamonds, mathematical test.</strong> We have data on two random samples of diamonds: one with diamonds that weigh 0.99 carats and one with diamonds that weigh 1 carat. Each sample has 23 diamonds. Sample statistics for the price per carat of diamonds in each sample are provided below. Conduct a hypothesis test using a mathematical model to evaluate if there is a difference between the prices per carat of diamonds that weigh 0.99 carats and diamonds that weigh 1 carat Make sure to state your hypotheses clearly, check relevant conditions, and interpret your results in context of the data. <span class="citation" data-cites="ggplot2">[@ggplot2]</span></li>
</ol>
<pre><code>\vspace{-3mm}





::: {.cell layout-ncol="2"}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; 0.99 carats &lt;/td&gt;
   &lt;td style="text-align:center;width: 3em; "&gt; $44.51 &lt;/td&gt;
   &lt;td style="text-align:center;width: 3em; "&gt; $13.32 &lt;/td&gt;
   &lt;td style="text-align:center;width: 2em; "&gt; 23 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; 1 carat &lt;/td&gt;
   &lt;td style="text-align:center;width: 3em; "&gt; $57.20 &lt;/td&gt;
   &lt;td style="text-align:center;width: 3em; "&gt; $18.19 &lt;/td&gt;
   &lt;td style="text-align:center;width: 2em; "&gt; 23 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::

::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-7-1.png){width=100%}
:::
:::</code></pre>
<!--- MOM ims-20-09
ims_exercise: "20.9"
title: "Diamonds, mathematical test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.9 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomized two-sample t-test (inspired by diamonds price-per-carat context)
$n1 = rand(20, 30)
$n2 = rand(20, 30)
$xbar1 = rrand(40, 55, 0.01)
$xbar2 = rrand(50, 70, 0.01) where ($xbar2 - $xbar1 > 3)
$s1 = rrand(8, 18, 0.01)
$s2 = rrand(8, 18, 0.01)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$decision = ($pval < 0.05) ? "Reject H<sub>0</sub>" : "Fail to reject H<sub>0</sub>"

$abstolerance = 0.01
$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "df = "
$readerlabel[0] = "standard error"
$readerlabel[1] = "t statistic"
$readerlabel[2] = "degrees of freedom"

// === Question Text ===
// Two independent random samples of a product are collected. Sample statistics:
// <br><br>
// <table border="1" cellpadding="5"><tr><th></th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Group 1</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Group 2</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Conduct a two-tailed hypothesis test for the difference in population means (H<sub>0</sub>: &mu;<sub>1</sub> = &mu;<sub>2</sub>, H<sub>A</sub>: &mu;<sub>1</sub> &ne; &mu;<sub>2</sub>).
// Use the conservative degrees of freedom: df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error of the difference: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) Degrees of freedom: $answerbox[2]
// <br>
// (d) P-value (two-tailed): $answerbox[3]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $df
$answer[3] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0
$abstolerance[3] = 0.005

END MOM --->
<ol start="14" type="1">
<li><strong>A/B testing.</strong> A/B testing is a user experience research methodology where two variants of a page are shown to users at random. A company wants to evaluate whether users will spend more time, on average, on Page A or Page B using an A/B test. Two user experience designers at the company, Lucie and Müge, are tasked with conducting the analysis of the data collected. They agree on how the null hypothesis should be set: on average, users spend the same amount of time on Page A and Page B. Lucie believes that Page B will provide a better experience for users and hence wants to use a one-tailed test, Müge believes that a two-tailed test would be a better choice. Which designer do you agree with, and why?</li>
</ol>
<!--- MOM ims-20-10
ims_exercise: "20.10"
title: "A/B testing"
type: multiple_choice
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.10 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Conceptual: one-tailed vs. two-tailed test choice

$choices = array(
  "M&uuml;ge (two-tailed), because without prior evidence that one page is better, a two-tailed test allows detection of a difference in either direction.",
  "Lucie (one-tailed), because she has a specific expectation about which page is better.",
  "It does not matter; both approaches will give the same p-value.",
  "Neither; an A/B test should not use hypothesis testing at all."
)

// === Question Text ===
// A company wants to evaluate whether users spend more time on Page A or Page B using an A/B test. Two designers agree on H<sub>0</sub>: users spend the same average time on both pages. Lucie wants a one-tailed test (she believes Page B is better), while M&uuml;ge wants a two-tailed test.
// <br><br>
// Which designer do you agree with, and why?

// === Answer ===
$answer = $choices[0]
$displayformat = "radio"

END MOM --->
<ol start="15" type="1">
<li><strong>Mindfulness intervention for nurses.</strong> In order to address extremely challenging and stressful situations for intensive care unit nurses, researchers ran a mindfulness-based intervention (MBI) study on 60 nurses working in three hospitals in El-Beheira, Egypt. The participants were randomly allocated to one of the two groups: the treatment group (MBI) received 8 MBI sessions and the control group received no intervention. The nurses’ emotional exhaustion was measured using 9 items from a questionnaire of the Maslach Burnout Inventory-Human Services Survey for Medical Personnel; the questions are recorded on a Likert scale where 0 indicated “Never” and 6 indicates “Every day”. Nurses in the treatment group had an emotional exhaustion score of 15.47, with a standard deviation of 4.44, and nurses in the control group had an emotional exhaustion score of 32.43, with a standard deviation of 8.87. Do these data provide convincing evidence that the emotional exhaustion decrease is different for the patients in the treatment group compared to the control group? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Othman:2023">[@Othman:2023]</span></li>
</ol>
<!--- MOM ims-20-14
ims_exercise: "20.14"
title: "Mindfulness intervention for nurses"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.14 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize summary stats (inspired by mindfulness intervention context)
// Treatment group: lower emotional exhaustion; Control group: higher
$n1 = rand(25, 35)
$n2 = rand(25, 35)
$xbar1 = rrand(12, 20, 0.01)
$s1 = rrand(3, 6, 0.01)
$xbar2 = rrand(28, 38, 0.01)
$s2 = rrand(6, 12, 0.01)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$alpha_val = 0.05
$decision = ($pval < $alpha_val) ? "Reject H<sub>0</sub>" : "Fail to reject H<sub>0</sub>"

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "p-value = "

// === Question Text ===
// Researchers ran a mindfulness-based intervention (MBI) study. Participants were randomly allocated to treatment (MBI) or control (no intervention). Emotional exhaustion was measured on a scale.
// <br><br>
// <table border="1" cellpadding="5"><tr><th></th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Treatment (MBI)</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Control</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Do these data provide convincing evidence that emotional exhaustion differs between the two groups? Use &alpha; = $alpha_val. Use df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error of the difference: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) P-value (two-tailed): $answerbox[2]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0.001

END MOM --->
<ol start="16" type="1">
<li><strong>Chicken diet: horsebean vs.&nbsp;linseed.</strong> Chicken farming is a multi-billion dollar industry, and any methods that increase the growth rate of young chicks can reduce consumer costs while increasing company profits, possibly by millions of dollars. An experiment was conducted to measure and compare the effectiveness of various feed supplements on the growth rate of chickens. Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. In this exercise we consider chicks that were fed horsebean and linseed. Below are some summary statistics from this dataset along with box plots showing the distribution of weights by feed type.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="citation" data-cites="data:chickwts">[@data:chickwts]</span></li>
</ol>
<pre><code>::: {.cell layout-ncol="3"}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Horsebean &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Linseed &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Mean &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 160.2 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 218.8 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; SD &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 38.6 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 52.2 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; n &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 10.0 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 12.0 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::

::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-8-1.png){width=100%}
:::

::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-8-2.png){width=100%}
:::
:::





a.  Describe the distributions of weights of chickens that were fed horsebean and linseed.

b.  Do these data provide strong evidence that the average weights of chickens that were fed linseed and horsebean are different?
    Use a 5% discernibility level.

c.  What type of error might we have committed?
    Explain.

d.  Would your conclusion change if we used $\alpha = 0.01$?</code></pre>
<!--- MOM ims-20-15
ims_exercise: "20.15"
title: "Chicken diet: horsebean vs. linseed"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.15 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Fixed data from chickwts dataset: horsebean vs linseed
// Horsebean: n=10, mean=160.20, sd=38.63
// Linseed: n=12, mean=218.75, sd=52.24
$n1 = 12
$n2 = 10
$xbar1 = 218.75
$s1 = 52.24
$xbar2 = 160.20
$s2 = 38.63

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * (1 - $pval_left), 4)

$choices_error = array(
  "Type I error, because we rejected H<sub>0</sub>.",
  "Type II error, because we rejected H<sub>0</sub>.",
  "Type I error, because we failed to reject H<sub>0</sub>.",
  "Type II error, because we failed to reject H<sub>0</sub>."
)

$choices_alpha01 = array(
  "Yes, since p-value > 0.01, we would fail to reject H<sub>0</sub> at &alpha; = 0.01.",
  "No, the conclusion would be the same regardless of &alpha;.",
  "Yes, the evidence would be even stronger at &alpha; = 0.01.",
  "No, because the test statistic does not change."
)

$ansprompt[0] = "t = "
$ansprompt[1] = "p-value = "

// === Question Text ===
// Chicken weights by feed type (from the chickwts dataset):
// <br><br>
// <table border="1" cellpadding="5"><tr><th></th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Linseed</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Horsebean</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// (a) Test whether there is a difference in average weights (two-tailed, &alpha; = 0.05). Use df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br>Test statistic t: $answerbox[0]
// <br>P-value: $answerbox[1]
// <br><br>
// (b) What type of error might we have committed? $answerbox[2]
// <br><br>
// (c) Would your conclusion change if we used &alpha; = 0.01? $answerbox[3]

// === Answer ===
$answer[0] = $tstat
$answer[1] = $pval
$answer[2] = $choices_error[0]
$answer[3] = $choices_alpha01[0]
$abstolerance[0] = 0.01
$abstolerance[1] = 0.005
$displayformat[2] = "radio"
$displayformat[3] = "radio"
$answerformat[2] = $choices_error
$answerformat[3] = $choices_alpha01

END MOM --->
<ol start="17" type="1">
<li><strong>Fuel efficiency in the city.</strong> Each year the US Environmental Protection Agency (EPA) releases fuel economy data on cars manufactured in that year. Below are summary statistics on fuel efficiency (in miles/gallon) from random samples of cars with manual and automatic transmissions manufactured in 2021. Do these data provide strong evidence of a difference between the average fuel efficiency of cars with manual and automatic transmissions in terms of their average city mileage?<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <span class="citation" data-cites="data:epa2021">[@data:epa2021]</span></li>
</ol>
<pre><code>::: {.cell layout-ncol="2"}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; CITY &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Automatic &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 17.4 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 3.44 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 25 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Manual &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 22.7 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 4.58 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 25 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::

::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-9-1.png){width=100%}
:::
:::</code></pre>
<!--- MOM ims-20-16
ims_exercise: "20.16"
title: "Fuel efficiency in the city"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.16 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomized two-sample t-test (fuel efficiency context)
$n1 = rand(20, 35)
$n2 = rand(20, 35)
$xbar1 = rrand(18, 28, 0.01)
$xbar2 = rrand(22, 35, 0.01) where (abs($xbar2 - $xbar1) > 2)
$s1 = rrand(4, 10, 0.01)
$s2 = rrand(4, 10, 0.01)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "p-value = "

// === Question Text ===
// Random samples of cars with two different transmission types were tested for city fuel efficiency (miles per gallon):
// <br><br>
// <table border="1" cellpadding="5"><tr><th>City MPG</th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Automatic</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Manual</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Do these data provide strong evidence of a difference between the average city fuel efficiency of cars with automatic and manual transmissions? Use a two-tailed test with df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) P-value (two-tailed): $answerbox[2]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0.005

END MOM --->
<ol start="18" type="1">
<li><strong>Chicken diet: casein vs.&nbsp;soybean.</strong> Casein is a common weight gain supplement for humans. Does it have an effect on chickens? An experiment was conducted to measure and compare the effectiveness of various feed supplements on the growth rate of chickens. Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. In this exercise we consider chicks that were fed casein and soybean. Assume that the conditions for conducting inference using mathematical models are met, and using the data provided below, test the hypothesis that the average weight of chickens that were fed casein is different than the average weight of chickens that were fed soybean. If your hypothesis test yields a statistically discernible result, discuss whether the higher average weight of chickens can be attributed to the casein diet. <span class="citation" data-cites="data:chickwts">[@data:chickwts]</span></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; Feed type &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; casein &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 323.58 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 64.43 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 12 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; soybean &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 246.43 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 54.13 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 14 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::</code></pre>
<!--- MOM ims-20-17
ims_exercise: "20.17"
title: "Chicken diet: casein vs. soybean"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.17 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Fixed data from chickwts: casein vs soybean
// Casein: n=12, mean=323.58, sd=64.43
// Soybean: n=14, mean=246.43, sd=54.13
$n1 = 12
$n2 = 14
$xbar1 = 323.58
$s1 = 64.43
$xbar2 = 246.43
$s2 = 54.13

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * (1 - $pval_left), 4)

$choices_causal = array(
  "Yes, because this was a randomized experiment, the difference can be attributed to the diet.",
  "No, because observational studies cannot establish causation.",
  "No, because we do not know the population sizes.",
  "Yes, because the p-value is small."
)

$ansprompt[0] = "t = "
$ansprompt[1] = "p-value = "

// === Question Text ===
// Chicken weights by feed type (from the chickwts dataset):
// <br><br>
// <table border="1" cellpadding="5"><tr><th>Feed type</th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Casein</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Soybean</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Test whether the average weight differs between chickens fed casein and soybean (two-tailed, &alpha; = 0.05). Use df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Test statistic t: $answerbox[0]
// <br>
// (b) P-value (two-tailed): $answerbox[1]
// <br><br>
// (c) If the result is statistically discernible, can the higher weight be attributed to the casein diet? $answerbox[2]

// === Answer ===
$answer[0] = $tstat
$answer[1] = $pval
$answer[2] = $choices_causal[0]
$abstolerance[0] = 0.01
$abstolerance[1] = 0.005
$displayformat[2] = "radio"
$answerformat[2] = $choices_causal

END MOM --->
<ol start="19" type="1">
<li><strong>Fuel efficiency on the highway.</strong> Each year the US Environmental Protection Agency (EPA) releases fuel economy data on cars manufactured in that year. Below are summary statistics on fuel efficiency (in miles/gallon) from random samples of cars with manual and automatic transmissions manufactured in 2021. Do these data provide strong evidence of a difference between the average fuel efficiency of cars with manual and automatic transmissions in terms of their average highway mileage? <span class="citation" data-cites="data:epa2021">[@data:epa2021]</span></li>
</ol>
<pre><code>::: {.cell layout-ncol="2"}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; HIGHWAY &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:center;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Automatic &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 23.7 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 3.90 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 25 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Manual &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 30.9 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 5.13 &lt;/td&gt;
   &lt;td style="text-align:center;"&gt; 25 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::

::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-11-1.png){width=100%}
:::
:::</code></pre>
<!--- MOM ims-20-18
ims_exercise: "20.18"
title: "Fuel efficiency on the highway"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.18 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomized two-sample t-test (highway fuel efficiency context)
$n1 = rand(20, 35)
$n2 = rand(20, 35)
$xbar1 = rrand(25, 38, 0.01)
$xbar2 = rrand(30, 45, 0.01) where (abs($xbar2 - $xbar1) > 2)
$s1 = rrand(4, 12, 0.01)
$s2 = rrand(4, 12, 0.01)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "p-value = "

// === Question Text ===
// Random samples of cars with two transmission types were tested for highway fuel efficiency (miles per gallon):
// <br><br>
// <table border="1" cellpadding="5"><tr><th>Highway MPG</th><th>Mean</th><th>SD</th><th>n</th></tr>
// <tr><td>Automatic</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Manual</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Do these data provide strong evidence of a difference in average highway fuel efficiency? Use a two-tailed test with df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) P-value (two-tailed): $answerbox[2]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0.005

END MOM --->
<ol start="20" type="1">
<li><strong>Gaming, distracted eating, and intake.</strong> A group of researchers who are interested in the possible effects of distracting stimuli during eating, such as an increase or decrease in the amount of food consumption, monitored food intake for a group of 44 patients who were randomized into two equal groups. The treatment group ate lunch while playing solitaire, and the control group ate lunch without any added distractions. Patients in the treatment group ate 52.1 grams of biscuits, with a standard deviation of 45.1 grams, and patients in the control group ate 27.1 grams of biscuits, with a standard deviation of 26.4 grams. Do these data provide convincing evidence that the average food intake (measured in amount of biscuits consumed) is different for the patients in the treatment group compared to the control group? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Oldham:2011">[@Oldham:2011]</span></li>
</ol>
<!--- MOM ims-20-19
ims_exercise: "20.19"
title: "Gaming, distracted eating, and intake"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.19 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize summary stats (distracted eating context)
// Treatment: ate while distracted; Control: no distraction
$n1 = rand(18, 28)
$n2 = $n1
$xbar1 = rrand(40, 65, 0.1)
$s1 = rrand(30, 55, 0.1)
$xbar2 = rrand(18, 35, 0.1) where ($xbar1 - $xbar2 > 10)
$s2 = rrand(18, 35, 0.1)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * (1 - $pval_left), 4)

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "p-value = "

// === Question Text ===
// Researchers studied the effects of distracting stimuli during eating. A total of {2*$n1} patients were randomized into two equal groups. The treatment group ate lunch while playing solitaire; the control group ate without distraction. Food intake (grams of biscuits) was measured.
// <br><br>
// <table border="1" cellpadding="5"><tr><th></th><th>Mean (grams)</th><th>SD</th><th>n</th></tr>
// <tr><td>Treatment (distracted)</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Control</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Do these data provide convincing evidence that average food intake differs between treatment and control? Use a two-tailed test with df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error of the difference: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) P-value (two-tailed): $answerbox[2]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0.005

END MOM --->
<ol start="21" type="1">
<li><strong>Gaming, distracted eating, and recall.</strong> A group of researchers who are interested in the possible effects of distracting stimuli during eating, such as an increase or decrease in the amount of food consumption, monitored food intake for a group of 44 patients who were randomized into two equal groups. The 22 patients in the treatment group who ate their lunch while playing solitaire were asked to do a serial-order recall of the food lunch items they ate. The average number of items recalled by the patients in this group was 4. 9, with a standard deviation of 1.8. The average number of items recalled by the patients in the control group (no distraction) was 6.1, with a standard deviation of 1.8. Do these data provide strong evidence that the average numbers of food items recalled by the patients in the treatment and control groups are different? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Oldham:2011">[@Oldham:2011]</span></li>
</ol>
<!--- MOM ims-20-20
ims_exercise: "20.20"
title: "Gaming, distracted eating, and recall"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 20.20 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize summary stats (distracted eating recall context)
// Treatment: distracted eating → fewer items recalled; Control: more recalled
$n1 = rand(18, 28)
$n2 = $n1
$xbar1 = rrand(3.5, 5.5, 0.1)
$s1 = rrand(1.2, 2.5, 0.1)
$xbar2 = rrand(5.5, 7.5, 0.1) where ($xbar2 - $xbar1 > 0.5)
$s2 = rrand(1.2, 2.5, 0.1)

$diff = round($xbar1 - $xbar2, 2)
$se = round(sqrt($s1*$s1/$n1 + $s2*$s2/$n2), 4)
$tstat = round($diff / $se, 2)
$df = min($n1 - 1, $n2 - 1)

// Two-tailed p-value
$pval_left = tcdf($tstat, $df)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "p-value = "

// === Question Text ===
// Researchers studied the effects of distracting stimuli during eating. A total of {2*$n1} patients were randomized into two equal groups. The treatment group ate while playing solitaire; the control group ate without distraction. After lunch, each patient was asked to do a serial-order recall of the food items eaten.
// <br><br>
// <table border="1" cellpadding="5"><tr><th></th><th>Mean items recalled</th><th>SD</th><th>n</th></tr>
// <tr><td>Treatment (distracted)</td><td>$xbar1</td><td>$s1</td><td>$n1</td></tr>
// <tr><td>Control</td><td>$xbar2</td><td>$s2</td><td>$n2</td></tr></table>
// <br>
// Do these data provide strong evidence that the average number of food items recalled differs between treatment and control? Use a two-tailed test with df = min(n<sub>1</sub>&minus;1, n<sub>2</sub>&minus;1).
// <br><br>
// (a) Standard error of the difference: $answerbox[0]
// <br>
// (b) Test statistic t: $answerbox[1]
// <br>
// (c) P-value (two-tailed): $answerbox[2]

// === Answer ===
$answer[0] = $se
$answer[1] = $tstat
$answer[2] = $pval
$abstolerance[0] = 0.01
$abstolerance[1] = 0.01
$abstolerance[2] = 0.005

END MOM --->
<ol start="22" type="1">
<li><strong>High School and Beyond, randomization test.</strong> The National Center of Education Statistics conducted a survey of high school seniors, collecting test data on reading, writing, and several other subjects. Here we examine a simple random sample of 200 students from this survey.</li>
</ol>
<pre><code>Side-by-side box plots of reading and writing scores as well as a histogram of the differences in scores are shown below.
Also provided below is a histogram of randomized averages of paired differences of scores (read - write), with the observed difference ($\bar{x}_{read-write} = -0.545$) marked with a red vertical line.
The randomization distribution was produced by doing the following 1000 times: for each student, the two scores were randomly assigned to either read or write, and the average was taken across all students in the sample.[^_21-ex-inference-paired-means-1]





::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-12-1.png){width=100%}
:::
:::





a.  Is there a clear difference in the average reading and writing scores?

b.  Are the reading and writing scores of each student independent of each other?

c.  Create hypotheses appropriate for the following research question: is there an evident difference in the average scores of students in the reading and writing exam?

d.  Is the average of the observed difference in scores $(\bar{x}_{read-write} = -0.545)$ consistent with the distribution of randomized average differences?
    Explain.

e.  Do these data provide convincing evidence of a difference between the average scores on the two exams?
    Estimate the p-value from the randomization test, and conclude the hypothesis test using words like "score on reading test" and "score on writing test."</code></pre>
<!--- MOM ims-21-06
ims_exercise: "21.6"
title: "High School and Beyond, randomization test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.6 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// This exercise uses a specific dataset (hsb2) with fixed values.
// Randomization: vary the context slightly by providing summary stats.
// Original: n=200, xbar_diff = -0.545, s_diff = 8.887

$n = 200
$dbar = -0.545
$sd = 8.887
$choices_yn = array("Yes", "No")
$choices_hyp = array("H0: mu_diff = 0, HA: mu_diff != 0", "H0: mu_diff = 0, HA: mu_diff < 0", "H0: mu_diff = 0, HA: mu_diff > 0", "H0: mu_diff != 0, HA: mu_diff = 0")

// === Question Text ===
// A random sample of $n students took both a reading and writing exam. The mean of the paired differences (read - write) is `bar x` = $dbar with a standard deviation of s = $sd.
// <br><br>
// (a) Are the reading and writing scores of each student independent of each other?
// $answerbox[0]
// <br><br>
// (b) Which hypotheses are appropriate for testing whether there is a difference in the average reading and writing scores?
// $answerbox[1]

// === Answer ===
$answer[0] = "No"
$displayformat[0] = "radio"
$answer[1] = "H0: mu_diff = 0, HA: mu_diff != 0"
$displayformat[1] = "radio"

END MOM --->
<ol start="23" type="1">
<li><strong>Global warming, randomization test.</strong> Let’s consider a limited set of climate data, examining temperature differences in 1950 vs 2022. We sampled 26 locations in the US from the National Oceanic and Atmospheric Administration’s (NOAA) historical data, where the data was available for both years of interest. <span class="citation" data-cites="webpage:noaa19482018">[@webpage:noaa19482018]</span> The data are not a random sample, but they are selected to be a representative sample across the land area of the lower 48 United States. Using the hottest day of the year as a measure can make the results susceptible to outliers. Instead, to get a sense for how hot a year was, we calculate the 90<span class="math inline">\(^{th}\)</span> percentile; that is, we find the maximum temperature on the day that was hotter than 90% of the days that year. We want to know: is the 90<span class="math inline">\(^{th}\)</span> percentile high temperature greater in 2022 or in 1950? The difference in 90<span class="math inline">\(^{th}\)</span> percentile high temperature (high temperature for 2022 - high temperature for 1950) was calculated for each of the 26 locations. The average of the 26 differences was 2.52<span class="math inline">\(^\circ\)</span>F with a standard deviation of 2.95<span class="math inline">\(^\circ\)</span>F. We are interested in determining whether these data provide strong evidence that the 90<span class="math inline">\(^{th}\)</span> percentile high temperature is higher in 2022 than in 1950.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></li>
</ol>
<pre><code>:::: {layout="[-0.05, 0.45, -0.05, 0.45]"}
:::{#question}
a.  Create hypotheses appropriate for the following research question: is there an evident difference in the 90$^{th}$ percentile high temp across the two years (1950 and 2022)?\

b.  Is the average of the observed difference in scores $(\bar{x}_{2022-1950} = 2.53$\^\circ$F)$ consistent with the distribution of randomized average differences?
    Explain.
:::
:::{#plot}




::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-13-1.png){width=98%}
:::
:::




:::
::::

c.  Do these data provide convincing evidence of a difference between the 90$^{th}$ percentile high temperature?
    Estimate the p-value from the randomization test, and conclude the hypothesis test using words like "90$^{th}$ percentile high temperature in 1950" and "90$^{th}$ percentile high temperature in 2022."</code></pre>
<!--- MOM ims-21-07
ims_exercise: "21.7"
title: "Global warming, randomization test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.7 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// This exercise uses a specific dataset (us_temperature) with fixed values.
// n=26, dbar=2.53, sd=2.95
// Requires figure interpretation for parts (b) and (c); provide conceptual parts.

$choices_hyp = array("H0: mu_diff = 0, HA: mu_diff != 0", "H0: mu_diff = 0, HA: mu_diff > 0", "H0: mu_diff = 0, HA: mu_diff < 0", "H0: mu_diff != 0, HA: mu_diff = 0")

// === Question Text ===
// Researchers compared the 90th percentile high temperature in 1950 versus 2022 at 26 sampled locations. The difference (2022 - 1950) was calculated for each location. The average of the 26 differences was 2.53&deg;F with a standard deviation of 2.95&deg;F.
// <br><br>
// (a) Which hypotheses are appropriate for testing whether there is a difference in the 90th percentile high temperature across the two years?
// $answerbox[0]

// === Answer ===
$answer[0] = "H0: mu_diff = 0, HA: mu_diff != 0"
$displayformat[0] = "radio"

END MOM --->
<ol start="24" type="1">
<li><strong>High School and Beyond, mathematical test.</strong> We considered the differences between the reading and writing scores of a random sample of 200 students who took the High School and Beyond Survey.</li>
</ol>
<pre><code>a.  Create hypotheses appropriate for the following research question: is there an evident difference in the average scores of students in the reading and writing exam?

b.  Check the conditions required to complete this test.

c.  The average observed difference in scores is $\bar{x}_{read-write} = -0.545$, and the standard deviation of the differences is $s_{read-write} = 8.887$ points.
    Do these data provide convincing evidence of a difference between the average scores on the two exams?

d.  What type of error might we have made?
    Explain what the error means in the context of the application.

e.  Based on the results of this hypothesis test, would you expect a confidence interval for the average difference between the reading and writing scores to include 0?
    Explain your reasoning.</code></pre>
<!--- MOM ims-21-10
ims_exercise: "21.10"
title: "High School and Beyond, mathematical test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.10 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Paired t-test: randomize dbar, sd, n
// t = dbar / (sd / sqrt(n)), df = n-1, two-tailed
$n = rand(80, 250)
$dbar = rrand(-4.0, 4.0, 0.01) where (abs($dbar) > 0.3)
$sd = rrand(6.0, 14.0, 0.01)
$df = $n - 1
$se = round($sd / sqrt($n), 4)
$tstat = round($dbar / $se, 2)
$pval_left = tcdf($tstat, $df, 4)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$alpha_val = 0.05
$decision = ($pval < $alpha_val) ? "Reject H0" : "Fail to reject H0"
$errortype = ($pval < $alpha_val) ? "Type I" : "Type II"

$abstolerance = 0.01

// === Question Text ===
// The paired differences (test 1 - test 2) for a random sample of $n students have mean `bar x`<sub>diff</sub> = $dbar and standard deviation s<sub>diff</sub> = $sd.
// <br><br>
// Test whether there is a difference in the average scores on the two exams using &alpha; = $alpha_val.
// <br><br>
// H<sub>0</sub>: &mu;<sub>diff</sub> = 0 &nbsp;&nbsp; H<sub>A</sub>: &mu;<sub>diff</sub> &ne; 0
// <br><br>
// (a) Degrees of freedom: $answerbox[0]
// <br><br>
// (b) Standard error: $answerbox[1]
// <br><br>
// (c) Test statistic t: $answerbox[2]
// <br><br>
// (d) p-value (two-tailed): $answerbox[3]

$ansprompt[0] = "df = "
$ansprompt[1] = "SE = "
$ansprompt[2] = "t = "
$ansprompt[3] = "p-value = "

// === Answer ===
$answer[0] = $df
$abstolerance[0] = 0
$answer[1] = round($se, 4)
$abstolerance[1] = 0.01
$answer[2] = $tstat
$abstolerance[2] = 0.02
$answer[3] = $pval
$abstolerance[3] = 0.005

END MOM --->
<ol start="25" type="1">
<li><strong>Global warming, mathematical test.</strong> We considered the change in the 90<span class="math inline">\(^{th}\)</span> percentile high temperature in 1950 versus 2022 at 26 sampled locations from the NOAA database. <span class="citation" data-cites="webpage:noaa19482018">[@webpage:noaa19482018]</span> The mean and standard deviation of the reported differences are 2.53<span class="math inline">\(^\circ\)</span>F and 2.95<span class="math inline">\(^\circ\)</span>F.</li>
</ol>
<pre><code>:::: {layout="[-0.05, 0.45, -0.05, 0.45]"}
:::{#question}
a.  Is there a relationship between the observations collected in 1950 and 2022?
    Or are the observations in the two groups independent?
    Explain your reasoning.\

b.  Write hypotheses for this research in symbols and in words.\

c.  Check the conditions required to complete this test.    
:::
:::{#plot}




::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-14-1.png){width=98%}
:::
:::




:::
::::

\vspace{-2mm}

d.  Calculate the test statistic and find the p-value.

e.  Use $\alpha = 0.05$ to evaluate the test, and interpret your conclusion in context.

f.  What type of error might we have made?
    Explain in context what the error means.

g.  Based on the results of this hypothesis test, would you expect a confidence interval for the average difference between the 90$^{th}$ percentile high temperture from 1950 to 2022 to include 0?
    Explain your reasoning.</code></pre>
<!--- MOM ims-21-11
ims_exercise: "21.11"
title: "Global warming, mathematical test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.11 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Paired t-test: randomize a scenario similar to global warming
// Original: n=26, dbar=2.53, sd=2.95, two-tailed
$n = rand(20, 40)
$dbar = rrand(1.0, 5.0, 0.01)
$sd = rrand(2.0, 5.0, 0.01)
$df = $n - 1
$se = round($sd / sqrt($n), 3)
$tstat = round($dbar / $se, 2)

// Two-tailed p-value
$pval_right = round(1 - tcdf($tstat, $df, 6), 4)
$pval = round(2 * $pval_right, 4)

$alpha_val = 0.05
$decision = ($pval < $alpha_val) ? "Reject H0" : "Fail to reject H0"
$choices_dec = array("Reject H0", "Fail to reject H0")

$abstolerance = 0.01

// === Question Text ===
// Researchers compared paired measurements at $n locations. The mean difference is `bar x`<sub>diff</sub> = $dbar and the standard deviation is s<sub>diff</sub> = $sd.
// <br><br>
// Test whether there is a difference using a paired t-test at &alpha; = $alpha_val.
// <br><br>
// H<sub>0</sub>: &mu;<sub>diff</sub> = 0 &nbsp;&nbsp; H<sub>A</sub>: &mu;<sub>diff</sub> &ne; 0
// <br><br>
// (a) Standard error: $answerbox[0]
// <br><br>
// (b) Test statistic t: $answerbox[1]
// <br><br>
// (c) Degrees of freedom: $answerbox[2]
// <br><br>
// (d) p-value (two-tailed): $answerbox[3]
// <br><br>
// (e) Decision at &alpha; = $alpha_val: $answerbox[4]

$ansprompt[0] = "SE = "
$ansprompt[1] = "t = "
$ansprompt[2] = "df = "
$ansprompt[3] = "p-value = "

// === Answer ===
$answer[0] = $se
$abstolerance[0] = 0.01
$answer[1] = $tstat
$abstolerance[1] = 0.02
$answer[2] = $df
$abstolerance[2] = 0
$answer[3] = $pval
$abstolerance[3] = 0.005
$answer[4] = $decision
$displayformat[4] = "radio"

END MOM --->
<ol start="26" type="1">
<li><strong>Possible paired randomized differences.</strong> Two observations were collected on each of five people. Which of the following could be a possible randomization of the paired differences given in the table below? If the set of values could not be a randomized set of differences, indicate why not.</li>
</ol>
<pre><code>:::: {layout="[-0.05, 0.35, -0.02, 0.58]"}
:::{#question}
a.  -2, 1, 1, 11, -2

b.  -4, 11, -2, 0, 1

c.  -2, 2, -11, 11, -2, 2, 0, 1, -1

d.  0, -1, 2, -4, 11

e.  4, -11, 2, 0, -1
:::
:::{#table}




::: {.cell}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
&lt;tr&gt;
&lt;th style="empty-cells: hide;border-bottom:hidden;" colspan="1"&gt;&lt;/th&gt;
&lt;th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="5"&gt;&lt;div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; "&gt;People&lt;/div&gt;&lt;/th&gt;
&lt;/tr&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; 1 &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; 2 &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; 3 &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; 4 &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; 5 &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Observation 1 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 3 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 14 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 4 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 5 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 10 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Observation 2 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 7 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 3 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 6 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 5 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 9 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;"&gt; Difference &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; -4 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 11 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; -2 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 0 &lt;/td&gt;
   &lt;td style="text-align:right;"&gt; 1 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::




:::
::::</code></pre>
<!--- MOM ims-21-14
ims_exercise: "21.14"
title: "Possible paired randomized differences"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.14 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// The original differences are: -4, 11, -2, 0, 1
// Valid randomizations must have the same absolute values with possibly flipped signs, and 5 values.
// (a) -2, 1, 1, 11, -2 — Not valid (has different absolute values: two 1s and two 2s)
// (b) -4, 11, -2, 0, 1 — Valid (same values, same signs — original data)
// (c) -2, 2, -11, 11, -2, 2, 0, 1, -1 — Not valid (9 values instead of 5)
// (d) 0, -1, 2, -4, 11 — Valid (same absolute values, some signs flipped, reordered)
// (e) 4, -11, 2, 0, -1 — Valid (all signs flipped from original)

$choices_valid = array("Could be a valid randomization", "Could NOT be a valid randomization")

// === Question Text ===
// Two observations were collected on each of five people. The original paired differences are: -4, 11, -2, 0, 1.
// <br><br>
// In a paired randomization test, we randomly assign each difference a positive or negative sign (equivalent to randomly swapping which observation is subtracted from which).
// <br><br>
// Which of the following could be a possible randomization of the paired differences?
// <br><br>
// (a) -2, 1, 1, 11, -2
// $answerbox[0]
// <br><br>
// (b) -4, 11, -2, 0, 1
// $answerbox[1]
// <br><br>
// (c) -2, 2, -11, 11, -2, 2, 0, 1, -1
// $answerbox[2]
// <br><br>
// (d) 0, -1, 2, -4, 11
// $answerbox[3]
// <br><br>
// (e) 4, -11, 2, 0, -1
// $answerbox[4]

// === Answer ===
$displayformat = "radio"
$answer[0] = "Could NOT be a valid randomization"
$answer[1] = "Could be a valid randomization"
$answer[2] = "Could NOT be a valid randomization"
$answer[3] = "Could be a valid randomization"
$answer[4] = "Could be a valid randomization"

END MOM --->
<ol start="27" type="1">
<li><strong>Study environment.</strong> In order to test the effects of listening to music while studying versus studying in silence, students agree to be randomized to two treatments (i.e., study with music or study in silence). There are two exams during the semester, so the researchers can either randomize the students to have one exam with music and one with silence (randomly selecting which exam corresponds to which study environment) or the researchers can randomize the students to one study habit for both exams.</li>
</ol>
<pre><code>The researchers are interested in estimating the true population difference of exam score for those who listen to music while studying as compared to those who study in silence.

a.  Describe the experiment which is consistent with a paired designed experiment.
    How is the treatment assigned, and how are the data collected such that the observations are paired?

b.  Describe the experiment which is consistent with an indpenedent samples experiment.
    How is the treatment assigned, and how are the data collected such that the observations are independent?</code></pre>
<!--- MOM ims-21-15
ims_exercise: "21.15"
title: "Study environment"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.15 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
$choices_design = array(
  "Each student studies under both conditions (one for each exam), and we compare individual student differences.",
  "Each student studies under one condition for both exams, and we compare group averages.",
  "Students choose which condition to use for each exam.",
  "Each student studies under both conditions for the same exam."
)

// === Question Text ===
// Students agree to be randomized to two study treatments: study with music or study in silence. There are two exams during the semester.
// <br><br>
// (a) Which design is consistent with a <b>paired</b> experiment?
// $answerbox[0]
// <br><br>
// (b) Which design is consistent with an <b>independent samples</b> experiment?
// $answerbox[1]

// === Answer ===
$displayformat = "radio"
$answer[0] = "Each student studies under both conditions (one for each exam), and we compare individual student differences."
$answer[1] = "Each student studies under one condition for both exams, and we compare group averages."

END MOM --->
<ol start="28" type="1">
<li><strong>Friday the 13th, traffic.</strong> In the early 1990’s, researchers in the UK collected data on traffic flow on Friday the 13th with the goal of addressing issues of how superstitions regarding Friday the 13th affect human behavior and and whether Friday the 13th is an unlucky day. The histograms below show the distributions of numbers of cars passing by a specific intersection on Friday the 6th and Friday the 13th for many such date pairs. Also provided are some sample statistics, where the difference is the number of cars on the 6th minus the number of cars on the 13th.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <span class="citation" data-cites="Scanlon:1993">[@Scanlon:1993]</span></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-16-1.png){width=100%}
:::

::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; n &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; SD &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; sixth &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 10 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 128,385 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 7,259 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; thirteenth &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 10 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 126,550 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 7,664 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; diff &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 10 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 1,836 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 1,176 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::





a.  Are there any underlying structures in these data that should be considered in an analysis?
    Explain.

b.  What are the hypotheses for evaluating whether the number of people out on Friday the 6$^{\text{th}}$ is different than the number out on Friday the 13$^{\text{th}}$?

c.  Check conditions to carry out the hypothesis test from part (b) using mathematical models.

d.  Calculate the test statistic and the p-value.

e.  What is the conclusion of the hypothesis test?

f.  Interpret the p-value in this context.

g.  What type of error might have been made in the conclusion of your test?
    Explain.</code></pre>
<!--- MOM ims-21-16
ims_exercise: "21.16"
title: "Friday the 13th, traffic"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.16 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Paired t-test with summary stats. Randomize a scenario inspired by Friday the 13th.
// Original: n=10, diff_mean=1836, diff_sd=1176 (approximate from friday dataset)
// Randomize more broadly
$n = rand(6, 15)
$dbar = rrand(-5.0, 5.0, 0.01) where (abs($dbar) > 1.0)
$sd = rrand(2.0, 6.0, 0.01)
$df = $n - 1
$se = round($sd / sqrt($n), 4)
$tstat = round($dbar / $se, 2)

// Two-tailed
$pval_left = tcdf($tstat, $df, 6)
$pval = round(2 * min($pval_left, 1 - $pval_left), 4)

$alpha_val = 0.05
$decision = ($pval < $alpha_val) ? "Reject H0" : "Fail to reject H0"
$errortype = ($pval < $alpha_val) ? "Type I error (rejecting H0 when it is actually true)" : "Type II error (failing to reject H0 when it is actually false)"
$choices_dec = array("Reject H0", "Fail to reject H0")
$choices_err = array("Type I error (rejecting H0 when it is actually true)", "Type II error (failing to reject H0 when it is actually false)")

$abstolerance = 0.01

// === Question Text ===
// Researchers collected paired measurements on $n date pairs. The mean and standard deviation of the paired differences are `bar x`<sub>diff</sub> = $dbar and s<sub>diff</sub> = $sd.
// <br><br>
// Test whether there is a difference in the population means using a paired t-test at &alpha; = $alpha_val.
// <br><br>
// H<sub>0</sub>: &mu;<sub>diff</sub> = 0 &nbsp;&nbsp; H<sub>A</sub>: &mu;<sub>diff</sub> &ne; 0
// <br><br>
// (a) Degrees of freedom: $answerbox[0]
// <br><br>
// (b) Standard error: $answerbox[1]
// <br><br>
// (c) Test statistic t: $answerbox[2]
// <br><br>
// (d) p-value (two-tailed): $answerbox[3]
// <br><br>
// (e) Decision at &alpha; = $alpha_val: $answerbox[4]
// <br><br>
// (f) What type of error might have been made? $answerbox[5]

$ansprompt[0] = "df = "
$ansprompt[1] = "SE = "
$ansprompt[2] = "t = "
$ansprompt[3] = "p-value = "

// === Answer ===
$answer[0] = $df
$abstolerance[0] = 0
$answer[1] = round($se, 4)
$abstolerance[1] = 0.01
$answer[2] = $tstat
$abstolerance[2] = 0.02
$answer[3] = $pval
$abstolerance[3] = 0.005
$answer[4] = $decision
$displayformat[4] = "radio"
$answer[5] = $errortype
$displayformat[5] = "radio"

END MOM --->
<ol start="29" type="1">
<li><strong>Friday the 13th, accidents.</strong> In the early 1990’s, researchers in the UK collected data the number of traffic accident related emergency room (ER) admissions on Friday the 13th with the goal of addressing issues of how superstitions regarding Friday the 13th affect human behavior and and whether Friday the 13th is an unlucky day. The histograms below show the distributions of numbers of ER admissions at specific emergency rooms on Friday the 6th and Friday the 13th for many such date pairs. Also provided are some sample statistics, where the difference is the ER admissions on the 6th minus the ER admissions on the 13th.<span class="citation" data-cites="Scanlon:1993">[@Scanlon:1993]</span></li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch12-hypothesis-tests-means_files/figure-html/unnamed-chunk-17-1.png){width=100%}
:::

::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt;  &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; n &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; SD &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; sixth &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 6 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 8 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 3 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; thirteenth &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 6 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 11 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 4 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; "&gt; diff &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 6 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; -3 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 3 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::





a.  Conduct a hypothesis test using mathematical models to evaluate if there is a difference between the average numbers of traffic accident related emergency room admissions between Friday the 6$^{\text{th}}$ and Friday the 13$^{\text{th}}$.

b.  Calculate a 95% confidence interval using mathematical models for the difference between the average numbers of traffic accident related emergency room admissions between Friday the 6$^{\text{th}}$ and Friday the 13$^{\text{th}}$.

c.  The conclusion of the original study states, "Friday 13th is unlucky for some. The risk of hospital admission as a result of a transport accident may be increased by as much as 52%. Staying at home is recommended." Do you agree with this statement?
    Explain your reasoning.</code></pre>
<!--- MOM ims-21-17
ims_exercise: "21.17"
title: "Friday the 13th, accidents"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 21.17 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Paired t-test + CI. Randomize scenario inspired by Friday 13th accidents.
// Original: n=6, dbar=-3.33, sd=3.01 (approx)
$n = rand(5, 12)
$dbar = rrand(-6.0, -1.0, 0.01)
$sd = rrand(2.0, 5.0, 0.01)
$df = $n - 1
$se = round($sd / sqrt($n), 4)
$tstat = round($dbar / $se, 2)

// Two-tailed
$pval_left = tcdf($tstat, $df, 6)
$pval = round(2 * $pval_left, 4)

// 95% CI
$tstar95 = invtcdf(0.975, $df, 4)
$me95 = round($tstar95 * $se, 2)
$lower95 = round($dbar - $me95, 2)
$upper95 = round($dbar + $me95, 2)

$alpha_val = 0.05

$abstolerance = 0.05

// === Question Text ===
// Researchers collected paired data on $n date pairs. The mean and standard deviation of the paired differences (condition 1 - condition 2) are `bar x`<sub>diff</sub> = $dbar and s<sub>diff</sub> = $sd.
// <br><br>
// (a) Conduct a paired t-test at &alpha; = $alpha_val.
// <br>H<sub>0</sub>: &mu;<sub>diff</sub> = 0 &nbsp;&nbsp; H<sub>A</sub>: &mu;<sub>diff</sub> &ne; 0
// <br><br>
// Test statistic t: $answerbox[0]
// <br>Degrees of freedom: $answerbox[1]
// <br>p-value (two-tailed): $answerbox[2]
// <br><br>
// (b) Calculate a 95% confidence interval for the mean difference.
// <br><br>
// Lower bound: $answerbox[3]
// <br>Upper bound: $answerbox[4]

$ansprompt[0] = "t = "
$ansprompt[1] = "df = "
$ansprompt[2] = "p-value = "
$ansprompt[3] = "Lower = "
$ansprompt[4] = "Upper = "

// === Answer ===
$answer[0] = $tstat
$abstolerance[0] = 0.02
$answer[1] = $df
$abstolerance[1] = 0
$answer[2] = $pval
$abstolerance[2] = 0.005
$answer[3] = $lower95
$abstolerance[3] = 0.1
$answer[4] = $upper95
$abstolerance[4] = 0.1

END MOM --->


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The <a href="https://ggplot2.tidyverse.org/reference/diamonds.html"><code>diamonds</code></a> data used in this exercise can be found in the <a href="http://ggplot2.tidyverse.org/"><strong>ggplot2</strong></a> R package.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The <a href="http://openintrostat.github.io/openintro/reference/lizard_run.html"><code>lizard_run</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/chickwts.html"><code>chickwts</code></a> data used in this exercise can be found in the <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html"><strong>datasets</strong></a> R package.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The <a href="http://openintrostat.github.io/openintro/reference/epa2021.html"><code>epa2021</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The <a href="http://openintrostat.github.io/openintro/reference/us_temperature.html"><code>us_temperature</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The <a href="http://openintrostat.github.io/openintro/reference/friday.html"><code>friday</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch11-ci-for-means.html" class="pagination-link" aria-label="Confidence Intervals for Means">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch13-inference-proportions.html" class="pagination-link" aria-label="Inference for Proportions">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>