<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>17&nbsp; Analysis of Variance – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch17-multiple-comparisons.html" rel="next">
<link href="../chapters/ch15-chisq-independence.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8a91fbd6dc43518bbcbbe5f3fb33f285.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iv.html">Apply</a></li><li class="breadcrumb-item"><a href="../chapters/ch16-anova.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statbench-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatBench Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-mlb-batting" id="toc-sec-mlb-batting" class="nav-link active" data-scroll-target="#sec-mlb-batting"><span class="header-section-number">17.1</span> Case study: MLB batting</a>
  <ul class="collapse">
  <li><a href="#why-not-just-compare-the-most-different-groups" id="toc-why-not-just-compare-the-most-different-groups" class="nav-link" data-scroll-target="#why-not-just-compare-the-most-different-groups"><span class="header-section-number">17.1.1</span> Why not just compare the most different groups?</a></li>
  </ul></li>
  <li><a href="#sec-rand-anova" id="toc-sec-rand-anova" class="nav-link" data-scroll-target="#sec-rand-anova"><span class="header-section-number">17.2</span> Randomization test for comparing many means</a>
  <ul class="collapse">
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic"><span class="header-section-number">17.2.1</span> The F-statistic</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">17.2.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics" id="toc-observed-statistic-vs.-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics"><span class="header-section-number">17.2.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul></li>
  <li><a href="#sec-math-anova" id="toc-sec-math-anova" class="nav-link" data-scroll-target="#sec-math-anova"><span class="header-section-number">17.3</span> Mathematical model for ANOVA</a>
  <ul class="collapse">
  <li><a href="#variability-of-the-statistic-1" id="toc-variability-of-the-statistic-1" class="nav-link" data-scroll-target="#variability-of-the-statistic-1"><span class="header-section-number">17.3.1</span> Variability of the statistic</a></li>
  <li><a href="#the-p-value-from-the-f-distribution" id="toc-the-p-value-from-the-f-distribution" class="nav-link" data-scroll-target="#the-p-value-from-the-f-distribution"><span class="header-section-number">17.3.2</span> The p-value from the F-distribution</a></li>
  <li><a href="#reading-an-anova-table" id="toc-reading-an-anova-table" class="nav-link" data-scroll-target="#reading-an-anova-table"><span class="header-section-number">17.3.3</span> Reading an ANOVA table</a></li>
  </ul></li>
  <li><a href="#sec-anova-conditions" id="toc-sec-anova-conditions" class="nav-link" data-scroll-target="#sec-anova-conditions"><span class="header-section-number">17.4</span> Conditions for ANOVA</a></li>
  <li><a href="#sec-ch24-review" id="toc-sec-ch24-review" class="nav-link" data-scroll-target="#sec-ch24-review"><span class="header-section-number">17.5</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">17.5.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">17.5.2</span> Key terms</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">17.5.3</span> Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iv.html">Apply</a></li><li class="breadcrumb-item"><a href="../chapters/ch16-anova.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-warning no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Draft Chapter.</strong> This chapter is part of UWL’s STAT 145 curriculum and is under active development. Content is substantially complete but may undergo revisions. Feedback welcome.</p>
</div>
</div>
</div>
<div class="chapterintro">
<p>In earlier chapters, we developed methods to compare the mean of a numerical outcome across two groups. An important aspect of those analyses was to look at the difference in sample means as an estimate for the difference in population means. When comparing more than two groups, simple subtraction will not fully capture the variation across three or more groups. As with two groups, the research question focuses on whether group membership is independent of the numerical response variable. In this chapter, we focus on a new statistic that incorporates differences in means across more than two groups. Although the ideas are similar to the <span class="math inline">\(t\)</span>-test, they have earned their own name: <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance, or <strong>ANOVA</strong>.</p>
</div>
<p>Sometimes we want to compare means across many groups. We might initially think to do pairwise comparisons. For example, if there were three groups, we might compare the first mean with the second, then with the third, and finally compare the second and third means – a total of three comparisons. However, this strategy can be treacherous. If we have many groups and do many comparisons, it is likely that we will eventually find a difference just by chance, even if there is no difference in the populations. Instead, we should apply a holistic test to check whether there is evidence that at least one pair of groups is different, which is where ANOVA saves the day.</p>
<p>ANOVA uses a single hypothesis test to check whether the means across many groups are equal:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The mean outcome is the same across all groups: <span class="math inline">\(\mu_1 = \mu_2 = \cdots = \mu_k\)</span> where <span class="math inline">\(\mu_j\)</span> represents the mean of the outcome for observations in category <span class="math inline">\(j\)</span>.</li>
<li><span class="math inline">\(H_A\)</span>: At least one mean is different.</li>
</ul>
<p>Generally, we must check three conditions before performing ANOVA:</p>
<ul>
<li>The observations are independent within and between groups.</li>
<li>The responses within each group are nearly normal.</li>
<li>The variability across the groups is about equal.</li>
</ul>
<p>When these conditions are met, we may perform ANOVA to determine whether the data provide convincing evidence against the null hypothesis.</p>
<div class="workedexample">
<p>College departments commonly run multiple sections of the same introductory course. Consider a statistics department that runs three sections of an intro stats course. We might like to determine whether there are substantial differences in first exam scores across sections A, B, and C. Describe appropriate hypotheses.</p>
<hr>
<ul>
<li><span class="math inline">\(H_0\)</span>: The average score is identical in all sections, <span class="math inline">\(\mu_A = \mu_B = \mu_C\)</span>. The observed differences are due to chance.</li>
<li><span class="math inline">\(H_A\)</span>: The average score varies by class. We would reject the null hypothesis if there were larger differences among the class averages than what we might expect from chance alone.</li>
</ul>
</div>
<p>Strong evidence favoring the alternative hypothesis in ANOVA is described by unusually large differences among the group means. Assessing the variability of the group means relative to the variability among individual observations within each group is key to ANOVA’s success.</p>
<div class="workedexample">
<p>Consider the figure below showing two sets of three groups.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-variability-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two sets of side-by-side dot plots. The first set shows three groups where within-group variability swamps between-group differences. The second set shows three groups where between-group differences are clearly visible because within-group variability is small.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-variability-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-variability-comparison-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;17.1: Side-by-side dot plots for two sets of three groups. In the first set (Groups I, II, III), the within-group variability is large relative to the between-group differences. In the second set (Groups IV, V, VI), the within-group variability is small and the between-group differences are clearly visible."><img src="ch16-anova_files/figure-html/fig-variability-comparison-1.png" class="img-fluid figure-img" alt="Two sets of side-by-side dot plots. The first set shows three groups where within-group variability swamps between-group differences. The second set shows three groups where between-group differences are clearly visible because within-group variability is small." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-variability-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.1: Side-by-side dot plots for two sets of three groups. In the first set (Groups I, II, III), the within-group variability is large relative to the between-group differences. In the second set (Groups IV, V, VI), the within-group variability is small and the between-group differences are clearly visible.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Compare Groups I, II, and III. Can you visually determine if the group differences are real? Now compare Groups IV, V, and VI.</p>
<hr>
<p>Any real difference in Groups I, II, and III is difficult to discern because the data within each group are very volatile relative to differences in the group averages. On the other hand, Groups IV, V, and VI show noticeable differences because those differences are large <em>relative to the variability in individual observations within each group</em>.</p>
</div>
<section id="sec-mlb-batting" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="sec-mlb-batting"><span class="header-section-number">17.1</span> Case study: MLB batting</h2>
<p>We would like to determine whether there are real differences in batting performance among baseball players according to their position: outfielder (OF), infielder (IF), and catcher (C). We use data from 429 Major League Baseball players from the 2018 season who had at least 100 at-bats. The measure of batting performance is the on-base percentage (OBP), which roughly represents the fraction of the time a player successfully gets on base or hits a home run.</p>
<p>Summary statistics for each group:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Position</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OF</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">0.320</td>
<td style="text-align: center;">0.044</td>
</tr>
<tr class="even">
<td>IF</td>
<td style="text-align: center;">205</td>
<td style="text-align: center;">0.318</td>
<td style="text-align: center;">0.037</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">0.302</td>
<td style="text-align: center;">0.038</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlb-obp-boxplots" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Side-by-side box plots showing on-base percentage for outfielders, infielders, and catchers. Catchers have a slightly lower median, but the distributions overlap substantially.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlb-obp-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-mlb-obp-boxplots-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;17.2: Side-by-side box plots of on-base percentage for 429 players across three positions. The variability appears approximately constant across groups. Catchers seem to have a slightly lower on-base percentage."><img src="ch16-anova_files/figure-html/fig-mlb-obp-boxplots-1.png" class="img-fluid figure-img" alt="Side-by-side box plots showing on-base percentage for outfielders, infielders, and catchers. Catchers have a slightly lower median, but the distributions overlap substantially." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlb-obp-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.2: Side-by-side box plots of on-base percentage for 429 players across three positions. The variability appears approximately constant across groups. Catchers seem to have a slightly lower on-base percentage.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>The null hypothesis under consideration is <span class="math inline">\(\mu_{OF} = \mu_{IF} = \mu_{C}\)</span>. Write the null and alternative hypotheses in plain language.</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(H_0\)</span>: The average on-base percentage is equal across the three positions. <span class="math inline">\(H_A\)</span>: The average on-base percentage varies across some (or all) groups.
</details>
</div>
<div class="workedexample">
<p>What would be an appropriate point estimate of the on-base percentage by outfielders, <span class="math inline">\(\mu_{OF}\)</span>?</p>
<hr>
<p>A good estimate of the on-base percentage by outfielders would be the sample average of OBP for just those players who are outfielders: <span class="math inline">\(\bar{x}_{OF} = 0.320\)</span>.</p>
</div>
<section id="why-not-just-compare-the-most-different-groups" class="level3" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="why-not-just-compare-the-most-different-groups"><span class="header-section-number">17.1.1</span> Why not just compare the most different groups?</h3>
<div class="workedexample">
<p>The largest difference between sample means is between catchers and outfielders. Why might it be inappropriate to simply test whether <span class="math inline">\(\mu_C\)</span> and <span class="math inline">\(\mu_{OF}\)</span> are different?</p>
<hr>
<p>The primary issue is <strong>data snooping</strong> (also called <strong>data fishing</strong>). We are inspecting the data before picking the groups to compare. It is inappropriate to examine all data informally and only afterward decide which parts to formally test. Naturally, we would pick the groups with the largest differences, which inflates the Type I error rate.</p>
<p>For example, suppose we measure aptitude for students in 20 classrooms where all students are randomly assigned. With so many groups, we will probably observe a few that look different just by chance. If we select only those classes and perform a formal test, we will probably reach the wrong conclusion.</p>
</div>
</section>
</section>
<section id="sec-rand-anova" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="sec-rand-anova"><span class="header-section-number">17.2</span> Randomization test for comparing many means</h2>
<section id="the-f-statistic" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="the-f-statistic"><span class="header-section-number">17.2.1</span> The F-statistic</h3>
<p>The method of analysis of variance focuses on answering one question: is the variability in the sample means so large that it seems unlikely to be from chance alone? We quantify the between-group variability using the <strong>mean square between groups (MSG)</strong>, which has degrees of freedom <span class="math inline">\(df_G = k - 1\)</span> where <span class="math inline">\(k\)</span> is the number of groups. The MSG can be thought of as a scaled variance formula for the group means.</p>
<p>We also need a benchmark for how much variability to expect if the null hypothesis is true. For this, we compute the <strong>mean square error (MSE)</strong>, which measures the variability <em>within</em> groups and has degrees of freedom <span class="math inline">\(df_E = n - k\)</span>.</p>
<p>The <strong>F-statistic</strong> is the ratio of these two quantities:</p>
<p><span class="math display">\[F = \frac{MSG}{MSE}\]</span></p>
<p>The MSG represents between-group variability, and MSE measures within-group variability. When the null hypothesis is true, any differences among sample means are due to chance, and the MSG and MSE should be about equal, making <span class="math inline">\(F\)</span> close to 1. Large values of <span class="math inline">\(F\)</span> suggest that the between-group differences are larger than what we would expect from random variation.</p>
<div class="important">
<p><strong>The test statistic for three or more means is an F.</strong></p>
<p>The F statistic is a ratio of how the groups differ (MSG) as compared to how the observations within a group vary (MSE).</p>
<p><span class="math display">\[F = \frac{MSG}{MSE}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, <span class="math inline">\(F\)</span> has an F-distribution with <span class="math inline">\(df_1 = k - 1\)</span> and <span class="math inline">\(df_2 = n - k\)</span>.</p>
<p><strong>Conditions:</strong></p>
<ul>
<li>Independent observations, both within and across groups</li>
<li>Large samples and no extreme outliers</li>
</ul>
</div>
</section>
<section id="variability-of-the-statistic" class="level3" data-number="17.2.2">
<h3 data-number="17.2.2" class="anchored" data-anchor-id="variability-of-the-statistic"><span class="header-section-number">17.2.2</span> Variability of the statistic</h3>
<p>Suppose we have three exams (A, B, and C) and want to investigate whether they differ in difficulty:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_A = \mu_B = \mu_C\)</span>. The exams are equally difficult.</li>
<li><span class="math inline">\(H_A\)</span>: At least one exam is more (or less) difficult than the others.</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Exam</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">Min</th>
<th style="text-align: center;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">75.1</td>
<td style="text-align: center;">13.9</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">72.0</td>
<td style="text-align: center;">13.8</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">79.4</td>
<td style="text-align: center;">14.1</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exam-boxplots" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Side-by-side box plots of exam scores for exams A, B, and C. Exam C has a slightly higher median than A and B.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exam-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-exam-boxplots-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;17.3: Box plots of exam scores for three exam versions. Exam C appears to have a higher median, but the distributions overlap."><img src="ch16-anova_files/figure-html/fig-exam-boxplots-1.png" class="img-fluid figure-img" alt="Side-by-side box plots of exam scores for exams A, B, and C. Exam C has a slightly higher median than A and B." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exam-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.3: Box plots of exam scores for three exam versions. Exam C appears to have a higher median, but the distributions overlap.
</figcaption>
</figure>
</div>
</div>
</div>
<p>To perform a randomization test, we randomly reassign the exam labels to the observed scores. If the null hypothesis is true, the exam version should not matter, so any score could belong to any exam version.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-randomization-process" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four panels showing the randomization process: original data, shuffled exam labels, reconnected labels, and sorted groups with a new F-statistic.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-randomization-process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-randomization-process-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;17.4: The randomization process: exam version labels are randomly shuffled across the observed scores to generate a new assignment, from which a new F-statistic is computed."><img src="ch16-anova_files/figure-html/fig-randomization-process-1.png" class="img-fluid figure-img" alt="Four panels showing the randomization process: original data, shuffled exam labels, reconnected labels, and sorted groups with a new F-statistic." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-randomization-process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.4: The randomization process: exam version labels are randomly shuffled across the observed scores to generate a new assignment, from which a new F-statistic is computed.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By repeating this process 1,000 times, we build a null distribution of F-statistics.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null-f-dist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of 1,000 randomized F statistics. The distribution is right-skewed with most values below 2.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-f-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-null-f-dist-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;17.5: Histogram of F-statistics from 1,000 randomizations. The distribution is right-skewed with most values below 2. The tail extends to about 6."><img src="ch16-anova_files/figure-html/fig-null-f-dist-1.png" class="img-fluid figure-img" alt="Histogram of 1,000 randomized F statistics. The distribution is right-skewed with most values below 2." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-f-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.5: Histogram of F-statistics from 1,000 randomizations. The distribution is right-skewed with most values below 2. The tail extends to about 6.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="observed-statistic-vs.-null-statistics" class="level3" data-number="17.2.3">
<h3 data-number="17.2.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics"><span class="header-section-number">17.2.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null-f-observed" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of 1,000 randomized F statistics with the observed F = 3.48 shown as a red vertical line. The shaded area to the right represents the p-value of about 0.036.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-f-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-null-f-observed-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;17.6: Histogram of F-statistics from 1,000 randomizations with the observed F-statistic of 3.48 marked by a red line. The area to the right represents the p-value."><img src="ch16-anova_files/figure-html/fig-null-f-observed-1.png" class="img-fluid figure-img" alt="Histogram of 1,000 randomized F statistics with the observed F = 3.48 shown as a red vertical line. The shaded area to the right represents the p-value of about 0.036." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-f-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.6: Histogram of F-statistics from 1,000 randomizations with the observed F-statistic of 3.48 marked by a red line. The area to the right represents the p-value.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Using statistical software, we find that 3.6% of the randomized F statistics were at or above the observed test statistic of <span class="math inline">\(F = 3.48\)</span>. That is, the p-value is 0.036. Assuming a significance level of <span class="math inline">\(\alpha = 0.05\)</span>, the p-value is smaller than the significance level, which leads us to reject the null hypothesis. We conclude that the difficulty level is different for at least one of the exams.</p>
</section>
</section>
<section id="sec-math-anova" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="sec-math-anova"><span class="header-section-number">17.3</span> Mathematical model for ANOVA</h2>
<p>The randomization test on the F-statistic has a corresponding mathematical theory: the <strong>F-distribution</strong>.</p>
<section id="variability-of-the-statistic-1" class="level3" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="variability-of-the-statistic-1"><span class="header-section-number">17.3.1</span> Variability of the statistic</h3>
<p>The larger the observed variability in the sample means (MSG) relative to the within-group variability (MSE), the larger the F-statistic and the stronger the evidence against the null hypothesis. We use the upper tail of the F-distribution to compute the p-value.</p>
<div class="important">
<p><strong>The F-statistic and the F-test.</strong></p>
<p>Analysis of variance (ANOVA) uses a test statistic, the F-statistic, which represents a standardized ratio of variability in the sample means relative to the variability within the groups. If <span class="math inline">\(H_0\)</span> is true and the model conditions are satisfied, the F-statistic follows an F-distribution with parameters <span class="math inline">\(df_1 = k - 1\)</span> and <span class="math inline">\(df_2 = n - k\)</span>. The upper tail of the F-distribution is used to compute the p-value.</p>
</div>
<div class="guidedpractice">
<p>For the MLB data, <span class="math inline">\(MSG = 0.00803\)</span> and <span class="math inline">\(MSE = 0.00158\)</span>. Identify the degrees of freedom associated with MSG and MSE and verify the F-statistic is approximately 5.077.</p>
<details>
<summary>
Show answer
</summary>
There are <span class="math inline">\(k = 3\)</span> groups, so <span class="math inline">\(df_G = k - 1 = 2\)</span>. There are <span class="math inline">\(n = 429\)</span> total observations, so <span class="math inline">\(df_E = n - k = 426\)</span>. The F-statistic is <span class="math inline">\(F = \frac{MSG}{MSE} = \frac{0.00803}{0.00158} = 5.08 \approx 5.077\)</span>.
</details>
</div>
</section>
<section id="the-p-value-from-the-f-distribution" class="level3" data-number="17.3.2">
<h3 data-number="17.3.2" class="anchored" data-anchor-id="the-p-value-from-the-f-distribution"><span class="header-section-number">17.3.2</span> The p-value from the F-distribution</h3>
<p>A p-value can be computed from the F-statistic using an F-distribution with <span class="math inline">\(df_1 = df_G\)</span> and <span class="math inline">\(df_2 = df_E\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-f-pvalue" class="quarto-float quarto-figure quarto-figure-center anchored" alt="F-distribution curve with df1 = 2 and df2 = 426. The area to the right of F = 5.077 is shaded, indicating a small p-value.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-f-pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-f-pvalue-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;17.7: An F-distribution with df_1 = 2 and df_2 = 426. The area to the right of F = 5.077 is shaded, representing a p-value of approximately 0.0066."><img src="ch16-anova_files/figure-html/fig-f-pvalue-1.png" class="img-fluid figure-img" alt="F-distribution curve with df1 = 2 and df2 = 426. The area to the right of F = 5.077 is shaded, indicating a small p-value." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-f-pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.7: An F-distribution with <span class="math inline">\(df_1 = 2\)</span> and <span class="math inline">\(df_2 = 426\)</span>. The area to the right of <span class="math inline">\(F = 5.077\)</span> is shaded, representing a p-value of approximately 0.0066.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="workedexample">
<p>The p-value corresponding to <span class="math inline">\(F = 5.077\)</span> with <span class="math inline">\(df_1 = 2\)</span> and <span class="math inline">\(df_2 = 426\)</span> is approximately 0.0066. Does this provide strong evidence against the null hypothesis?</p>
<hr>
<p>The p-value is smaller than 0.05, indicating the evidence is strong enough to reject the null hypothesis at a significance level of 0.05. The data provide strong evidence that the average on-base percentage varies by player’s primary field position.</p>
</div>
<p>Note that the small p-value tells us there is a notable difference somewhere, but ANOVA does <strong>not</strong> tell us <em>which</em> group is different. Follow-up analyses (discussed in the next chapter on multiple comparisons) are needed.</p>
</section>
<section id="reading-an-anova-table" class="level3" data-number="17.3.3">
<h3 data-number="17.3.3" class="anchored" data-anchor-id="reading-an-anova-table"><span class="header-section-number">17.3.3</span> Reading an ANOVA table</h3>
<p>ANOVA results are commonly presented in a table. Here is the ANOVA table for the MLB data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum Sq</th>
<th style="text-align: center;">Mean Sq</th>
<th style="text-align: center;">F value</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>position</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.0161</td>
<td style="text-align: center;">0.00803</td>
<td style="text-align: center;">5.077</td>
<td style="text-align: center;">0.0066</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td style="text-align: center;">426</td>
<td style="text-align: center;">0.6740</td>
<td style="text-align: center;">0.00158</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>The key information is in the last two columns: the F-statistic (5.077) and the p-value (0.0066).</p>
<div class="definition">
<p><strong>Components of an ANOVA table.</strong></p>
<ul>
<li><strong>Sum of Squares Between Groups (SSG):</strong> Measures the total variability of the group means around the overall mean. <span class="math inline">\(SSG = \sum_{j=1}^{k} n_j (\bar{x}_j - \bar{x})^2\)</span>.</li>
<li><strong>Sum of Squared Errors (SSE):</strong> Measures the total variability of observations around their group means. <span class="math inline">\(SSE = \sum_{j=1}^{k} (n_j - 1) s_j^2\)</span>.</li>
<li><strong>Sum of Squares Total (SST):</strong> The total variability in all observations. <span class="math inline">\(SST = SSG + SSE\)</span>.</li>
<li><strong>Mean Square Between Groups (MSG):</strong> <span class="math inline">\(MSG = SSG / (k - 1)\)</span>.</li>
<li><strong>Mean Square Error (MSE):</strong> <span class="math inline">\(MSE = SSE / (n - k)\)</span>.</li>
<li><strong>F-statistic:</strong> <span class="math inline">\(F = MSG / MSE\)</span>.</li>
</ul>
</div>
</section>
</section>
<section id="sec-anova-conditions" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="sec-anova-conditions"><span class="header-section-number">17.4</span> Conditions for ANOVA</h2>
<p>There are three conditions to check before performing ANOVA:</p>
<ul>
<li><p><strong>Independence.</strong> If the data are a simple random sample, this condition is generally satisfied. For experiments, carefully consider whether the data may be independent (e.g., no pairing).</p></li>
<li><p><strong>Approximately normal.</strong> As with one- and two-sample testing for means, the normality assumption is especially important when sample sizes are small. With large sample sizes within each group, we look mainly for extreme outliers.</p></li>
<li><p><strong>Constant variance.</strong> The variability in the groups should be about equal. This can be checked by examining side-by-side box plots or comparing the standard deviations across groups. A common rule of thumb is that the ratio of the largest to smallest group standard deviation should be less than 2.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-obp-histograms" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three histograms of on-base percentage, one for each field position. All are reasonably bell-shaped and symmetric.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-obp-histograms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch16-anova_files/figure-html/fig-obp-histograms-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;17.8: Histograms of OBP for each field position, showing that the distributions are reasonably bell-shaped and symmetric."><img src="ch16-anova_files/figure-html/fig-obp-histograms-1.png" class="img-fluid figure-img" alt="Three histograms of on-base percentage, one for each field position. All are reasonably bell-shaped and symmetric." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-obp-histograms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.8: Histograms of OBP for each field position, showing that the distributions are reasonably bell-shaped and symmetric.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="important">
<p><strong>Diagnostics for an ANOVA analysis.</strong></p>
<p>Independence is always important. The normality condition matters most when group sizes are small (with large groups, look only for extreme outliers). The constant variance condition is especially important when group sizes differ.</p>
</div>
</section>
<section id="sec-ch24-review" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="sec-ch24-review"><span class="header-section-number">17.5</span> Chapter review</h2>
<section id="summary" class="level3" data-number="17.5.1">
<h3 data-number="17.5.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">17.5.1</span> Summary</h3>
<p>In this chapter, we introduced both the randomization test and the mathematical model for comparing means across two or more groups using ANOVA. The F-statistic measures the ratio of between-group variability (MSG) to within-group variability (MSE). When the null hypothesis is true and the conditions are satisfied, the F-statistic follows an F-distribution. A significant result tells us that at least one group mean differs from the others, but does not identify <em>which</em> groups differ. For that, we need multiple comparison procedures, which are covered in the next chapter.</p>
</section>
<section id="key-terms" class="level3" data-number="17.5.2">
<h3 data-number="17.5.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">17.5.2</span> Key terms</h3>
<ul>
<li>ANOVA (analysis of variance)</li>
<li>F-statistic</li>
<li>F-distribution</li>
<li>F-test</li>
<li>Mean square between groups (MSG)</li>
<li>Mean square error (MSE)</li>
<li>Sum of squares between groups (SSG)</li>
<li>Sum of squared errors (SSE)</li>
<li>Sum of squares total (SST)</li>
<li>Degrees of freedom (ANOVA)</li>
<li>Data snooping / data fishing</li>
</ul>
</section>
<section id="exercises" class="level3 exercises" data-number="17.5.3">
<h3 class="exercises anchored" data-number="17.5.3" data-anchor-id="exercises"><span class="header-section-number">17.5.3</span> Exercises</h3>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _22-ex-inference-many-means -->
<ol type="1">
<li><strong>Fill in the blank.</strong> When doing an ANOVA, you observe large differences in means between groups. Within the ANOVA framework, this would most likely be interpreted as evidence strongly favoring the _____________ hypothesis.</li>
</ol>
<!--- MOM ims-22-01
ims_exercise: "22.1"
title: "Fill in the blank"
type: short_answer
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.1 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// No randomization needed — single correct answer

// === Question Text ===
// When doing an ANOVA, you observe large differences in means between groups.
// Within the ANOVA framework, this would most likely be interpreted as evidence
// strongly favoring the _________ hypothesis.
//
// $answerbox

// === Answer ===
$answer = "alternative"
$showanswer = "The alternative hypothesis. Large differences in group means lead to a large F statistic, which provides evidence against the null hypothesis (that all means are equal) and in favor of the alternative."

END MOM --->
<ol start="2" type="1">
<li><strong>Which test?</strong> We would like to test if students who are in the social sciences, natural sciences, arts and humanities, and other fields spend the same amount of time, on average, studying for a course. What type of test should we use? Explain your reasoning.</li>
</ol>
<!--- MOM ims-22-02
ims_exercise: "22.2"
title: "Which test?"
type: short_answer
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.2 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Scenario pool: (context, number_of_groups, correct_test, explanation)
$scenarios = array(
  array("We would like to test if students who are in the social sciences, natural sciences, arts and humanities, and other fields spend the same amount of time, on average, studying for a course.", 4, "ANOVA", "There are more than two groups (four fields of study) being compared on a numerical variable (study time), so ANOVA is the appropriate test."),
  array("We would like to test if the average commute time differs among employees who drive, take public transit, bike, or walk to work.", 4, "ANOVA", "There are more than two groups (four commute methods) being compared on a numerical variable (commute time), so ANOVA is the appropriate test."),
  array("We would like to test if the average customer satisfaction rating differs among five different restaurant chains.", 5, "ANOVA", "There are more than two groups (five restaurant chains) being compared on a numerical variable (satisfaction rating), so ANOVA is the appropriate test."),
  array("We would like to test if the average amount of sleep per night differs among college freshmen, sophomores, juniors, and seniors.", 4, "ANOVA", "There are more than two groups (four class years) being compared on a numerical variable (hours of sleep), so ANOVA is the appropriate test.")
)
$idx = rand(0, count($scenarios)-1)
$context = $scenarios[$idx][0]
$k = $scenarios[$idx][1]
$correct = $scenarios[$idx][2]
$explain = $scenarios[$idx][3]

$choices = array("ANOVA (analysis of variance)", "Two-sample t-test", "Chi-square test", "Paired t-test")

// === Question Text ===
// $context
// <br><br>
// What type of test should we use?
//
// $answerbox
//
// [if showork]
// $explain
// [/if]

// === Answer ===
$answer = "ANOVA (analysis of variance)"
$displayformat = "radio"

END MOM --->
<ol start="3" type="1">
<li><p><strong>Cuckoo bird egg lengths, randomize once.</strong> Cuckoo birds lay their eggs in other birds’ nests, making them known as brood parasites. One question relates to whether the size of the cuckoo egg differs depending on the species of the host bird.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <span class="citation" data-cites="Latter:1902">[@Latter:1902]</span> Consider the following plots, one represents the original data, the second represents data where the host species has been randomly assigned to the egg length.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch16-anova_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="ch16-anova_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Consider the average length of the eggs for each species. Is the average length for the original data: more variable, less variable, or about the same as the randomized species? Describe what you see in the plots.</p></li>
<li><p>Consider the standard deviation of the lengths of the eggs within each species. Is the within species standard deviation of the length for the original data: bigger, smaller, or about the same as the randomized species?</p></li>
<li><p>Recall that the F statistic’s numerator measures how much the groups vary (MSG) with the denominator measuring how much the within species values vary (MSE), which of the plots above would have a larger F statistic, the original data or the randomized data? Explain.</p></li>
</ol></li>
</ol>
<!--- MOM ims-22-03
ims_exercise: "22.3"
title: "Cuckoo bird egg lengths, randomize once"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.3 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
// Conceptual questions about original vs. randomized data in ANOVA context.
// No randomization needed — fixed conceptual answers.

$choices_a = array("More variable", "Less variable", "About the same")
$answer_a = "More variable"

$choices_b = array("About the same", "Bigger", "Smaller")
$answer_b = "About the same"

$choices_c = array("The original data", "The randomized data", "They would be about the same")
$answer_c = "The original data"

// === Question Text ===
// Researchers studied cuckoo bird eggs laid in nests of different host bird species.
// One plot shows the original data (egg lengths by host species), and a second plot
// shows data where the host species labels have been randomly shuffled (assigned at random to the egg lengths).
//
// (a) Consider the average egg length for each species. Is the average length for the
// original data more variable, less variable, or about the same as for the randomized species?
// $answerbox[0]
//
// (b) Consider the standard deviation of egg lengths <em>within</em> each species.
// Is the within-species SD for the original data bigger, smaller, or about the same
// as for the randomized species?
// $answerbox[1]
//
// (c) The F statistic's numerator measures how much the group means vary (MSG) and the
// denominator measures how much values vary within groups (MSE). Which plot would have
// a larger F statistic?
// $answerbox[2]

// === Answer ===
$answer[0] = $answer_a
$displayformat[0] = "radio"
$answer[1] = $answer_b
$displayformat[1] = "radio"
$answer[2] = $answer_c
$displayformat[2] = "radio"

END MOM --->
<ol start="4" type="1">
<li><p><strong>Cuckoo bird egg lengths, randomization test.</strong> Cuckoo birds lay their eggs in other birds’ nests, making them known as brood parasites. One question relates to whether the size of the cuckoo egg differs depending on the species of the host bird.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <span class="citation" data-cites="Latter:1902">[@Latter:1902]</span> Using the randomization distribution of the F statistic (host species randomized to egg length), conduct a hypothesis test to evaluate if there is a difference, in the population, between the average egg lengths for different host bird species. Make sure to state your hypotheses clearly and interpret your results in context of the data.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch16-anova_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="ch16-anova_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div></li>
</ol>
<!--- MOM ims-22-04
ims_exercise: "22.4"
title: "Cuckoo bird egg lengths, randomization test"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.4 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate data for k groups (simulating egg lengths by host species)
$k = rand(4, 6)
$species_names = array("Meadow Pipit", "Tree Pipit", "Hedge Sparrow", "Robin", "Pied Wagtail", "Wren")

// Generate group sizes and data
$n1 = rand(10, 20)
$n2 = rand(10, 20)
$n3 = rand(10, 20)
$n4 = rand(10, 20)

$g1 = normrand(rrand(22.0, 23.5, 0.1), rrand(0.8, 1.2, 0.1), $n1, 1)
$g2 = normrand(rrand(21.5, 23.0, 0.1), rrand(0.8, 1.2, 0.1), $n2, 1)
$g3 = normrand(rrand(22.5, 24.0, 0.1), rrand(0.8, 1.2, 0.1), $n3, 1)
$g4 = normrand(rrand(21.0, 22.5, 0.1), rrand(0.8, 1.2, 0.1), $n4, 1)

$result = anova1way($g1, $g2, $g3, $g4)
$F_stat = round($result[0][3], 2)
$pval = round($result[0][4], 4)
$df_b = $result[0][1]
$df_w = $result[1][1]

$alpha_val = 0.05
$decision_choices = array("Reject the null hypothesis", "Fail to reject the null hypothesis")
$decision = ($pval < $alpha_val) ? "Reject the null hypothesis" : "Fail to reject the null hypothesis"

$abstolerance = 0.05

// === Question Text ===
// Researchers measured cuckoo bird egg lengths (in mm) found in nests of different host bird species.
// The data for four species are summarized below:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Host species</th><th>n</th><th>Mean</th><th>SD</th></tr>
// <tr><td>{$species_names[0]}</td><td>$n1</td><td>{round(mean($g1),1)}</td><td>{round(stdev($g1),1)}</td></tr>
// <tr><td>{$species_names[1]}</td><td>$n2</td><td>{round(mean($g2),1)}</td><td>{round(stdev($g2),1)}</td></tr>
// <tr><td>{$species_names[2]}</td><td>$n3</td><td>{round(mean($g3),1)}</td><td>{round(stdev($g3),1)}</td></tr>
// <tr><td>{$species_names[3]}</td><td>$n4</td><td>{round(mean($g4),1)}</td><td>{round(stdev($g4),1)}</td></tr>
// </table>
// <br>
// Conduct a hypothesis test to evaluate if there is a difference in average egg lengths
// across the host bird species. Use &alpha; = 0.05.
// <br><br>
// (a) Degrees of freedom (between groups): $answerbox[0]
// <br>
// (b) Degrees of freedom (within groups): $answerbox[1]
// <br>
// (c) F statistic: $answerbox[2]
// <br>
// (d) p-value: $answerbox[3]
// <br>
// (e) Decision at &alpha; = 0.05: $answerbox[4]

// === Answer ===
$answer[0] = $df_b
$answer[1] = $df_w
$answer[2] = $F_stat
$answer[3] = $pval
$answer[4] = $decision
$displayformat[4] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0
$abstolerance[2] = 0.1
$abstolerance[3] = 0.005

END MOM --->
<ol start="5" type="1">
<li><p><strong>Chicken diet and weight, many groups.</strong> An experiment was conducted to measure and compare the effectiveness of various feed supplements on the growth rate of chickens. Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. Sample statistics and a visualization of the observed data are shown below. <span class="citation" data-cites="data:chickwts">[@data:chickwts]</span></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="ch16-anova_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="ch16-anova_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid"></a></p>
</div>
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Feed type</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">casein</td>
<td style="text-align: center;">323.58</td>
<td style="text-align: center;">64.43</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">horsebean</td>
<td style="text-align: center;">160.20</td>
<td style="text-align: center;">38.63</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">linseed</td>
<td style="text-align: center;">218.75</td>
<td style="text-align: center;">52.24</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">meatmeal</td>
<td style="text-align: center;">276.91</td>
<td style="text-align: center;">64.90</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">soybean</td>
<td style="text-align: center;">246.43</td>
<td style="text-align: center;">54.13</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">sunflower</td>
<td style="text-align: center;">328.92</td>
<td style="text-align: center;">48.84</td>
<td style="text-align: center;">12</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Using the ANOVA output below, conduct a hypothesis test to determine if these data provide convincing evidence that the average weight of chicks varies across some (or all) groups. Make sure to check relevant conditions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">feed</td>
<td style="text-align: right; width: 5em;">5</td>
<td style="text-align: right; width: 5em;">231,129.2</td>
<td style="text-align: right; width: 5em;">46,225.832</td>
<td style="text-align: right; width: 5em;">15.3648</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">Residuals</td>
<td style="text-align: right; width: 5em;">65</td>
<td style="text-align: right; width: 5em;">195,556.0</td>
<td style="text-align: right; width: 5em;">3,008.554</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
</tbody>
</table>


</div>
</div></li>
</ol>
<!--- MOM ims-22-05
ims_exercise: "22.5"
title: "Chicken diet and weight, many groups"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.5 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate 4 groups of chick weights with different feed supplements
$n1 = rand(10, 14)
$n2 = rand(10, 14)
$n3 = rand(10, 14)
$n4 = rand(10, 14)

$g1 = normrand(rand(220, 280), rand(30, 50), $n1, 1)
$g2 = normrand(rand(260, 330), rand(30, 50), $n2, 1)
$g3 = normrand(rand(200, 260), rand(30, 50), $n3, 1)
$g4 = normrand(rand(300, 360), rand(30, 50), $n4, 1)

$result = anova1way($g1, $g2, $g3, $g4)
$SS_b = round($result[0][0], 2)
$df_b = $result[0][1]
$MS_b = round($result[0][2], 2)
$F_stat = round($result[0][3], 2)
$pval = round($result[0][4], 4)
$SS_w = round($result[1][0], 2)
$df_w = $result[1][1]
$MS_w = round($result[1][2], 2)
$SS_t = round($result[2][0], 2)
$df_t = $result[2][1]

$N = $n1 + $n2 + $n3 + $n4

$feeds = array("casein", "horsebean", "linseed", "sunflower")

$alpha_val = 0.05
$decision_choices = array("Reject H0 — the data provide convincing evidence that average weight varies across groups", "Fail to reject H0 — the data do not provide convincing evidence of a difference")
$decision = ($pval < $alpha_val) ? "Reject H0 — the data provide convincing evidence that average weight varies across groups" : "Fail to reject H0 — the data do not provide convincing evidence of a difference"

$abstolerance = 0.1

// === Question Text ===
// An experiment measured the effectiveness of various feed supplements on chicken growth.
// Newly hatched chicks were randomly allocated into four groups. Summary statistics:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Feed type</th><th>n</th><th>Mean</th><th>SD</th></tr>
// <tr><td>{$feeds[0]}</td><td>$n1</td><td>{round(mean($g1),1)}</td><td>{round(stdev($g1),1)}</td></tr>
// <tr><td>{$feeds[1]}</td><td>$n2</td><td>{round(mean($g2),1)}</td><td>{round(stdev($g2),1)}</td></tr>
// <tr><td>{$feeds[2]}</td><td>$n3</td><td>{round(mean($g3),1)}</td><td>{round(stdev($g3),1)}</td></tr>
// <tr><td>{$feeds[3]}</td><td>$n4</td><td>{round(mean($g4),1)}</td><td>{round(stdev($g4),1)}</td></tr>
// </table>
// <br>
// An ANOVA was conducted. Use the results to answer the following:
// <br><br>
// (a) Degrees of freedom (between): $answerbox[0]
// <br>
// (b) Degrees of freedom (within): $answerbox[1]
// <br>
// (c) F statistic: $answerbox[2]
// <br>
// (d) p-value: $answerbox[3]
// <br>
// (e) Conclusion at &alpha; = 0.05: $answerbox[4]

// === Answer ===
$answer[0] = $df_b
$answer[1] = $df_w
$answer[2] = $F_stat
$answer[3] = $pval
$answer[4] = $decision
$displayformat[4] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0
$abstolerance[2] = 0.15
$abstolerance[3] = 0.005

END MOM --->
<ol start="6" type="1">
<li><p><strong>Teaching descriptive statistics.</strong> A study compared five different methods for teaching descriptive statistics. The five methods were traditional lecture and discussion, programmed textbook instruction, programmed text with lectures, computer instruction, and computer instruction with lectures. 45 students were randomly assigned, 9 to each method. After completing the course, students took a 1-hour exam.</p>
<ol type="a">
<li><p>What are the hypotheses for evaluating if the average test scores are different for the different teaching methods?</p></li>
<li><p>What are the degrees of freedom associated with the <span class="math inline">\(F\)</span>-test for evaluating these hypotheses?</p></li>
<li><p>Suppose the p-value for this test is 0.0168. What is the conclusion?</p></li>
</ol></li>
</ol>
<!--- MOM ims-22-06
ims_exercise: "22.6"
title: "Teaching descriptive statistics"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.6 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize: k groups, n per group
$k = randfrom(3, 4, 5, 6)
$n_per = randfrom(8, 9, 10, 12, 15)
$N = $k * $n_per
$df_b = $k - 1
$df_w = $N - $k

// Generate a randomized p-value
$pval = rrand(0.001, 0.15, 0.001)
$alpha_val = 0.05

$decision_choices = array("Reject H0 — there is convincing evidence that average scores differ across methods", "Fail to reject H0 — there is not convincing evidence that average scores differ across methods")
$decision = ($pval < $alpha_val) ? "Reject H0 — there is convincing evidence that average scores differ across methods" : "Fail to reject H0 — there is not convincing evidence that average scores differ across methods"

// Context pool
$contexts = array(
  array("teaching methods", "teaching method"),
  array("study techniques", "study technique"),
  array("tutoring approaches", "tutoring approach"),
  array("training programs", "training program")
)
$cidx = rand(0, count($contexts)-1)
$context_plural = $contexts[$cidx][0]
$context_singular = $contexts[$cidx][1]

// === Question Text ===
// A study compared $k different {$context_plural} for an introductory course.
// $N students were randomly assigned, $n_per to each {$context_singular}.
// After completing the course, students took an exam.
// <br><br>
// (a) What are the degrees of freedom for the between-groups (numerator) of the F-test?
// $answerbox[0]
// <br>
// (b) What are the degrees of freedom for the within-groups (denominator) of the F-test?
// $answerbox[1]
// <br>
// (c) Suppose the p-value for this test is $pval. Using &alpha; = $alpha_val, what is the conclusion?
// $answerbox[2]

// === Answer ===
$answer[0] = $df_b
$answer[1] = $df_w
$answer[2] = $decision
$displayformat[2] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0

END MOM --->
<ol start="7" type="1">
<li><p><strong>Coffee, depression, and physical activity.</strong> Caffeine is the world’s most widely used stimulant, with approximately 80% consumed in the form of coffee. Participants in a study investigating the relationship between coffee consumption and exercise were asked to report the number of hours they spent per week on moderate (e.g., brisk walking) and vigorous (e.g., strenuous sports and jogging) exercise. Based on these data the researchers estimated the total hours of metabolic equivalent tasks (MET) per week, a value always greater than 0. The table below gives summary statistics of MET for women in this study based on the amount of coffee consumed. <span class="citation" data-cites="Lucas:2011">[@Lucas:2011]</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Caffeinated coffee consumption
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1 cup / week or fewer</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2-6 cups / week</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1 cups / day</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2-3 cups / day</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">4 cups / day or more</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3em;">Mean</td>
<td style="text-align: right; width: 6em;">18.7</td>
<td style="text-align: right; width: 6em;">19.6</td>
<td style="text-align: right; width: 6em;">19.3</td>
<td style="text-align: right; width: 6em;">18.9</td>
<td style="text-align: right; width: 6em;">17.5</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">SD</td>
<td style="text-align: right; width: 6em;">21.1</td>
<td style="text-align: right; width: 6em;">25.5</td>
<td style="text-align: right; width: 6em;">22.5</td>
<td style="text-align: right; width: 6em;">22.0</td>
<td style="text-align: right; width: 6em;">22.0</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3em;">n</td>
<td style="text-align: right; width: 6em;">12,215.0</td>
<td style="text-align: right; width: 6em;">6,617.0</td>
<td style="text-align: right; width: 6em;">17,234.0</td>
<td style="text-align: right; width: 6em;">12,290.0</td>
<td style="text-align: right; width: 6em;">2,383.0</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Write the hypotheses for evaluating if the average physical activity level varies among the different levels of coffee consumption.</p></li>
<li><p>Check conditions and describe any assumptions you must make to proceed with the test.</p></li>
<li><p>Below is the output associated with this test. What is the conclusion of the test?</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">cofee</td>
<td style="text-align: right; width: 5em;">4</td>
<td style="text-align: right; width: 5em;">10,508</td>
<td style="text-align: right; width: 5em;">2,627</td>
<td style="text-align: right; width: 5em;">5.2</td>
<td style="text-align: right; width: 5em;">3e-04</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">Residuals</td>
<td style="text-align: right; width: 5em;">50,734</td>
<td style="text-align: right; width: 5em;">25,564,819</td>
<td style="text-align: right; width: 5em;">504</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">Total</td>
<td style="text-align: right; width: 5em;">50,738</td>
<td style="text-align: right; width: 5em;">25,575,327</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
</tbody>
</table>


</div>
</div></li>
</ol>
<!--- MOM ims-22-07
ims_exercise: "22.7"
title: "Coffee, depression, and physical activity"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.7 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate a randomized ANOVA table with k groups and large sample sizes
$k = randfrom(4, 5, 6)
$df_b = $k - 1

// Large sample sizes (mimicking survey data)
$ns = array()
$N = 0
for ($i = 0; $i < $k; $i++) {
  $ns[$i] = rand(800, 5000)
  $N = $N + $ns[$i]
}
$df_w = $N - $k
$df_t = $N - 1

// Generate SS values to produce a reasonable F and p-value
$MS_w = rrand(300, 700, 1)
$SS_w = round($MS_w * $df_w, 0)
$F_stat = rrand(2.5, 8.0, 0.1)
$MS_b = round($F_stat * $MS_w, 0)
$SS_b = round($MS_b * $df_b, 0)
$SS_t = $SS_b + $SS_w

// Recompute exact F
$F_stat = round($MS_b / $MS_w, 1)
$pval = round(fcdf($F_stat, $df_b, $df_w), 4)

$alpha_val = 0.05
$decision_choices = array("Reject H0 — the data provide convincing evidence that the average differs across groups", "Fail to reject H0 — the data do not provide convincing evidence of a difference across groups")
$decision = ($pval < $alpha_val) ? "Reject H0 — the data provide convincing evidence that the average differs across groups" : "Fail to reject H0 — the data do not provide convincing evidence of a difference across groups"

$abstolerance = 0.05

// === Question Text ===
// A large study with $N total participants compared a numerical outcome across $k groups.
// The ANOVA table is shown below:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Source</th><th>df</th><th>Sum Sq</th><th>Mean Sq</th><th>F</th><th>p-value</th></tr>
// <tr><td>Group</td><td>$df_b</td><td>$SS_b</td><td>$MS_b</td><td>$F_stat</td><td>$pval</td></tr>
// <tr><td>Residuals</td><td>$df_w</td><td>$SS_w</td><td>$MS_w</td><td></td><td></td></tr>
// <tr><td>Total</td><td>$df_t</td><td>$SS_t</td><td></td><td></td><td></td></tr>
// </table>
// <br>
// (a) How many groups are being compared? $answerbox[0]
// <br>
// (b) What is the total sample size? $answerbox[1]
// <br>
// (c) What is the p-value? $answerbox[2]
// <br>
// (d) Using &alpha; = 0.05, what is the conclusion? $answerbox[3]

// === Answer ===
$answer[0] = $k
$answer[1] = $N
$answer[2] = $pval
$answer[3] = $decision
$displayformat[3] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0
$abstolerance[2] = 0.005

END MOM --->
<ol start="8" type="1">
<li><p><strong>Student performance across discussion sections.</strong> A professor who teaches a large introductory statistics class (197 students) with eight discussion sections would like to test if student performance differs by discussion section, where each discussion section has a different teaching assistant. The summary table below shows the average final exam score for each discussion section as well as the standard deviation of scores and the number of students in each section.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 6</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 7</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sec 8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 2em;">Mean</td>
<td style="text-align: right; width: 3em;">92.94</td>
<td style="text-align: right; width: 3em;">91.11</td>
<td style="text-align: right; width: 3em;">91.80</td>
<td style="text-align: right; width: 3em;">92.45</td>
<td style="text-align: right; width: 3em;">89.30</td>
<td style="text-align: right; width: 3em;">88.30</td>
<td style="text-align: right; width: 3em;">90.12</td>
<td style="text-align: right; width: 3em;">93.35</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 2em;">SD</td>
<td style="text-align: right; width: 3em;">4.21</td>
<td style="text-align: right; width: 3em;">5.58</td>
<td style="text-align: right; width: 3em;">3.43</td>
<td style="text-align: right; width: 3em;">5.92</td>
<td style="text-align: right; width: 3em;">9.32</td>
<td style="text-align: right; width: 3em;">7.27</td>
<td style="text-align: right; width: 3em;">6.93</td>
<td style="text-align: right; width: 3em;">4.57</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 2em;">n</td>
<td style="text-align: right; width: 3em;">33.00</td>
<td style="text-align: right; width: 3em;">19.00</td>
<td style="text-align: right; width: 3em;">10.00</td>
<td style="text-align: right; width: 3em;">29.00</td>
<td style="text-align: right; width: 3em;">33.00</td>
<td style="text-align: right; width: 3em;">10.00</td>
<td style="text-align: right; width: 3em;">32.00</td>
<td style="text-align: right; width: 3em;">31.00</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The ANOVA output below can be used to test for differences between the average scores from the different discussion sections.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">section</td>
<td style="text-align: right; width: 5em;">7</td>
<td style="text-align: right; width: 5em;">525.01</td>
<td style="text-align: right; width: 5em;">75.00</td>
<td style="text-align: right; width: 5em;">1.87</td>
<td style="text-align: right; width: 5em;">0.0767</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">Residuals</td>
<td style="text-align: right; width: 5em;">189</td>
<td style="text-align: right; width: 5em;">7,584.11</td>
<td style="text-align: right; width: 5em;">40.13</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">Total</td>
<td style="text-align: right; width: 5em;">196</td>
<td style="text-align: right; width: 5em;">8,109.12</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Conduct a hypothesis test to determine if these data provide convincing evidence that the average score varies across some (or all) groups. Check conditions and describe any assumptions you must make to proceed with the test.</p></li>
</ol>
<!--- MOM ims-22-08
ims_exercise: "22.8"
title: "Student performance across discussion sections"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.8 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize number of sections and students
$k = randfrom(5, 6, 7, 8)
$ns = array()
$N = 0
for ($i = 0; $i < $k; $i++) {
  $ns[$i] = rand(10, 35)
  $N = $N + $ns[$i]
}

$df_b = $k - 1
$df_w = $N - $k
$df_t = $N - 1

// Generate ANOVA table values — targeting a borderline or clear result
$MS_w = rrand(25, 55, 0.01)
$F_stat = rrand(1.0, 3.5, 0.01)
$MS_b = round($F_stat * $MS_w, 2)
$SS_b = round($MS_b * $df_b, 2)
$SS_w = round($MS_w * $df_w, 2)
$SS_t = round($SS_b + $SS_w, 2)

// Recompute exact values
$F_stat = round($MS_b / $MS_w, 2)
$pval = round(fcdf($F_stat, $df_b, $df_w), 4)

$alpha_val = 0.05
$decision_choices = array("Reject H0 — the data provide convincing evidence that average scores differ across sections", "Fail to reject H0 — the data do not provide convincing evidence that average scores differ across sections")
$decision = ($pval < $alpha_val) ? "Reject H0 — the data provide convincing evidence that average scores differ across sections" : "Fail to reject H0 — the data do not provide convincing evidence that average scores differ across sections"

// === Question Text ===
// A professor teaches a large introductory statistics class ($N students) with $k discussion sections,
// each led by a different teaching assistant. The professor wants to test if student performance
// differs by section. The ANOVA output is:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Source</th><th>df</th><th>Sum Sq</th><th>Mean Sq</th><th>F</th><th>p-value</th></tr>
// <tr><td>Section</td><td>$df_b</td><td>$SS_b</td><td>$MS_b</td><td>$F_stat</td><td>$pval</td></tr>
// <tr><td>Residuals</td><td>$df_w</td><td>$SS_w</td><td>$MS_w</td><td></td><td></td></tr>
// <tr><td>Total</td><td>$df_t</td><td>$SS_t</td><td></td><td></td><td></td></tr>
// </table>
// <br>
// (a) What are the degrees of freedom for the F-test (numerator, denominator)?
// <br>df (between): $answerbox[0] &nbsp; df (within): $answerbox[1]
// <br><br>
// (b) What is the F statistic? $answerbox[2]
// <br>
// (c) What is the p-value? $answerbox[3]
// <br>
// (d) Using &alpha; = 0.05, what is the conclusion? $answerbox[4]

// === Answer ===
$answer[0] = $df_b
$answer[1] = $df_w
$answer[2] = $F_stat
$answer[3] = $pval
$answer[4] = $decision
$displayformat[4] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0
$abstolerance[2] = 0.01
$abstolerance[3] = 0.005

END MOM --->
<ol start="9" type="1">
<li><p><strong>GPA and major.</strong> Undergraduate students in an introductory statistics course at Duke University conducted a survey about GPA and major. The density plots show the distributions of GPA among three groups of majors. ANOVA output is also provided.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch16-anova_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="ch16-anova_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">major</td>
<td style="text-align: right; width: 5em;">2</td>
<td style="text-align: right; width: 5em;">0.03</td>
<td style="text-align: right; width: 5em;">0.02</td>
<td style="text-align: right; width: 5em;">0.21</td>
<td style="text-align: right; width: 5em;">0.81</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">Residuals</td>
<td style="text-align: right; width: 5em;">195</td>
<td style="text-align: right; width: 5em;">15.77</td>
<td style="text-align: right; width: 5em;">0.08</td>
<td style="text-align: right; width: 5em;">NA</td>
<td style="text-align: right; width: 5em;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Write the hypotheses for testing for a difference between average GPA across majors.</p></li>
<li><p>What is the conclusion of the hypothesis test?</p></li>
<li><p>How many students answered the questions on the survey, i.e., what is the sample size?</p></li>
</ol></li>
</ol>
<!--- MOM ims-22-09
ims_exercise: "22.9"
title: "GPA and major"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.9 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Randomize: k groups and total sample size
$k = randfrom(3, 4, 5)
$N = rand(100, 300)
$df_b = $k - 1
$df_w = $N - $k
$df_t = $N - 1

// Generate ANOVA table — targeting non-significant results sometimes
$MS_w = rrand(0.05, 0.20, 0.01)
$F_stat = rrand(0.5, 4.0, 0.01)
$MS_b = round($F_stat * $MS_w, 4)
$SS_b = round($MS_b * $df_b, 2)
$SS_w = round($MS_w * $df_w, 2)
$SS_t = round($SS_b + $SS_w, 2)

$F_stat = round($MS_b / $MS_w, 2)
$pval = round(fcdf($F_stat, $df_b, $df_w), 4)

$alpha_val = 0.05
$conclusion_choices = array("Reject H0 — there is convincing evidence that average GPA differs across groups", "Fail to reject H0 — there is not convincing evidence that average GPA differs across groups")
$conclusion = ($pval < $alpha_val) ? "Reject H0 — there is convincing evidence that average GPA differs across groups" : "Fail to reject H0 — there is not convincing evidence that average GPA differs across groups"

// === Question Text ===
// Students in an introductory statistics course were surveyed about their GPA and major.
// An ANOVA was conducted to test for differences in average GPA across $k groups of majors.
// The ANOVA output is:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Source</th><th>df</th><th>Sum Sq</th><th>Mean Sq</th><th>F</th><th>p-value</th></tr>
// <tr><td>Major</td><td>$df_b</td><td>$SS_b</td><td>{round($MS_b,4)}</td><td>$F_stat</td><td>$pval</td></tr>
// <tr><td>Residuals</td><td>$df_w</td><td>$SS_w</td><td>{round($MS_w,4)}</td><td></td><td></td></tr>
// <tr><td>Total</td><td>$df_t</td><td>$SS_t</td><td></td><td></td><td></td></tr>
// </table>
// <br>
// (a) What is the conclusion of the hypothesis test at &alpha; = 0.05?
// $answerbox[0]
// <br><br>
// (b) How many students were surveyed (total sample size)?
// $answerbox[1]
// <br>
// (Hint: Use the total degrees of freedom.)

// === Answer ===
$answer[0] = $conclusion
$displayformat[0] = "radio"
$answer[1] = $N
$abstolerance[1] = 0

END MOM --->
<ol start="10" type="1">
<li><strong>Work hours and education.</strong> The General Social Survey collects data on demographics, education, and work, among many other characteristics of US residents. <span class="citation" data-cites="data:gss:2010">[@data:gss:2010]</span> Using ANOVA, we can consider educational attainment levels for all 1,172 respondents at once. Below are the distributions of hours worked by educational attainment and relevant summary statistics that will be helpful in carrying out this analysis.</li>
</ol>
<pre><code>::: {.cell layout-ncol="2"}
::: {.cell-output-display}
![](ch16-anova_files/figure-html/unnamed-chunk-11-1.png){width=100%}
:::

::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; Educational attainment &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; Mean &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; SD &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; n &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 7em; "&gt; Lt High School &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 38.7 &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 15.8 &lt;/td&gt;
   &lt;td style="text-align:right;width: 2em; "&gt; 121 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 7em; "&gt; High School &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 39.6 &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 15.0 &lt;/td&gt;
   &lt;td style="text-align:right;width: 2em; "&gt; 546 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 7em; "&gt; Junior College &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 41.4 &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 18.1 &lt;/td&gt;
   &lt;td style="text-align:right;width: 2em; "&gt; 97 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 7em; "&gt; Bachelor &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 42.5 &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 13.6 &lt;/td&gt;
   &lt;td style="text-align:right;width: 2em; "&gt; 253 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 7em; "&gt; Graduate &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 40.8 &lt;/td&gt;
   &lt;td style="text-align:right;width: 3em; "&gt; 15.5 &lt;/td&gt;
   &lt;td style="text-align:right;width: 2em; "&gt; 155 &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::





a.  Write hypotheses for evaluating whether the average number of hours worked varies across the five groups.

b.  Check conditions and describe any assumptions you must make to proceed with the test.

c.  Below is the output associated with this test.
    What is the conclusion of the test?





::: {.cell}
::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; term &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; df &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; sumsq &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; meansq &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; statistic &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; p.value &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; font-family: monospace;"&gt; degree &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 4 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 2,006.16 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 501.54 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 2.19 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 0.07 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 5em; font-family: monospace;"&gt; Residuals &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 1,167 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 267,382.16 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; 229.12 &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; NA &lt;/td&gt;
   &lt;td style="text-align:right;width: 5em; "&gt; NA &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::</code></pre>
<!--- MOM ims-22-10
ims_exercise: "22.10"
title: "Work hours and education"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.10 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate 5 groups of work hours by education level
$n1 = rand(50, 150)
$n2 = rand(150, 400)
$n3 = rand(40, 100)
$n4 = rand(100, 250)
$n5 = rand(50, 150)

$g1 = normrand(rrand(38, 42, 0.1), rrand(12, 16, 0.1), $n1, 1)
$g2 = normrand(rrand(39, 43, 0.1), rrand(12, 16, 0.1), $n2, 1)
$g3 = normrand(rrand(40, 44, 0.1), rrand(12, 15, 0.1), $n3, 1)
$g4 = normrand(rrand(42, 46, 0.1), rrand(11, 15, 0.1), $n4, 1)
$g5 = normrand(rrand(41, 45, 0.1), rrand(12, 15, 0.1), $n5, 1)

$result = anova1way($g1, $g2, $g3, $g4, $g5)
$df_b = $result[0][1]
$df_w = $result[1][1]
$F_stat = round($result[0][3], 2)
$pval = round($result[0][4], 4)
$MS_b = round($result[0][2], 2)
$MS_w = round($result[1][2], 2)
$SS_b = round($result[0][0], 2)
$SS_w = round($result[1][0], 2)
$SS_t = round($result[2][0], 2)
$df_t = $result[2][1]
$N = $n1 + $n2 + $n3 + $n4 + $n5

$alpha_val = 0.05
$conclusion_choices = array("Reject H0 — there is convincing evidence that average hours worked differ across education levels", "Fail to reject H0 — there is not convincing evidence that average hours worked differ across education levels")
$conclusion = ($pval < $alpha_val) ? "Reject H0 — there is convincing evidence that average hours worked differ across education levels" : "Fail to reject H0 — there is not convincing evidence that average hours worked differ across education levels"

$abstolerance = 0.1

// === Question Text ===
// A survey collected data on hours worked per week by educational attainment for $N respondents
// across 5 education levels. The ANOVA results are:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Source</th><th>df</th><th>Sum Sq</th><th>Mean Sq</th><th>F</th><th>p-value</th></tr>
// <tr><td>Education</td><td>$df_b</td><td>$SS_b</td><td>$MS_b</td><td>$F_stat</td><td>$pval</td></tr>
// <tr><td>Residuals</td><td>$df_w</td><td>$SS_w</td><td>$MS_w</td><td></td><td></td></tr>
// <tr><td>Total</td><td>$df_t</td><td>$SS_t</td><td></td><td></td><td></td></tr>
// </table>
// <br>
// (a) How many groups are being compared? $answerbox[0]
// <br>
// (b) What is the F statistic? $answerbox[1]
// <br>
// (c) What is the p-value? $answerbox[2]
// <br>
// (d) Using &alpha; = 0.05, what is the conclusion? $answerbox[3]

// === Answer ===
$answer[0] = 5
$answer[1] = $F_stat
$answer[2] = $pval
$answer[3] = $conclusion
$displayformat[3] = "radio"
$abstolerance[0] = 0
$abstolerance[1] = 0.15
$abstolerance[2] = 0.005

END MOM --->
<ol start="11" type="1">
<li><strong>Matching observed data with randomized F statistics.</strong> Consider the following two datasets. The response variable is the <code>score</code> and the explanatory variable is whether the individual is in one of four groups.</li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch16-anova_files/figure-html/unnamed-chunk-13-1.png){width=100%}
:::
:::





The randomizations (randomly assigning group to the score, calculating a randomization F statistic) were done 1000 times for each of Dataset A and B.
The red line on each plot indicates the observed F statistic for the original (unrandomized) data.

a.  Does the randomization distribution on the left correspond to Dataset A or B?
    Explain.

b.  Does the randomization distribution on the right correspond to Dataset A or B?
    Explain.</code></pre>
<!--- MOM ims-22-13
ims_exercise: "22.13"
title: "Matching observed data with randomized F statistics"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.13 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Two datasets with same group means but different within-group SDs
// Dataset A: small SD (clear group differences) → large F
// Dataset B: large SD (noisy, groups overlap) → small F
$k = 4
$n_per = rand(20, 30)

$mu1 = rand(8, 12)
$mu2 = rand(3, 7)
$mu3 = rand(6, 10)
$mu4 = rand(1, 4)

$sd_small = rand(3, 6)
$sd_large = $sd_small * rand(3, 5)

// Dataset A (small SD → large F, clear separation)
$gA1 = normrand($mu1, $sd_small, $n_per, 1)
$gA2 = normrand($mu2, $sd_small, $n_per, 1)
$gA3 = normrand($mu3, $sd_small, $n_per, 1)
$gA4 = normrand($mu4, $sd_small, $n_per, 1)
$resA = anova1way_f($gA1, $gA2, $gA3, $gA4)
$F_A = round($resA[0], 2)

// Dataset B (large SD → small F, groups overlap)
$gB1 = normrand($mu1, $sd_large, $n_per, 1)
$gB2 = normrand($mu2, $sd_large, $n_per, 1)
$gB3 = normrand($mu3, $sd_large, $n_per, 1)
$gB4 = normrand($mu4, $sd_large, $n_per, 1)
$resB = anova1way_f($gB1, $gB2, $gB3, $gB4)
$F_B = round($resB[0], 2)

$dataset_choices = array("Dataset A (smaller within-group variability)", "Dataset B (larger within-group variability)")

// === Question Text ===
// Two datasets each have 4 groups with $n_per observations per group.
// Both datasets have similar group means, but they differ in within-group variability:
// <br>
// <ul>
// <li><b>Dataset A</b> has within-group SD &asymp; $sd_small (groups are clearly separated). F = $F_A.</li>
// <li><b>Dataset B</b> has within-group SD &asymp; $sd_large (groups overlap substantially). F = $F_B.</li>
// </ul>
// For each dataset, 1,000 randomizations were performed (randomly reassigning group labels).
// <br><br>
// (a) One randomization distribution has the observed F statistic far in the right tail
// (strong evidence against H<sub>0</sub>). Which dataset does this correspond to?
// $answerbox[0]
// <br><br>
// (b) The other randomization distribution has the observed F statistic closer to the
// bulk of the distribution (weaker evidence). Which dataset does this correspond to?
// $answerbox[1]

// === Answer ===
$answer[0] = "Dataset A (smaller within-group variability)"
$displayformat[0] = "radio"
$answer[1] = "Dataset B (larger within-group variability)"
$displayformat[1] = "radio"

END MOM --->
<ol start="12" type="1">
<li><strong>Child care hours.</strong> The China Health and Nutrition Survey aims to examine the effects of the health, nutrition, and family planning policies and programs implemented by national and local governments. <span class="citation" data-cites="data:china">[@data:china]</span> It, for example, collects information on number of hours Chinese parents spend taking care of their children under age 6. The side-by-side box plots below show the distribution of this variable by educational attainment of the parent. Also provided below is the ANOVA output for comparing average hours across educational attainment categories.</li>
</ol>
<pre><code>::: {.cell}
::: {.cell-output-display}
![](ch16-anova_files/figure-html/unnamed-chunk-14-1.png){width=2100}
:::

::: {.cell-output-display}

`````{=html}
&lt;table class="table table-striped table-condensed" style="margin-left: auto; margin-right: auto;"&gt;
 &lt;thead&gt;
  &lt;tr&gt;
   &lt;th style="text-align:left;"&gt; term &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; df &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; sumsq &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; meansq &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; statistic &lt;/th&gt;
   &lt;th style="text-align:right;"&gt; p.value &lt;/th&gt;
  &lt;/tr&gt;
 &lt;/thead&gt;
&lt;tbody&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 4em; font-family: monospace;"&gt; edu &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 4 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 4,142.09 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 1,035.52 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 1.26 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 0.28 &lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
   &lt;td style="text-align:left;width: 4em; font-family: monospace;"&gt; Residuals &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 794 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 653,047.83 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; 822.48 &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; NA &lt;/td&gt;
   &lt;td style="text-align:right;width: 4em; "&gt; NA &lt;/td&gt;
  &lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

`````

:::
:::





a.  Write the hypotheses for testing for a difference between the average number of hours spent on child care across educational attainment levels.

b.  What is the conclusion of the hypothesis test?</code></pre>
<!--- MOM ims-22-14
ims_exercise: "22.14"
title: "Child care hours"
type: multipart
license: "CC BY-SA 3.0 — Based on IMS 2e Exercise 22.14 (Çetinkaya-Rundel & Hardin)"
status: draft
uwl_equiv: null

// === Common Control ===
loadlibrary("stats")

// Generate 5 groups (education levels) with randomized hours
$n1 = rand(30, 80)
$n2 = rand(60, 150)
$n3 = rand(40, 100)
$n4 = rand(30, 80)
$n5 = rand(20, 60)

$g1 = normrand(rrand(30, 45, 0.1), rrand(25, 40, 0.1), $n1, 1)
$g2 = normrand(rrand(35, 50, 0.1), rrand(25, 40, 0.1), $n2, 1)
$g3 = normrand(rrand(32, 48, 0.1), rrand(25, 40, 0.1), $n3, 1)
$g4 = normrand(rrand(28, 42, 0.1), rrand(25, 40, 0.1), $n4, 1)
$g5 = normrand(rrand(25, 40, 0.1), rrand(25, 40, 0.1), $n5, 1)

$result = anova1way($g1, $g2, $g3, $g4, $g5)
$df_b = $result[0][1]
$df_w = $result[1][1]
$F_stat = round($result[0][3], 2)
$pval = round($result[0][4], 4)
$MS_b = round($result[0][2], 2)
$MS_w = round($result[1][2], 2)
$SS_b = round($result[0][0], 2)
$SS_w = round($result[1][0], 2)
$SS_t = round($result[2][0], 2)
$df_t = $result[2][1]
$N = $n1 + $n2 + $n3 + $n4 + $n5

$edu_labels = array("Primary school", "Lower middle school", "Upper middle school", "Technical/vocational", "College")

$alpha_val = 0.05
$conclusion_choices = array("Reject H0 — there is convincing evidence that average child care hours differ across education levels", "Fail to reject H0 — there is not convincing evidence that average child care hours differ across education levels")
$conclusion = ($pval < $alpha_val) ? "Reject H0 — there is convincing evidence that average child care hours differ across education levels" : "Fail to reject H0 — there is not convincing evidence that average child care hours differ across education levels"

$abstolerance = 0.1

// === Question Text ===
// A survey collected data on the number of hours parents spend on child care, categorized
// by educational attainment ($N total respondents across 5 education levels).
// Summary statistics:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Education level</th><th>n</th><th>Mean</th><th>SD</th></tr>
// <tr><td>{$edu_labels[0]}</td><td>$n1</td><td>{round(mean($g1),1)}</td><td>{round(stdev($g1),1)}</td></tr>
// <tr><td>{$edu_labels[1]}</td><td>$n2</td><td>{round(mean($g2),1)}</td><td>{round(stdev($g2),1)}</td></tr>
// <tr><td>{$edu_labels[2]}</td><td>$n3</td><td>{round(mean($g3),1)}</td><td>{round(stdev($g3),1)}</td></tr>
// <tr><td>{$edu_labels[3]}</td><td>$n4</td><td>{round(mean($g4),1)}</td><td>{round(stdev($g4),1)}</td></tr>
// <tr><td>{$edu_labels[4]}</td><td>$n5</td><td>{round(mean($g5),1)}</td><td>{round(stdev($g5),1)}</td></tr>
// </table>
// <br>
// ANOVA output:
// <br><br>
// <table border="1" cellpadding="5">
// <tr><th>Source</th><th>df</th><th>Sum Sq</th><th>Mean Sq</th><th>F</th><th>p-value</th></tr>
// <tr><td>Education</td><td>$df_b</td><td>$SS_b</td><td>$MS_b</td><td>$F_stat</td><td>$pval</td></tr>
// <tr><td>Residuals</td><td>$df_w</td><td>$SS_w</td><td>$MS_w</td><td></td><td></td></tr>
// <tr><td>Total</td><td>$df_t</td><td>$SS_t</td><td></td><td></td><td></td></tr>
// </table>
// <br>
// (a) What is the F statistic? $answerbox[0]
// <br>
// (b) What is the p-value? $answerbox[1]
// <br>
// (c) What is the conclusion at &alpha; = 0.05? $answerbox[2]

// === Answer ===
$answer[0] = $F_stat
$answer[1] = $pval
$answer[2] = $conclusion
$displayformat[2] = "radio"
$abstolerance[0] = 0.1
$abstolerance[1] = 0.005

END MOM --->


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The <a href="https://rdrr.io/cran/Stat2Data/man/Cuckoo.html"><code>Cuckoo</code></a> data used in this exercise can be found in the <a href="https://cran.r-project.org/web/packages/Stat2Data/index.html"><strong>Stat2Data</strong></a> R package.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The data <a href="https://rdrr.io/cran/Stat2Data/man/Cuckoo.html"><code>Cuckoo</code></a> used in this exercise can be found in the <a href="https://cran.r-project.org/web/packages/Stat2Data/index.html"><strong>Stat2Data</strong></a> R package.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch15-chisq-independence.html" class="pagination-link" aria-label="Chi-Square Test of Independence">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch17-multiple-comparisons.html" class="pagination-link" aria-label="Multiple Comparisons">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>