<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>22&nbsp; Probability Rules – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch22-random-variables.html" rel="next">
<link href="../parts/part-v.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8a91fbd6dc43518bbcbbe5f3fb33f285.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-v.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/ch21-probability-rules.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Relationships</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21-probability-rules.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23-expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25-normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-vi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Design</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26-type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statbench-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatBench Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-defining-probability" id="toc-sec-defining-probability" class="nav-link active" data-scroll-target="#sec-defining-probability"><span class="header-section-number">22.1</span> Defining probability</a>
  <ul class="collapse">
  <li><a href="#simulation-the-law-of-large-numbers-in-action" id="toc-simulation-the-law-of-large-numbers-in-action" class="nav-link" data-scroll-target="#simulation-the-law-of-large-numbers-in-action"><span class="header-section-number">22.1.1</span> Simulation: The law of large numbers in action</a></li>
  </ul></li>
  <li><a href="#sec-sample-spaces" id="toc-sec-sample-spaces" class="nav-link" data-scroll-target="#sec-sample-spaces"><span class="header-section-number">22.2</span> Sample spaces and events</a></li>
  <li><a href="#sec-complement" id="toc-sec-complement" class="nav-link" data-scroll-target="#sec-complement"><span class="header-section-number">22.3</span> The complement rule</a></li>
  <li><a href="#sec-addition-rule" id="toc-sec-addition-rule" class="nav-link" data-scroll-target="#sec-addition-rule"><span class="header-section-number">22.4</span> The addition rule</a>
  <ul class="collapse">
  <li><a href="#disjoint-mutually-exclusive-events" id="toc-disjoint-mutually-exclusive-events" class="nav-link" data-scroll-target="#disjoint-mutually-exclusive-events"><span class="header-section-number">22.4.1</span> Disjoint (mutually exclusive) events</a></li>
  <li><a href="#probability-distributions" id="toc-probability-distributions" class="nav-link" data-scroll-target="#probability-distributions"><span class="header-section-number">22.4.2</span> Probability distributions</a></li>
  <li><a href="#the-general-addition-rule" id="toc-the-general-addition-rule" class="nav-link" data-scroll-target="#the-general-addition-rule"><span class="header-section-number">22.4.3</span> The general addition rule</a></li>
  </ul></li>
  <li><a href="#sec-conditional-probability" id="toc-sec-conditional-probability" class="nav-link" data-scroll-target="#sec-conditional-probability"><span class="header-section-number">22.5</span> Conditional probability</a>
  <ul class="collapse">
  <li><a href="#exploring-conditional-probability-with-data" id="toc-exploring-conditional-probability-with-data" class="nav-link" data-scroll-target="#exploring-conditional-probability-with-data"><span class="header-section-number">22.5.1</span> Exploring conditional probability with data</a></li>
  <li><a href="#marginal-and-joint-probabilities" id="toc-marginal-and-joint-probabilities" class="nav-link" data-scroll-target="#marginal-and-joint-probabilities"><span class="header-section-number">22.5.2</span> Marginal and joint probabilities</a></li>
  <li><a href="#the-conditional-probability-formula" id="toc-the-conditional-probability-formula" class="nav-link" data-scroll-target="#the-conditional-probability-formula"><span class="header-section-number">22.5.3</span> The conditional probability formula</a></li>
  </ul></li>
  <li><a href="#sec-multiplication-rule" id="toc-sec-multiplication-rule" class="nav-link" data-scroll-target="#sec-multiplication-rule"><span class="header-section-number">22.6</span> The multiplication rule</a>
  <ul class="collapse">
  <li><a href="#multiplication-rule-for-independent-processes" id="toc-multiplication-rule-for-independent-processes" class="nav-link" data-scroll-target="#multiplication-rule-for-independent-processes"><span class="header-section-number">22.6.1</span> Multiplication rule for independent processes</a></li>
  <li><a href="#the-general-multiplication-rule" id="toc-the-general-multiplication-rule" class="nav-link" data-scroll-target="#the-general-multiplication-rule"><span class="header-section-number">22.6.2</span> The general multiplication rule</a></li>
  <li><a href="#tree-diagrams" id="toc-tree-diagrams" class="nav-link" data-scroll-target="#tree-diagrams"><span class="header-section-number">22.6.3</span> Tree diagrams</a></li>
  </ul></li>
  <li><a href="#sec-independence" id="toc-sec-independence" class="nav-link" data-scroll-target="#sec-independence"><span class="header-section-number">22.7</span> Independence</a></li>
  <li><a href="#sec-bayes-theorem" id="toc-sec-bayes-theorem" class="nav-link" data-scroll-target="#sec-bayes-theorem"><span class="header-section-number">22.8</span> Bayes’ theorem (optional)</a></li>
  <li><a href="#sec-ch14-review" id="toc-sec-ch14-review" class="nav-link" data-scroll-target="#sec-ch14-review"><span class="header-section-number">22.9</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">22.9.1</span> Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">22.9.2</span> Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-v.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/ch21-probability-rules.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-warning no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Draft Chapter.</strong> This chapter is part of UWL’s STAT 145 curriculum and is under active development. Content is substantially complete but may undergo revisions. Feedback welcome.</p>
</div>
</div>
</div>
<div class="chapterintro">
<p>Probability forms the foundation of statistics, and you are probably already aware of many of the ideas we will discuss in this chapter. However, formalizing these concepts is likely new. While this chapter provides the theoretical foundation for the inference methods you have already been using, it also offers practical tools for reasoning about uncertainty. We will define probability, develop rules for combining probabilities, and explore conditional probability and independence — all concepts that underpin the inference methods from Parts II and III.</p>
</div>
<div class="statbench">
<p><strong>StatBench tools for this chapter</strong>: The probability concepts in this chapter provide the theoretical foundation for the distribution calculators and inference tools you used in earlier parts of the book. Try the <strong>Binomial Distribution Calculator</strong> to see probability in action — set <span class="math inline">\(n = 1\)</span> for a single Bernoulli trial.</p>
<p><a href="https://datascienceuwl.github.io/statbench/distribution/binomial/" target="_blank">Launch Binomial Distribution Calculator</a></p>
</div>
<section id="sec-defining-probability" class="level2" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="sec-defining-probability"><span class="header-section-number">22.1</span> Defining probability</h2>
<p>Statistics is built on probability, and probability gives us the language to describe uncertainty. We begin with a few simple examples that may feel familiar.</p>
<div class="workedexample">
<p>A “die,” the singular of “dice,” is a cube with six faces numbered 1, 2, 3, 4, 5, and 6. What is the chance of getting a 1 when rolling a fair die?</p>
<p>If the die is fair, then the chance of a 1 is as good as the chance of any other number. Since there are six equally likely outcomes, the chance must be 1-in-6 or, equivalently, <span class="math inline">\(1/6\)</span>.</p>
</div>
<div class="workedexample">
<p>What is the chance of getting a 1 or 2 on the next roll?</p>
<p>The outcomes 1 and 2 constitute two of the six equally likely outcomes, so the chance of getting one of these two is <span class="math inline">\(2/6 = 1/3\)</span>.</p>
</div>
<div class="workedexample">
<p>What is the chance of not rolling a 2?</p>
<p>Since the chance of rolling a 2 is <span class="math inline">\(1/6\)</span>, the chance of not rolling a 2 must be <span class="math inline">\(1 - 1/6 = 5/6\)</span>. Alternatively, not rolling a 2 means getting a 1, 3, 4, 5, or 6, which makes up five of the six equally likely outcomes.</p>
</div>
<p>We use probability to describe and understand apparent randomness. We frame probability in terms of a <strong>random process</strong> giving rise to an <strong>outcome</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Random process</th>
<th style="text-align: left;">Possible outcomes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Roll a die</td>
<td style="text-align: left;">1, 2, 3, 4, 5, or 6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flip a coin</td>
<td style="text-align: left;">H or T</td>
</tr>
</tbody>
</table>
<div class="definition">
<p>The <strong>probability</strong> of an outcome is the proportion of times the outcome would occur if we observed the random process an infinite number of times. Probability always takes values between 0 and 1 (inclusive) and may also be expressed as a percentage between 0% and 100%.</p>
</div>
<p>Probability can be illustrated by rolling a die many times. Let <span class="math inline">\(\hat{p}_n\)</span> be the proportion of outcomes that are 1 after the first <span class="math inline">\(n\)</span> rolls. As the number of rolls increases, <span class="math inline">\(\hat{p}_n\)</span> converges to the probability <span class="math inline">\(p = 1/6\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-law-large-numbers" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line plot showing the proportion of 1s in a die-rolling simulation converging to 1/6 as the number of rolls increases from 1 to 100,000.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-law-large-numbers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch21-probability-rules_files/figure-html/fig-law-large-numbers-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;22.1: The fraction of die rolls that are 1 at each stage in a simulation. The proportion tends to get closer to 1/6 as the number of rolls increases."><img src="ch21-probability-rules_files/figure-html/fig-law-large-numbers-1.png" class="img-fluid figure-img" alt="Line plot showing the proportion of 1s in a die-rolling simulation converging to 1/6 as the number of rolls increases from 1 to 100,000." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-law-large-numbers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.1: The fraction of die rolls that are 1 at each stage in a simulation. The proportion tends to get closer to 1/6 as the number of rolls increases.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="definition">
<p><strong>Law of Large Numbers.</strong> As more observations are collected, the proportion <span class="math inline">\(\hat{p}_n\)</span> of occurrences with a particular outcome converges to the probability <span class="math inline">\(p\)</span> of that outcome.</p>
</div>
<p>Occasionally the proportion will veer away from the true probability, but these deviations become smaller as the number of trials increases.</p>
<p>We write the probability of rolling a 1 as <span class="math inline">\(P(\text{rolling a 1})\)</span>. When the context is clear, we abbreviate this as <span class="math inline">\(P(1)\)</span>.</p>
<div class="guidedpractice">
<p>Random processes include rolling a die and flipping a coin. (a) Think of another random process. (b) Describe all the possible outcomes of that process.</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li>and (b) Here are several examples. (i) Whether someone gets sick next month: outcomes are <em>sick</em> and <em>not sick</em>. (ii) Randomly selecting a person and measuring their height: the outcome is a positive number. (iii) Whether the stock market goes up or down next week: outcomes are <em>up</em>, <em>down</em>, and <em>no change</em>. (iv) The number of emails you receive tomorrow: the outcome is a non-negative integer.</li>
</ol>
</details>
</div>
<section id="simulation-the-law-of-large-numbers-in-action" class="level3 original" data-number="22.1.1">
<h3 data-number="22.1.1" class="anchored" data-anchor-id="simulation-the-law-of-large-numbers-in-action"><span class="header-section-number">22.1.1</span> Simulation: The law of large numbers in action</h3>
<p>One of the most powerful ways to build intuition about probability is through simulation. Imagine writing a computer program that simulates flipping a fair coin 10,000 times and tracking the running proportion of heads after each flip.</p>
<ul>
<li>After 10 flips, the proportion of heads might be 0.30 or 0.70 — quite far from 0.50.</li>
<li>After 100 flips, the proportion is likely between 0.40 and 0.60.</li>
<li>After 1,000 flips, the proportion is usually between 0.47 and 0.53.</li>
<li>After 10,000 flips, it is almost certainly within 0.01 of 0.50.</li>
</ul>
<p>This is the Law of Large Numbers at work. The key insight is that probability is a <em>long-run</em> concept. In the short run, anything can happen. In the long run, patterns emerge with remarkable stability.</p>
<p>This simulation perspective will recur throughout our course. In Parts II and III, we used simulation to build sampling distributions and test hypotheses. Here in Part IV, we develop the <em>mathematical</em> rules that explain <em>why</em> those simulations work.</p>
</section>
</section>
<section id="sec-sample-spaces" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="sec-sample-spaces"><span class="header-section-number">22.2</span> Sample spaces and events</h2>
<div class="definition">
<p>The <strong>sample space</strong> <span class="math inline">\(S\)</span> of a random process is the set of all possible outcomes. An <strong>event</strong> is a subset of the sample space — that is, a collection of one or more outcomes.</p>
</div>
<p>For rolling a single die, the sample space is <span class="math inline">\(S = \{1, 2, 3, 4, 5, 6\}\)</span>.</p>
<p>Let <span class="math inline">\(A\)</span> represent the event that the die roll results in 1 or 2, so <span class="math inline">\(A = \{1, 2\}\)</span>. Let <span class="math inline">\(B\)</span> represent the event that the die roll is 4 or 6, so <span class="math inline">\(B = \{4, 6\}\)</span>. These events are shown visually in the diagram below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-die-events" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Diagram showing numbers 1 through 6 with events A circling 1 and 2, B circling 4 and 6, and D circling 2 and 3.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-die-events-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch21-probability-rules_files/figure-html/fig-die-events-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;22.2: Three events for die outcomes. A and B are disjoint since they share no outcomes."><img src="ch21-probability-rules_files/figure-html/fig-die-events-1.png" class="img-fluid figure-img" alt="Diagram showing numbers 1 through 6 with events A circling 1 and 2, B circling 4 and 6, and D circling 2 and 3." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-die-events-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.2: Three events for die outcomes. A and B are disjoint since they share no outcomes.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-complement" class="level2" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="sec-complement"><span class="header-section-number">22.3</span> The complement rule</h2>
<p>Let <span class="math inline">\(D = \{2, 3\}\)</span> represent the event that the outcome of a die roll is 2 or 3. Then the <strong>complement</strong> of <span class="math inline">\(D\)</span>, denoted <span class="math inline">\(D^c\)</span>, represents all outcomes in the sample space that are <em>not</em> in <span class="math inline">\(D\)</span>:</p>
<p><span class="math display">\[D^c = \{1, 4, 5, 6\}\]</span></p>
<div class="guidedpractice">
<ol type="a">
<li>Compute <span class="math inline">\(P(D^c) = P(\text{rolling a 1, 4, 5, or 6})\)</span>. (b) What is <span class="math inline">\(P(D) + P(D^c)\)</span>?</li>
</ol>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li>The outcomes are disjoint and each has probability <span class="math inline">\(1/6\)</span>, so <span class="math inline">\(P(D^c) = 4/6 = 2/3\)</span>. (b) <span class="math inline">\(P(D) = 1/6 + 1/6 = 1/3\)</span>. Since <span class="math inline">\(D\)</span> and <span class="math inline">\(D^c\)</span> are disjoint, <span class="math inline">\(P(D) + P(D^c) = 1/3 + 2/3 = 1\)</span>.</li>
</ol>
</details>
</div>
<p>A complement <span class="math inline">\(A^c\)</span> is constructed so that (i) every possible outcome not in <span class="math inline">\(A\)</span> is in <span class="math inline">\(A^c\)</span>, and (ii) <span class="math inline">\(A\)</span> and <span class="math inline">\(A^c\)</span> are disjoint. This gives us:</p>
<div class="important">
<p><strong>Complement rule.</strong> The complement of event <span class="math inline">\(A\)</span> is denoted <span class="math inline">\(A^c\)</span> and represents all outcomes not in <span class="math inline">\(A\)</span>. The probabilities of <span class="math inline">\(A\)</span> and <span class="math inline">\(A^c\)</span> are related by:</p>
<p><span class="math display">\[P(A) + P(A^c) = 1 \qquad \text{equivalently,} \qquad P(A) = 1 - P(A^c)\]</span></p>
</div>
<p>The complement rule is especially useful when computing a probability directly would be tedious but the complement is simple.</p>
<div class="workedexample">
<p>Let <span class="math inline">\(A\)</span> represent the event where the sum of two dice is less than 12. What is <span class="math inline">\(P(A)\)</span>?</p>
<p>The complement <span class="math inline">\(A^c\)</span> is the event that the sum equals 12. The only way to roll a sum of 12 is to get two 6s, so <span class="math inline">\(P(A^c) = 1/36\)</span>. Using the complement rule:</p>
<p><span class="math display">\[P(A) = 1 - P(A^c) = 1 - \frac{1}{36} = \frac{35}{36}\]</span></p>
</div>
<div class="guidedpractice">
<p>Find the following probabilities for rolling two dice: (a) The sum is <em>not</em> 6. (b) The sum is at least 4. (c) The sum is no more than 10.</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><span class="math inline">\(P(\text{sum} = 6) = 5/36\)</span>, so <span class="math inline">\(P(\text{not 6}) = 1 - 5/36 = 31/36\)</span>. (b) <span class="math inline">\(P(\text{sum} = 2 \text{ or } 3) = 1/36 + 2/36 = 1/12\)</span>, so <span class="math inline">\(P(\text{at least 4}) = 1 - 1/12 = 11/12\)</span>. (c) <span class="math inline">\(P(\text{sum} = 11 \text{ or } 12) = 2/36 + 1/36 = 1/12\)</span>, so <span class="math inline">\(P(\text{no more than 10}) = 1 - 1/12 = 11/12\)</span>.</li>
</ol>
</details>
</div>
</section>
<section id="sec-addition-rule" class="level2" data-number="22.4">
<h2 data-number="22.4" class="anchored" data-anchor-id="sec-addition-rule"><span class="header-section-number">22.4</span> The addition rule</h2>
<section id="disjoint-mutually-exclusive-events" class="level3" data-number="22.4.1">
<h3 data-number="22.4.1" class="anchored" data-anchor-id="disjoint-mutually-exclusive-events"><span class="header-section-number">22.4.1</span> Disjoint (mutually exclusive) events</h3>
<p>Two outcomes or events are called <strong>disjoint</strong> (or <strong>mutually exclusive</strong>) if they cannot both happen at the same time. For instance, when rolling a die, the outcomes 1 and 2 are disjoint since they cannot both occur on a single roll.</p>
<div class="important">
<p><strong>Addition rule for disjoint events.</strong> If <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> are disjoint events, then:</p>
<p><span class="math display">\[P(A_1 \text{ or } A_2) = P(A_1) + P(A_2)\]</span></p>
<p>More generally, if <span class="math inline">\(A_1, A_2, \ldots, A_k\)</span> are all mutually disjoint, then:</p>
<p><span class="math display">\[P(A_1 \text{ or } A_2 \text{ or } \cdots \text{ or } A_k) = P(A_1) + P(A_2) + \cdots + P(A_k)\]</span></p>
</div>
<div class="guidedpractice">
<p>We are interested in the probability of rolling a 1, 4, or 5. (a) Explain why the outcomes 1, 4, and 5 are disjoint. (b) Apply the addition rule to determine <span class="math inline">\(P(1 \text{ or } 4 \text{ or } 5)\)</span>.</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li>At most one of these outcomes can occur on a single die roll, so they are disjoint. (b) <span class="math inline">\(P(1 \text{ or } 4 \text{ or } 5) = P(1) + P(4) + P(5) = 1/6 + 1/6 + 1/6 = 3/6 = 1/2\)</span>.</li>
</ol>
</details>
</div>
</section>
<section id="probability-distributions" class="level3" data-number="22.4.2">
<h3 data-number="22.4.2" class="anchored" data-anchor-id="probability-distributions"><span class="header-section-number">22.4.2</span> Probability distributions</h3>
<p>A <strong>probability distribution</strong> is a table of all disjoint outcomes and their associated probabilities. For example, the distribution for the sum of two dice:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dice sum</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">9</th>
<th style="text-align: center;">10</th>
<th style="text-align: center;">11</th>
<th style="text-align: center;">12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Probability</td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{2}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{4}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{5}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{6}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{5}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{4}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{2}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{36}\)</span></td>
</tr>
</tbody>
</table>
<div class="important">
<p><strong>Rules for probability distributions.</strong> A valid probability distribution must satisfy three rules:</p>
<ol type="1">
<li>The outcomes listed must be disjoint.</li>
<li>Each probability must be between 0 and 1.</li>
<li>The probabilities must total 1.</li>
</ol>
</div>
</section>
<section id="the-general-addition-rule" class="level3" data-number="22.4.3">
<h3 data-number="22.4.3" class="anchored" data-anchor-id="the-general-addition-rule"><span class="header-section-number">22.4.3</span> The general addition rule</h3>
<p>When events are <em>not</em> disjoint, we cannot simply add their probabilities — doing so would double-count the outcomes they share.</p>
<p>Consider a standard deck of 52 cards. Let <span class="math inline">\(A\)</span> be the event “the card is a diamond” and <span class="math inline">\(B\)</span> be the event “the card is a face card.” These events overlap: the jack, queen, and king of diamonds are both diamonds and face cards.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-venn-cards" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Venn diagram with two overlapping circles labeled Diamonds and Face Cards. The left-only region shows 10, the overlap shows 3, the right-only region shows 9, and outside both circles shows 30.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-venn-cards-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch21-probability-rules_files/figure-html/fig-venn-cards-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;22.3: A Venn diagram for diamonds and face cards showing 10 diamonds that are not face cards, 9 face cards that are not diamonds, and 3 cards that are both."><img src="ch21-probability-rules_files/figure-html/fig-venn-cards-1.png" class="img-fluid figure-img" alt="Venn diagram with two overlapping circles labeled Diamonds and Face Cards. The left-only region shows 10, the overlap shows 3, the right-only region shows 9, and outside both circles shows 30." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-venn-cards-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.3: A Venn diagram for diamonds and face cards showing 10 diamonds that are not face cards, 9 face cards that are not diamonds, and 3 cards that are both.
</figcaption>
</figure>
</div>
</div>
</div>
<p>If we compute <span class="math inline">\(P(A) + P(B) = 13/52 + 12/52 = 25/52\)</span>, we have counted the 3 cards in the overlap twice. We correct this:</p>
<p><span class="math display">\[P(A \text{ or } B) = P(A) + P(B) - P(A \text{ and } B) = \frac{13}{52} + \frac{12}{52} - \frac{3}{52} = \frac{22}{52} = \frac{11}{26}\]</span></p>
<div class="important">
<p><strong>General addition rule.</strong> For any two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> (disjoint or not):</p>
<p><span class="math display">\[P(A \text{ or } B) = P(A) + P(B) - P(A \text{ and } B)\]</span></p>
</div>
<div class="caution">
<p><strong>“Or” is inclusive in statistics.</strong> When we write “<span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span>,” we mean “<span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, or both” unless explicitly stated otherwise.</p>
</div>
<div class="guidedpractice">
<ol type="a">
<li>If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are disjoint, explain why <span class="math inline">\(P(A \text{ and } B) = 0\)</span>. (b) Show that the general addition rule simplifies to the simpler addition rule when <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are disjoint.</li>
</ol>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li>If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are disjoint, they can never occur simultaneously, so <span class="math inline">\(P(A \text{ and } B) = 0\)</span>. (b) Substituting 0 for <span class="math inline">\(P(A \text{ and } B)\)</span> in the general addition rule gives <span class="math inline">\(P(A \text{ or } B) = P(A) + P(B) - 0 = P(A) + P(B)\)</span>, which is the simpler addition rule.</li>
</ol>
</details>
</div>
</section>
</section>
<section id="sec-conditional-probability" class="level2" data-number="22.5">
<h2 data-number="22.5" class="anchored" data-anchor-id="sec-conditional-probability"><span class="header-section-number">22.5</span> Conditional probability</h2>
<section id="exploring-conditional-probability-with-data" class="level3" data-number="22.5.1">
<h3 data-number="22.5.1" class="anchored" data-anchor-id="exploring-conditional-probability-with-data"><span class="header-section-number">22.5.1</span> Exploring conditional probability with data</h3>
<p>There can be rich relationships between two or more variables, and conditional probability provides the framework for exploring them. Suppose we have data from a study classifying 1,822 photos using both a machine learning (ML) algorithm and human judgment:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Truth: fashion</th>
<th style="text-align: right;">Truth: not</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ML: pred_fashion</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">219</td>
</tr>
<tr class="even">
<td style="text-align: left;">ML: pred_not</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">1491</td>
<td style="text-align: right;">1603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">1513</td>
<td style="text-align: right;">1822</td>
</tr>
</tbody>
</table>
<div class="workedexample">
<p>If a photo is actually about fashion, what is the chance the ML classifier correctly identified it?</p>
<p>Of the 309 fashion photos, the ML algorithm correctly classified 197:</p>
<p><span class="math display">\[P(\text{ML predicts fashion} \mid \text{truth is fashion}) = \frac{197}{309} = 0.638\]</span></p>
</div>
<p>We call this a <strong>conditional probability</strong> because we computed the probability <em>under a condition</em> — that the photo was actually about fashion.</p>
</section>
<section id="marginal-and-joint-probabilities" class="level3" data-number="22.5.2">
<h3 data-number="22.5.2" class="anchored" data-anchor-id="marginal-and-joint-probabilities"><span class="header-section-number">22.5.2</span> Marginal and joint probabilities</h3>
<div class="definition">
<p>A <strong>marginal probability</strong> is a probability based on a single variable, without regard to other variables. A <strong>joint probability</strong> is the probability of two or more outcomes occurring together.</p>
</div>
<p>From the photo classification data: <span class="math inline">\(P(\text{ML predicts fashion}) = 219/1822 = 0.120\)</span> is a marginal probability, while <span class="math inline">\(P(\text{ML predicts fashion and truth is fashion}) = 197/1822 = 0.108\)</span> is a joint probability.</p>
</section>
<section id="the-conditional-probability-formula" class="level3" data-number="22.5.3">
<h3 data-number="22.5.3" class="anchored" data-anchor-id="the-conditional-probability-formula"><span class="header-section-number">22.5.3</span> The conditional probability formula</h3>
<div class="important">
<p><strong>Conditional probability.</strong> The conditional probability of outcome <span class="math inline">\(A\)</span> given condition <span class="math inline">\(B\)</span> is:</p>
<p><span class="math display">\[P(A \mid B) = \frac{P(A \text{ and } B)}{P(B)}\]</span></p>
</div>
<p>The vertical bar “<span class="math inline">\(\mid\)</span>” is read as “given.”</p>
<div class="workedexample">
<p>Using the photo classification data, we can verify our earlier calculation using proportions alone:</p>
<p><span class="math display">\[P(\text{truth is fashion} \mid \text{ML predicts fashion}) = \frac{P(\text{truth is fashion and ML predicts fashion})}{P(\text{ML predicts fashion})} = \frac{0.108}{0.120} = 0.900\]</span></p>
<p>If the ML classifier says a photo is about fashion, there is a 90% probability it actually is.</p>
</div>
<div class="guidedpractice">
<p>The smallpox dataset provides data on 6,224 individuals in Boston in 1721. Of these, 3.92% were inoculated. Among those not inoculated, 14.11% died. Among those inoculated, only 2.46% died. Write out, in formal notation, the probability a randomly selected person who was not inoculated died from smallpox.</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(P(\text{result} = \text{died} \mid \text{inoculated} = \text{no}) = \frac{P(\text{died and not inoculated})}{P(\text{not inoculated})} = \frac{0.1356}{0.9608} = 0.1411\)</span>.
</details>
</div>
</section>
</section>
<section id="sec-multiplication-rule" class="level2" data-number="22.6">
<h2 data-number="22.6" class="anchored" data-anchor-id="sec-multiplication-rule"><span class="header-section-number">22.6</span> The multiplication rule</h2>
<section id="multiplication-rule-for-independent-processes" class="level3" data-number="22.6.1">
<h3 data-number="22.6.1" class="anchored" data-anchor-id="multiplication-rule-for-independent-processes"><span class="header-section-number">22.6.1</span> Multiplication rule for independent processes</h3>
<p>Consider rolling two dice. If <span class="math inline">\(1/6\)</span> of the time the first die is a 1, and <span class="math inline">\(1/6\)</span> of <em>those</em> times the second die is also a 1, then:</p>
<p><span class="math display">\[P(\text{both are 1}) = \frac{1}{6} \times \frac{1}{6} = \frac{1}{36}\]</span></p>
<div class="important">
<p><strong>Multiplication rule for independent processes.</strong> If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> represent events from two different and independent processes, then:</p>
<p><span class="math display">\[P(A \text{ and } B) = P(A) \times P(B)\]</span></p>
<p>If there are <span class="math inline">\(k\)</span> events <span class="math inline">\(A_1, \ldots, A_k\)</span> from <span class="math inline">\(k\)</span> independent processes, then:</p>
<p><span class="math display">\[P(A_1 \text{ and } A_2 \text{ and } \cdots \text{ and } A_k) = P(A_1) \times P(A_2) \times \cdots \times P(A_k)\]</span></p>
</div>
<div class="guidedpractice">
<p>About 9% of people are left-handed. Suppose 2 people are selected at random from the US population. (a) What is the probability that both are left-handed? (b) What is the probability that both are right-handed?</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><span class="math inline">\(0.09 \times 0.09 = 0.0081\)</span>. (b) <span class="math inline">\(P(\text{right-handed}) = 1 - 0.09 = 0.91\)</span>, so <span class="math inline">\(0.91 \times 0.91 = 0.8281\)</span>.</li>
</ol>
</details>
</div>
<div class="guidedpractice">
<p>Suppose 5 people are selected at random. (a) What is the probability that all are right-handed? (b) What is the probability that not all are right-handed?</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><span class="math inline">\(0.91^5 = 0.624\)</span>. (b) Using the complement: <span class="math inline">\(P(\text{not all right-handed}) = 1 - 0.624 = 0.376\)</span>.</li>
</ol>
</details>
</div>
</section>
<section id="the-general-multiplication-rule" class="level3" data-number="22.6.2">
<h3 data-number="22.6.2" class="anchored" data-anchor-id="the-general-multiplication-rule"><span class="header-section-number">22.6.2</span> The general multiplication rule</h3>
<p>The general multiplication rule handles events that may not be independent:</p>
<div class="important">
<p><strong>General multiplication rule.</strong> If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> represent two outcomes or events, then:</p>
<p><span class="math display">\[P(A \text{ and } B) = P(A \mid B) \times P(B)\]</span></p>
<p>This is simply a rearrangement of the conditional probability formula.</p>
</div>
<div class="workedexample">
<p>In the smallpox data, 96.08% of residents were not inoculated, and 85.88% of those who were not inoculated survived. What is the probability that a resident was not inoculated and lived?</p>
<p><span class="math display">\[P(\text{lived and not inoculated}) = P(\text{lived} \mid \text{not inoculated}) \times P(\text{not inoculated}) = 0.8588 \times 0.9608 = 0.8251\]</span></p>
</div>
</section>
<section id="tree-diagrams" class="level3" data-number="22.6.3">
<h3 data-number="22.6.3" class="anchored" data-anchor-id="tree-diagrams"><span class="header-section-number">22.6.3</span> Tree diagrams</h3>
<p><strong>Tree diagrams</strong> are a tool to organize outcomes and probabilities when two or more processes occur in sequence and each process is conditioned on its predecessors.</p>
<div class="workedexample">
<p>Suppose 13% of students earned an A on the midterm. Of those who earned an A on the midterm, 47% received an A on the final. Of those who earned lower than an A on the midterm, 11% received an A on the final. You randomly pick up a final exam and notice the student received an A. What is the probability the student also earned an A on the midterm?</p>
<p>We organize the information into a tree diagram:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tree-midterm" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Tree diagram splitting on midterm grade (A with probability 0.13, Other with probability 0.87), then splitting on final grade with conditional probabilities. Joint probabilities shown at the ends of branches.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tree-midterm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch21-probability-rules_files/figure-html/fig-tree-midterm-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;22.4: Tree diagram for midterm and final exam grades."><img src="ch21-probability-rules_files/figure-html/fig-tree-midterm-1.png" class="img-fluid figure-img" alt="Tree diagram splitting on midterm grade (A with probability 0.13, Other with probability 0.87), then splitting on final grade with conditional probabilities. Joint probabilities shown at the ends of branches." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tree-midterm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.4: Tree diagram for midterm and final exam grades.
</figcaption>
</figure>
</div>
</div>
</div>
<p>From the tree:</p>
<ul>
<li><span class="math inline">\(P(\text{midterm A and final A}) = 0.13 \times 0.47 = 0.0611\)</span></li>
<li><span class="math inline">\(P(\text{final A}) = 0.0611 + 0.0957 = 0.1568\)</span></li>
<li><span class="math inline">\(P(\text{midterm A} \mid \text{final A}) = \frac{0.0611}{0.1568} = 0.390\)</span></li>
</ul>
<p>The probability the student also earned an A on the midterm is about 0.39.</p>
</div>
<div class="important">
<p><strong>Sum of conditional probabilities.</strong> If <span class="math inline">\(A_1, \ldots, A_k\)</span> represent all disjoint outcomes of a variable, and <span class="math inline">\(B\)</span> is an event, then:</p>
<p><span class="math display">\[P(A_1 \mid B) + P(A_2 \mid B) + \cdots + P(A_k \mid B) = 1\]</span></p>
<p>The complement rule also holds for conditional probabilities: <span class="math inline">\(P(A \mid B) = 1 - P(A^c \mid B)\)</span>.</p>
</div>
</section>
</section>
<section id="sec-independence" class="level2" data-number="22.7">
<h2 data-number="22.7" class="anchored" data-anchor-id="sec-independence"><span class="header-section-number">22.7</span> Independence</h2>
<div class="definition">
<p>Two processes are <strong>independent</strong> if knowing the outcome of one provides no useful information about the outcome of the other. Mathematically, events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if:</p>
<p><span class="math display">\[P(A \text{ and } B) = P(A) \times P(B)\]</span></p>
<p>Equivalently, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if <span class="math inline">\(P(A \mid B) = P(A)\)</span>.</p>
</div>
<div class="workedexample">
<p>If we draw one card from a shuffled deck, is the event that the card is a heart independent of the event that the card is an ace?</p>
<p><span class="math inline">\(P(\heartsuit) = 1/4\)</span>, <span class="math inline">\(P(\text{ace}) = 1/13\)</span>, and <span class="math inline">\(P(\heartsuit \text{ and ace}) = 1/52\)</span>. We check:</p>
<p><span class="math display">\[P(\heartsuit) \times P(\text{ace}) = \frac{1}{4} \times \frac{1}{13} = \frac{1}{52} = P(\heartsuit \text{ and ace})\]</span></p>
<p>Because the equation holds, “heart” and “ace” are independent events.</p>
</div>
<div class="guidedpractice">
<p>Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> represent the outcomes of rolling two dice. (a) What is <span class="math inline">\(P(X = 1)\)</span>? (b) What is <span class="math inline">\(P(Y = 1 \text{ and } X = 1)\)</span>? (c) Compute <span class="math inline">\(P(Y = 1 \mid X = 1)\)</span>. (d) Compare <span class="math inline">\(P(Y = 1)\)</span> with the result from (c).</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><span class="math inline">\(1/6\)</span>. (b) <span class="math inline">\(1/36\)</span>. (c) <span class="math inline">\(\frac{1/36}{1/6} = 1/6\)</span>. (d) <span class="math inline">\(P(Y = 1) = 1/6\)</span>, the same as part (c). Knowledge about <span class="math inline">\(X\)</span> does not change the probability for <span class="math inline">\(Y\)</span>, confirming the dice are independent.</li>
</ol>
</details>
</div>
<div class="caution">
<p><strong>The gambler’s fallacy.</strong> Ron is watching a roulette table and notices the last five spins were all black. He bets on red, reasoning that “black six times in a row” is unlikely. This reasoning is flawed: each spin is independent of the previous spins. Past outcomes provide no information about future ones. Casinos often post recent outcomes precisely to encourage this fallacy.</p>
</div>
</section>
<section id="sec-bayes-theorem" class="level2" data-number="22.8">
<h2 data-number="22.8" class="anchored" data-anchor-id="sec-bayes-theorem"><span class="header-section-number">22.8</span> Bayes’ theorem (optional)</h2>
<p>In many situations, we are given <span class="math inline">\(P(B \mid A)\)</span> but need <span class="math inline">\(P(A \mid B)\)</span> — the “inverted” conditional probability. Bayes’ theorem provides a systematic way to perform this inversion.</p>
<div class="workedexample">
<p>In Canada, about 0.35% of women over 40 develop breast cancer in any given year. Mammograms produce false negatives 11% of the time (indicating no cancer when cancer is present) and false positives 7% of the time (indicating cancer when none is present). If a randomly selected woman over 40 tests positive, what is the probability she actually has breast cancer?</p>
<p>We organize the information into a tree diagram:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tree-cancer" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Tree diagram with primary branches for Cancer (0.0035) and No Cancer (0.9965), each splitting into Positive and Negative mammogram results with conditional probabilities and joint probabilities at the branch ends.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tree-cancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch21-probability-rules_files/figure-html/fig-tree-cancer-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;22.5: Tree diagram for breast cancer screening."><img src="ch21-probability-rules_files/figure-html/fig-tree-cancer-1.png" class="img-fluid figure-img" alt="Tree diagram with primary branches for Cancer (0.0035) and No Cancer (0.9965), each splitting into Positive and Negative mammogram results with conditional probabilities and joint probabilities at the branch ends." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tree-cancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.5: Tree diagram for breast cancer screening.
</figcaption>
</figure>
</div>
</div>
</div>
<p>From the tree:</p>
<ul>
<li><span class="math inline">\(P(\text{cancer and positive}) = 0.0035 \times 0.89 = 0.00312\)</span></li>
<li><span class="math inline">\(P(\text{positive}) = 0.00312 + 0.06976 = 0.07288\)</span></li>
<li><span class="math inline">\(P(\text{cancer} \mid \text{positive}) = \frac{0.00312}{0.07288} \approx 0.043\)</span></li>
</ul>
<p>Even with a positive mammogram, there is only about a 4% chance the patient has breast cancer. This is why doctors often run additional tests.</p>
</div>
<div class="important">
<p><strong>Bayes’ theorem.</strong> If <span class="math inline">\(A_1, A_2, \ldots, A_k\)</span> represent all possible disjoint outcomes of a first variable, and <span class="math inline">\(B\)</span> is an observed outcome of a second variable, then:</p>
<p><span class="math display">\[P(A_1 \mid B) = \frac{P(B \mid A_1) \, P(A_1)}{P(B \mid A_1) \, P(A_1) + P(B \mid A_2) \, P(A_2) + \cdots + P(B \mid A_k) \, P(A_k)}\]</span></p>
<p>The numerator is the probability of getting both <span class="math inline">\(A_1\)</span> and <span class="math inline">\(B\)</span>. The denominator is the total (marginal) probability of <span class="math inline">\(B\)</span>.</p>
</div>
<p><strong>To apply Bayes’ theorem:</strong></p>
<ol type="1">
<li>Identify the marginal probabilities: <span class="math inline">\(P(A_1), P(A_2), \ldots, P(A_k)\)</span>.</li>
<li>Identify the conditional probabilities: <span class="math inline">\(P(B \mid A_1), P(B \mid A_2), \ldots, P(B \mid A_k)\)</span>.</li>
<li>Substitute into the formula.</li>
</ol>
<div class="guidedpractice">
<p>Jose visits campus on Thursday evenings. Academic events occur 35% of evenings, sporting events 20%, and no events 45%. The parking garage fills up 25% of the time during academic events, 70% during sporting events, and 5% when there are no events. If Jose finds the garage full, what is the probability there is a sporting event?</p>
<details>
<summary>
Show answer
</summary>
Using Bayes’ theorem with <span class="math inline">\(A_1\)</span> = sporting, <span class="math inline">\(A_2\)</span> = academic, <span class="math inline">\(A_3\)</span> = none, and <span class="math inline">\(B\)</span> = garage full: <span class="math inline">\(P(\text{sporting} \mid \text{full}) = \frac{0.7 \times 0.2}{0.7 \times 0.2 + 0.25 \times 0.35 + 0.05 \times 0.45} = \frac{0.14}{0.25} = 0.56\)</span>. There is a 56% probability of a sporting event.
</details>
</div>
<p>The strategy of updating beliefs based on new evidence is the foundation of <strong>Bayesian statistics</strong>, an important branch of statistics that we will not have time to explore further in this course.</p>
</section>
<section id="sec-ch14-review" class="level2" data-number="22.9">
<h2 data-number="22.9" class="anchored" data-anchor-id="sec-ch14-review"><span class="header-section-number">22.9</span> Chapter review</h2>
<section id="summary" class="level3" data-number="22.9.1">
<h3 data-number="22.9.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">22.9.1</span> Summary</h3>
<p>In this chapter, we developed the mathematical rules of probability:</p>
<ul>
<li><strong>Probability</strong> is the long-run proportion of times an outcome occurs, governed by the <strong>Law of Large Numbers</strong>.</li>
<li>The <strong>sample space</strong> <span class="math inline">\(S\)</span> is the set of all possible outcomes; an <strong>event</strong> is a subset of <span class="math inline">\(S\)</span>.</li>
<li><strong>Complement rule</strong>: <span class="math inline">\(P(A) = 1 - P(A^c)\)</span>.</li>
<li><strong>Addition rule</strong>: <span class="math inline">\(P(A \text{ or } B) = P(A) + P(B) - P(A \text{ and } B)\)</span>. For disjoint events, <span class="math inline">\(P(A \text{ and } B) = 0\)</span>.</li>
<li><strong>Conditional probability</strong>: <span class="math inline">\(P(A \mid B) = P(A \text{ and } B) / P(B)\)</span>.</li>
<li><strong>Multiplication rule</strong>: <span class="math inline">\(P(A \text{ and } B) = P(A \mid B) \times P(B)\)</span>. For independent events, <span class="math inline">\(P(A \text{ and } B) = P(A) \times P(B)\)</span>.</li>
<li>Events are <strong>independent</strong> if knowing one occurred does not change the probability of the other.</li>
<li><strong>Bayes’ theorem</strong> inverts conditional probabilities.</li>
</ul>
</section>
<section id="exercises" class="level3 exercises" data-number="22.9.2">
<h3 class="exercises anchored" data-number="22.9.2" data-anchor-id="exercises"><span class="header-section-number">22.9.2</span> Exercises</h3>
<p>Exercises for this chapter are under development.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../parts/part-v.html" class="pagination-link" aria-label="Foundations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Foundations</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch22-random-variables.html" class="pagination-link" aria-label="Random Variables">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>