<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Exploring Categorical Data – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/describing-distributions.html" rel="next">
<link href="../chapters/study-design.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-c76bc2edb0e532e390ad582fcbf98d52.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-975f4eb663ddd4de51f5ac11eb3fbb8a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d90903f2ca6eb1a33c5609737f932d54.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/data-visualization.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../technology-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Technology Setup</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-visualization.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore — Part Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Exploring a Distribution</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decision-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-simulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate — Part Review</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-calculate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate — Part Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Inference for Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Two Means</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-apply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply — Part Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Several Means (ANOVA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Association Between Two Categorical Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Fitting and Testing a Regression Line</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Type II Error and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations — Part Review</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statlens-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatLens Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-viz-categorical" id="toc-sec-viz-categorical" class="nav-link active" data-scroll-target="#sec-viz-categorical"><span class="header-section-number">4.1</span> Visualizing one categorical variable</a>
  <ul class="collapse">
  <li><a href="#bar-charts" id="toc-bar-charts" class="nav-link" data-scroll-target="#bar-charts"><span class="header-section-number">4.1.1</span> Bar charts</a></li>
  <li><a href="#pie-charts" id="toc-pie-charts" class="nav-link" data-scroll-target="#pie-charts"><span class="header-section-number">4.1.2</span> Pie charts</a></li>
  <li><a href="#waffle-charts" id="toc-waffle-charts" class="nav-link" data-scroll-target="#waffle-charts"><span class="header-section-number">4.1.3</span> Waffle charts</a></li>
  </ul></li>
  <li><a href="#sec-two-categorical" id="toc-sec-two-categorical" class="nav-link" data-scroll-target="#sec-two-categorical"><span class="header-section-number">4.2</span> Two categorical variables</a>
  <ul class="collapse">
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">4.2.1</span> Contingency tables</a></li>
  <li><a href="#row-and-column-proportions" id="toc-row-and-column-proportions" class="nav-link" data-scroll-target="#row-and-column-proportions"><span class="header-section-number">4.2.2</span> Row and column proportions</a></li>
  <li><a href="#sec-bar-two-vars" id="toc-sec-bar-two-vars" class="nav-link" data-scroll-target="#sec-bar-two-vars"><span class="header-section-number">4.2.3</span> Bar charts for two categorical variables</a></li>
  </ul></li>
  <li><a href="#sec-effective-viz" id="toc-sec-effective-viz" class="nav-link" data-scroll-target="#sec-effective-viz"><span class="header-section-number">4.3</span> Effective data visualization</a>
  <ul class="collapse">
  <li><a href="#keep-it-simple" id="toc-keep-it-simple" class="nav-link" data-scroll-target="#keep-it-simple"><span class="header-section-number">4.3.1</span> Keep it simple</a></li>
  <li><a href="#use-color-to-draw-attention" id="toc-use-color-to-draw-attention" class="nav-link" data-scroll-target="#use-color-to-draw-attention"><span class="header-section-number">4.3.2</span> Use color to draw attention</a></li>
  <li><a href="#tell-a-story" id="toc-tell-a-story" class="nav-link" data-scroll-target="#tell-a-story"><span class="header-section-number">4.3.3</span> Tell a story</a></li>
  <li><a href="#order-matters" id="toc-order-matters" class="nav-link" data-scroll-target="#order-matters"><span class="header-section-number">4.3.4</span> Order matters</a></li>
  <li><a href="#make-labels-readable" id="toc-make-labels-readable" class="nav-link" data-scroll-target="#make-labels-readable"><span class="header-section-number">4.3.5</span> Make labels readable</a></li>
  <li><a href="#pick-a-purpose" id="toc-pick-a-purpose" class="nav-link" data-scroll-target="#pick-a-purpose"><span class="header-section-number">4.3.6</span> Pick a purpose</a></li>
  <li><a href="#select-meaningful-colors" id="toc-select-meaningful-colors" class="nav-link" data-scroll-target="#select-meaningful-colors"><span class="header-section-number">4.3.7</span> Select meaningful colors</a></li>
  </ul></li>
  <li><a href="#sec-data-visualization-review" id="toc-sec-data-visualization-review" class="nav-link" data-scroll-target="#sec-data-visualization-review"><span class="header-section-number">4.4</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.4.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">4.4.2</span> Key terms</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">4.5</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#statlens-exercises" id="toc-statlens-exercises" class="nav-link" data-scroll-target="#statlens-exercises">StatLens Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-i.html">Explore</a></li><li class="breadcrumb-item"><a href="../chapters/data-visualization.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>This chapter focuses on <strong>categorical data</strong> — variables whose values are categories or labels rather than numbers. We begin with visualizations for a single categorical variable (bar charts, pie charts, waffle charts), then move to tools for exploring the relationship between two categorical variables (contingency tables and stacked bar charts). We close with principles for creating effective, honest data visualizations.</p>
</div>
<div class="statlens">
<p><strong>StatLens tools for this chapter</strong>: Use the <a href="https://datascienceuwl.github.io/statlens/explore/one-cat/" target="_blank">One Categorical Variable</a> explorer for bar charts, pie charts, and waffle charts. Use the <a href="https://datascienceuwl.github.io/statlens/explore/categorical/" target="_blank">Categorical Data (Two Variables)</a> explorer for contingency tables and stacked bar charts.</p>
</div>
<section id="sec-viz-categorical" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-viz-categorical"><span class="header-section-number">4.1</span> Visualizing one categorical variable</h2>
<section id="bar-charts" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="bar-charts"><span class="header-section-number">4.1.1</span> Bar charts</h3>
<p>A <strong>bar chart</strong> is the most common way to display the distribution of a single categorical variable. Each category gets its own bar, and the height (or length) of the bar represents either the count or the proportion of observations in that category.</p>
<p>Consider a dataset of 10,000 loans from a lending platform. Each borrower’s homeownership status is recorded as <code>rent</code>, <code>mortgage</code>, or <code>own</code>. The frequency table below summarizes the data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Homeownership</th>
<th style="text-align: right;">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rent</td>
<td style="text-align: right;">3,858</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mortgage</td>
<td style="text-align: right;">4,789</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Own</td>
<td style="text-align: right;">1,353</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>10,000</strong></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<div id="fig-homeownership-bar" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A bar chart with three bars showing the distribution of homeownership. The mortgage bar is tallest at about 4,800, followed by rent at about 3,900, and own at about 1,400.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-homeownership-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-homeownership-bar-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;4.1: Bar chart showing counts of homeownership status. Mortgage is the tallest bar, followed by rent, then own."><img src="data-visualization_files/figure-html/fig-homeownership-bar-1.png" class="img-fluid figure-img" alt="A bar chart with three bars showing the distribution of homeownership. The mortgage bar is tallest at about 4,800, followed by rent at about 3,900, and own at about 1,400." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-homeownership-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Bar chart showing counts of homeownership status. Mortgage is the tallest bar, followed by rent, then own.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A bar chart of proportions conveys the same information but rescales the vertical axis so the bars represent the fraction of observations in each category. In the homeownership example, about 47.9% of borrowers have a mortgage, 38.6% rent, and 13.5% own their home outright.</p>
<div class="guidedpractice">
<p>In the homeownership bar chart, which category is most common? Which is least common? About what fraction of borrowers rent?</p>
<details>
<summary>
Show answer
</summary>
Mortgage is the most common category and own is the least common. About 38.6% of borrowers rent their home.
</details>
</div>
</section>
<section id="pie-charts" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="pie-charts"><span class="header-section-number">4.1.2</span> Pie charts</h3>
<p>A <strong>pie chart</strong> divides a circle into slices, where each slice represents a category and the size of the slice corresponds to the proportion of observations in that category.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pie-vs-bar" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A pie chart on the left and a bar chart on the right showing homeownership. In the pie chart it is difficult to tell which slice is larger, mortgage or rent. The bar chart makes this comparison much easier.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pie-vs-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-pie-vs-bar-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;4.2: A pie chart and bar chart displaying the same homeownership data side by side. Comparing mortgage and rent is much easier in the bar chart."><img src="data-visualization_files/figure-html/fig-pie-vs-bar-1.png" class="img-fluid figure-img" alt="A pie chart on the left and a bar chart on the right showing homeownership. In the pie chart it is difficult to tell which slice is larger, mortgage or rent. The bar chart makes this comparison much easier." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pie-vs-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: A pie chart and bar chart displaying the same homeownership data side by side. Comparing mortgage and rent is much easier in the bar chart.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Pie charts can give a quick high-level overview, especially when a variable has only a few levels or when each level represents a simple fraction (one-half, one-quarter, etc.). However, bar charts are almost always easier to read because our eyes are better at comparing lengths than angles or areas.</p>
<div class="important">
<p><strong>Bar charts vs.&nbsp;pie charts.</strong> When a categorical variable has many levels, bar charts are far superior to pie charts for making comparisons. Reserve pie charts for situations where the variable has very few categories and the goal is to show how a whole breaks into parts.</p>
</div>
</section>
<section id="waffle-charts" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="waffle-charts"><span class="header-section-number">4.1.3</span> Waffle charts</h3>
<div class="original">
<p>A <strong>waffle chart</strong> is another way to visualize proportions. It uses a grid (often 10 by 10 = 100 squares) where each square represents 1% of the data. Squares are shaded according to the categories. Like pie charts, waffle charts work best when the number of categories is small, but they can make it easier to compare proportions that do not correspond to simple fractions.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-waffle-homeownership" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A 10 by 10 grid of colored squares. About 48 squares are blue (mortgage), 39 are pink (rent), and 13 are dark teal (own), showing that mortgage is the most common homeownership status.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-waffle-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-waffle-homeownership-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;4.3: A waffle chart of homeownership status. Each square represents 1% of borrowers."><img src="data-visualization_files/figure-html/fig-waffle-homeownership-1.png" class="img-fluid figure-img" alt="A 10 by 10 grid of colored squares. About 48 squares are blue (mortgage), 39 are pink (rent), and 13 are dark teal (own), showing that mortgage is the most common homeownership status." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-waffle-homeownership-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: A waffle chart of homeownership status. Each square represents 1% of borrowers.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Why might a waffle chart be easier to read than a pie chart when comparing two categories with similar proportions (say, 38% and 42%)?</p>
<details>
<summary>
Show answer
</summary>
In a waffle chart, you can count the number of shaded squares for each category, making it straightforward to see the difference. In a pie chart, the angle difference between 38% and 42% is very subtle and hard to judge visually.
</details>
</div>
<div class="statlens">
<p><strong>Try it yourself.</strong> Open the <a href="https://datascienceuwl.github.io/statlens/explore/one-cat/?dataset=brexit&amp;labels=names&amp;activity=ch03-categorical-charts.json" target="_blank">Comparing Charts for Categorical Data</a> activity to explore Brexit survey data interactively. Switch between bar charts, pie charts, and waffle charts to see which makes it easiest to compare five response categories.</p>
</div>
</section>
</section>
<section id="sec-two-categorical" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-two-categorical"><span class="header-section-number">4.2</span> Two categorical variables</h2>
<p>When we want to explore the relationship between two categorical variables, we organize the data in a <strong>contingency table</strong> and display it with stacked or grouped bar charts.</p>
<section id="contingency-tables" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">4.2.1</span> Contingency tables</h3>
<div class="definition">
<p>A <strong>contingency table</strong> summarizes data for two categorical variables. The rows represent the levels of one variable, the columns represent the levels of the other, and each cell contains the count of observations in that combination. <strong>Row totals</strong> and <strong>column totals</strong> give the marginal distributions.</p>
</div>
<p>Consider a dataset of 10,000 loans. Each loan has a homeownership status (<code>rent</code>, <code>mortgage</code>, or <code>own</code>) and an application type (<code>joint</code> or <code>individual</code>). The contingency table below summarizes these two variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">362</td>
<td style="text-align: right;">950</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">1,495</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">3,496</td>
<td style="text-align: right;">3,839</td>
<td style="text-align: right;">1,170</td>
<td style="text-align: right;">8,505</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>3,858</strong></td>
<td style="text-align: right;"><strong>4,789</strong></td>
<td style="text-align: right;"><strong>1,353</strong></td>
<td style="text-align: right;"><strong>10,000</strong></td>
</tr>
</tbody>
</table>
<p>Each cell represents a count. For example, 3,496 loans were made by individuals who rent their home. The row totals tell us that 1,495 loans were joint applications and 8,505 were individual applications. The column totals tell us the overall distribution of homeownership.</p>
<div class="guidedpractice">
<p>What does the value 950 in the table represent? What does the column total 4,789 represent?</p>
<details>
<summary>
Show answer
</summary>
The value 950 represents the number of loans that were joint applications from borrowers with a mortgage. The column total 4,789 represents the total number of borrowers (both joint and individual) who have a mortgage.
</details>
</div>
</section>
<section id="row-and-column-proportions" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="row-and-column-proportions"><span class="header-section-number">4.2.2</span> Row and column proportions</h3>
<p>Raw counts can be hard to compare when group sizes differ. Instead, we can compute <strong>row proportions</strong> or <strong>column proportions</strong> to see conditional relationships.</p>
<div class="definition">
<p><strong>Row proportions</strong> are computed by dividing each count by its row total. They show how a variable is distributed <em>within each level</em> of the row variable.</p>
<p><strong>Column proportions</strong> are computed by dividing each count by its column total. They show how a variable is distributed <em>within each level</em> of the column variable.</p>
<p>Both row and column proportions are examples of <strong>conditional proportions</strong> — the proportion of observations in one category, conditional on (given) the level of the other variable.</p>
</div>
<p><strong>Row proportions</strong> (each count divided by its row total):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">0.242</td>
<td style="text-align: right;">0.635</td>
<td style="text-align: right;">0.122</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: right;">0.451</td>
<td style="text-align: right;">0.138</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
<p>For example, <span class="math inline">\(3{,}496 / 8{,}505 = 0.411\)</span>, meaning 41.1% of individual applicants rent their home.</p>
<p><strong>Column proportions</strong> (each count divided by its column total):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rent</th>
<th style="text-align: right;">Mortgage</th>
<th style="text-align: right;">Own</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Joint</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="even">
<td style="text-align: left;">Individual</td>
<td style="text-align: right;">0.906</td>
<td style="text-align: right;">0.802</td>
<td style="text-align: right;">0.865</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
<p>The value 0.906 tells us that 90.6% of renters applied individually. This rate is higher than for borrowers with mortgages (80.2%) or who own their home (86.5%). Because these rates vary across the levels of homeownership, there is evidence that application type and homeownership may be <strong>associated</strong>.</p>
<div class="guidedpractice">
<p>What does 0.451 represent in the row proportions table? What does 0.802 represent in the column proportions table?</p>
<details>
<summary>
Show answer
</summary>
0.451 represents the proportion of individual applicants who have a mortgage. 0.802 represents the fraction of applicants with mortgages who applied as individuals.
</details>
</div>
<div class="workedexample">
<p>Data scientists use statistics to build email spam filters. One characteristic examined is email format (HTML or plain text). A contingency table of email format and spam status is shown below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">HTML</th>
<th style="text-align: right;">Text</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Not spam</td>
<td style="text-align: right;">2,568</td>
<td style="text-align: right;">986</td>
<td style="text-align: right;">3,554</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spam</td>
<td style="text-align: right;">158</td>
<td style="text-align: right;">209</td>
<td style="text-align: right;">367</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>2,726</strong></td>
<td style="text-align: right;"><strong>1,195</strong></td>
<td style="text-align: right;"><strong>3,921</strong></td>
</tr>
</tbody>
</table>
<p>Which would be more useful for classifying email: row or column proportions?</p>
<hr>
<p>A data scientist would want to know how the proportion of spam changes depending on email format. This corresponds to <strong>column proportions</strong>: <span class="math inline">\(209/1{,}195 = 17.5\%\)</span> of plain text emails are spam, compared to <span class="math inline">\(158/2{,}726 = 5.8\%\)</span> of HTML emails. Plain text emails are more likely to be spam. Row or column proportions are not equivalent — before computing, consider which variable you want to “condition on” (usually the explanatory variable).</p>
</div>
<div class="guidedpractice">
<p>In the spam example, which variable would you consider the explanatory variable and which the response?</p>
<details>
<summary>
Show answer
</summary>
Email format (HTML vs.&nbsp;text) is the explanatory variable — it is a characteristic of the email that might help explain or predict whether the email is spam. Spam status (spam vs.&nbsp;not spam) is the response variable.
</details>
</div>
</section>
<section id="sec-bar-two-vars" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="sec-bar-two-vars"><span class="header-section-number">4.2.3</span> Bar charts for two categorical variables</h3>
<p>Bar charts can be extended to display the relationship between two categorical variables. There are three common variants:</p>
<div class="definition">
<p>A <strong>stacked bar chart</strong> stacks the bars for the second variable on top of each other within each level of the first variable. It shows both the total count and the breakdown by the second variable.</p>
<p>A <strong>100% stacked bar chart</strong> (also called a standardized or filled bar chart) is like a stacked bar chart, but the bars are scaled to the same height (100%). It shows the <em>proportion</em> of each category of the second variable within each level of the first variable.</p>
<p>A <strong>side-by-side bar chart</strong> (also called a grouped or dodged bar chart) places bars for the second variable next to each other within each level of the first variable. It makes it easy to compare counts across groups.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bar-types-stacked" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three bar charts displaying the relationship between homeownership (rent, mortgage, own) and application type (joint, individual). The stacked bar chart shows total counts with application types stacked. The 100% stacked bar chart shows each bar at 100% height with proportional shading. The side-by-side bar chart places joint and individual bars next to each other for each homeownership category.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bar-types-stacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-bar-types-stacked-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4.4: Three bar charts showing homeownership and application type: stacked, 100% stacked, and side-by-side."><img src="data-visualization_files/figure-html/fig-bar-types-stacked-1.png" class="img-fluid figure-img" alt="Three bar charts displaying the relationship between homeownership (rent, mortgage, own) and application type (joint, individual). The stacked bar chart shows total counts with application types stacked. The 100% stacked bar chart shows each bar at 100% height with proportional shading. The side-by-side bar chart places joint and individual bars next to each other for each homeownership category." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bar-types-stacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: Three bar charts showing homeownership and application type: stacked, 100% stacked, and side-by-side.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="workedexample">
<p>When is each type of bar chart most useful?</p>
<hr>
<ul>
<li>The <strong>stacked bar chart</strong> is most useful when you want to see both the total count for each group and the breakdown by the second variable.</li>
<li>The <strong>100% stacked bar chart</strong> is helpful when comparing proportions across groups, especially when the groups have very different sizes. However, it sacrifices information about the total count.</li>
<li>The <strong>side-by-side bar chart</strong> makes it easy to compare individual counts directly. It works well for showing both variables without implying one is the explanatory variable. However, it requires more horizontal space.</li>
</ul>
</div>
<div class="important">
<p><strong>Detecting association in a 100% stacked bar chart.</strong> If the proportional breakdown of the response variable is the <em>same</em> across all levels of the explanatory variable, then the variables are <strong>not</strong> associated — the colored segments will line up at the same heights. If the breakdown <em>differs</em> across levels, the variables are associated.</p>
</div>
<div class="guidedpractice">
<p>In the 100% stacked bar chart above, how can you tell whether homeownership and application type are associated?</p>
<details>
<summary>
Show answer
</summary>
If the variables were not associated, the division between joint and individual would occur at the same height in every bar. Since the bars are divided at different heights — mortgage holders have a higher proportion of joint applications than renters or owners — the variables appear to be associated.
</details>
</div>
<div class="statlens">
<p><strong>Try it yourself.</strong> Open the <a href="https://datascienceuwl.github.io/statlens/explore/categorical/?dataset=diabetes2&amp;activity=ch03-two-way-tables.json" target="_blank">Exploring Two-Way Tables</a> activity to explore a contingency table from a diabetes clinical trial. The guided steps walk you through counts, row proportions, column proportions, and three bar chart types — so you can see how each display answers a different question.</p>
</div>
</section>
</section>
<section id="sec-effective-viz" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-effective-viz"><span class="header-section-number">4.3</span> Effective data visualization</h2>
<div class="original">
<p>Graphs can powerfully communicate ideas directly and quickly. However, there are times when a visualization conveys a message that is inaccurate or misleading. This section provides guiding principles for creating clear, honest, and effective visualizations.</p>
</div>
<section id="keep-it-simple" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="keep-it-simple"><span class="header-section-number">4.3.1</span> Keep it simple</h3>
<p>Colors should be used purposefully — to group items or differentiate levels in meaningful ways. Colors used only for decoration can be distracting.</p>
<p>Consider a company that has summarized its costs into five categories. A three-dimensional pie chart makes it hard to compare the sizes of the slices, and the unnecessary 3D effect distorts the proportions. A simple bar chart conveys the same information much more clearly.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../images/pie-3d.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="A 3D pie chart showing five cost categories. The 3D perspective distorts the proportions — for instance, “Labor” at 31% looks disproportionately large because it is in the foreground."><img src="../images/pie-3d.jpg" class="img-fluid figure-img" alt="A three-dimensional pie chart showing five cost categories: Labor 31%, Machinery 27%, Buildings and Administration 22%, Workpiece Materials 17%, and Cutting Tools 3%. The 3D effect makes it hard to compare slice sizes accurately."></a></p>
<figcaption>A 3D pie chart showing five cost categories. The 3D perspective distorts the proportions — for instance, “Labor” at 31% looks disproportionately large because it is in the foreground.</figcaption>
</figure>
</div>
<p>A simple bar chart of the same data makes the comparisons effortless:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bar-vs-3d-pie" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A horizontal bar chart with five bars showing cost categories. Labor is the longest bar at 31%, followed by Machinery at 27%, Buildings and Administration at 22%, Workpiece Materials at 17%, and Cutting Tools at 3%.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bar-vs-3d-pie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-bar-vs-3d-pie-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;4.5: A bar chart of the same cost data. The relative sizes of each category are immediately clear."><img src="data-visualization_files/figure-html/fig-bar-vs-3d-pie-1.png" class="img-fluid figure-img" alt="A horizontal bar chart with five bars showing cost categories. Labor is the longest bar at 31%, followed by Machinery at 27%, Buildings and Administration at 22%, Workpiece Materials at 17%, and Cutting Tools at 3%." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bar-vs-3d-pie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.5: A bar chart of the same cost data. The relative sizes of each category are immediately clear.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="use-color-to-draw-attention" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="use-color-to-draw-attention"><span class="header-section-number">4.3.2</span> Use color to draw attention</h3>
<p>An important principle is to use color <strong>to draw attention</strong> to the most important part of your graphic. Default rainbow coloring often adds no meaning and can confuse readers.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-color-attention" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three horizontal bar charts of cost categories. The first uses a different bright color for each bar (distracting). The second uses gray for most bars and red for Buildings and Administration, drawing immediate attention. The third adds a dashed border to the red bar for people who cannot distinguish colors.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-color-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-color-attention-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;4.6: Three versions of the same bar chart. The first uses distracting rainbow colors. The second highlights one important bar in red against gray bars. The third adds both color and a dashed border for accessibility."><img src="data-visualization_files/figure-html/fig-color-attention-1.png" class="img-fluid figure-img" alt="Three horizontal bar charts of cost categories. The first uses a different bright color for each bar (distracting). The second uses gray for most bars and red for Buildings and Administration, drawing immediate attention. The third adds a dashed border to the red bar for people who cannot distinguish colors." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-color-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.6: Three versions of the same bar chart. The first uses distracting rainbow colors. The second highlights one important bar in red against gray bars. The third adds both color and a dashed border for accessibility.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="important">
<p><strong>Accessibility matters.</strong> Not everyone perceives color the same way. When using color to draw attention, also consider adding a secondary visual cue (such as a pattern, line style, or border) so that the highlighted feature is distinguishable even for people with color vision deficiency.</p>
</div>
</section>
<section id="tell-a-story" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="tell-a-story"><span class="header-section-number">4.3.3</span> Tell a story</h3>
<p>Effective graphs often include <strong>annotations</strong> — text, lines, or labels that provide context beyond the raw data. For example, adding a note that “July is the start of the fiscal year” to a time series of monthly hiring can explain why there is a spike every July.</p>
</section>
<section id="order-matters" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="order-matters"><span class="header-section-number">4.3.4</span> Order matters</h3>
<p>The arrangement of categories in a bar chart can help or hinder understanding. Alphabetical order is rarely the most informative choice. Consider ordering bars by frequency (tallest to shortest) or by a meaningful sequence (such as the order the options appeared in a survey question).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bar-ordering" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three bar charts of Brexit survey responses. The first is alphabetically ordered (confusing). The second is in frequency order (most to least common). The third follows the natural survey order from Very well to Don't know, which tells the clearest story.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bar-ordering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="data-visualization_files/figure-html/fig-bar-ordering-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;4.7: Three versions of a bar chart showing survey responses ordered alphabetically, by frequency, and by the original survey order."><img src="data-visualization_files/figure-html/fig-bar-ordering-1.png" class="img-fluid figure-img" alt="Three bar charts of Brexit survey responses. The first is alphabetically ordered (confusing). The second is in frequency order (most to least common). The third follows the natural survey order from Very well to Don't know, which tells the clearest story." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bar-ordering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.7: Three versions of a bar chart showing survey responses ordered alphabetically, by frequency, and by the original survey order.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="make-labels-readable" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="make-labels-readable"><span class="header-section-number">4.3.5</span> Make labels readable</h3>
<p>When category labels are long, consider using horizontal bars (where labels appear along the vertical axis with plenty of space) rather than vertical bars (where labels must be angled or truncated).</p>
</section>
<section id="pick-a-purpose" class="level3" data-number="4.3.6">
<h3 data-number="4.3.6" class="anchored" data-anchor-id="pick-a-purpose"><span class="header-section-number">4.3.6</span> Pick a purpose</h3>
<p>Every graphical decision should be made with a purpose. Before choosing a chart type, ask:</p>
<ul>
<li>What is the key comparison I want the reader to make?</li>
<li>Which chart type makes that comparison easiest?</li>
<li>Am I showing proportions, counts, distributions, or relationships?</li>
</ul>
<div class="workedexample">
<p>A survey asks residents of five regions about their opinion on a policy, with responses ranging from “Very well” to “Very badly.” You want to compare how opinions differ across regions. What visualization would you choose?</p>
<hr>
<p>A 100% stacked bar chart would be useful if the main comparison is about proportions within each region. A side-by-side bar chart would work if comparing raw counts across regions matters. A faceted bar chart — one panel per region — would allow the most detailed comparison. The best choice depends on which comparison is most important to the story you are telling.</p>
</div>
</section>
<section id="select-meaningful-colors" class="level3" data-number="4.3.7">
<h3 data-number="4.3.7" class="anchored" data-anchor-id="select-meaningful-colors"><span class="header-section-number">4.3.7</span> Select meaningful colors</h3>
<p>Default or rainbow color schemes are not always the best choice. Perceptually uniform color scales (such as the viridis or cividis scales) are designed to be distinguishable by people with a variety of color vision abilities and to be readable when printed in grayscale. For ordinal data, a sequential color scale (light to dark) communicates the ordering effectively.</p>
<div class="original">
<p><strong>Summary of data visualization principles:</strong></p>
<ol type="1">
<li><strong>Keep it simple</strong> — avoid unnecessary 3D effects, decorative colors, and chart junk</li>
<li><strong>Use color with purpose</strong> — to group, differentiate, or draw attention</li>
<li><strong>Include context</strong> — titles, axis labels, annotations, and data sources</li>
<li><strong>Choose appropriate ordering</strong> — by frequency, natural order, or meaningful sequence</li>
<li><strong>Make labels readable</strong> — flip axes if labels are long; avoid angled text</li>
<li><strong>Consider your audience</strong> — use accessible color schemes and secondary visual cues</li>
<li><strong>Match the chart to the question</strong> — each chart type has strengths; choose deliberately</li>
</ol>
</div>
</section>
</section>
<section id="sec-data-visualization-review" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-data-visualization-review"><span class="header-section-number">4.4</span> Chapter review</h2>
<section id="summary" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.4.1</span> Summary</h3>
<p>This chapter introduced tools for exploring categorical data. For a single categorical variable, <strong>bar charts</strong> are the primary visualization, with <strong>pie charts</strong> reserved for simple cases and <strong>waffle charts</strong> useful for estimating percentages. For two categorical variables, <strong>contingency tables</strong> organize counts, <strong>row and column proportions</strong> reveal conditional relationships, and <strong>stacked</strong>, <strong>100% stacked</strong>, and <strong>side-by-side bar charts</strong> provide visual comparisons. When the proportional breakdown of one variable differs across levels of the other, the variables are <strong>associated</strong>. Effective visualizations follow principles of simplicity, purposeful use of color, meaningful ordering, and accessibility.</p>
</section>
<section id="key-terms" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">4.4.2</span> Key terms</h3>
<ul>
<li>Bar chart, pie chart, waffle chart</li>
<li>Frequency table, proportion</li>
<li>Contingency table, row totals, column totals</li>
<li>Row proportions, column proportions, conditional proportions</li>
<li>Stacked bar chart, 100% stacked bar chart, side-by-side bar chart</li>
<li>Association (between categorical variables)</li>
<li>Explanatory variable, response variable</li>
</ul>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="4.5">
<h2 class="exercises anchored" data-number="4.5" data-anchor-id="exercises"><span class="header-section-number">4.5</span> Exercises</h2>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _04-ex-explore-categorical -->
<ol type="1">
<li><strong>Antibiotic use in children.</strong> The bar plot and the pie chart below show the distribution of pre-existing medical conditions of children involved in a study on the optimal duration of antibiotic use in treatment of tracheitis, which is an upper respiratory infection.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="data-visualization_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="data-visualization_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>What features are apparent in the bar plot but not in the pie chart?</p></li>
<li><p>What features are apparent in the pie chart but not in the bar plot?</p></li>
<li><p>Which graph would you prefer to use for displaying these categorical data? </p></li>
</ol>
<ol start="2" type="1">
<li><strong>Views on immigration.</strong> Nine-hundred and ten (910) randomly sampled registered voters from Tampa, FL were asked if they thought workers who have illegally entered the US should be (i) allowed to keep their jobs and apply for US citizenship, (ii) allowed to keep their jobs as temporary guest workers but not allowed to apply for US citizenship, or (iii) lose their jobs and have to leave the country. The results of the survey by political ideology are shown below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Response</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Conservative</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Liberal</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Moderate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Apply for citizenship</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">278</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guest worker</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">262</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leave the country</td>
<td style="text-align: right;">179</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">350</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not sure</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">372</td>
<td style="text-align: right;">175</td>
<td style="text-align: right;">363</td>
<td style="text-align: right;">910</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What percent of these Tampa, FL voters identify themselves as conservatives?</p></li>
<li><p>What percent of these Tampa, FL voters are in favor of the citizenship option?</p></li>
<li><p>What percent of these Tampa, FL voters identify themselves as conservatives and are in favor of the citizenship option?</p></li>
<li><p>What percent of these Tampa, FL voters who identify themselves as conservatives are also in favor of the citizenship option? What percent of moderates share this view? What percent of liberals share this view?</p></li>
<li><p>Do political ideology and views on immigration appear to be associated? Explain your reasoning.</p></li>
<li><p>Conjecture other variables that might explain the potential relationship between these two variables.</p></li>
</ol>
<ol start="3" type="1">
<li><strong>Black Lives Matter.</strong> A Washington Post-Schar School poll conducted in the United States in June 2020, among a random national sample of 1,006 adults, asked respondents whether they support or oppose protests following George Floyd’s killing that have taken place in cities across the US. The survey also collected information on the age of the respondents. <span class="citation" data-cites="survey:blmWaPoScar:2020">(<a href="#ref-survey:blmWaPoScar:2020" role="doc-biblioref">Washington Post 2020</a>)</span> The results are summarized in the stacked bar plot below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="data-visualization_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="data-visualization_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Based on the stacked bar plot, do views on the protests and age appear to be associated? Explain your reasoning.</p></li>
<li><p>Conjecture other possible variables that might explain the potential association between these two variables. </p></li>
</ol>
<ol start="4" type="1">
<li><strong>Raise taxes.</strong> A random sample of registered voters nationally were asked whether they think it’s better to raise taxes on the rich or raise taxes on the poor. The survey also collected information on the political party affiliation of the respondents. <span class="citation" data-cites="survey:raiseTaxes:2015">(<a href="#ref-survey:raiseTaxes:2015" role="doc-biblioref">Polling 2015</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="data-visualization_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="data-visualization_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Based on the stacked bar plot shown above, do views on raising taxes and political affiliation appear to be associated? Explain your reasoning.</p></li>
<li><p>Conjecture other possible variables that might explain the potential association between these two variables.</p></li>
</ol>
<ol start="5" type="1">
<li><strong>Heart transplant data display.</strong> The Stanford University Heart Transplant Study was conducted to determine whether an experimental heart transplant program increased lifespan. Each patient entering the program was officially designated a heart transplant candidate, meaning that they were gravely ill and might benefit from a new heart. Patients were randomly assigned into treatment and control groups. Patients in the treatment group received a transplant, and those in the control group did not. The visualizations below display two different versions of the study results. <span class="citation" data-cites="Turnbull+Brown+Hu:1974">(<a href="#ref-Turnbull+Brown+Hu:1974" role="doc-biblioref">Turnbull, Brown, and Hu 1974</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="data-visualization_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="data-visualization_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Provide one aspect of the two group comparison that is easier to see from the stacked bar plot (left)?</p></li>
<li><p>Provide one aspect of the two group comparison that is easeir to see from the standardized bar plot (right)?</p></li>
<li><p>For the Heart Transplant Study which of those aspects would be more important to display? That is, which bar plot would be better as a data visualization? </p></li>
</ol>
<ol start="6" type="1">
<li><strong>Shipping holiday gifts data display.</strong> A local news survey asked 500 randomly sampled Los Angeles residents which shipping carrier they prefer to use for shipping holiday gifts. The bar plots below show the distribution of responses by age group as well as distribution of responses by shipping method.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="data-visualization_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="data-visualization_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:95.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Which graph (top or bottom) would you use to understand the shipping choices of people of different ages? Explain.</p></li>
<li><p>Which graph (top or bottom) would you use to understand the age distribution across different types of shipping choices? Explain.</p></li>
<li><p>A new shipping company would like to market to people over the age of 55. Who will be their biggest competitor? Explain.</p></li>
<li><p>FedEx would like to reach out to grow their market share so as to balance the age demographics of FedEx users. To what age group should FedEx market?</p></li>
</ol>
<ol start="7" type="1">
<li><strong>On-time arrivals.</strong> Consider all of the flights out of New York City in 2013 that flew into Puerto Rico (BQN), Los Angeles (LAX), or San Francisco (SFO) on the following two airlines: JetBlue (B6) or United Airlines (UA). Below are the tabulated counts for the number of flights <code>delayed</code> and <code>on time</code> for each airline into each city.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">dest</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">carrier</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">status</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">271</td>
</tr>
<tr class="even">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="even">
<td style="text-align: left;">BQN</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">151</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">670</td>
</tr>
<tr class="even">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">999</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">2368</td>
</tr>
<tr class="even">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">3402</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">405</td>
</tr>
<tr class="even">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">B6</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">615</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">delayed</td>
<td style="text-align: right;">2694</td>
</tr>
<tr class="even">
<td style="text-align: left;">SFO</td>
<td style="text-align: left;">UA</td>
<td style="text-align: left;">on time</td>
<td style="text-align: right;">4034</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What percent of all JetBlue flights were delayed? What percent of all United Airlines flights were delayed? (Note, the overall delay proportions are typically what would be reported and associated with an airline.)</p></li>
<li><p>For each of the three airports, find the percent of delayed flights for each of JetBlue and United (you should have 6 numbers).</p></li>
<li><p>United has a higher proportion of delayed flights for each of the three cities, yet JetBlue has a higher proportion of delayed flights overall. Explain, using the data counts provided, how the seeming paradox could happen.</p></li>
</ol>
<ol start="8" type="1">
<li><strong>US House of Representatives.</strong> The US House of Representatives is dominated by two political parties: Democrats and Republicans. Democrats are thought to be the more liberal party and Republicans are considered to be the more conservative party. However, within each party there is an internal spectrum of liberal to conservative. For example, conservative Democrats and liberal Republicans would be labeled moderate. Consider an election where the only change in membership is that the most conservative Democrats are replaced by a set of liberal Republicans who are more liberal than the incumbent Republicans but more conservative than the Democrats they replaced.</li>
</ol>
<ol type="a">
<li><p>After the election, is the Democratic wing of the House more conservative or more liberal? Explain.</p></li>
<li><p>After the election, is the Republican wing of the House more conservative or more liberal? Explain.</p></li>
<li><p>After the election, is the overall House membership more conservative or more liberal? Explain.</p></li>
<li><p>In what settings would you report the outcome of the change in House membership to be more conservative? And in what settings would you report the outcome of the change in House membership to be more liberal?</p></li>
</ol>
<details class="dataset-sources">
<summary>
Dataset sources
</summary>
<small><a href="http://openintrostat.github.io/openintro/reference/antibiotics.html"><code>antibiotics</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/immigration.html"><code>immigration</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/heart_transplant.html"><code>heart_transplant</code></a> (openintro) | <code>flights</code> (<a href="https://github.com/tidyverse/nycflights13">nycflights13</a>)</small>
</details>
<!-- StatLens Interactive Exercises — Chapter 3 -->
<!-- These exercises use StatLens tools for hands-on exploration. -->
<section id="statlens-exercises" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="statlens-exercises">StatLens Exercises</h3>
<p>The following exercises use <a href="https://datascienceuwl.github.io/statlens" target="_blank">StatLens</a>, an interactive statistics tool. Each exercise includes a link that opens a pre-loaded dataset — explore, interact, and answer the questions.</p>
<ol start="10" type="1">
<li><p><strong>Which chart for categorical data?</strong> Open the <a href="https://datascienceuwl.github.io/statlens/explore/one-cat/?dataset=jury&amp;labels=names" class="open-in-statlens" target="_blank" aria-label="Explore jury data in StatLens">jury racial composition data</a> in StatLens. This dataset records the race of 275 jurors from a county. The chart opens with numeric labels hidden so you can focus on the visual patterns.</p>
<ol type="a">
<li><p>Start with the <strong>bar chart</strong>. Using only the bar heights, rank the four racial groups from most to least represented. Which group is clearly the largest?</p></li>
<li><p>Switch to a <strong>pie chart</strong>. Try to rank the four groups from largest to smallest using only the visual size of each slice. Is it easier or harder than with the bar chart? Check the <strong>Show values</strong> box to reveal the numbers — how close was your ranking?</p></li>
<li><p>Switch to a <strong>waffle chart</strong> (uncheck <strong>Show values</strong> first). Count the squares for the White group to estimate their percentage. Then check <strong>Show values</strong> to see the actual number. Is estimating percentages easier from the waffle chart or the pie chart? Why?</p></li>
<li><p>If a community advocacy group wanted to argue that the jury pool does not reflect the racial makeup of the county, which chart type would make the strongest visual case? Explain your reasoning.</p></li>
</ol></li>
</ol>
<ol start="11" type="1">
<li><p><strong>Detecting association in a two-way table.</strong> Open the <a href="https://datascienceuwl.github.io/statlens/explore/categorical/?dataset=heart_transplant" class="open-in-statlens" target="_blank" aria-label="Explore heart transplant data in StatLens">heart transplant data</a> in StatLens. This dataset records whether patients in a heart transplant study were in the treatment group (received a transplant) or the control group, and whether they survived or died.</p>
<ol type="a">
<li><p>Look at the <strong>contingency table</strong> (counts). How many patients received a transplant? How many survived overall? How many patients both received a transplant and survived?</p></li>
<li><p>Switch the table to <strong>Row Proportions</strong>. What proportion of the treatment group survived? What proportion of the control group survived? Based on these proportions, does there appear to be an association between receiving a transplant and survival?</p></li>
<li><p>Now switch to <strong>Column Proportions</strong>. Among those who survived, what proportion were in the treatment group? Why does this answer a different question than what you found in part (b)?</p></li>
<li><p>View the data as a <strong>100% Stacked</strong> bar chart. If group assignment and survival were independent (not associated), what would the bar chart look like? Describe how the actual chart differs from that independent scenario.</p></li>
</ol></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-survey:raiseTaxes:2015" class="csl-entry" role="listitem">
Polling, Public Policy. 2015. <span>“Americans on College Degrees, Classic Literature, the Seasons, and More, Data Collected Feb 20-22, 2015.”</span> <a href="http://www.openintro.org/redirect.php?go=textbook-PPP_30215">http://www.openintro.org/redirect.php?go=textbook-PPP_30215</a>.
</div>
<div id="ref-Turnbull+Brown+Hu:1974" class="csl-entry" role="listitem">
Turnbull, B., B. Brown, and M. Hu. 1974. <span>“Survivorship of Heart Transplant Data.”</span> <em>Journal of the American Statistical Association</em> 69: 74–80. <a href="https://doi.org/10.1080/01621459.1974.10480130">https://doi.org/10.1080/01621459.1974.10480130</a>.
</div>
<div id="ref-survey:blmWaPoScar:2020" class="csl-entry" role="listitem">
Washington Post. 2020. <span>“Washington Post-Schar School National Poll, Data Collected June 2-7, 2020.”</span> <a href="http://www.openintro.org/redirect.php?go=exercise-wapo-2020-blm-poll">http://www.openintro.org/redirect.php?go=exercise-wapo-2020-blm-poll</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/study-design.html" class="pagination-link" aria-label="Data Collection and Study Design">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/describing-distributions.html" class="pagination-link" aria-label="Exploring Quantitative Data">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>