<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>24&nbsp; Expected Value and Variance – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/binomial.html" rel="next">
<link href="../chapters/random-variables.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-c76bc2edb0e532e390ad582fcbf98d52.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-975f4eb663ddd4de51f5ac11eb3fbb8a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d90903f2ca6eb1a33c5609737f932d54.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-v.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/expected-value.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decision-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/expected-value.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statlens-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatLens Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-expected-value" id="toc-sec-expected-value" class="nav-link active" data-scroll-target="#sec-expected-value"><span class="header-section-number">24.1</span> Expected value of a random variable</a>
  <ul class="collapse">
  <li><a href="#the-expected-value-as-a-center-of-gravity" id="toc-the-expected-value-as-a-center-of-gravity" class="nav-link" data-scroll-target="#the-expected-value-as-a-center-of-gravity"><span class="header-section-number">24.1.1</span> The expected value as a center of gravity</a></li>
  </ul></li>
  <li><a href="#sec-variance-rv" id="toc-sec-variance-rv" class="nav-link" data-scroll-target="#sec-variance-rv"><span class="header-section-number">24.2</span> Variance of a random variable</a></li>
  <li><a href="#sec-ev-properties" id="toc-sec-ev-properties" class="nav-link" data-scroll-target="#sec-ev-properties"><span class="header-section-number">24.3</span> Properties of expected value</a></li>
  <li><a href="#sec-var-properties" id="toc-sec-var-properties" class="nav-link" data-scroll-target="#sec-var-properties"><span class="header-section-number">24.4</span> Properties of variance</a></li>
  <li><a href="#sec-linear-combinations" id="toc-sec-linear-combinations" class="nav-link" data-scroll-target="#sec-linear-combinations"><span class="header-section-number">24.5</span> Linear combinations of random variables</a>
  <ul class="collapse">
  <li><a href="#expected-value-of-a-linear-combination" id="toc-expected-value-of-a-linear-combination" class="nav-link" data-scroll-target="#expected-value-of-a-linear-combination"><span class="header-section-number">24.5.1</span> Expected value of a linear combination</a></li>
  <li><a href="#variance-of-a-linear-combination" id="toc-variance-of-a-linear-combination" class="nav-link" data-scroll-target="#variance-of-a-linear-combination"><span class="header-section-number">24.5.2</span> Variance of a linear combination</a></li>
  <li><a href="#why-variances-add-even-when-we-subtract" id="toc-why-variances-add-even-when-we-subtract" class="nav-link" data-scroll-target="#why-variances-add-even-when-we-subtract"><span class="header-section-number">24.5.3</span> Why variances add even when we subtract</a></li>
  </ul></li>
  <li><a href="#sec-ch16-review" id="toc-sec-ch16-review" class="nav-link" data-scroll-target="#sec-ch16-review"><span class="header-section-number">24.6</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">24.6.1</span> Summary</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">24.7</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-v.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/expected-value.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Extended Content.</strong> This chapter extends beyond UWL’s core STAT 145 curriculum. It is included for completeness and for instructors who wish to cover additional topics. Content is in draft form.</p>
</div>
</div>
</div>
<div class="chapterintro">
<p>How much revenue should a bookstore expect per student? How much variability should a stock investor anticipate in their portfolio? These questions require us to summarize a random variable’s distribution with just two numbers: its <strong>expected value</strong> (center) and <strong>variance</strong> (spread). In this chapter, we define these quantities, develop useful computational properties, and extend them to linear combinations of random variables. These tools will be essential when we study the binomial and normal distributions in the chapters that follow.</p>
</div>
<section id="sec-expected-value" class="level2" data-number="24.1">
<h2 data-number="24.1" class="anchored" data-anchor-id="sec-expected-value"><span class="header-section-number">24.1</span> Expected value of a random variable</h2>
<p>We introduced random variables in the random variables chapter. Now we develop the tools to summarize them numerically, starting with the expected value — the long-run average of a random variable.</p>
<div class="workedexample">
<p>Two books are assigned for a statistics class: a textbook ($137) and a study guide ($33). From past experience, the bookstore knows that 20% of enrolled students buy neither book, 55% buy the textbook only, and 25% buy both books. If there are 100 students enrolled, how many books should the bookstore expect to sell?</p>
<p>About 20 students buy 0 books, 55 buy 1 book (55 books total), and 25 buy 2 books (50 books total). The bookstore should expect to sell about <span class="math inline">\(0 + 55 + 50 = 105\)</span> books.</p>
</div>
<div class="workedexample">
<p>What is the average revenue per student?</p>
<p>The expected total revenue is <span class="math inline">\(\$0 \times 20 + \$137 \times 55 + \$170 \times 25 = \$11{,}785\)</span>, and there are 100 students. The expected revenue per student is <span class="math inline">\(\$11{,}785 / 100 = \$117.85\)</span>.</p>
</div>
<p>Notice that the “average revenue per student” was computed by multiplying each outcome by its probability and summing:</p>
<p><span class="math display">\[0 \times 0.20 + 137 \times 0.55 + 170 \times 0.25 = 117.85\]</span></p>
<p>This is the <strong>expected value</strong> of the random variable <span class="math inline">\(X\)</span>.</p>
<div class="definition">
<p><strong>Expected value of a discrete random variable.</strong> If <span class="math inline">\(X\)</span> takes outcomes <span class="math inline">\(x_1, x_2, \ldots, x_k\)</span> with probabilities <span class="math inline">\(P(X = x_1), P(X = x_2), \ldots, P(X = x_k)\)</span>, the <strong>expected value</strong> of <span class="math inline">\(X\)</span> is:</p>
<p><span class="math display">\[E(X) = x_1 \cdot P(X = x_1) + x_2 \cdot P(X = x_2) + \cdots + x_k \cdot P(X = x_k) = \sum_{i=1}^{k} x_i \, P(X = x_i)\]</span></p>
<p>The Greek letter <span class="math inline">\(\mu\)</span> may be used in place of <span class="math inline">\(E(X)\)</span>.</p>
</div>
<p>The expected value represents the <strong>long-run average</strong> of the random variable. If we were to observe the random process many, many times, the average of all observed values would converge to <span class="math inline">\(E(X)\)</span>.</p>
<section id="the-expected-value-as-a-center-of-gravity" class="level3 original" data-number="24.1.1">
<h3 data-number="24.1.1" class="anchored" data-anchor-id="the-expected-value-as-a-center-of-gravity"><span class="header-section-number">24.1.1</span> The expected value as a center of gravity</h3>
<p>In physics, the expected value corresponds to the <strong>center of gravity</strong> (or balance point) of a distribution. Imagine cutting out the shape of a probability distribution from a piece of cardboard. The expected value is the point where you could balance the cutout on the tip of your finger. This is why we sometimes call <span class="math inline">\(E(X)\)</span> the “mean” — it is exactly analogous to the sample mean <span class="math inline">\(\bar{x}\)</span>, but for a probability distribution rather than a data set.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-expected-value-balance" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A bar balanced on a fulcrum at the position 117.85, with weights at positions 0, 137, and 170 proportional to the probabilities 0.20, 0.55, and 0.25.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-expected-value-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="expected-value_files/figure-html/fig-expected-value-balance-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;24.1: A weight system representing the bookstore distribution balanced at the mean of $117.85."><img src="expected-value_files/figure-html/fig-expected-value-balance-1.png" class="img-fluid figure-img" alt="A bar balanced on a fulcrum at the position 117.85, with weights at positions 0, 137, and 170 proportional to the probabilities 0.20, 0.55, and 0.25." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-expected-value-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.1: A weight system representing the bookstore distribution balanced at the mean of $117.85.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<div class="guidedpractice">
<p>A campus shuttle arrives every 10 minutes. The number of students boarding follows this distribution:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(x\)</span></th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P(X = x)\)</span></td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
<p>What is the expected number of students who board?</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(E(X) = 0(0.10) + 1(0.25) + 2(0.35) + 3(0.20) + 4(0.10) = 0 + 0.25 + 0.70 + 0.60 + 0.40 = 1.95\)</span>. On average, about 1.95 students board the shuttle at this stop.
</details>
</div>
<div class="caution">
<p>The expected value does not have to be a value that the random variable can actually take. In the shuttle example, <span class="math inline">\(E(X) = 1.95\)</span>, but you can never have 1.95 students board. The expected value is a long-run average, not a prediction of any single outcome.</p>
</div>
</section>
<section id="sec-variance-rv" class="level2" data-number="24.2">
<h2 data-number="24.2" class="anchored" data-anchor-id="sec-variance-rv"><span class="header-section-number">24.2</span> Variance of a random variable</h2>
<p>The expected value tells us where the center of a distribution lies, but it says nothing about the <em>spread</em>. The bookstore might want to know not just the average revenue per student, but how much that revenue varies from student to student.</p>
<div class="definition">
<p><strong>Variance of a discrete random variable.</strong> If <span class="math inline">\(X\)</span> takes outcomes <span class="math inline">\(x_1, \ldots, x_k\)</span> with probabilities <span class="math inline">\(P(X = x_1), \ldots, P(X = x_k)\)</span> and expected value <span class="math inline">\(\mu = E(X)\)</span>, then the <strong>variance</strong> of <span class="math inline">\(X\)</span> is:</p>
<p><span class="math display">\[\text{Var}(X) = \sigma^2 = \sum_{i=1}^{k} (x_i - \mu)^2 \, P(X = x_i)\]</span></p>
<p>The <strong>standard deviation</strong> is <span class="math inline">\(\sigma = \sqrt{\text{Var}(X)}\)</span>.</p>
</div>
<p>The variance is the average squared deviation from the mean, weighted by the probabilities. The standard deviation has the same units as <span class="math inline">\(X\)</span>, which makes it more interpretable.</p>
<div class="workedexample">
<p>Compute the variance and standard deviation of the bookstore revenue per student.</p>
<p>We organize the calculation in a table with <span class="math inline">\(\mu = 117.85\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(x_1 = 0\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_2 = 137\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_3 = 170\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P(X = x_i)\)</span></td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x_i - \mu\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-117.85\)</span></td>
<td style="text-align: center;"><span class="math inline">\(19.15\)</span></td>
<td style="text-align: center;"><span class="math inline">\(52.15\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((x_i - \mu)^2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(13{,}888.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(366.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2{,}719.6\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\((x_i - \mu)^2 \cdot P(X = x_i)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2{,}777.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(201.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(679.9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3{,}659.3\)</span></td>
</tr>
</tbody>
</table>
<p>The variance is <span class="math inline">\(\sigma^2 = 3{,}659.3\)</span> and the standard deviation is <span class="math inline">\(\sigma = \sqrt{3{,}659.3} = \$60.49\)</span>.</p>
</div>
<div class="guidedpractice">
<p>The bookstore also sells a chemistry textbook ($159) and supplement ($41). From past experience, 15% of chemistry students buy neither, 25% buy the textbook only, and 60% buy both. Let <span class="math inline">\(Y\)</span> be the revenue from a single chemistry student. (a) Write out the probability distribution of <span class="math inline">\(Y\)</span>. (b) Compute <span class="math inline">\(E(Y)\)</span>. (c) Compute <span class="math inline">\(\text{SD}(Y)\)</span>.</p>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><span class="math inline">\(Y\)</span> takes values $0, $159, $200 with probabilities 0.15, 0.25, 0.60. (b) <span class="math inline">\(E(Y) = 0(0.15) + 159(0.25) + 200(0.60) = 0 + 39.75 + 120 = \$159.75\)</span>. (c) <span class="math inline">\(\text{Var}(Y) = (0 - 159.75)^2(0.15) + (159 - 159.75)^2(0.25) + (200 - 159.75)^2(0.60) = 3828.0 + 0.1 + 972.0 = 4800.1\)</span>, so <span class="math inline">\(\text{SD}(Y) = \sqrt{4800.1} \approx \$69.28\)</span>.</li>
</ol>
</details>
</div>
</section>
<section id="sec-ev-properties" class="level2" data-number="24.3">
<h2 data-number="24.3" class="anchored" data-anchor-id="sec-ev-properties"><span class="header-section-number">24.3</span> Properties of expected value</h2>
<div class="original">
<p>The expected value has several important algebraic properties that make it easy to work with. These properties follow from the definition but are worth stating explicitly because we will use them frequently.</p>
<div class="important">
<p><strong>Properties of expected value.</strong> For a random variable <span class="math inline">\(X\)</span> and constants <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>:</p>
<ol type="1">
<li><strong>Adding a constant shifts the mean</strong>: <span class="math inline">\(E(X + b) = E(X) + b\)</span></li>
<li><strong>Multiplying by a constant scales the mean</strong>: <span class="math inline">\(E(aX) = a \cdot E(X)\)</span></li>
<li><strong>General linear transformation</strong>: <span class="math inline">\(E(aX + b) = a \cdot E(X) + b\)</span></li>
</ol>
</div>
<p><strong>Why these make sense:</strong> If every student’s textbook cost increases by $10 (adding a constant <span class="math inline">\(b = 10\)</span>), then the average cost also increases by $10. If the bookstore marks up all prices by 20% (multiplying by <span class="math inline">\(a = 1.20\)</span>), then the average revenue also increases by 20%.</p>
<div class="workedexample">
<p>Suppose the bookstore offers a 10% discount to students who buy both books. The discounted price is <span class="math inline">\(0.90 \times X\)</span>, where <span class="math inline">\(X\)</span> is the original price. What is the expected revenue per student under the discount?</p>
<p>Using the property <span class="math inline">\(E(aX) = aE(X)\)</span>:</p>
<p><span class="math display">\[E(0.90X) = 0.90 \times E(X) = 0.90 \times 117.85 = \$106.07\]</span></p>
<p>The expected revenue per student drops from $117.85 to $106.07.</p>
</div>
<div class="guidedpractice">
<p>The bookstore charges a flat $5 processing fee in addition to book costs. If <span class="math inline">\(X\)</span> is the cost of books and the total charge is <span class="math inline">\(Y = X + 5\)</span>, what is <span class="math inline">\(E(Y)\)</span>?</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(E(Y) = E(X + 5) = E(X) + 5 = 117.85 + 5 = \$122.85\)</span>.
</details>
</div>
</div>
</section>
<section id="sec-var-properties" class="level2" data-number="24.4">
<h2 data-number="24.4" class="anchored" data-anchor-id="sec-var-properties"><span class="header-section-number">24.4</span> Properties of variance</h2>
<div class="original">
<p>Variance has different algebraic properties than expected value. The most important distinction: adding a constant does not change the variance.</p>
<div class="important">
<p><strong>Properties of variance.</strong> For a random variable <span class="math inline">\(X\)</span> and constants <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>:</p>
<ol type="1">
<li><strong>Adding a constant does not change variance</strong>: <span class="math inline">\(\text{Var}(X + b) = \text{Var}(X)\)</span></li>
<li><strong>Multiplying by a constant scales variance by the square</strong>: <span class="math inline">\(\text{Var}(aX) = a^2 \cdot \text{Var}(X)\)</span></li>
<li><strong>General linear transformation</strong>: <span class="math inline">\(\text{Var}(aX + b) = a^2 \cdot \text{Var}(X)\)</span></li>
</ol>
<p>For standard deviations:</p>
<p><span class="math display">\[\text{SD}(aX + b) = |a| \cdot \text{SD}(X)\]</span></p>
</div>
<p><strong>Why adding a constant does not change variance:</strong> If every student pays $5 more, the <em>spread</em> of payments does not change — everyone’s payment shifts by the same amount. The center moves, but the variability stays the same.</p>
<p><strong>Why multiplying scales by the square:</strong> If every price is doubled (<span class="math inline">\(a = 2\)</span>), then deviations from the mean are also doubled, so <em>squared</em> deviations are multiplied by <span class="math inline">\(2^2 = 4\)</span>.</p>
<div class="workedexample">
<p>For the bookstore revenue with <span class="math inline">\(\text{Var}(X) = 3{,}659.3\)</span> and <span class="math inline">\(\sigma_X = \$60.49\)</span>:</p>
<ul>
<li>If a $5 fee is added: <span class="math inline">\(\text{Var}(X + 5) = \text{Var}(X) = 3{,}659.3\)</span> and <span class="math inline">\(\text{SD}(X+5) = \$60.49\)</span>.</li>
<li>If a 10% discount is applied: <span class="math inline">\(\text{Var}(0.90X) = 0.90^2 \times 3{,}659.3 = 0.81 \times 3{,}659.3 = 2{,}964.0\)</span> and <span class="math inline">\(\text{SD}(0.90X) = 0.90 \times 60.49 = \$54.44\)</span>.</li>
</ul>
</div>
<div class="guidedpractice">
<p>Suppose temperatures in Celsius are converted to Fahrenheit using <span class="math inline">\(F = 1.8C + 32\)</span>. If the standard deviation of daily high temperatures is <span class="math inline">\(\sigma_C = 5^\circ\text{C}\)</span>, what is the standard deviation in Fahrenheit?</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(\text{SD}(1.8C + 32) = 1.8 \times \text{SD}(C) = 1.8 \times 5 = 9^\circ\text{F}\)</span>. The additive constant 32 does not affect the spread.
</details>
</div>
</div>
</section>
<section id="sec-linear-combinations" class="level2" data-number="24.5">
<h2 data-number="24.5" class="anchored" data-anchor-id="sec-linear-combinations"><span class="header-section-number">24.5</span> Linear combinations of random variables</h2>
<p>Sometimes the total outcome is best described as a sum of several random variables. For instance, a person’s total weekly commute time is the sum of five daily commute times.</p>
<div class="definition">
<p>A <strong>linear combination</strong> of random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is an expression of the form <span class="math inline">\(aX + bY\)</span>, where <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are fixed constants.</p>
</div>
<div class="workedexample">
<p>John travels to work five days a week. Let <span class="math inline">\(X_i\)</span> represent his travel time on day <span class="math inline">\(i\)</span>. His total weekly commute time is:</p>
<p><span class="math display">\[W = X_1 + X_2 + X_3 + X_4 + X_5\]</span></p>
<p>If the average daily commute is 18 minutes, the expected weekly total is:</p>
<p><span class="math display">\[E(W) = E(X_1) + E(X_2) + \cdots + E(X_5) = 18 + 18 + 18 + 18 + 18 = 90 \text{ minutes}\]</span></p>
</div>
<section id="expected-value-of-a-linear-combination" class="level3" data-number="24.5.1">
<h3 data-number="24.5.1" class="anchored" data-anchor-id="expected-value-of-a-linear-combination"><span class="header-section-number">24.5.1</span> Expected value of a linear combination</h3>
<div class="important">
<p><strong>Expected value of a linear combination.</strong> For random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> with constants <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>:</p>
<p><span class="math display">\[E(aX + bY) = a \cdot E(X) + b \cdot E(Y)\]</span></p>
<p>This generalizes to any number of random variables:</p>
<p><span class="math display">\[E(a_1 X_1 + a_2 X_2 + \cdots + a_k X_k) = a_1 E(X_1) + a_2 E(X_2) + \cdots + a_k E(X_k)\]</span></p>
<p>This property holds whether or not the random variables are independent.</p>
</div>
<div class="guidedpractice">
<p>Elena is selling a TV at auction (expected profit <span class="math inline">\(X\)</span>: $175) and buying a toaster oven (expected cost <span class="math inline">\(Y\)</span>: $23). Her net gain is <span class="math inline">\(X - Y\)</span>. What is her expected net gain?</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(E(X - Y) = E(X) - E(Y) = 175 - 23 = \$152\)</span>.
</details>
</div>
<div class="workedexample">
<p>Leonard has invested $6,000 in Caterpillar stock (CAT) and $2,000 in Exxon Mobil stock (XOM). If <span class="math inline">\(X\)</span> represents CAT’s monthly percentage return (in decimal form) and <span class="math inline">\(Y\)</span> represents XOM’s return, his portfolio change is <span class="math inline">\(6000X + 2000Y\)</span>. If <span class="math inline">\(E(X) = 0.020\)</span> and <span class="math inline">\(E(Y) = 0.002\)</span>:</p>
<p><span class="math display">\[E(6000X + 2000Y) = 6000 \times 0.020 + 2000 \times 0.002 = \$124\]</span></p>
<p>Leonard expects to gain $124 per month on average.</p>
</div>
</section>
<section id="variance-of-a-linear-combination" class="level3" data-number="24.5.2">
<h3 data-number="24.5.2" class="anchored" data-anchor-id="variance-of-a-linear-combination"><span class="header-section-number">24.5.2</span> Variance of a linear combination</h3>
<div class="important">
<p><strong>Variance of a linear combination (independent case).</strong> If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <strong>independent</strong> random variables, then:</p>
<p><span class="math display">\[\text{Var}(aX + bY) = a^2 \cdot \text{Var}(X) + b^2 \cdot \text{Var}(Y)\]</span></p>
<p>The standard deviation is: <span class="math inline">\(\text{SD}(aX + bY) = \sqrt{a^2 \text{Var}(X) + b^2 \text{Var}(Y)}\)</span>.</p>
</div>
<div class="caution">
<p><strong>Independence is required for the variance formula.</strong> The formula <span class="math inline">\(\text{Var}(aX + bY) = a^2\text{Var}(X) + b^2\text{Var}(Y)\)</span> is only valid when <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent. If the variables are not independent, an additional covariance term is needed.</p>
<p>However, the expected value formula <span class="math inline">\(E(aX + bY) = aE(X) + bE(Y)\)</span> always holds, regardless of independence.</p>
</div>
<div class="workedexample">
<p>John’s daily commute has a standard deviation of 4 minutes, and the commute times for different days are independent. What is the standard deviation of his weekly commute time <span class="math inline">\(W = X_1 + X_2 + X_3 + X_4 + X_5\)</span>?</p>
<p>Each coefficient is 1, and <span class="math inline">\(\text{Var}(X_i) = 4^2 = 16\)</span>:</p>
<p><span class="math display">\[\text{Var}(W) = 1^2(16) + 1^2(16) + 1^2(16) + 1^2(16) + 1^2(16) = 5 \times 16 = 80\]</span></p>
<p><span class="math display">\[\text{SD}(W) = \sqrt{80} \approx 8.94 \text{ minutes}\]</span></p>
<p>Notice that the standard deviation of the sum (8.94 minutes) is <em>not</em> five times the daily standard deviation (which would be 20 minutes). Variabilities do not add up as simply as means do — we must add <em>variances</em>, not standard deviations.</p>
</div>
<div class="workedexample">
<p>Leonard’s portfolio has <span class="math inline">\(\text{Var}(X) = 0.0057\)</span> and <span class="math inline">\(\text{Var}(Y) = 0.0021\)</span> (where the stocks are approximately independent). What is the standard deviation of his monthly return?</p>
<p><span class="math display">\[\text{Var}(6000X + 2000Y) = 6000^2 \times 0.0057 + 2000^2 \times 0.0021 = 205{,}200 + 8{,}400 = 213{,}600\]</span></p>
<p><span class="math display">\[\text{SD} = \sqrt{213{,}600} \approx \$462\]</span></p>
<p>While an average monthly return of $124 sounds nice, a standard deviation of $462 means the returns are highly volatile.</p>
</div>
<div class="guidedpractice">
<p>Elena’s TV sale has <span class="math inline">\(\text{SD}(X) = \$25\)</span> and her toaster oven purchase has <span class="math inline">\(\text{SD}(Y) = \$8\)</span>. Assuming the auctions are independent, compute the standard deviation of her net gain <span class="math inline">\(X - Y\)</span>.</p>
<details>
<summary>
Show answer
</summary>
Note that <span class="math inline">\(X - Y = 1 \cdot X + (-1) \cdot Y\)</span>. So <span class="math inline">\(\text{Var}(X - Y) = 1^2 \times 25^2 + (-1)^2 \times 8^2 = 625 + 64 = 689\)</span>. Thus <span class="math inline">\(\text{SD}(X - Y) = \sqrt{689} \approx \$26.25\)</span>. The negative coefficient is eliminated when we square it — subtracting a random variable introduces <em>more</em> variability, not less.
</details>
</div>
</section>
<section id="why-variances-add-even-when-we-subtract" class="level3 original" data-number="24.5.3">
<h3 data-number="24.5.3" class="anchored" data-anchor-id="why-variances-add-even-when-we-subtract"><span class="header-section-number">24.5.3</span> Why variances add even when we subtract</h3>
<p>A common source of confusion: the variance of a difference is the <em>sum</em> of the variances (not the difference). This makes sense intuitively. If you buy a bag of apples and a bag of oranges, the uncertainty in the total weight is a combination of both uncertainties — regardless of whether you are adding or subtracting the weights. Two sources of randomness always create more total uncertainty.</p>
</section>
</section>
<section id="sec-ch16-review" class="level2" data-number="24.6">
<h2 data-number="24.6" class="anchored" data-anchor-id="sec-ch16-review"><span class="header-section-number">24.6</span> Chapter review</h2>
<section id="summary" class="level3" data-number="24.6.1">
<h3 data-number="24.6.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">24.6.1</span> Summary</h3>
<ul>
<li>The <strong>expected value</strong> <span class="math inline">\(E(X) = \sum x_i P(X = x_i)\)</span> is the long-run average of a random variable.</li>
<li>The <strong>variance</strong> <span class="math inline">\(\text{Var}(X) = \sum (x_i - \mu)^2 P(X = x_i)\)</span> measures spread; the <strong>standard deviation</strong> is <span class="math inline">\(\sigma = \sqrt{\text{Var}(X)}\)</span>.</li>
<li><strong>Expected value properties</strong>: <span class="math inline">\(E(aX + b) = aE(X) + b\)</span> (always holds).</li>
<li><strong>Variance properties</strong>: <span class="math inline">\(\text{Var}(aX + b) = a^2 \text{Var}(X)\)</span> (adding a constant does not change variance).</li>
<li><strong>Linear combinations</strong>: <span class="math inline">\(E(aX + bY) = aE(X) + bE(Y)\)</span> (always). <span class="math inline">\(\text{Var}(aX + bY) = a^2\text{Var}(X) + b^2\text{Var}(Y)\)</span> (requires independence).</li>
<li>Variances always add, even when random variables are subtracted.</li>
</ul>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="24.7">
<h2 class="exercises anchored" data-number="24.7" data-anchor-id="exercises"><span class="header-section-number">24.7</span> Exercises</h2>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _03-ex-random-variables, _03-ex-review -->
<ol type="1">
<li><strong>Portfolio return.</strong> A portfolio’s value increases by 18% during a financial boom and by 9% during normal times. It decreases by 12% during a recession. What is the expected return on this portfolio if each scenario is equally likely? </li>
</ol>
<ol start="2" type="1">
<li><strong>Baggage fees.</strong> An airline charges the following baggage fees: $25 for the first bag and $35 for the second. Suppose 54% of passengers have no checked luggage, 34% have one piece of checked luggage and 12% have two pieces. We suppose a negligible portion of people check more than two bags.</li>
</ol>
<ol type="a">
<li><p>Build a probability model, compute the average revenue per passenger, and compute the corresponding standard deviation.</p></li>
<li><p>About how much revenue should the airline expect for a flight of 120 passengers? With what standard deviation? Note any assumptions you make and if you think they are justified. </p></li>
</ol>
<ol start="3" type="1">
<li><strong>American roulette.</strong> The game of American roulette involves spinning a wheel with 38 slots: 18 red, 18 black, and 2 green. A ball is spun onto the wheel and will eventually land in a slot, where each slot has an equal chance of capturing the ball. Gamblers can place bets on red or black. If the ball lands on their color, they double their money. If it lands on another color, they lose their money. Suppose you bet $1 on red. What’s the expected value and standard deviation of your winnings? </li>
</ol>
<ol start="4" type="1">
<li><strong>One big bet vs many small bets.</strong> A college basketball player makes 55% of her free throws. Consider a game where you bet on her next attempt: if she makes the shot you win the amount you bet; if she misses you lose that amount.</li>
</ol>
<ol type="a">
<li><p><strong>Setup A.</strong> You place a single $3 bet on one free throw. Find the expected value and standard deviation of your winnings <span class="math inline">\(W_A\)</span>.</p></li>
<li><p><strong>Setup B.</strong> You place three independent $1 bets, one on each of three free-throw attempts. Find the expected value and standard deviation of your total winnings <span class="math inline">\(W_B\)</span>.</p></li>
<li><p>Compare your answers to parts (a) and (b). What does the comparison say about the riskiness of concentrating a stake in one large bet versus splitting it across several small ones?</p></li>
</ol>
<ol start="5" type="1">
<li><strong>Cost of breakfast.</strong> Sally gets a cup of coffee and a muffin every day for breakfast from one of the many coffee shops in her neighborhood. She picks a coffee shop each morning at random and independently of previous days. The average price of a cup of coffee is $1.40 with a standard deviation of 30¢ ($0.30), the average price of a muffin is $2.50 with a standard deviation of 15¢, and the two prices are independent of each other.</li>
</ol>
<ol type="a">
<li><p>What is the mean and standard deviation of the amount she spends on breakfast daily?</p></li>
<li><p>What is the mean and standard deviation of the amount she spends on breakfast weekly (7 days)? </p></li>
</ol>
<ol start="6" type="1">
<li><strong>Scooping ice cream.</strong> Ice cream usually comes in 1.5 quart boxes (48 fluid ounces), and ice cream scoops hold about 2 ounces. However, there is some variability in the amount of ice cream in a box as well as the amount of ice cream scooped out. We represent the amount of ice cream in the box as <span class="math inline">\(X\)</span> and the amount scooped out as <span class="math inline">\(Y\)</span>. Suppose these random variables have the following means, standard deviations, and variances:</li>
</ol>
<div class="line-block"><span class="math inline">\(Y\)</span> | 2 | 0.25 | 0.0625 |</div>
<ol type="a">
<li><p>An entire box of ice cream, plus 3 scoops from a second box is served at a party. How much ice cream do you expect to have been served at this party? What is the standard deviation of the amount of ice cream served?</p></li>
<li><p>How much ice cream would you expect to be left in the box after scooping out one scoop of ice cream? That is, find the expected value of <span class="math inline">\(X-Y\)</span>. What is the standard deviation of the amount left in the box?</p></li>
<li><p>Using the context of this exercise, explain why we add variances when we subtract one random variable from another. </p></li>
</ol>
<ol start="7" type="1">
<li><strong>Variance of a mean, Part I.</strong> Suppose <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are independent observations from a population with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2 = 25\)</span>. Let <span class="math inline">\(\bar{X} = (X_1 + X_2)/2\)</span>.</li>
</ol>
<ol type="a">
<li><p>Compute <span class="math inline">\(\text{Var}(X_1 + X_2)\)</span> and <span class="math inline">\(\text{Var}(\bar{X})\)</span>.</p></li>
<li><p>In general (for any <span class="math inline">\(\sigma^2\)</span>), which formula gives <span class="math inline">\(\text{Var}(\bar{X})\)</span> when <span class="math inline">\(n = 2\)</span>? </p></li>
</ol>
<ol start="8" type="1">
<li><strong>Variance of a mean, Part II.</strong> Now suppose <span class="math inline">\(X_1, X_2, X_3\)</span> are independent observations from a population with variance <span class="math inline">\(\sigma^2 = 25\)</span>. Let <span class="math inline">\(\bar{X} = (X_1 + X_2 + X_3)/3\)</span>.</li>
</ol>
<ol type="a">
<li><p>Compute <span class="math inline">\(\text{Var}(\bar{X})\)</span>.</p></li>
<li><p>Compared to Part I (where <span class="math inline">\(n = 2\)</span>), as the sample size <span class="math inline">\(n\)</span> increases, what happens to <span class="math inline">\(\text{Var}(\bar{X})\)</span>?</p></li>
<li><p>For a sample of size <span class="math inline">\(n\)</span> from this same population, what is the smallest <span class="math inline">\(n\)</span> that guarantees <span class="math inline">\(\text{SD}(\bar{X}) \le 1\)</span>? </p></li>
</ol>
<ol start="9" type="1">
<li><strong>Variance of a mean, Part III.</strong> Generalize Parts I and II. Suppose <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are independent observations from a population with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>, and let <span class="math inline">\(\bar{X} = (1/n) \sum_{i=1}^n X_i\)</span>.</li>
</ol>
<ol type="a">
<li><p>Which formula gives <span class="math inline">\(\text{Var}(\bar{X})\)</span>?</p></li>
<li><p>Suppose <span class="math inline">\(\sigma^2 = 36\)</span> and <span class="math inline">\(n = 16\)</span>. Compute <span class="math inline">\(\text{Var}(\bar{X})\)</span> and <span class="math inline">\(\text{SD}(\bar{X})\)</span>.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/random-variables.html" class="pagination-link" aria-label="Random Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/binomial.html" class="pagination-link" aria-label="Binomial Distribution">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>