<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Linear Regression – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/prediction-model-fit.html" rel="next">
<link href="../chapters/correlation.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-c76bc2edb0e532e390ad582fcbf98d52.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-975f4eb663ddd4de51f5ac11eb3fbb8a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d90903f2ca6eb1a33c5609737f932d54.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iv.html">Apply</a></li><li class="breadcrumb-item"><a href="../chapters/linear-regression.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decision-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linear-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Type II Error and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statlens-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatLens Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-fitting-line" id="toc-sec-fitting-line" class="nav-link active" data-scroll-target="#sec-fitting-line"><span class="header-section-number">20.1</span> Fitting a line to data</a>
  <ul class="collapse">
  <li><a href="#using-linear-regression-to-predict-possum-head-lengths" id="toc-using-linear-regression-to-predict-possum-head-lengths" class="nav-link" data-scroll-target="#using-linear-regression-to-predict-possum-head-lengths"><span class="header-section-number">20.1.1</span> Using linear regression to predict possum head lengths</a></li>
  </ul></li>
  <li><a href="#sec-residuals" id="toc-sec-residuals" class="nav-link" data-scroll-target="#sec-residuals"><span class="header-section-number">20.2</span> Residuals</a>
  <ul class="collapse">
  <li><a href="#residual-plots" id="toc-residual-plots" class="nav-link" data-scroll-target="#residual-plots"><span class="header-section-number">20.2.1</span> Residual plots</a></li>
  </ul></li>
  <li><a href="#sec-least-squares" id="toc-sec-least-squares" class="nav-link" data-scroll-target="#sec-least-squares"><span class="header-section-number">20.3</span> Least squares regression</a>
  <ul class="collapse">
  <li><a href="#the-objective-minimize-squared-residuals" id="toc-the-objective-minimize-squared-residuals" class="nav-link" data-scroll-target="#the-objective-minimize-squared-residuals"><span class="header-section-number">20.3.1</span> The objective: minimize squared residuals</a></li>
  <li><a href="#interpreting-the-slope-and-intercept" id="toc-interpreting-the-slope-and-intercept" class="nav-link" data-scroll-target="#interpreting-the-slope-and-intercept"><span class="header-section-number">20.3.2</span> Interpreting the slope and intercept</a></li>
  <li><a href="#computing-the-slope-and-intercept-from-summary-statistics" id="toc-computing-the-slope-and-intercept-from-summary-statistics" class="nav-link" data-scroll-target="#computing-the-slope-and-intercept-from-summary-statistics"><span class="header-section-number">20.3.3</span> Computing the slope and intercept from summary statistics</a></li>
  </ul></li>
  <li><a href="#sec-r-squared" id="toc-sec-r-squared" class="nav-link" data-scroll-target="#sec-r-squared"><span class="header-section-number">20.4</span> R-squared</a></li>
  <li><a href="#sec-inference-slope" id="toc-sec-inference-slope" class="nav-link" data-scroll-target="#sec-inference-slope"><span class="header-section-number">20.5</span> Inference for the slope</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">20.5.1</span> Hypotheses</a></li>
  <li><a href="#randomization-test-for-the-slope" id="toc-randomization-test-for-the-slope" class="nav-link" data-scroll-target="#randomization-test-for-the-slope"><span class="header-section-number">20.5.2</span> Randomization test for the slope</a></li>
  <li><a href="#mathematical-model-the-t-test-for-slope" id="toc-mathematical-model-the-t-test-for-slope" class="nav-link" data-scroll-target="#mathematical-model-the-t-test-for-slope"><span class="header-section-number">20.5.3</span> Mathematical model: the t-test for slope</a></li>
  <li><a href="#confidence-intervals-for-the-slope" id="toc-confidence-intervals-for-the-slope" class="nav-link" data-scroll-target="#confidence-intervals-for-the-slope"><span class="header-section-number">20.5.4</span> Confidence intervals for the slope</a></li>
  </ul></li>
  <li><a href="#sec-conditions-regression" id="toc-sec-conditions-regression" class="nav-link" data-scroll-target="#sec-conditions-regression"><span class="header-section-number">20.6</span> Conditions for linear regression</a></li>
  <li><a href="#sec-ch27-review" id="toc-sec-ch27-review" class="nav-link" data-scroll-target="#sec-ch27-review"><span class="header-section-number">20.7</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">20.7.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">20.7.2</span> Key terms</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">20.8</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iv.html">Apply</a></li><li class="breadcrumb-item"><a href="../chapters/linear-regression.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-warning no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Draft Chapter.</strong> This chapter is part of UWL’s STAT 145 curriculum and is under active development. Content is substantially complete but may undergo revisions. Feedback welcome.</p>
</div>
</div>
</div>
<div class="chapterintro">
<p>Linear regression is a powerful statistical technique for describing the relationship between two quantitative variables. Many people have some familiarity with regression just from reading the news, where straight lines are overlaid on scatterplots. In this chapter, we build on the ideas of correlation from the previous chapter to develop the least squares regression line. We learn how to interpret the slope and intercept, use residuals to assess model fit, quantify the strength of the model with <span class="math inline">\(R^2\)</span>, and perform inference on the slope to test whether a linear relationship exists in the population.</p>
</div>
<section id="sec-fitting-line" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="sec-fitting-line"><span class="header-section-number">20.1</span> Fitting a line to data</h2>
<p>Linear regression is the statistical method for fitting a line to data where the relationship between two variables, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, can be modeled by a straight line with some error:</p>
<p><span class="math display">\[y = b_0 + b_1 x + e\]</span></p>
<p>The values <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> represent the model’s <strong>intercept</strong> and <strong>slope</strong>, respectively, and the error is represented by <span class="math inline">\(e\)</span>. These values are calculated from the data – they are sample statistics. If the observed data are a random sample from a target population, these values are point estimates for the population parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>When we use <span class="math inline">\(x\)</span> to predict <span class="math inline">\(y\)</span>, we call <span class="math inline">\(x\)</span> the <strong>predictor</strong> variable (or explanatory variable) and <span class="math inline">\(y\)</span> the <strong>outcome</strong> variable (or response variable). We often write the model without the error term when focusing on the predicted average outcome:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_1 x\]</span></p>
<p>The “hat” on <span class="math inline">\(y\)</span> signifies that this is a predicted (estimated) value.</p>
<p>It is rare for all data to fall perfectly on a straight line. Instead, data more commonly appear as a cloud of points, where the trend may be strong or weak.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-three-relationships" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three scatterplots. The first shows a strong negative linear relationship, the second shows a moderate positive relationship, and the third shows almost no relationship.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-three-relationships-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-three-relationships-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;20.1: Three scatterplots with fabricated data showing a strong negative linear trend, a moderate positive linear trend, and a very weak trend."><img src="linear-regression_files/figure-html/fig-three-relationships-1.png" class="img-fluid figure-img" alt="Three scatterplots. The first shows a strong negative linear relationship, the second shows a moderate positive relationship, and the third shows almost no relationship." width="3000"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-three-relationships-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1: Three scatterplots with fabricated data showing a strong negative linear trend, a moderate positive linear trend, and a very weak trend.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are also cases where fitting a straight line is inappropriate, even if there is a clear relationship between the variables. When the relationship is nonlinear, a linear model can be misleading.</p>
<section id="using-linear-regression-to-predict-possum-head-lengths" class="level3" data-number="20.1.1">
<h3 data-number="20.1.1" class="anchored" data-anchor-id="using-linear-regression-to-predict-possum-head-lengths"><span class="header-section-number">20.1.1</span> Using linear regression to predict possum head lengths</h3>
<p>Researchers captured 104 brushtail possums in Australia and took body measurements. We consider total body length (cm) as the predictor to predict head length (mm).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-possum-regression" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatterplot with total length on the x-axis and head length on the y-axis, with a least squares line superimposed.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-possum-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-possum-regression-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;20.2: A scatterplot showing head length against total length for 104 brushtail possums, with a linear model fit to the data."><img src="linear-regression_files/figure-html/fig-possum-regression-1.png" class="img-fluid figure-img" alt="A scatterplot with total length on the x-axis and head length on the y-axis, with a least squares line superimposed." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-possum-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.2: A scatterplot showing head length against total length for 104 brushtail possums, with a linear model fit to the data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The equation for this line is:</p>
<p><span class="math display">\[\hat{y} = 41 + 0.59x\]</span></p>
<p>We can use this line to make predictions. For instance, the equation predicts a possum with a total length of 80 cm will have a head length of:</p>
<p><span class="math display">\[\hat{y} = 41 + 0.59 \times 80 = 88.2 \text{ mm}\]</span></p>
<p>This estimate may be viewed as an average: the equation predicts that possums with a total length of 80 cm will have an average head length of 88.2 mm.</p>
</section>
</section>
<section id="sec-residuals" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="sec-residuals"><span class="header-section-number">20.2</span> Residuals</h2>
<p><strong>Residuals</strong> are the leftover variation in the data after accounting for the model fit:</p>
<p><span class="math display">\[\text{Data} = \text{Fit} + \text{Residual}\]</span></p>
<p>Each observation has a residual. If an observation is above the regression line, its residual is positive. If it is below the line, the residual is negative.</p>
<div class="important">
<p><strong>Residual: Difference between observed and expected.</strong></p>
<p>The residual of the <span class="math inline">\(i^{th}\)</span> observation <span class="math inline">\((x_i, y_i)\)</span> is the difference between the observed outcome and the predicted outcome:</p>
<p><span class="math display">\[e_i = y_i - \hat{y}_i\]</span></p>
<p>We identify <span class="math inline">\(\hat{y}_i\)</span> by plugging <span class="math inline">\(x_i\)</span> into the model.</p>
</div>
<div class="workedexample">
<p>The linear fit is <span class="math inline">\(\hat{y} = 41 + 0.59x\)</span>. Compute the residual for the observation <span class="math inline">\((76.0, 85.1)\)</span>.</p>
<hr>
<p>First compute the predicted value: <span class="math inline">\(\hat{y} = 41 + 0.59 \times 76.0 = 85.84\)</span>. The residual is <span class="math inline">\(e = 85.1 - 85.84 = -0.74\)</span> mm. The negative residual indicates that the model overpredicted head length for this possum.</p>
</div>
<div class="guidedpractice">
<p>If a model underestimates an observation, will the residual be positive or negative? What about if it overestimates?</p>
<details>
<summary>
Show answer
</summary>
If a model underestimates an observation, the residual is positive (the actual value exceeds the prediction). If it overestimates, the residual is negative.
</details>
</div>
<section id="residual-plots" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="residual-plots"><span class="header-section-number">20.2.1</span> Residual plots</h3>
<p>Residuals are helpful in evaluating how well a linear model fits a dataset. We display them in a <strong>residual plot</strong>, where the horizontal axis shows the predicted values and the vertical axis shows the residuals.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-possum-residuals" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A residual plot with predicted values on the x-axis and residuals on the y-axis, scattered randomly around the horizontal line at zero.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-possum-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-possum-residuals-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;20.3: A residual plot for the possum model. The residuals appear randomly scattered around zero with no obvious pattern."><img src="linear-regression_files/figure-html/fig-possum-residuals-1.png" class="img-fluid figure-img" alt="A residual plot with predicted values on the x-axis and residuals on the y-axis, scattered randomly around the horizontal line at zero." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-possum-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.3: A residual plot for the possum model. The residuals appear randomly scattered around zero with no obvious pattern.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="workedexample">
<p>What patterns should we look for in a residual plot?</p>
<hr>
<ul>
<li><strong>No pattern (good):</strong> Residuals scattered randomly around zero suggest the linear model is appropriate.</li>
<li><strong>Curved pattern (bad):</strong> A U-shape or other curve in the residuals indicates a nonlinear relationship that a straight line fails to capture.</li>
<li><strong>Fan shape (bad):</strong> Increasing or decreasing spread in the residuals indicates non-constant variability.</li>
</ul>
</div>
</section>
</section>
<section id="sec-least-squares" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="sec-least-squares"><span class="header-section-number">20.3</span> Least squares regression</h2>
<p>Fitting linear models by eye is subjective. <strong>Least squares regression</strong> provides an objective, rigorous approach.</p>
<section id="the-objective-minimize-squared-residuals" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="the-objective-minimize-squared-residuals"><span class="header-section-number">20.3.1</span> The objective: minimize squared residuals</h3>
<p>We want a line with small residuals. The <strong>least squares line</strong> minimizes the sum of the squared residuals:</p>
<p><span class="math display">\[e_1^2 + e_2^2 + \cdots + e_n^2\]</span></p>
<p>Why square the residuals rather than just sum their absolute values?</p>
<ol type="1">
<li>It is the most commonly used method.</li>
<li>It is widely supported in statistical software.</li>
<li>A residual twice as large is usually more than twice as bad. Squaring accounts for this.</li>
<li>The inference theory connecting the model to population parameters is most straightforward with least squares.</li>
</ol>
</section>
<section id="interpreting-the-slope-and-intercept" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="interpreting-the-slope-and-intercept"><span class="header-section-number">20.3.2</span> Interpreting the slope and intercept</h3>
<p>For the Elmhurst College data, the least squares line predicting gift aid (in $1,000s) from family income (in $1,000s) is:</p>
<p><span class="math display">\[\widehat{\text{aid}} = 24.3 - 0.0431 \times \text{family\_income}\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Term</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std. Error</th>
<th style="text-align: center;">T statistic</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td style="text-align: center;">24.32</td>
<td style="text-align: center;">1.29</td>
<td style="text-align: center;">18.83</td>
<td style="text-align: center;">&lt;0.0001</td>
</tr>
<tr class="even">
<td>family_income</td>
<td style="text-align: center;">-0.0431</td>
<td style="text-align: center;">0.0108</td>
<td style="text-align: center;">-3.98</td>
<td style="text-align: center;">0.0002</td>
</tr>
</tbody>
</table>
<div class="workedexample">
<p>What do the intercept and slope mean?</p>
<hr>
<p><strong>Slope (<span class="math inline">\(b_1 = -0.0431\)</span>):</strong> For each additional $1,000 of family income, we would expect a student to receive $43.10 less in gift aid, on average. The negative coefficient means higher income is associated with less aid. We must be cautious: this is an observational study, so we cannot interpret a causal connection.</p>
<p><strong>Intercept (<span class="math inline">\(b_0 = 24.32\)</span>):</strong> The model predicts that a student whose family has no income would receive $24,320 in gift aid, on average. This is meaningful because the family income for some students is near zero. In other applications, the intercept may have no practical meaning if <span class="math inline">\(x = 0\)</span> is outside the range of the data.</p>
</div>
<div class="important">
<p><strong>Interpreting parameters estimated by least squares.</strong></p>
<p>The <strong>slope</strong> describes the estimated difference in the predicted average outcome of <span class="math inline">\(y\)</span> if the predictor variable <span class="math inline">\(x\)</span> were one unit larger.</p>
<p>The <strong>intercept</strong> describes the average outcome of <span class="math inline">\(y\)</span> if <span class="math inline">\(x = 0\)</span>, provided the linear model is valid at <span class="math inline">\(x = 0\)</span> (which may not be the case if <span class="math inline">\(x = 0\)</span> is far outside the observed data range).</p>
</div>
</section>
<section id="computing-the-slope-and-intercept-from-summary-statistics" class="level3" data-number="20.3.3">
<h3 data-number="20.3.3" class="anchored" data-anchor-id="computing-the-slope-and-intercept-from-summary-statistics"><span class="header-section-number">20.3.3</span> Computing the slope and intercept from summary statistics</h3>
<p>The slope can be computed using the correlation and the standard deviations of the two variables:</p>
<p><span class="math display">\[b_1 = \frac{s_y}{s_x} \cdot r\]</span></p>
<p>The least squares line always passes through the point <span class="math inline">\((\bar{x}, \bar{y})\)</span>. Using the point-slope form:</p>
<p><span class="math display">\[b_0 = \bar{y} - b_1 \cdot \bar{x}\]</span></p>
<div class="important">
<p><strong>Identifying the least squares line from summary statistics.</strong></p>
<ul>
<li>Estimate the slope: <span class="math inline">\(b_1 = (s_y / s_x) \cdot r\)</span>.</li>
<li>Find the intercept using the fact that <span class="math inline">\((\bar{x}, \bar{y})\)</span> is on the line: <span class="math inline">\(b_0 = \bar{y} - b_1 \bar{x}\)</span>.</li>
</ul>
</div>
</section>
</section>
<section id="sec-r-squared" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="sec-r-squared"><span class="header-section-number">20.4</span> R-squared</h2>
<p>We evaluated the strength of a linear relationship using <span class="math inline">\(r\)</span>. More commonly, we describe the strength of a linear fit using <span class="math inline">\(R^2\)</span>, called <strong>R-squared</strong> or the <strong>coefficient of determination</strong>.</p>
<div class="important">
<p><strong>Coefficient of determination: proportion of variability explained by the model.</strong></p>
<p><span class="math inline">\(R^2\)</span> measures the proportion of variation in the outcome variable <span class="math inline">\(y\)</span> that is explained by the linear model with predictor <span class="math inline">\(x\)</span>. Since <span class="math inline">\(r\)</span> is always between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>, <span class="math inline">\(R^2\)</span> is always between 0 and 1.</p>
<p><span class="math display">\[R^2 = 1 - \frac{SSE}{SST}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(SST = \sum (y_i - \bar{y})^2\)</span> is the <strong>total sum of squares</strong>, measuring total variability in <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(SSE = \sum (y_i - \hat{y}_i)^2 = \sum e_i^2\)</span> is the <strong>sum of squared errors</strong>, measuring leftover variability after using the model.</li>
</ul>
<p>For simple linear regression, <span class="math inline">\(R^2 = r^2\)</span>.</p>
</div>
<div class="workedexample">
<p>For the Elmhurst data, the correlation is <span class="math inline">\(r = -0.499\)</span>. What proportion of the variability in gift aid is explained by family income?</p>
<hr>
<p><span class="math inline">\(R^2 = (-0.499)^2 = 0.249\)</span>, or about 25%. Family income explains about 25% of the variability in gift aid among these students.</p>
</div>
<div class="guidedpractice">
<p>If a linear model has a very strong negative relationship with <span class="math inline">\(r = -0.97\)</span>, how much of the variation in the outcome is explained by the predictor?</p>
<details>
<summary>
Show answer
</summary>
<span class="math inline">\(R^2 = (-0.97)^2 = 0.94\)</span>, or about 94% of the variation is explained.
</details>
</div>
<div class="statlens">
<p><strong>Explore the fit.</strong> Open the <a href="https://datascienceuwl.github.io/statlens/explore/regression/" target="_blank">Regression Explorer</a> to see the least-squares line, residual plot, and <span class="math inline">\(r\)</span> / <span class="math inline">\(R^2\)</span> for a dataset — or fit a line by hand in the <a href="https://datascienceuwl.github.io/statlens/explore/regression-by-eye/" target="_blank">Regression by Eye</a> lab. For inference on the slope, the <a href="https://datascienceuwl.github.io/statlens/inference/slope/" target="_blank">Slope <span class="math inline">\(t\)</span>-Test</a> reports the test and confidence interval for <span class="math inline">\(\beta_1\)</span>.</p>
</div>
</section>
<section id="sec-inference-slope" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="sec-inference-slope"><span class="header-section-number">20.5</span> Inference for the slope</h2>
<p>We have been computing sample statistics <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, but these are estimates of population parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. We now turn to formal inference: testing whether a linear relationship exists in the population.</p>
<section id="hypotheses" class="level3" data-number="20.5.1">
<h3 data-number="20.5.1" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">20.5.1</span> Hypotheses</h3>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span>. There is no linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\beta_1 \ne 0\)</span>. There is a linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</li>
</ul>
</section>
<section id="randomization-test-for-the-slope" class="level3" data-number="20.5.2">
<h3 data-number="20.5.2" class="anchored" data-anchor-id="randomization-test-for-the-slope"><span class="header-section-number">20.5.2</span> Randomization test for the slope</h3>
<p>If the null hypothesis is true (<span class="math inline">\(\beta_1 = 0\)</span>), then <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are not linearly related. We can simulate this by <strong>permuting</strong> the response variable: randomly shuffling the <span class="math inline">\(y\)</span> values while keeping the <span class="math inline">\(x\)</span> values fixed. This breaks any relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-permutation-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots side by side. The left shows the original data with a positive trend. The right shows permuted data with no trend.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permutation-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-permutation-comparison-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;20.4: Original data showing a positive linear relationship between weeks of gestation and birth weight, alongside the same data after permuting the weight variable, which destroys the relationship."><img src="linear-regression_files/figure-html/fig-permutation-comparison-1.png" class="img-fluid figure-img" alt="Two scatterplots side by side. The left shows the original data with a positive trend. The right shows permuted data with no trend." width="3000"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permutation-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.4: Original data showing a positive linear relationship between weeks of gestation and birth weight, alongside the same data after permuting the weight variable, which destroys the relationship.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By repeating the permutation many times and computing the slope each time, we build a null distribution of slopes.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null-slopes" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of permuted slopes centered at zero, ranging from about -0.15 to +0.15. The observed slope of 0.335 is far to the right of the distribution.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-null-slopes-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;20.5: Histogram of slopes from 1,000 permutations of birth weight. The permuted slopes range from about -0.15 to +0.15, centered at zero. The observed slope of 0.335 is far from this distribution."><img src="linear-regression_files/figure-html/fig-null-slopes-1.png" class="img-fluid figure-img" alt="Histogram of permuted slopes centered at zero, ranging from about -0.15 to +0.15. The observed slope of 0.335 is far to the right of the distribution." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.5: Histogram of slopes from 1,000 permutations of birth weight. The permuted slopes range from about <span class="math inline">\(-0.15\)</span> to <span class="math inline">\(+0.15\)</span>, centered at zero. The observed slope of 0.335 is far from this distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The observed slope of 0.335 is far from any value in the null distribution. We reject <span class="math inline">\(H_0\)</span> and conclude there is a linear relationship between weeks of gestation and birth weight.</p>
</section>
<section id="mathematical-model-the-t-test-for-slope" class="level3" data-number="20.5.3">
<h3 data-number="20.5.3" class="anchored" data-anchor-id="mathematical-model-the-t-test-for-slope"><span class="header-section-number">20.5.3</span> Mathematical model: the t-test for slope</h3>
<p>When the technical conditions are met, we can use the <span class="math inline">\(t\)</span>-distribution to test the slope:</p>
<p><span class="math display">\[T = \frac{b_1 - 0}{SE_{b_1}}\]</span></p>
<p>This <span class="math inline">\(T\)</span>-statistic follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = n - 2\)</span>.</p>
<div class="workedexample">
<p>The regression output for predicting the change in House seats for the President’s party from the unemployment rate is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Term</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std. Error</th>
<th style="text-align: center;">T statistic</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td style="text-align: center;">-7.36</td>
<td style="text-align: center;">5.16</td>
<td style="text-align: center;">-1.43</td>
<td style="text-align: center;">0.1649</td>
</tr>
<tr class="even">
<td>unemp</td>
<td style="text-align: center;">-0.89</td>
<td style="text-align: center;">0.835</td>
<td style="text-align: center;">-1.07</td>
<td style="text-align: center;">0.2961</td>
</tr>
</tbody>
</table>
<p>The p-value of 0.2961 is not discernible. The data do not provide convincing evidence that the unemployment rate is a useful predictor of midterm election outcomes.</p>
</div>
</section>
<section id="confidence-intervals-for-the-slope" class="level3" data-number="20.5.4">
<h3 data-number="20.5.4" class="anchored" data-anchor-id="confidence-intervals-for-the-slope"><span class="header-section-number">20.5.4</span> Confidence intervals for the slope</h3>
<div class="important">
<p><strong>Confidence intervals for model coefficients.</strong></p>
<p>Confidence intervals for model coefficients can be computed using the <span class="math inline">\(t\)</span>-distribution:</p>
<p><span class="math display">\[b_1 \pm t_{df}^* \times SE_{b_1}\]</span></p>
<p>where <span class="math inline">\(t_{df}^*\)</span> is the critical value corresponding to the confidence level, with <span class="math inline">\(df = n - 2\)</span>.</p>
</div>
<div class="workedexample">
<p>Using the Elmhurst College regression output (<span class="math inline">\(b_1 = -0.0431\)</span>, <span class="math inline">\(SE = 0.0108\)</span>, <span class="math inline">\(df = 48\)</span>), compute a 95% confidence interval for the slope.</p>
<hr>
<p>The critical value is <span class="math inline">\(t_{48}^* = 2.01\)</span>. The confidence interval is:</p>
<p><span class="math display">\[-0.0431 \pm 2.01 \times 0.0108 = (-0.0648, -0.0214)\]</span></p>
<p>We are 95% confident that for each additional $1,000 in family income, the university’s gift aid decreases by between $21.40 and $64.80 on average.</p>
</div>
</section>
</section>
<section id="sec-conditions-regression" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="sec-conditions-regression"><span class="header-section-number">20.6</span> Conditions for linear regression</h2>
<p>For the mathematical inference to be valid, we check four conditions, often remembered by the <strong>LINE</strong> mnemonic:</p>
<ul>
<li><strong>L – Linear model:</strong> The data should show a linear trend. Check the scatterplot and residual plot.</li>
<li><strong>I – Independent observations:</strong> Be cautious with time series data or clustered observations.</li>
<li><strong>N – Nearly normal residuals:</strong> Residuals should be approximately normally distributed. This is less critical for large samples (Central Limit Theorem), but outliers are always a concern.</li>
<li><strong>E – Equal variability:</strong> The variability of points around the line should be roughly constant across all values of <span class="math inline">\(x\)</span>. A “fan shape” in the residual plot indicates a violation.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagnostics-grid" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A grid of 2 by 4 plots showing four types of regression condition violations: nonlinearity, outlier, non-constant variance, and correlated observations.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostics-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="linear-regression_files/figure-html/fig-diagnostics-grid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;20.6: Four scatterplots and their residual plots showing common violations: nonlinearity, an outlier, increasing variability, and correlated observations."><img src="linear-regression_files/figure-html/fig-diagnostics-grid-1.png" class="img-fluid figure-img" alt="A grid of 2 by 4 plots showing four types of regression condition violations: nonlinearity, outlier, non-constant variance, and correlated observations." width="3600"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostics-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.6: Four scatterplots and their residual plots showing common violations: nonlinearity, an outlier, increasing variability, and correlated observations.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="important">
<p><strong>Diagnostics for linear regression.</strong></p>
<p>Independence is always important. The normality condition matters most for small samples. The constant variance condition is especially important for inference. The linearity condition is the most fundamental – if the true relationship is not linear, the slope estimate has no meaningful interpretation.</p>
</div>
</section>
<section id="sec-ch27-review" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="sec-ch27-review"><span class="header-section-number">20.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="20.7.1">
<h3 data-number="20.7.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">20.7.1</span> Summary</h3>
<p>In this chapter, we developed the least squares regression line as a tool for modeling the linear relationship between two quantitative variables. The slope describes the predicted change in <span class="math inline">\(y\)</span> for a one-unit increase in <span class="math inline">\(x\)</span>, and the intercept describes the predicted value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>. Residuals measure the difference between observed and predicted values, and residual plots help assess whether the linear model is appropriate. The coefficient of determination <span class="math inline">\(R^2\)</span> quantifies the proportion of variability in <span class="math inline">\(y\)</span> explained by the model. For inference, we use either a randomization test or the <span class="math inline">\(t\)</span>-distribution to test whether the slope is discernibly different from zero, and we can construct confidence intervals for the slope. The LINE conditions (linearity, independence, normality, equal variance) must be checked for the mathematical model to be valid.</p>
</section>
<section id="key-terms" class="level3" data-number="20.7.2">
<h3 data-number="20.7.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">20.7.2</span> Key terms</h3>
<ul>
<li>Predictor / outcome variable</li>
<li>Least squares line</li>
<li>Slope (<span class="math inline">\(b_1\)</span>) and intercept (<span class="math inline">\(b_0\)</span>)</li>
<li>Residual</li>
<li>Residual plot</li>
<li>R-squared (<span class="math inline">\(R^2\)</span>) / coefficient of determination</li>
<li>Total sum of squares (SST) / sum of squared errors (SSE)</li>
<li>T-test for slope</li>
<li>LINE conditions</li>
<li>Extrapolation</li>
</ul>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="20.8">
<h2 class="exercises anchored" data-number="20.8" data-anchor-id="exercises"><span class="header-section-number">20.8</span> Exercises</h2>
<p>Answers to odd-numbered exercises are provided inline.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _07-ex-model-slr, _24-ex-inf-model-slr -->
<ol type="1">
<li><strong>Units of regression.</strong> Consider a regression predicting the number of calories (cal) from width (cm) for a sample of square shaped chocolate brownies. What are the units of the correlation coefficient, the intercept, and the slope? </li>
</ol>
<ol start="2" type="1">
<li><strong>Which is higher?</strong> Determine if (I) or (II) is higher or if they are equal: “<em>For a regression line, the uncertainty associated with the slope estimate,</em> <span class="math inline">\(b_1\)</span><em>, is higher when (I) there is a lot of scatter around the regression line or (II) there is very little scatter around the regression line.</em>” Explain your reasoning. </li>
</ol>
<ol start="3" type="1">
<li><strong>The Coast Starlight, regression.</strong> The Coast Starlight Amtrak train runs from Seattle to Los Angeles. The scatterplot below displays the distance between each stop (in miles) and the amount of time it takes to travel from one stop to another (in minutes). The mean travel time from one stop to the next on the Coast Starlight is 129 mins, with a standard deviation of 113 minutes. The mean distance traveled from one stop to the next is 108 miles with a standard deviation of 99 miles. The correlation between travel time and distance is 0.636.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="linear-regression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Write the equation of the regression line for predicting travel time.</p></li>
<li><p>Interpret the slope and the intercept in this context.</p></li>
<li><p>Calculate <span class="math inline">\(R^2\)</span> of the regression line for predicting travel time from distance traveled for the Coast Starlight, and interpret <span class="math inline">\(R^2\)</span> in the context of the application.</p></li>
<li><p>The distance between Santa Barbara and Los Angeles is 103 miles. Use the model to estimate the time it takes for the Starlight to travel between these two cities.</p></li>
<li><p>It takes the Coast Starlight about 168 mins to travel from Santa Barbara to Los Angeles. Calculate the residual and explain the meaning of this residual value.</p></li>
<li><p>Suppose Amtrak is considering adding a stop to the Coast Starlight 500 miles away from Los Angeles. Would it be appropriate to use this linear model to predict the travel time from Los Angeles to this point? </p></li>
</ol>
<ol start="4" type="1">
<li><strong>Body measurements, regression.</strong> Researchers studying anthropometry collected body and skeletal diameter measurements, as well as age, weight, height and sex for 507 physically active individuals. The scatterplot below shows the relationship between height and shoulder girth (circumference of shoulders measured over deltoid muscles), both measured in centimeters. The mean shoulder girth is 107.20 cm with a standard deviation of 10.37 cm. The mean height is 171.14 cm with a standard deviation of 9.41 cm. The correlation between height and shoulder girth is 0.67. <span class="citation" data-cites="Heinz:2003">(<a href="#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="linear-regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Write the equation of the regression line for predicting height.</p></li>
<li><p>Interpret the slope and the intercept in this context.</p></li>
<li><p>Calculate <span class="math inline">\(R^2\)</span> of the regression line for predicting height from shoulder girth, and interpret it in the context of the application.</p></li>
<li><p>A randomly selected student from your class has a shoulder girth of 100 cm. Predict the height of this student using the model.</p></li>
<li><p>The student from part (d) is 160 cm tall. Calculate the residual, and explain what this residual means.</p></li>
<li><p>A one year old has a shoulder girth of 56 cm. Would it be appropriate to use this linear model to predict the height of this child? </p></li>
</ol>
<ol start="5" type="1">
<li><strong>Poverty and unemployment.</strong> The following scatterplot shows the relationship between percent of population below the poverty level (<code>poverty</code>) from unemployment rate among those ages 20-64 (<code>unemployment_rate</code>) in counties in the US, as provided by data from the 2019 American Community Survey. The regression output for the model for predicting <code>poverty</code> from <code>unemployment_rate</code> is also provided.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">4.604</td>
<td style="text-align: right; width: 5em;">0.349</td>
<td style="text-align: right; width: 5em;">13.182</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">unemployment_rate</td>
<td style="text-align: right; width: 5em;">2.054</td>
<td style="text-align: right; width: 5em;">0.062</td>
<td style="text-align: right; width: 5em;">33.110</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.45, 0.5]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="questions" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Write out the linear model.</p></li>
<li><p>Interpret the intercept.</p></li>
<li><p>Interpret the slope.</p></li>
<li><p>The <span class="math inline">\(R^2\)</span> of this model is 46%.<br>
Interpret this value.</p></li>
<li><p>Calculate the correlation coefficient.</p></li>
</ol>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="linear-regression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="6" type="1">
<li><strong>Cat weights.</strong> The following regression output is for predicting the heart weight (<code>Hwt</code>, in g) of cats from their body weight (<code>Bwt</code>, in kg). The coefficients are estimated using a dataset of 144 domestic cats.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-0.357</td>
<td style="text-align: right; width: 5em;">0.692</td>
<td style="text-align: right; width: 5em;">-0.515</td>
<td style="text-align: right; width: 5em;">0.6072</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">Bwt</td>
<td style="text-align: right; width: 5em;">4.034</td>
<td style="text-align: right; width: 5em;">0.250</td>
<td style="text-align: right; width: 5em;">16.119</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.45, 0.5]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="questions" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Write out the linear model.</p></li>
<li><p>Interpret the intercept.</p></li>
<li><p>Interpret the slope.</p></li>
<li><p>The <span class="math inline">\(R^2\)</span> of this model is 65%.<br>
Interpret <span class="math inline">\(R^2\)</span>.</p></li>
<li><p>Calculate the correlation coefficient.</p></li>
</ol>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="linear-regression_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="7" type="1">
<li><strong>Helmets and lunches.</strong> The scatterplot shows the relationship between socioeconomic status measured as the percentage of children in a neighborhood receiving reduced-fee lunches at school (<code>lunch</code>) and the percentage of bike riders in the neighborhood wearing helmets (<code>helmet</code>). The average percentage of children receiving reduced-fee lunches is 30.83% with a standard deviation of 26.72% and the average percentage of bike riders wearing helmets is 30.88% with a standard deviation of 16.95%.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-9-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="linear-regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>If the <span class="math inline">\(R^2\)</span> for the least-squares regression line for these data is 72%, what is the correlation between <code>lunch</code> and <code>helmet</code>?</p></li>
<li><p>Calculate the slope and intercept for the least-squares regression line for these data.</p></li>
<li><p>Interpret the intercept of the least-squares regression line in the context of the application.</p></li>
<li><p>Interpret the slope of the least-squares regression line in the context of the application.</p></li>
<li><p>What would the value of the residual be for a neighborhood where 40% of the children receive reduced-fee lunches and 40% of the bike riders wear helmets? Interpret the meaning of this residual in the context of the application.</p></li>
</ol>
<ol start="8" type="1">
<li><strong>Body measurements, randomization test.</strong> Researchers studying anthropometry collected body and skeletal diameter measurements, as well as age, weight, height and sex for 507 physically active individuals. A linear model is built to predict height based on shoulder girth (circumference of shoulders measured over deltoid muscles), both measured in centimeters. <span class="citation" data-cites="Heinz:2003">(<a href="#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span> Shown below are the linear model output for predicting height from shoulder girth and the histogram of slopes from 1,000 randomized datasets (1,000 times, <code>hgt</code> was permuted and regressed against <code>sho_gi</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</li>
</ol>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.6, 0.4]">
<div class="quarto-layout-row">
<div id="table" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 3em;">105.832</td>
<td style="text-align: right; width: 3em;">3.272</td>
<td style="text-align: right; width: 3em;">32.340</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">sho_gi</td>
<td style="text-align: right; width: 3em;">0.604</td>
<td style="text-align: right; width: 3em;">0.030</td>
<td style="text-align: right; width: 3em;">20.049</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="linear-regression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model predicting height from shoulder girth is differen than 0.</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like shoulder girth and height).</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion from the mathematical model? Explain your reasoning.</p></li>
</ol>
<ol start="9" type="1">
<li><strong>Baby’s weight and father’s age, randomization test.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby. <span class="citation" data-cites="data:births14">(<a href="#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span> Shown below are the linear model output for predicting baby’s weight (in pounds) from father’s age (in years) and the histogram of slopes from 1000 randomized datasets (1000 times, <code>weight</code> was permuted and regressed against <code>fage</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</li>
</ol>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.6, 0.4]">
<div class="quarto-layout-row">
<div id="table" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 3em;">7.101</td>
<td style="text-align: right; width: 3em;">0.199</td>
<td style="text-align: right; width: 3em;">35.674</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 3em;">0.005</td>
<td style="text-align: right; width: 3em;">0.006</td>
<td style="text-align: right; width: 3em;">0.757</td>
<td style="text-align: right; width: 3em;">0.4495</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="linear-regression_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model for predicting baby’s weight from father’s age is different than 0?</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like father’s age and weight of baby). What does the conclusion of your test say about whether the father’s age is a useful predictor of baby’s weight?</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion from the mathematical model? Explain your reasoning. </p></li>
</ol>
<ol start="10" type="1">
<li><strong>Body measurements, mathematical test.</strong> The scatterplot and least squares summary below show the relationship between weight measured in kilograms and height measured in centimeters of 507 physically active individuals. <span class="citation" data-cites="Heinz:2003">(<a href="#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></li>
</ol>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.4, 0.6]">
<div class="quarto-layout-row">
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="linear-regression_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="output" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 4em;">-105.01</td>
<td style="text-align: right; width: 4em;">7.54</td>
<td style="text-align: right; width: 3em;">-13.93</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em; font-family: monospace;">hgt</td>
<td style="text-align: right; width: 4em;">1.02</td>
<td style="text-align: right; width: 4em;">0.04</td>
<td style="text-align: right; width: 3em;">23.13</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>Describe the relationship between height and weight.</p></li>
<li><p>Write the equation of the regression line. Interpret the slope and intercept in context.</p></li>
<li><p>Do the data provide convincing evidence that the true slope parameter is different than 0? State the null and alternative hypotheses, report the p-value (using a mathematical model), and state your conclusion.</p></li>
<li><p>The correlation coefficient for height and weight is 0.72. Calculate <span class="math inline">\(R^2\)</span> and interpret it in context. </p></li>
</ol>
<ol start="11" type="1">
<li><strong>Baby’s weight and father’s age, mathematical test.</strong> Is the father’s age useful in predicting the baby’s weight? The scatterplot and least squares summary below show the relationship between baby’s weight (measured in pounds) and father’s age for a random sample of babies. <span class="citation" data-cites="data:births14">(<a href="#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span></li>
</ol>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.4, 0.6]">
<div class="quarto-layout-row">
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="linear-regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="output" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 4em;">7.1042</td>
<td style="text-align: right; width: 4em;">0.1936</td>
<td style="text-align: right; width: 3em;">36.6980</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 4em;">0.0047</td>
<td style="text-align: right; width: 4em;">0.0061</td>
<td style="text-align: right; width: 3em;">0.7794</td>
<td style="text-align: right; width: 3em;">0.4359</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What is the predicted weight of a baby whose father is 30 years old?</p></li>
<li><p>Do the data provide convincing evidence that the model for predicting baby weights from father’s age has a slope different than 0? State the null and alternative hypotheses, report the p-value (using a mathematical model), and state your conclusion.</p></li>
<li><p>Based on your conclusion, is father’s age a useful predictor of baby’s weight?</p></li>
</ol>
<ol start="12" type="1">
<li><strong>Body measurements, bootstrap percentile interval.</strong> In order to estimate the slope of the model predicting height based on shoulder girth (circumference of shoulders measured over deltoid muscles), 1,000 bootstrap samples are taken from a dataset of body measurements from 507 people. A linear model predicting height based on shoulder girth is fit to each bootstrap sample, and the slope is estimated. A histogram of these slopes is shown below. <span class="citation" data-cites="Heinz:2003">(<a href="#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="linear-regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap percentile method and the histogram above, find a 98% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem. </p></li>
</ol>
<ol start="13" type="1">
<li><strong>Baby’s weight and father’s age, bootstrap percentile interval.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby. Below is the bootstrap distribution of the slope statistic from 1,000 different bootstrap samples of the data. <span class="citation" data-cites="data:births14">(<a href="#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-19-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="linear-regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap percentile method and the histogram above, find a 95% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
<ol start="14" type="1">
<li><strong>Body measurements, standard error bootstrap interval.</strong> A linear model is built to predict height based on shoulder girth (circumference of shoulders measured over deltoid muscles), both measured in centimeters. <span class="citation" data-cites="Heinz:2003">(<a href="#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span> Shown below are the linear model output for predicting height from shoulder girth and the bootstrap distribution of the slope statistic from 1,000 different bootstrap samples of the data.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">105.832</td>
<td style="text-align: right; width: 5em;">3.272</td>
<td style="text-align: right; width: 5em;">32.340</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">sho_gi</td>
<td style="text-align: right; width: 5em;">0.604</td>
<td style="text-align: right; width: 5em;">0.030</td>
<td style="text-align: right; width: 5em;">20.049</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 98% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-21-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="linear-regression_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="15" type="1">
<li><strong>Baby’s weight and father’s age, standard error bootstrap interval.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby. <span class="citation" data-cites="data:births14">(<a href="#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span> Shown below are the linear model output for predicting baby’s weight (in pounds) from father’s age (in years) and the the bootstrap distribution of the slope statistic from 1000 different bootstrap samples of the data.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">7.101</td>
<td style="text-align: right; width: 5em;">0.199</td>
<td style="text-align: right; width: 5em;">35.674</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 5em;">0.005</td>
<td style="text-align: right; width: 5em;">0.006</td>
<td style="text-align: right; width: 5em;">0.757</td>
<td style="text-align: right; width: 5em;">0.4495</td>
</tr>
</tbody>
</table>


</div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 95% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-23-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19"><img src="linear-regression_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="16" type="1">
<li><strong>Murders and poverty, randomization test.</strong> The following regression output is for predicting annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas. Shown below are the linear model output for predicting annual murders per million from percentage living in poverty for metropolitan areas and the histogram of slopes from 1000 randomized datasets (1000 times, <code>annual_murders_per_mil</code> was permuted and regressed against <code>perc_pov</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.901</td>
<td style="text-align: right; width: 5em;">7.789</td>
<td style="text-align: right; width: 5em;">-3.839</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.559</td>
<td style="text-align: right; width: 5em;">0.390</td>
<td style="text-align: right; width: 5em;">6.562</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model for predicting annual murder rate from poverty percentage is different than 0?</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like murder rate and poverty).</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion which would have been obtained using the mathematical model? Explain your reasoning.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-25-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20"><img src="linear-regression_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="17" type="1">
<li><strong>Murders and poverty, mathematical test.</strong> The table below shows the output of a linear model annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.9012</td>
<td style="text-align: right; width: 5em;">7.7892</td>
<td style="text-align: right; width: 5em;">-3.8388</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.5594</td>
<td style="text-align: right; width: 5em;">0.3900</td>
<td style="text-align: right; width: 5em;">6.5623</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What are the hypotheses for evaluating whether the slope of the model predicting annual murder rate from poverty percentage is different than 0?</p></li>
<li><p>State the conclusion of the hypothesis test from part (a) in context. What does this say about whether poverty percentage is a useful predictor of annual murder rate?</p></li>
<li><p>Calculate a 95% confidence interval for the slope of poverty percentage, and interpret it in context.</p></li>
<li><p>Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning. </p></li>
</ol>
<ol start="18" type="1">
<li><strong>Murders and poverty, bootstrap percentile interval.</strong> Data on annual murders per million (<code>annual_murders_per_mil</code>) and percentage living in poverty (<code>perc_pov</code>) is collected from a random sample of 20 metropolitan areas. Using these data we want to estimate the slope of the model predicting <code>annual_murders_per_mil</code> from <code>perc_pov</code>. We take 1,000 bootstrap samples of the data and fit a linear model predicting <code>annual_murders_per_mil</code> from <code>perc_pov</code> to each bootstrap sample. A histogram of these slopes is shown below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-27-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21"><img src="linear-regression_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the percentile bootstrap method and the histogram above, find a 90% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
<ol start="19" type="1">
<li><strong>Murders and poverty, standard error bootstrap interval.</strong> A linear model is built to predict annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas. Shown below are the standard linear model output for predicting annual murders per million from percentage living in poverty for metropolitan areas and the bootstrap distribution of the slope statistic from 1000 different bootstrap samples of the data.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.901</td>
<td style="text-align: right; width: 5em;">7.789</td>
<td style="text-align: right; width: 5em;">-3.839</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.559</td>
<td style="text-align: right; width: 5em;">0.390</td>
<td style="text-align: right; width: 5em;">6.562</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-28-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22"><img src="linear-regression_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 90% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem. </p></li>
</ol>
<ol start="20" type="1">
<li><strong>I heart cats.</strong> Researchers collected data on heart and body weights of 144 domestic adult cats. The table below shows the output of a linear model predicting heart weight (measured in grams) from body weight (measured in kilograms) of these cats.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-0.3567</td>
<td style="text-align: right; width: 5em;">0.6923</td>
<td style="text-align: right; width: 5em;">-0.5152</td>
<td style="text-align: right; width: 5em;">0.6072</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">Bwt</td>
<td style="text-align: right; width: 5em;">4.0341</td>
<td style="text-align: right; width: 5em;">0.2503</td>
<td style="text-align: right; width: 5em;">16.1194</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>What are the hypotheses for evaluating whether body weight is positively associated with heart weight in cats?</p></li>
<li><p>State the conclusion of the hypothesis test from part (a) in context.</p></li>
<li><p>Calculate a 95% confidence interval for the slope of body weight, and interpret it in context.</p></li>
<li><p>Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning.</p></li>
</ol>
<ol start="21" type="1">
<li><strong>Beer and blood alcohol content.</strong> Many people believe that weight, drinking habits, and many other factors are much more important in predicting blood alcohol content (BAC) than simply considering the number of drinks a person consumed. Here we examine data from sixteen student volunteers at Ohio State University who each drank a randomly assigned number of cans of beer. These students were evenly divided between men and women, and they differed in weight and drinking habits. Thirty minutes later, a police officer measured their blood alcohol content (BAC) in grams of alcohol per deciliter of blood. The scatterplot and regression table summarize the findings. <span class="citation" data-cites="Malkevitc+Lesser:2008">(<a href="#ref-Malkevitc+Lesser:2008" role="doc-biblioref">Malkevitch and Lesser 2008</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="linear-regression_files/figure-html/unnamed-chunk-30-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23"><img src="linear-regression_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="2100"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-0.0127</td>
<td style="text-align: right; width: 5em;">0.0126</td>
<td style="text-align: right; width: 5em;">-1.0050</td>
<td style="text-align: right; width: 5em;">0.332</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">beers</td>
<td style="text-align: right; width: 5em;">0.0180</td>
<td style="text-align: right; width: 5em;">0.0024</td>
<td style="text-align: right; width: 5em;">7.4796</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Describe the relationship between the number of cans of beer and BAC.</p></li>
<li><p>Write the equation of the regression line. Interpret the slope and intercept in context.</p></li>
<li><p>Do the data provide convincing evidence that drinking more cans of beer is associated with an increase in blood alcohol? State the null and alternative hypotheses, report the p-value, and state your conclusion.</p></li>
<li><p>The correlation coefficient for number of cans of beer and BAC is 0.89. Calculate <span class="math inline">\(R^2\)</span> and interpret it in context.</p></li>
<li><p>Suppose we visit a bar in our own town, ask people how many drinks they have had, and also measure their BAC. Would the relationship between number of drinks and BAC would be as strong as the relationship found in the Ohio State study? Why? </p></li>
</ol>
<details class="dataset-sources">
<summary>
Dataset sources
</summary>
<small><a href="http://openintrostat.github.io/openintro/reference/coast_starlight.html"><code>coast_starlight</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/bdims.html"><code>bdims</code></a> (openintro) | <a href="http://openintrostat.github.io/usdata/reference/%20county_2019.html"><code>county_2019</code></a> (usdata) | <a href="https://cran.r-project.org/web/packages/MASS/MASS.pdf"><code>cats</code></a> (MASS) | <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> (openintro) | <a href="https://stat.ethz.ch/R-manual/R-patched/library/MASS/html/cats.html"><code>cats</code></a> (MASS) | <a href="http://openintrostat.github.io/openintro/reference/bac.html"><code>bac</code></a> (openintro)</small>
</details>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Heinz:2003" class="csl-entry" role="listitem">
Heinz, G., L. J. Peterson, R. W. Johnson, and C. J. Kerk. 2003. <span>“Exploring Relationships in Body Dimensions.”</span> <em>Journal of Statistics Education</em> 11 (2). <a href="http://www.openintro.org/redirect.php?go=textbook-body_dim_2003">http://www.openintro.org/redirect.php?go=textbook-body_dim_2003</a>.
</div>
<div id="ref-data:births14" class="csl-entry" role="listitem">
ICPSR. 2014. <span>“United States Department of Health and Human Services. Centers for Disease Control and Prevention. National Center for Health Statistics. Natality Detail File, 2014 United States. Inter-University Consortium for Political and Social Research, 2016-10-07.”</span> <a href="https://doi.org/10.3886/ICPSR36461.v1">https://doi.org/10.3886/ICPSR36461.v1</a>.
</div>
<div id="ref-Malkevitc+Lesser:2008" class="csl-entry" role="listitem">
Malkevitch, J., and L. M. Lesser. 2008. <em>For All Practical Purposes: Mathematical Literacy in Today’s World</em>. WH Freeman &amp; Co.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/correlation.html" class="pagination-link" aria-label="Correlation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/prediction-model-fit.html" class="pagination-link" aria-label="Prediction and Model Fit">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>