<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Normal Approximation – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/inference-proportions.html" rel="next">
<link href="../parts/part-iii.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-c76bc2edb0e532e390ad582fcbf98d52.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-fa71510ea4db812cff2b03fe3038c499.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-fd7030a8de49711e2ec3484694643bf1.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Unit 3: Compute</a></li><li class="breadcrumb-item"><a href="../chapters/normal-approximation.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 1: Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Explore</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Exploring a Distribution</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 2: Simulate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/randomization-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decision-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-simulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-simulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Simulate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 3: Compute</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-approximation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-calculate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-calculate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Compute</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Inference for Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Two Means</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 4: Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">ANOVA for Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-apply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-apply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Apply</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Several Means (ANOVA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Association Between Two Categorical Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-chisq-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Association Between Two Categorical Variables (AI version)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Fitting and Testing a Regression Line</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 5: Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">More About the Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Type II Error and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Foundations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../technology-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Technology Setup</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statlens-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">StatLens Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-normal-dist" id="toc-sec-normal-dist" class="nav-link active" data-scroll-target="#sec-normal-dist"><span class="header-section-number">11.1</span> The normal distribution</a>
  <ul class="collapse">
  <li><a href="#the-standard-normal-distribution" id="toc-the-standard-normal-distribution" class="nav-link" data-scroll-target="#the-standard-normal-distribution"><span class="header-section-number">11.1.1</span> The standard normal distribution</a></li>
  </ul></li>
  <li><a href="#sec-68-95-997" id="toc-sec-68-95-997" class="nav-link" data-scroll-target="#sec-68-95-997"><span class="header-section-number">11.2</span> The 68-95-99.7 rule</a></li>
  <li><a href="#sec-z-scores" id="toc-sec-z-scores" class="nav-link" data-scroll-target="#sec-z-scores"><span class="header-section-number">11.3</span> Z-scores and standardizing</a></li>
  <li><a href="#sec-normal-probs" id="toc-sec-normal-probs" class="nav-link" data-scroll-target="#sec-normal-probs"><span class="header-section-number">11.4</span> Finding probabilities from the normal distribution</a>
  <ul class="collapse">
  <li><a href="#left-tail-probabilities-percentiles" id="toc-left-tail-probabilities-percentiles" class="nav-link" data-scroll-target="#left-tail-probabilities-percentiles"><span class="header-section-number">11.4.1</span> Left-tail probabilities (percentiles)</a></li>
  <li><a href="#right-tail-probabilities" id="toc-right-tail-probabilities" class="nav-link" data-scroll-target="#right-tail-probabilities"><span class="header-section-number">11.4.2</span> Right-tail probabilities</a></li>
  <li><a href="#probabilities-between-two-values" id="toc-probabilities-between-two-values" class="nav-link" data-scroll-target="#probabilities-between-two-values"><span class="header-section-number">11.4.3</span> Probabilities between two values</a></li>
  <li><a href="#finding-values-from-percentiles" id="toc-finding-values-from-percentiles" class="nav-link" data-scroll-target="#finding-values-from-percentiles"><span class="header-section-number">11.4.4</span> Finding values from percentiles</a></li>
  <li><a href="#the-normal-probability-table" id="toc-the-normal-probability-table" class="nav-link" data-scroll-target="#the-normal-probability-table"><span class="header-section-number">11.4.5</span> The normal probability table</a></li>
  </ul></li>
  <li><a href="#sec-normal-approx-sampling" id="toc-sec-normal-approx-sampling" class="nav-link" data-scroll-target="#sec-normal-approx-sampling"><span class="header-section-number">11.5</span> The normal approximation to sampling distributions</a>
  <ul class="collapse">
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem"><span class="header-section-number">11.5.1</span> The Central Limit Theorem</a></li>
  <li><a href="#standard-error-quantifying-the-variability-of-a-statistic" id="toc-standard-error-quantifying-the-variability-of-a-statistic" class="nav-link" data-scroll-target="#standard-error-quantifying-the-variability-of-a-statistic"><span class="header-section-number">11.5.2</span> Standard error: quantifying the variability of a statistic</a></li>
  <li><a href="#connecting-simulation-and-normal-approximation" id="toc-connecting-simulation-and-normal-approximation" class="nav-link" data-scroll-target="#connecting-simulation-and-normal-approximation"><span class="header-section-number">11.5.3</span> Connecting simulation and normal approximation</a></li>
  <li><a href="#confidence-intervals-using-the-normal-model" id="toc-confidence-intervals-using-the-normal-model" class="nav-link" data-scroll-target="#confidence-intervals-using-the-normal-model"><span class="header-section-number">11.5.4</span> Confidence intervals using the normal model</a></li>
  </ul></li>
  <li><a href="#sec-normal-when" id="toc-sec-normal-when" class="nav-link" data-scroll-target="#sec-normal-when"><span class="header-section-number">11.6</span> When does the normal model apply – and when doesn’t it?</a></li>
  <li><a href="#sec-normal-approximation-review" id="toc-sec-normal-approximation-review" class="nav-link" data-scroll-target="#sec-normal-approximation-review"><span class="header-section-number">11.7</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">11.7.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">11.7.2</span> Key terms</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">11.8</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#statlens-exercises" id="toc-statlens-exercises" class="nav-link" data-scroll-target="#statlens-exercises">StatLens Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-iii.html">Unit 3: Compute</a></li><li class="breadcrumb-item"><a href="../chapters/normal-approximation.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normal Approximation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>In the randomization tests and bootstrap confidence intervals chapters, we used simulation-based methods to make inferences about population parameters. Those methods are powerful and flexible, but they share a limitation: every new problem requires running thousands of simulations. In this chapter, we introduce the <strong>normal distribution</strong>, a mathematical model that describes the bell-shaped pattern we keep seeing in our sampling distributions. When certain conditions are met, the normal distribution lets us calculate probabilities and construct confidence intervals using formulas instead of simulations. This is not a replacement for simulation-based thinking – it is a complement. The normal model provides the theoretical justification for <em>why</em> those simulations work the way they do.</p>
</div>
<section id="sec-normal-dist" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="sec-normal-dist"><span class="header-section-number">11.1</span> The normal distribution</h2>
<p>Among all the distributions encountered in statistics, one is overwhelmingly the most common. The symmetric, unimodal, bell-shaped curve is so ubiquitous that it goes by many names: the <strong>normal curve</strong>, the <strong>normal model</strong>, or the <strong>normal distribution</strong>.</p>
<div class="definition">
<p>The <strong>normal distribution</strong> is a symmetric, unimodal, bell-shaped distribution described by two <strong>parameters</strong>: the mean <span class="math inline">\(\mu\)</span> (which determines the center) and the standard deviation <span class="math inline">\(\sigma\)</span> (which determines the spread). We write the distribution in shorthand as <span class="math inline">\(N(\mu, \sigma)\)</span>.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-two-normal-curves" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two bell-shaped normal distribution curves side by side. The left curve is centered at 0 with a narrow spread (standard deviation 1). The right curve is centered at 19 with a wider spread (standard deviation 4). Both curves are symmetric and unimodal.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-normal-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="normal-approximation_files/figure-html/fig-two-normal-curves-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;11.1: Two normal distributions with different parameters. The left curve has μ = 0 and σ = 1; the right curve has μ = 19 and σ = 4. Changing μ shifts the curve left or right; changing σ stretches or compresses it. ↗ Try this live — vary μ and σ and watch the curve slide and rescale."><img src="normal-approximation_files/figure-html/fig-two-normal-curves-1.png" class="img-fluid figure-img" alt="Two bell-shaped normal distribution curves side by side. The left curve is centered at 0 with a narrow spread (standard deviation 1). The right curve is centered at 19 with a wider spread (standard deviation 4). Both curves are symmetric and unimodal." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-normal-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: Two normal distributions with different parameters. The left curve has μ = 0 and σ = 1; the right curve has μ = 19 and σ = 4. Changing μ shifts the curve left or right; changing σ stretches or compresses it. <a href="https://learnlens.org/statlens/conceptual/normal-distribution/">↗ Try this live</a> — vary μ and σ and watch the curve slide and rescale.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Key properties of the normal distribution:</p>
<ul>
<li>The curve is perfectly symmetric about the mean <span class="math inline">\(\mu\)</span>.</li>
<li>The total area under the curve is exactly 1 (representing 100% of observations). We can interpret any area under the curve as a <strong>proportion</strong> — and, equivalently, as the <strong>probability</strong> of a randomly selected observation falling in that range.</li>
<li>The tails extend infinitely in both directions but get very close to zero far from the center.</li>
<li>Changing <span class="math inline">\(\mu\)</span> shifts the entire curve left or right without changing its shape.</li>
<li>Increasing <span class="math inline">\(\sigma\)</span> makes the curve wider and shorter; decreasing <span class="math inline">\(\sigma\)</span> makes it narrower and taller.</li>
</ul>
<div class="important">
<p><strong>Normal distribution facts.</strong> Many variables are <em>nearly</em> normal, but none are <em>exactly</em> normal. The normal distribution, while not perfect for any single problem, is extremely useful for a wide variety of problems. Variables like SAT scores, adult heights, and blood pressure measurements closely follow the normal distribution.</p>
</div>
<section id="the-standard-normal-distribution" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="the-standard-normal-distribution"><span class="header-section-number">11.1.1</span> The standard normal distribution</h3>
<p>The normal distribution with mean <span class="math inline">\(\mu = 0\)</span> and standard deviation <span class="math inline">\(\sigma = 1\)</span> is called the <strong>standard normal distribution</strong>, written <span class="math inline">\(N(0, 1)\)</span>. It serves as a reference distribution that we will use throughout the course.</p>
<div class="workedexample">
<p>Write down the shorthand for a normal distribution with each set of parameters.</p>
<ol type="a">
<li>Mean 5 and standard deviation 3</li>
<li>Mean <span class="math inline">\(-100\)</span> and standard deviation 10</li>
<li>Mean 2 and standard deviation 9</li>
</ol>
<hr>
<ol type="a">
<li><span class="math inline">\(N(\mu = 5, \sigma = 3)\)</span></li>
<li><span class="math inline">\(N(\mu = -100, \sigma = 10)\)</span></li>
<li><span class="math inline">\(N(\mu = 2, \sigma = 9)\)</span></li>
</ol>
</div>
</section>
</section>
<section id="sec-68-95-997" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="sec-68-95-997"><span class="header-section-number">11.2</span> The 68-95-99.7 rule</h2>
<p>One of the most useful facts about the normal distribution is how observations spread out around the mean. This relationship is captured by the <strong>68-95-99.7 rule</strong> (sometimes called the <strong>empirical rule</strong>).</p>
<div class="definition">
<p><strong>The 68-95-99.7 rule.</strong> For any normal distribution <span class="math inline">\(N(\mu, \sigma)\)</span>:</p>
<ul>
<li>About <strong>68%</strong> of observations fall within <strong>1 standard deviation</strong> of the mean: between <span class="math inline">\(\mu - \sigma\)</span> and <span class="math inline">\(\mu + \sigma\)</span>.</li>
<li>About <strong>95%</strong> of observations fall within <strong>2 standard deviations</strong> of the mean: between <span class="math inline">\(\mu - 2\sigma\)</span> and <span class="math inline">\(\mu + 2\sigma\)</span>.</li>
<li>About <strong>99.7%</strong> of observations fall within <strong>3 standard deviations</strong> of the mean: between <span class="math inline">\(\mu - 3\sigma\)</span> and <span class="math inline">\(\mu + 3\sigma\)</span>.</li>
</ul>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-68-95-997" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A normal distribution curve with three nested shaded regions. The innermost region within one standard deviation of the mean is labeled 68 percent. The middle region within two standard deviations is spanned by a pink two-headed arrow labeled 95 percent. The outermost region within three standard deviations is spanned by a red two-headed arrow labeled 99.7 percent. The horizontal axis is labeled at mu minus three sigma through mu plus three sigma.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-68-95-997-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="normal-approximation_files/figure-html/fig-68-95-997-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;11.2: The 68-95-99.7 rule on a normal curve. About 68% of the area lies within μ ± σ, 95% within μ ± 2σ, and 99.7% within μ ± 3σ. Each labeled arrow bar spans exactly the region its percentage measures. ↗ Try this live — drag the cutlines to see the 68-95-99.7 boundaries live."><img src="normal-approximation_files/figure-html/fig-68-95-997-1.png" class="img-fluid figure-img" alt="A normal distribution curve with three nested shaded regions. The innermost region within one standard deviation of the mean is labeled 68 percent. The middle region within two standard deviations is spanned by a pink two-headed arrow labeled 95 percent. The outermost region within three standard deviations is spanned by a red two-headed arrow labeled 99.7 percent. The horizontal axis is labeled at mu minus three sigma through mu plus three sigma." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-68-95-997-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: The 68-95-99.7 rule on a normal curve. About 68% of the area lies within μ ± σ, 95% within μ ± 2σ, and 99.7% within μ ± 3σ. Each labeled arrow bar spans exactly the region its percentage measures. <a href="https://learnlens.org/statlens/conceptual/normal-distribution/">↗ Try this live</a> — drag the cutlines to see the 68-95-99.7 boundaries live.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This rule gives quick, approximate answers without needing a calculator or software.</p>
<div class="workedexample">
<p>SAT scores closely follow the normal distribution with mean <span class="math inline">\(\mu = 1500\)</span> and standard deviation <span class="math inline">\(\sigma = 300\)</span>.</p>
<ol type="a">
<li>About what percent of test takers score between 1200 and 1800?</li>
<li>About what percent score between 1500 and 2100?</li>
</ol>
<hr>
<ol type="a">
<li><p>1200 is one standard deviation below the mean (<span class="math inline">\(1500 - 300 = 1200\)</span>), and 1800 is one standard deviation above the mean (<span class="math inline">\(1500 + 300 = 1800\)</span>). By the 68-95-99.7 rule, about <strong>68%</strong> of test takers score between 1200 and 1800.</p></li>
<li><p>The range from 900 to 2100 covers <span class="math inline">\(\mu \pm 2\sigma\)</span>, which contains about 95% of scores. Since the normal distribution is symmetric, the range from 1500 to 2100 (the upper half) contains about <span class="math inline">\(\frac{95\%}{2} = 47.5\%\)</span> of scores.</p></li>
</ol>
</div>
<div class="guidedpractice">
<p>Adult male heights in the US follow approximately a normal distribution with mean 70 inches and standard deviation 3.3 inches. Using the 68-95-99.7 rule, approximately what percentage of adult males are between 63.4 and 76.6 inches tall?</p>
<details>
<summary>
Show answer
</summary>
63.4 inches is <span class="math inline">\(70 - 2(3.3) = 63.4\)</span> and 76.6 inches is <span class="math inline">\(70 + 2(3.3) = 76.6\)</span>. These are each 2 standard deviations from the mean, so by the 68-95-99.7 rule, approximately 95% of adult males have heights in this range.
</details>
</div>
<div class="guidedpractice">
<p>Continuing with SAT scores (<span class="math inline">\(\mu = 1500\)</span>, <span class="math inline">\(\sigma = 300\)</span>), about what percent of test takers score above 2100?</p>
<details>
<summary>
Show answer
</summary>
2100 is 2 standard deviations above the mean. By the 68-95-99.7 rule, about 95% of scores are within 2 standard deviations, leaving about 5% outside. Since the distribution is symmetric, about 2.5% are above 2100.
</details>
</div>
</section>
<section id="sec-z-scores" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="sec-z-scores"><span class="header-section-number">11.3</span> Z-scores and standardizing</h2>
<p>When comparing observations from different distributions, raw values are not directly comparable. A score of 1800 on the SAT and a score of 24 on the ACT look very different, but we need a common scale to determine which performance is better relative to other test takers. The solution is <strong>standardizing</strong> the observations.</p>
<div class="definition">
<p>The <strong>Z-score</strong> of an observation <span class="math inline">\(x\)</span> from a distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> is the number of standard deviations it falls above or below the mean:</p>
<p><span class="math display">\[Z = \frac{x - \mu}{\sigma}\]</span></p>
<ul>
<li>Positive Z-scores indicate observations <strong>above</strong> the mean.</li>
<li>Negative Z-scores indicate observations <strong>below</strong> the mean.</li>
<li>A Z-score of 0 means the observation equals the mean.</li>
</ul>
</div>
<div class="important">
<p>If the observation <span class="math inline">\(x\)</span> comes from a normal distribution <span class="math inline">\(N(\mu, \sigma)\)</span>, then its Z-score follows the standard normal distribution <span class="math inline">\(N(0, 1)\)</span>. Standardizing shifts the center to 0 and rescales the spread to 1, but preserves the normal shape.</p>
</div>
<div class="workedexample">
<p>SAT scores follow <span class="math inline">\(N(\mu = 1500, \sigma = 300)\)</span> and ACT scores follow <span class="math inline">\(N(\mu = 21, \sigma = 5)\)</span>. Nel scored 1800 on the SAT and Sian scored 24 on the ACT. Who performed better relative to other test takers?</p>
<hr>
<p>We compute Z-scores for each student.</p>
<p>Nel’s Z-score: <span class="math inline">\(Z_{\text{Nel}} = \frac{1800 - 1500}{300} = \frac{300}{300} = 1.00\)</span></p>
<p>Sian’s Z-score: <span class="math inline">\(Z_{\text{Sian}} = \frac{24 - 21}{5} = \frac{3}{5} = 0.60\)</span></p>
<p>Nel is 1 standard deviation above the SAT mean, while Sian is only 0.6 standard deviations above the ACT mean. Nel performed better relative to other test takers.</p>
</div>
<div class="guidedpractice">
<p>Head lengths of brushtail possums follow a nearly normal distribution with mean 92.6 mm and standard deviation 3.6 mm. Compute the Z-scores for possums with head lengths of 95.4 mm and 85.8 mm. Which possum has the more unusual head length?</p>
<details>
<summary>
Show answer
</summary>
For <span class="math inline">\(x_1 = 95.4\)</span> mm: <span class="math inline">\(Z_1 = \frac{95.4 - 92.6}{3.6} = \frac{2.8}{3.6} = 0.78\)</span>. For <span class="math inline">\(x_2 = 85.8\)</span> mm: <span class="math inline">\(Z_2 = \frac{85.8 - 92.6}{3.6} = \frac{-6.8}{3.6} = -1.89\)</span>. The second possum has a more unusual head length because <span class="math inline">\(|{-1.89}| &gt; |0.78|\)</span>.
</details>
</div>
<div class="workedexample">
<p>Let <span class="math inline">\(X\)</span> represent a value drawn at random from <span class="math inline">\(N(\mu = 3, \sigma = 2)\)</span>, and suppose we observe <span class="math inline">\(x = 5.19\)</span>.</p>
<ol type="a">
<li>Find the Z-score.</li>
<li>How many standard deviations above or below the mean is this observation?</li>
</ol>
<hr>
<ol type="a">
<li><p><span class="math inline">\(Z = \frac{x - \mu}{\sigma} = \frac{5.19 - 3}{2} = \frac{2.19}{2} = 1.095\)</span></p></li>
<li><p>The observation is 1.095 standard deviations <em>above</em> the mean. We know it is above because the Z-score is positive.</p></li>
</ol>
</div>
</section>
<section id="sec-normal-probs" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="sec-normal-probs"><span class="header-section-number">11.4</span> Finding probabilities from the normal distribution</h2>
<p>One of the most important skills in statistics is finding the probability that a normally distributed variable falls in a specified range. The idea is straightforward: <strong>area under the curve equals probability</strong>. You’ve already been doing this intuitively — in the randomization tests and bootstrap confidence intervals chapters, every time you counted “what fraction of simulated statistics were this extreme?” you were estimating a probability by looking at proportions in a distribution. The normal model just gives us a formula for the curve, so we can compute the area exactly instead of simulating it.</p>
<div class="important">
<p><strong>Strategy for normal probability problems.</strong> Always follow these steps:</p>
<ol type="1">
<li><strong>Draw a picture.</strong> Sketch the normal curve, mark the mean, and shade the area you want to find.</li>
<li><strong>Find the Z-score.</strong> Standardize the value(s) of interest using <span class="math inline">\(Z = \frac{x - \mu}{\sigma}\)</span>.</li>
<li><strong>Look up the area.</strong> Use a normal probability table, statistical software, or the StatLens Normal Distribution Explorer to find the area to the <strong>left</strong> of the Z-score.</li>
<li><strong>Adjust if needed.</strong> If you need a right-tail area, subtract the left-tail area from 1. For an area between two values, subtract the smaller left-tail area from the larger.</li>
</ol>
</div>
<section id="left-tail-probabilities-percentiles" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="left-tail-probabilities-percentiles"><span class="header-section-number">11.4.1</span> Left-tail probabilities (percentiles)</h3>
<p>The area to the left of a value on the normal curve gives the <strong>percentile</strong> – the proportion of observations that fall below that value.</p>
<div class="definition">
<p>The <strong>percentile</strong> of an observation is the percentage of values in the distribution that fall at or below that observation.</p>
</div>
<div class="workedexample">
<p>Nel scored 1800 on the SAT (<span class="math inline">\(Z = 1.00\)</span>). What percentile is this?</p>
<hr>
<p>We need the area to the left of <span class="math inline">\(Z = 1.00\)</span> on the standard normal curve.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-left-tail-z1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A standard normal distribution curve with the area to the left of z equals 1 shaded in blue. The shaded area represents approximately 84 percent of the distribution.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-left-tail-z1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="normal-approximation_files/figure-html/fig-normal-left-tail-z1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;11.3: The standard normal curve with the area to the left of Z = 1.00 shaded. This area represents Nel’s percentile. ↗ Try this live — drag the cutline to any Z value and read off the left-tail area."><img src="normal-approximation_files/figure-html/fig-normal-left-tail-z1-1.png" class="img-fluid figure-img" alt="A standard normal distribution curve with the area to the left of z equals 1 shaded in blue. The shaded area represents approximately 84 percent of the distribution." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-left-tail-z1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.3: The standard normal curve with the area to the left of Z = 1.00 shaded. This area represents Nel’s percentile. <a href="https://learnlens.org/statlens/conceptual/normal-distribution/">↗ Try this live</a> — drag the cutline to any Z value and read off the left-tail area.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Using a normal probability table or software, the area to the left of <span class="math inline">\(Z = 1.00\)</span> is <strong>0.8413</strong>. Nel is at the <strong>84th percentile</strong> – 84.13% of SAT takers scored lower.</p>
</div>
</section>
<section id="right-tail-probabilities" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="right-tail-probabilities"><span class="header-section-number">11.4.2</span> Right-tail probabilities</h3>
<div class="workedexample">
<p>Shannon is a randomly selected SAT taker. What is the probability Shannon scores at least 1630?</p>
<hr>
<p><strong>Step 1: Draw a picture.</strong> We shade the area above 1630 on the <span class="math inline">\(N(1500, 300)\)</span> curve.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-right-tail-1630" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A normal distribution curve centered at 1500 with a standard deviation of 300. The area to the right of 1630 is shaded, representing the probability of scoring at least 1630.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-right-tail-1630-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="normal-approximation_files/figure-html/fig-normal-right-tail-1630-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;11.4: A normal curve with mean 1500 and standard deviation 300. The area to the right of 1630 is shaded. ↗ Try this live — set μ, σ, and the cutline to reproduce this area."><img src="normal-approximation_files/figure-html/fig-normal-right-tail-1630-1.png" class="img-fluid figure-img" alt="A normal distribution curve centered at 1500 with a standard deviation of 300. The area to the right of 1630 is shaded, representing the probability of scoring at least 1630." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-right-tail-1630-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.4: A normal curve with mean 1500 and standard deviation 300. The area to the right of 1630 is shaded. <a href="https://learnlens.org/statlens/conceptual/normal-distribution/">↗ Try this live</a> — set μ, σ, and the cutline to reproduce this area.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Step 2: Find the Z-score.</strong></p>
<p><span class="math display">\[Z = \frac{1630 - 1500}{300} = \frac{130}{300} = 0.43\]</span></p>
<p><strong>Step 3: Look up the left-tail area.</strong> The area to the left of <span class="math inline">\(Z = 0.43\)</span> is 0.6664.</p>
<p><strong>Step 4: Adjust.</strong> The area to the <em>right</em> is <span class="math inline">\(1 - 0.6664 = 0.3336\)</span>.</p>
<p>The probability Shannon scores at least 1630 is <strong>0.3336</strong>, or about 33.4%.</p>
</div>
<div class="guidedpractice">
<p>If the probability of Shannon scoring at least 1630 is 0.3336, what is the probability Shannon scores <em>less than</em> 1630?</p>
<details>
<summary>
Show answer
</summary>
The probability of scoring less than 1630 is the area to the left: 0.6664, or about 66.6%. The left-tail and right-tail areas always sum to 1.
</details>
</div>
</section>
<section id="probabilities-between-two-values" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="probabilities-between-two-values"><span class="header-section-number">11.4.3</span> Probabilities between two values</h3>
<div class="workedexample">
<p>Adult male heights follow <span class="math inline">\(N(\mu = 70, \sigma = 3.3)\)</span> inches. What is the probability that a randomly selected adult male is between 5’9” (69 inches) and 6’2” (74 inches)?</p>
<hr>
<p><strong>Step 1: Draw a picture.</strong> Shade the area between 69 and 74 on the normal curve.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-between-69-74" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A normal distribution curve centered at 70 inches with standard deviation 3.3 inches. The area between 69 and 74 inches is shaded, representing the probability of being between those two heights.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-between-69-74-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="normal-approximation_files/figure-html/fig-normal-between-69-74-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;11.5: A normal curve centered at 70 with standard deviation 3.3. The area between 69 and 74 is shaded. ↗ Try this live — drag the two cutlines to shade any interval between them."><img src="normal-approximation_files/figure-html/fig-normal-between-69-74-1.png" class="img-fluid figure-img" alt="A normal distribution curve centered at 70 inches with standard deviation 3.3 inches. The area between 69 and 74 inches is shaded, representing the probability of being between those two heights." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-between-69-74-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.5: A normal curve centered at 70 with standard deviation 3.3. The area between 69 and 74 is shaded. <a href="https://learnlens.org/statlens/conceptual/normal-distribution/">↗ Try this live</a> — drag the two cutlines to shade any interval between them.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Step 2: Find both Z-scores.</strong></p>
<p><span class="math display">\[Z_1 = \frac{69 - 70}{3.3} = -0.30 \qquad Z_2 = \frac{74 - 70}{3.3} = 1.21\]</span></p>
<p><strong>Step 3: Look up both left-tail areas.</strong></p>
<ul>
<li>Area to the left of <span class="math inline">\(Z_1 = -0.30\)</span>: 0.3821</li>
<li>Area to the left of <span class="math inline">\(Z_2 = 1.21\)</span>: 0.8869</li>
</ul>
<p><strong>Step 4: Subtract.</strong></p>
<p><span class="math display">\[P(69 &lt; X &lt; 74) = 0.8869 - 0.3821 = 0.5048\]</span></p>
<p>About <strong>50.5%</strong> of adult males are between 5’9” and 6’2”.</p>
</div>
<div class="guidedpractice">
<p>What percent of SAT takers score between 1500 and 2000? (SAT scores follow <span class="math inline">\(N(1500, 300)\)</span>.)</p>
<details>
<summary>
Show answer
</summary>
First find the Z-scores: <span class="math inline">\(Z_1 = \frac{1500 - 1500}{300} = 0.00\)</span> and <span class="math inline">\(Z_2 = \frac{2000 - 1500}{300} = 1.67\)</span>. The left-tail areas are 0.5000 and 0.9525. The area between them is <span class="math inline">\(0.9525 - 0.5000 = 0.4525\)</span>, so about 45.25% score between 1500 and 2000.
</details>
</div>
</section>
<section id="finding-values-from-percentiles" class="level3" data-number="11.4.4">
<h3 data-number="11.4.4" class="anchored" data-anchor-id="finding-values-from-percentiles"><span class="header-section-number">11.4.4</span> Finding values from percentiles</h3>
<p>Sometimes we want to work backwards: given a percentile, find the observation.</p>
<div class="workedexample">
<p>Adult male heights follow <span class="math inline">\(N(70, 3.3)\)</span>. Yousef’s height is at the 40th percentile. How tall is Yousef?</p>
<hr>
<p><strong>Step 1: Draw a picture.</strong> The 40th percentile means 40% of the area is to the left.</p>
<p><strong>Step 2: Find the Z-score for the 40th percentile.</strong> Using a normal probability table (look for 0.40 in the body of the table) or software, <span class="math inline">\(Z = -0.25\)</span>.</p>
<p><strong>Step 3: Solve for <span class="math inline">\(x\)</span>.</strong> Using the Z-score formula:</p>
<p><span class="math display">\[-0.25 = \frac{x - 70}{3.3}\]</span></p>
<p><span class="math display">\[x = 70 + (-0.25)(3.3) = 70 - 0.825 = 69.2 \text{ inches}\]</span></p>
<p>Yousef is approximately 69.2 inches (about 5’9”) tall.</p>
</div>
<div class="guidedpractice">
<p>What is the 95th percentile for SAT scores?</p>
<details>
<summary>
Show answer
</summary>
The Z-score for the 95th percentile is <span class="math inline">\(Z = 1.645\)</span>. Then <span class="math inline">\(x = 1500 + 1.645 \times 300 = 1500 + 493.5 = 1993.5\)</span>. The 95th percentile for SAT scores is approximately 1994.
</details>
</div>
</section>
<section id="the-normal-probability-table" class="level3" data-number="11.4.5">
<h3 data-number="11.4.5" class="anchored" data-anchor-id="the-normal-probability-table"><span class="header-section-number">11.4.5</span> The normal probability table</h3>
<p>A <strong>normal probability table</strong> (also called a Z-table) lists areas to the left of Z-scores for the standard normal distribution. The table is organized with the ones and tenths digits of the Z-score in the rows, and the hundredths digit in the columns.</p>
<p><strong>Common Z-scores and areas worth remembering:</strong></p>
<table class="table-striped caption-top table">
<caption>Commonly used Z-scores and their corresponding left-tail areas.</caption>
<thead>
<tr class="header">
<th>Z-score</th>
<th>Left-tail area</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(-1.96\)</span></td>
<td>0.0250</td>
<td>2.5th percentile</td>
</tr>
<tr class="even">
<td><span class="math inline">\(-1.645\)</span></td>
<td>0.0500</td>
<td>5th percentile</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(-1.00\)</span></td>
<td>0.1587</td>
<td>15.87th percentile</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.00\)</span></td>
<td>0.5000</td>
<td>50th percentile (the mean)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1.00\)</span></td>
<td>0.8413</td>
<td>84.13th percentile</td>
</tr>
<tr class="even">
<td><span class="math inline">\(1.645\)</span></td>
<td>0.9500</td>
<td>95th percentile</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1.96\)</span></td>
<td>0.9750</td>
<td>97.5th percentile</td>
</tr>
<tr class="even">
<td><span class="math inline">\(2.576\)</span></td>
<td>0.9950</td>
<td>99.5th percentile</td>
</tr>
</tbody>
</table>
<div class="statlens">
<p><strong>See it in action.</strong> Open the <a href="https://learnlens.org/statlens/distribution/normal/" target="_blank">Normal Distribution Explorer</a> to verify entries in the table above — enter a Z-score, check the shaded area, then work backwards from a percentile.</p>
</div>
</section>
</section>
<section id="sec-normal-approx-sampling" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="sec-normal-approx-sampling"><span class="header-section-number">11.5</span> The normal approximation to sampling distributions</h2>
<p>In the sampling distributions chapter, we used simulation to explore sampling distributions – the distributions of sample statistics computed from many repeated samples. A striking pattern emerged: regardless of whether we were looking at sample means, sample proportions, or differences in means or proportions, the sampling distributions tended to be <strong>bell-shaped and symmetric</strong>. This is not a coincidence.</p>
<section id="the-central-limit-theorem" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="the-central-limit-theorem"><span class="header-section-number">11.5.1</span> The Central Limit Theorem</h3>
<div class="definition">
<p><strong>The Central Limit Theorem (CLT).</strong> When observations are independent and the sample size is sufficiently large, the sampling distribution of many common statistics (sample means, sample proportions, and their differences) is approximately normal, regardless of the shape of the population distribution.</p>
<p>Specifically:</p>
<ul>
<li>The sampling distribution of <span class="math inline">\(\bar{x}\)</span> is approximately <span class="math inline">\(N\!\left(\mu, \frac{\sigma}{\sqrt{n}}\right)\)</span>.</li>
<li>The sampling distribution of <span class="math inline">\(\hat{p}\)</span> is approximately <span class="math inline">\(N\!\left(p, \sqrt{\frac{p(1-p)}{n}}\right)\)</span>.</li>
</ul>
</div>
<p>The CLT is one of the most remarkable results in all of mathematics. It explains why simulation-based null distributions and bootstrap distributions looked bell-shaped: they were approximating the normal distribution all along.</p>
<div class="important">
<p><strong>Two conditions for the CLT to apply:</strong></p>
<ol type="1">
<li><strong>Independence.</strong> The observations must be independent of one another. This is satisfied when data come from a random sample or a randomized experiment.</li>
<li><strong>Sample size.</strong> The sample must be large enough. What counts as “large enough” depends on the context:
<ul>
<li>For <strong>proportions</strong>: at least 10 expected successes and 10 expected failures (<span class="math inline">\(np \geq 10\)</span> and <span class="math inline">\(n(1-p) \geq 10\)</span>). This is called the <strong>success-failure condition</strong>.</li>
<li>For <strong>means</strong>: <span class="math inline">\(n \geq 30\)</span> is a common guideline, though smaller samples can work if the population is not strongly skewed.</li>
</ul></li>
</ol>
</div>
</section>
<section id="standard-error-quantifying-the-variability-of-a-statistic" class="level3" data-number="11.5.2">
<h3 data-number="11.5.2" class="anchored" data-anchor-id="standard-error-quantifying-the-variability-of-a-statistic"><span class="header-section-number">11.5.2</span> Standard error: quantifying the variability of a statistic</h3>
<p>The CLT tells us the sampling distribution is approximately normal. But how wide is that normal distribution? The answer is given by the <strong>standard error</strong>.</p>
<div class="definition">
<p>The <strong>standard error (SE)</strong> of a statistic is the standard deviation of its sampling distribution. It measures how much the statistic varies from sample to sample.</p>
</div>
<p>The standard error depends on the parameter of interest:</p>
<table class="table-striped caption-top table">
<caption>Standard error formulas for common parameters.</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 35%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Point estimate</th>
<th>Standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Population mean <span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\bar{x}\)</span></td>
<td><span class="math inline">\(SE = \frac{s}{\sqrt{n}}\)</span></td>
</tr>
<tr class="even">
<td>Population proportion <span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\hat{p}\)</span></td>
<td><span class="math inline">\(SE = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span></td>
</tr>
<tr class="odd">
<td>Difference in means <span class="math inline">\(\mu_1 - \mu_2\)</span></td>
<td><span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span></td>
<td><span class="math inline">\(SE = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\)</span></td>
</tr>
<tr class="even">
<td>Difference in proportions <span class="math inline">\(p_1 - p_2\)</span></td>
<td><span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span></td>
<td><span class="math inline">\(SE = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}\)</span></td>
</tr>
</tbody>
</table>
<div class="important">
<p><strong>Margin of error.</strong> The distance <span class="math inline">\(z^* \times SE\)</span> is called the <strong>margin of error</strong>. For a 95% confidence interval, <span class="math inline">\(z^* = 1.96\)</span> (often rounded to 2), giving a margin of error of approximately <span class="math inline">\(2 \times SE\)</span>. This is directly connected to the 68-95-99.7 rule: 95% of sample statistics fall within about 2 standard errors of the true parameter value.</p>
</div>
</section>
<section id="connecting-simulation-and-normal-approximation" class="level3" data-number="11.5.3">
<h3 data-number="11.5.3" class="anchored" data-anchor-id="connecting-simulation-and-normal-approximation"><span class="header-section-number">11.5.3</span> Connecting simulation and normal approximation</h3>
<div class="original">
<p>Let’s see the connection between simulation-based methods and the normal approximation in a concrete example. As a quick reminder from the <a href="../chapters/randomization-tests.html">randomization tests chapter</a>, a hypothesis test weighs the <strong>null hypothesis</strong> <span class="math inline">\(H_0\)</span> (“no effect”) against the <strong>alternative</strong> <span class="math inline">\(H_A\)</span> (“real effect”), computes a <strong>p-value</strong> (probability of the observed data or more extreme under <span class="math inline">\(H_0\)</span>), and <strong>rejects</strong> <span class="math inline">\(H_0\)</span> when the p-value falls below the discernibility level <span class="math inline">\(\alpha\)</span>.</p>
<p>In the randomization tests chapter, we tested whether opportunity cost reminders reduce spending. We simulated 10,000 randomization samples and found a null distribution that was bell-shaped with a center of 0 and a spread described by <span class="math inline">\(SE \approx 0.078\)</span>. The observed difference was 0.20.</p>
<p><strong>Simulation approach:</strong> Count how many of the 10,000 simulated differences were at least as extreme as 0.20. The proportion gives the p-value: approximately 0.006.</p>
<p><strong>Normal approximation approach:</strong> Model the null distribution as <span class="math inline">\(N(0, 0.078)\)</span>. Compute the Z-score:</p>
<p><span class="math display">\[Z = \frac{0.20 - 0}{0.078} = 2.56\]</span></p>
<p>The area to the right of <span class="math inline">\(Z = 2.56\)</span> is 0.0052.</p>
<p>Both approaches give nearly the same p-value (0.006 vs.&nbsp;0.0052) and the same conclusion: reject <span class="math inline">\(H_0\)</span>. The normal approximation works because the conditions are met – independent observations and a sufficiently large sample.</p>
</div>
</section>
<section id="confidence-intervals-using-the-normal-model" class="level3" data-number="11.5.4">
<h3 data-number="11.5.4" class="anchored" data-anchor-id="confidence-intervals-using-the-normal-model"><span class="header-section-number">11.5.4</span> Confidence intervals using the normal model</h3>
<p>The normal approximation also lets us build confidence intervals without bootstrapping.</p>
<div class="important">
<p><strong>General confidence interval formula.</strong> When the sampling distribution of a statistic is approximately normal with standard error <span class="math inline">\(SE\)</span>, a confidence interval takes the form:</p>
<p><span class="math display">\[\text{point estimate} \pm z^* \times SE\]</span></p>
<p>where <span class="math inline">\(z^*\)</span> is chosen based on the desired confidence level:</p>
<table class="table-striped caption-top table">
<caption>Critical values <span class="math inline">\(z^*\)</span> for common confidence levels.</caption>
<thead>
<tr class="header">
<th>Confidence level</th>
<th><span class="math inline">\(z^*\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td>1.645</td>
</tr>
<tr class="even">
<td>95%</td>
<td>1.960</td>
</tr>
<tr class="odd">
<td>99%</td>
<td>2.576</td>
</tr>
</tbody>
</table>
</div>
<div class="workedexample">
<p>A study examined whether stents reduce stroke risk. The observed difference in 30-day stroke rates (treatment minus control) was <span class="math inline">\(\hat{p}_T - \hat{p}_C = 0.090\)</span>, with <span class="math inline">\(SE = 0.028\)</span>. Construct a 95% confidence interval.</p>
<hr>
<p>The conditions for the normal model have been verified. Using <span class="math inline">\(z^* = 1.96\)</span>:</p>
<p><span class="math display">\[0.090 \pm 1.96 \times 0.028 = 0.090 \pm 0.055 = (0.035, 0.145)\]</span></p>
<p>We are 95% confident that implanting a stent increased the 30-day stroke rate by between 3.5 and 14.5 percentage points. Since the interval does not contain 0, we have evidence of a real difference.</p>
</div>
</section>
</section>
<section id="sec-normal-when" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="sec-normal-when"><span class="header-section-number">11.6</span> When does the normal model apply – and when doesn’t it?</h2>
<p>The normal distribution is powerful but not universal. Here we summarize when it is and is not appropriate.</p>
<div class="important">
<p><strong>When the normal model is a good approximation:</strong></p>
<ul>
<li>Sample proportions <span class="math inline">\(\hat{p}\)</span>, when the success-failure condition is met (<span class="math inline">\(np \geq 10\)</span> and <span class="math inline">\(n(1-p) \geq 10\)</span>).</li>
<li>Sample means <span class="math inline">\(\bar{x}\)</span>, when the sample size is at least 30 or the population is approximately normal (we will use the <span class="math inline">\(t\)</span>-distribution for means – see the confidence intervals for means chapter).</li>
<li>Differences in proportions or means, when both groups satisfy the above conditions.</li>
</ul>
<p><strong>When the normal model is NOT a good approximation:</strong></p>
<ul>
<li>Small samples with a skewed population distribution.</li>
<li>Proportions near 0 or 1 with small sample sizes (the success-failure condition fails).</li>
<li>Data with strong dependence between observations.</li>
</ul>
</div>
<div class="workedexample">
<p>A medical consultant claims that only 3 of their 62 liver transplant clients had complications, compared to the national rate of 10%. Is it appropriate to use the normal approximation to test whether this consultant’s rate is lower?</p>
<hr>
<p>Under the null hypothesis (<span class="math inline">\(p_0 = 0.10\)</span>), we check the success-failure condition:</p>
<ul>
<li>Expected successes (complications): <span class="math inline">\(np_0 = 62 \times 0.10 = 6.2\)</span></li>
<li>Expected failures (no complications): <span class="math inline">\(n(1 - p_0) = 62 \times 0.90 = 55.8\)</span></li>
</ul>
<p>Since the expected number of successes (6.2) is less than 10, the <strong>success-failure condition is not met</strong>. The normal approximation would underestimate the variability and give an inaccurate p-value. A simulation-based approach (as in the randomization tests chapter) would be more appropriate here.</p>
</div>
<div class="caution">
<p><strong>When conditions fail, use simulation.</strong> If the success-failure condition is not met or the sample size is too small for the normal approximation, we should fall back on the simulation-based methods from the randomization tests and bootstrap confidence intervals chapters. The bootstrap and randomization approaches work well even when the normal model does not. This is one of the great advantages of simulation-based inference: it is more broadly applicable.</p>
</div>
</section>
<section id="sec-normal-approximation-review" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="sec-normal-approximation-review"><span class="header-section-number">11.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="11.7.1">
<h3 data-number="11.7.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">11.7.1</span> Summary</h3>
<p>This chapter introduced the normal distribution, the most commonly encountered distribution in statistics. Key concepts include:</p>
<ul>
<li>The normal distribution is described by two parameters: the mean <span class="math inline">\(\mu\)</span> (center) and standard deviation <span class="math inline">\(\sigma\)</span> (spread), written as <span class="math inline">\(N(\mu, \sigma)\)</span>.</li>
<li>The <strong>68-95-99.7 rule</strong> provides quick estimates: about 68%, 95%, and 99.7% of observations fall within 1, 2, and 3 standard deviations of the mean.</li>
<li>A <strong>Z-score</strong> standardizes an observation by measuring how many standard deviations it lies from the mean: <span class="math inline">\(Z = \frac{x - \mu}{\sigma}\)</span>.</li>
<li>Normal probabilities are found by computing Z-scores and looking up areas under the standard normal curve using tables, software, or StatLens.</li>
<li>The <strong>Central Limit Theorem</strong> guarantees that sampling distributions of means and proportions are approximately normal when the sample is large enough and observations are independent.</li>
<li>The <strong>standard error</strong> measures how much a statistic varies from sample to sample and is the key ingredient in confidence intervals and hypothesis tests.</li>
<li>The normal approximation and simulation-based methods give similar results when conditions are met, but simulation is more flexible when conditions fail.</li>
</ul>
</section>
<section id="key-terms" class="level3" data-number="11.7.2">
<h3 data-number="11.7.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">11.7.2</span> Key terms</h3>
<p>Normal distribution, standard normal distribution, parameters (μ and σ), 68-95-99.7 rule, Z-score, standardizing, percentile, Central Limit Theorem (CLT), standard error (SE), margin of error, success-failure condition.</p>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="11.8">
<h2 class="exercises anchored" data-number="11.8" data-anchor-id="exercises"><span class="header-section-number">11.8</span> Exercises</h2>
<p>Answers to odd-numbered exercises are provided in the <a href="../appendices/exercise-solutions.html#sec-solutions-normal-approximation">Exercise Solutions appendix</a> at the back of the book.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _13-ex-foundations-mathematical, _04-ex-normal-distribution, _12-ex-normal-approximation-gap -->
<ol type="1">
<li><strong>Chronic illness.</strong> In 2013, the Pew Research Foundation reported that “45% of U.S. adults report that they live with one or more chronic conditions”. However, this value was based on a sample, so it may not be a perfect estimate for the population parameter of interest on its own. The study reported a standard error of about 1.2%, and a normal model may reasonably be used in this setting.</li>
</ol>
<ol type="a">
<li><p>Create a 95% confidence interval for the proportion of U.S. adults who live with one or more chronic conditions. Also interpret the confidence interval in the context of the study. <span class="citation" data-cites="data:pewdiagnosis:2013">(<a href="#ref-data:pewdiagnosis:2013" role="doc-biblioref">Pew Research Center 2013</a>)</span></p></li>
<li><p>Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.</p>
<ol type="i">
<li><p>We can say with certainty that the confidence interval from part (a) contains the true percentage of U.S. adults who suffer from a chronic illness.</p></li>
<li><p>If we repeated this study 1,000 times and constructed a 95% confidence interval for each study, then approximately 950 of those confidence intervals would contain the true fraction of U.S. adults who suffer from chronic illnesses.</p></li>
<li><p>The poll provides statistically discernible evidence (at the <span class="math inline">\(\alpha = 0.05\)</span> level) that the percentage of U.S. adults who suffer from chronic illnesses is below 50%.</p></li>
<li><p>Since the standard error is 1.2%, only 1.2% of people in the study communicated uncertainty about their answer.</p></li>
</ol></li>
</ol>
<ol start="2" type="1">
<li><strong>Social media users and news, mathematical model.</strong> A poll conducted in 2022 found that 50% of U.S. adults (i.e., a proportion of 0.5) get news from social media sometimes or often. The standard error for this estimate was 0.5% (i.e., 0.005), and a normal distribution may be used to model the sample proportion. <span class="citation" data-cites="data:socialmedianews:2022">(<a href="#ref-data:socialmedianews:2022" role="doc-biblioref">Pew Research Center 2022</a>)</span></li>
</ol>
<ol type="a">
<li><p>Construct a 99% confidence interval for the fraction of U.S. adults who get news on social media sometimes or often, and interpret the confidence interval in context.</p></li>
<li><p>Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.</p>
<ol type="i">
<li><p>The data provide statistically discernible evidence that more than half of U.S. adults users get news through social media sometimes or often. Use a discernibility level of <span class="math inline">\(\alpha = 0.01\)</span>.</p></li>
<li><p>Since the standard error is 0.5%, we can conclude that 99.5% of all U.S. adults users were included in the study.</p></li>
<li><p>If we want to reduce the standard error of the estimate, we should collect less data.</p></li>
<li><p>If we construct a 90% confidence interval for the percentage of U.S. adults who get news through social media sometimes or often, the resulting confidence interval will be wider than a corresponding 99% confidence interval. </p></li>
</ol></li>
</ol>
<ol start="3" type="1">
<li><strong>Interpreting a Z score from a sample proportion.</strong> Suppose that you conduct a hypothesis test about a population proportion and calculate the Z score to be 0.47. Which of the following is the best interpretation of this value? For the problems which are not a good interpretation, indicate the statistical idea being described.</li>
</ol>
<ol type="a">
<li><p>The probability is 0.47 that the null hypothesis is true.</p></li>
<li><p>If the null hypothesis were true, the probability would be 0.47 of obtaining a sample proportion as far as observed from the hypothesized value of the population proportion.</p></li>
<li><p>The sample proportion is 0.47 standard errors greater than the hypothesized value of the population proportion.</p></li>
<li><p>The sample proportion is equal to 0.47 times the standard error.</p></li>
<li><p>The sample proportion is 0.47 away from the hypothesized value of the population.</p></li>
<li><p>The sample proportion is 0.47. </p></li>
</ol>
<ol start="4" type="1">
<li><strong>Mental health.</strong> The General Social Survey asked the question: “For how many days during the past 30 days was your mental health, which includes stress, depression, and problems with emotions, not good?” Based on responses from 1,151 US residents, the survey reported a 95% confidence interval of 3.40 to 4.24 days in 2010.</li>
</ol>
<ol type="a">
<li><p>Interpret this interval in context of the data.</p></li>
<li><p>What does “95% confident” mean? Explain in the context of the application.</p></li>
<li><p>Suppose the researchers think a 99% confidence level would be more appropriate for this interval. Will this new interval be smaller or wider than the 95% confidence interval?</p></li>
<li><p>If a new survey were to be done with 500 Americans, do you think the standard error of the estimate be larger, smaller, or about the same.</p></li>
</ol>
<ol start="5" type="1">
<li><strong>Area under the curve, Part I.</strong> What percent of a standard normal distribution <span class="math inline">\(N(\mu=0, \sigma=1)\)</span> is found in each region? Be sure to draw a graph.</li>
</ol>
<ol type="a">
<li><p><span class="math inline">\(Z &lt; -1.35\)</span></p></li>
<li><p><span class="math inline">\(Z &gt; 1.48\)</span></p></li>
<li><p><span class="math inline">\(-0.4 &lt; Z &lt; 1.5\)</span></p></li>
<li><p><span class="math inline">\(|Z| &gt; 2\)</span> </p></li>
</ol>
<ol start="6" type="1">
<li><strong>Area under the curve, Part II.</strong> What percent of a standard normal distribution <span class="math inline">\(N(\mu=0, \sigma=1)\)</span> is found in each region? Be sure to draw a graph.</li>
</ol>
<ol type="a">
<li><p><span class="math inline">\(Z &gt; -1.13\)</span></p></li>
<li><p><span class="math inline">\(Z &lt; 0.18\)</span></p></li>
<li><p><span class="math inline">\(Z &gt; 8\)</span></p></li>
<li><p><span class="math inline">\(|Z| &lt; 0.5\)</span> </p></li>
</ol>
<ol start="7" type="1">
<li><strong>GRE scores, Part I.</strong> Sophia who took the Graduate Record Examination (GRE) scored 160 on the Verbal Reasoning section and 157 on the Quantitative Reasoning section. The mean score for Verbal Reasoning section for all test takers was 151 with a standard deviation of 7, and the mean score for the Quantitative Reasoning was 153 with a standard deviation of 7.67. Suppose that both distributions are nearly normal.</li>
</ol>
<ol type="a">
<li><p>Write down the short-hand for these two normal distributions.</p></li>
<li><p>What is Sophia’s Z-score on the Verbal Reasoning section? On the Quantitative Reasoning section? Draw a standard normal distribution curve and mark these two Z-scores.</p></li>
<li><p>What do these Z-scores tell you?</p></li>
<li><p>Relative to others, which section did she do better on?</p></li>
<li><p>Find her percentile scores for the two exams.</p></li>
<li><p>What percent of the test takers did better than her on the Verbal Reasoning section? On the Quantitative Reasoning section?</p></li>
<li><p>Explain why simply comparing raw scores from the two sections could lead to an incorrect conclusion as to which section a student did better on.</p></li>
<li><p>If the distributions of the scores on these exams are not nearly normal, would your answers to parts (b) - (f) change? Explain your reasoning. </p></li>
</ol>
<ol start="8" type="1">
<li><strong>Triathlon times, Part I.</strong> In triathlons, it is common for racers to be placed into age and gender groups. Friends Leo and Mary both completed the Hermosa Beach Triathlon, where Leo competed in the <em>Men, Ages 30 - 34</em> group while Mary competed in the <em>Women, Ages 25 - 29</em> group. Leo completed the race in 1:22:28 (4948 seconds), while Mary completed the race in 1:31:53 (5513 seconds). Obviously Leo finished faster, but they are curious about how they did within their respective groups. Can you help them? Here is some information on the performance of their groups:</li>
</ol>
<ul>
<li>The finishing times of the <em>Men, Ages 30 - 34</em> group has a mean of 4313 seconds with a standard deviation of 583 seconds.</li>
<li>The finishing times of the <em>Women, Ages 25 - 29</em> group has a mean of 5261 seconds with a standard deviation of 807 seconds.</li>
<li>The distributions of finishing times for both groups are approximately Normal.</li>
</ul>
<p>Remember: a better performance corresponds to a faster finish.</p>
<ol type="a">
<li><p>Write down the short-hand for these two normal distributions.</p></li>
<li><p>What are the Z-scores for Leo’s and Mary’s finishing times? What do these Z-scores tell you?</p></li>
<li><p>Did Leo or Mary rank better in their respective groups? Explain your reasoning.</p></li>
<li><p>What percent of the triathletes did Leo finish faster than in his group?</p></li>
<li><p>What percent of the triathletes did Mary finish faster than in her group?</p></li>
<li><p>If the distributions of finishing times are not nearly normal, would your answers to parts (b) - (e) change? Explain your reasoning. </p></li>
</ol>
<ol start="9" type="1">
<li><strong>GRE scores, Part II.</strong> In a previous exercise we saw two distributions for GRE scores: <span class="math inline">\(N(\mu=151, \sigma=7)\)</span> for the verbal part of the exam and <span class="math inline">\(N(\mu=153, \sigma=7.67)\)</span> for the quantitative part. Use this information to compute each of the following:</li>
</ol>
<ol type="a">
<li><p>The score of a student who scored in the <span class="math inline">\(80^{th}\)</span> percentile on the Quantitative Reasoning section.</p></li>
<li><p>The score of a student who scored worse than 70% of the test takers in the Verbal Reasoning section. </p></li>
</ol>
<ol start="10" type="1">
<li><strong>Triathlon times, Part II.</strong> In a previous exercise we saw two distributions for triathlon times: <span class="math inline">\(N(\mu=4313, \sigma=583)\)</span> for <em>Men, Ages 30 - 34</em> and <span class="math inline">\(N(\mu=5261, \sigma=807)\)</span> for the <em>Women, Ages 25 - 29</em> group. Times are listed in seconds. Use this information to compute each of the following:</li>
</ol>
<ol type="a">
<li><p>The cutoff time for the fastest 5% of athletes in the men’s group, i.e.&nbsp;those who took the shortest 5% of time to finish.</p></li>
<li><p>The cutoff time for the slowest 10% of athletes in the women’s group. </p></li>
</ol>
<ol start="11" type="1">
<li><strong>LA weather, Part I.</strong> The average daily high temperature in June in LA is 77<span class="math inline">\(^\circ\)</span> F with a standard deviation of 5<span class="math inline">\(^\circ\)</span> F. Suppose that the temperatures in June closely follow a normal distribution.</li>
</ol>
<ol type="a">
<li><p>What is the probability of observing an 83<span class="math inline">\(^\circ\)</span> F temperature or higher in LA during a randomly chosen day in June?</p></li>
<li><p>How cool are the coldest 10% of the days (days with lowest high temperature) during June in LA? </p></li>
</ol>
<ol start="12" type="1">
<li><strong>CAPM.</strong> The Capital Asset Pricing Model (CAPM) is a financial model that assumes returns on a portfolio are normally distributed. Suppose a portfolio has an average annual return of 14.7% (i.e.&nbsp;an average gain of 14.7%) with a standard deviation of 33%. A return of 0% means the value of the portfolio doesn’t change, a negative return means that the portfolio loses money, and a positive return means that the portfolio gains money.</li>
</ol>
<ol type="a">
<li><p>What percent of years does this portfolio lose money, i.e.&nbsp;have a return less than 0%?</p></li>
<li><p>What is the cutoff for the highest 15% of annual returns with this portfolio? </p></li>
</ol>
<ol start="13" type="1">
<li><strong>LA weather, Part II.</strong> A previous exercise states that average daily high temperature in June in LA is 77<span class="math inline">\(^\circ\)</span> F with a standard deviation of 5<span class="math inline">\(^\circ\)</span> F, and it can be assumed that they follow a normal distribution. We use the following equation to convert <span class="math inline">\(^\circ\)</span> F (Fahrenheit) to <span class="math inline">\(^\circ\)</span> C (Celsius): <span class="math display">\[C = (F - 32) \times \frac{5}{9}.\]</span></li>
</ol>
<ol type="a">
<li><p>Write the probability model for the distribution of temperature in <span class="math inline">\(^\circ\)</span> C in June in LA.</p></li>
<li><p>What is the probability of observing a 28<span class="math inline">\(^\circ\)</span> C (which roughly corresponds to 83<span class="math inline">\(^\circ\)</span> F) temperature or higher in June in LA? Calculate using the <span class="math inline">\(^\circ\)</span> C model from part (a).</p></li>
<li><p>Did you get the same answer or different answers in part (b) of this question and part (a) of a previous exercise? Are you surprised? Explain.</p></li>
<li><p>Estimate the IQR of the temperatures (in <span class="math inline">\(^\circ\)</span> C) in June in LA. </p></li>
</ol>
<ol start="14" type="1">
<li><strong>Find the SD (seedling heights).</strong> Heights of seedlings in a greenhouse experiment are approximately normally distributed with mean 16 cm. The greenhouse classifies a seedling as “tall” when its height exceeds 20 cm, and about 15% of seedlings fall into that category.</li>
</ol>
<ol type="a">
<li><p>What is the z-score corresponding to the “tall” cutoff?</p></li>
<li><p>Use the z-score and the cutoff to find the standard deviation of seedling heights.</p></li>
<li><p>Which step lets you solve for <span class="math inline">\(\sigma\)</span> once the z-score is known?</p></li>
</ol>
<ol start="15" type="1">
<li><strong>Overlay: normal curve on a simulated sampling distribution.</strong> In a previous chapter you built the sampling distribution of <span class="math inline">\(\hat{p}\)</span> by drawing many random samples from a population with proportion <span class="math inline">\(p\)</span> and computing <span class="math inline">\(\hat{p}\)</span> each time. Below are three simulated sampling distributions of <span class="math inline">\(\hat{p}\)</span> for <span class="math inline">\(p = 0.30\)</span>, using 5,000 samples each. Each histogram has a normal curve <span class="math inline">\(N(\mu, \sigma)\)</span> overlaid, with <span class="math inline">\(\mu = p = 0.30\)</span> and <span class="math inline">\(\sigma = \sqrt{p(1-p)/n}\)</span>.</li>
</ol>
<ul>
<li><strong>Panel A:</strong> <span class="math inline">\(n = 10\)</span></li>
<li><strong>Panel B:</strong> <span class="math inline">\(n = 50\)</span></li>
<li><strong>Panel C:</strong> <span class="math inline">\(n = 200\)</span></li>
</ul>
<p>(Imagine three histograms stacked, each with a smooth bell curve laid over it. At <span class="math inline">\(n = 10\)</span> the histogram is chunky and the curve doesn’t hug it well, especially in the left tail near 0. At <span class="math inline">\(n = 50\)</span> the histogram is smoother and the curve fits well through the middle, with only small mismatch at the tails. At <span class="math inline">\(n = 200\)</span> the histogram and curve are nearly indistinguishable.)</p>
<ol type="a">
<li><p>In which panel does the normal curve fit the simulated sampling distribution best? Why?</p></li>
<li><p>In panel A (<span class="math inline">\(n = 10\)</span>), name one visible reason the fit is poor. What condition from the chapter is failing?</p></li>
<li><p>The chapter states the success-failure condition (<span class="math inline">\(np \ge 10\)</span> and <span class="math inline">\(n(1-p) \ge 10\)</span>) for the normal approximation. Check the condition for each panel using <span class="math inline">\(p = 0.30\)</span>. Which panels satisfy it?</p></li>
<li><p>What does this tell you about <em>why</em> the normal approximation is a useful tool? What does it require to work?</p></li>
</ol>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><p><strong>Panel C (<span class="math inline">\(n = 200\)</span>).</strong> Larger <span class="math inline">\(n\)</span> makes the sampling distribution smoother, more symmetric, and more centered — the normal curve hugs it closely.</p></li>
<li><p>The histogram at <span class="math inline">\(n = 10\)</span> has visible right-skew and a boundary effect at 0 (proportions can’t be negative, but the normal curve extends below 0). The success-failure condition fails: <span class="math inline">\(np = 10 \times 0.30 = 3\)</span>, well below the threshold of 10.</p></li>
<li><p>Panel A: <span class="math inline">\(np = 3\)</span>, <span class="math inline">\(n(1-p) = 7\)</span> — <strong>fails.</strong> Panel B: <span class="math inline">\(np = 15\)</span>, <span class="math inline">\(n(1-p) = 35\)</span> — <strong>passes.</strong> Panel C: <span class="math inline">\(np = 60\)</span>, <span class="math inline">\(n(1-p) = 140\)</span> — <strong>passes clearly.</strong></p></li>
<li><p>The normal approximation works because <em>sampling distributions</em> (not populations, not samples) tend to become nearly normal as <span class="math inline">\(n\)</span> grows. It requires enough sample size for the discreteness and skewness to smooth out — a fact you can <em>see</em> by comparing the panels. When the condition fails, prefer a simulation approach (from an earlier chapter) over the normal formula.</p></li>
</ol>
</details>
<!--- MOM original-12-01
title: "Bridge: normal curve on a simulated sampling distribution"
type: multipart
license: "CC BY-NC — UWL original"
status: skeleton
--->
<ol start="16" type="1">
<li><strong>Bridge: simulation p-value vs.&nbsp;normal-approximation p-value.</strong> In the randomization tests chapter, you tested for sex discrimination in a bank promotion study by shuffling promotion decisions many times and recording the difference in promotion rates between male and female applicants. The observed difference was <span class="math inline">\(\hat{p}_M - \hat{p}_F = 0.292\)</span>. Suppose the randomization distribution of the difference, based on 10,000 shuffles, was centered near 0 with a standard deviation of about 0.115, and 47 of the 10,000 shuffles produced a difference <span class="math inline">\(\ge 0.292\)</span>.</li>
</ol>
<ol type="a">
<li><p>Compute the <strong>simulation p-value</strong> (one-tailed).</p></li>
<li><p>Now compute the <strong>normal-approximation p-value</strong> for the same test. Treat the randomization distribution as approximately <span class="math inline">\(N(0, 0.115)\)</span> and compute the Z-score for the observed statistic <span class="math inline">\(0.292\)</span>; then use the tail probability under the standard normal (via technology).</p></li>
<li><p>Do the two p-values agree? Within what tolerance?</p></li>
<li><p>Under what conditions would you expect the two p-values to <em>disagree</em>? Name one situation where the simulation p-value would be more trustworthy.</p></li>
</ol>
<details>
<summary>
Show answer
</summary>
<ol type="a">
<li><p><strong>Simulation p-value <span class="math inline">\(= 47 / 10{,}000 = 0.0047\)</span>.</strong></p></li>
<li><p><span class="math inline">\(Z = (0.292 - 0) / 0.115 \approx 2.54\)</span>. Right-tail probability under <span class="math inline">\(N(0,1)\)</span>: <span class="math inline">\(P(Z \ge 2.54) \approx 0.0055\)</span>.</p></li>
<li><p><strong>Yes — very close.</strong> 0.0047 vs.&nbsp;0.0055 differ by less than one part in a thousand. Both would lead to the same conclusion at any reasonable <span class="math inline">\(\alpha\)</span>.</p></li>
<li><p>They can disagree when the randomization distribution isn’t well-approximated by a normal — for example: small sample size (chunky, non-smooth distribution), extreme observed statistic in the far tail (where normal approximation is least accurate), or a bounded / heavily-skewed statistic like a correlation near ±1 or a proportion near 0 or 1. In those cases the <strong>simulation p-value is more trustworthy</strong> — it just counts shuffles, it doesn’t assume a bell shape.</p></li>
</ol>
</details>
<!--- MOM original-12-02
title: "Bridge: simulation p-value vs. normal-approximation p-value"
type: multipart
license: "CC BY-NC — UWL original"
status: skeleton
--->
<!-- StatLens Interactive Exercises — Normal Approximation -->
<!-- HAND-AUTHORED (not generated). Pedagogy: reading normal probabilities,    -->
<!-- standardizing, the success-failure condition, and when the formula and   -->
<!-- the simulation agree.                                                    -->
<section id="statlens-exercises" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="statlens-exercises">StatLens Exercises</h3>
<p>Let <a href="https://learnlens.org/statlens" target="_blank">StatLens</a> do the arithmetic; spend your effort on the reasoning a calculator can’t do.</p>
<ol type="1">
<li><p><strong>Read a normal probability in plain English.</strong> Open the <a href="https://learnlens.org/statlens/distribution/normal/?mu=0&amp;sigma=1&amp;tail=right" target="_blank">Normal Distribution tool</a> preset to <span class="math inline">\(\mu = 0\)</span>, <span class="math inline">\(\sigma = 1\)</span>.</p>
<ol type="a">
<li>Drag the boundary to <span class="math inline">\(z = 1\)</span>. Report the area to the right. What is the matching area to the <em>left</em> of <span class="math inline">\(z = -1\)</span>? Why are they equal?</li>
<li>Switch to the “middle” tail and set the boundaries to <span class="math inline">\(\pm 2\)</span>. What is the area? Is your answer consistent with the <strong>68–95–99.7 rule</strong>?</li>
<li>Switch back to “left tail” and set the boundary so the area is exactly 0.025. What <span class="math inline">\(z\)</span>-value did you get? Where will you use this number later in the course?</li>
<li>A student says: “Areas under the curve are probabilities, so they must be less than 1.” Could you have an area of 1? An area of 0? What do those represent?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>Area to the right of <span class="math inline">\(z = 1\)</span> is about 0.159. Area to the left of <span class="math inline">\(z = -1\)</span> is also about 0.159. They’re equal because the standard normal is <strong>symmetric about 0</strong>.</p></li>
<li><p>About 0.954 — consistent with “95%” within <span class="math inline">\(\pm 2\)</span> SDs (the empirical rule’s <span class="math inline">\(\pm 2\)</span> figure is actually <span class="math inline">\(\pm 1.96\)</span>; both round to 95%).</p></li>
<li><p><span class="math inline">\(z \approx -1.96\)</span>. This is the <strong>critical value</strong> for a 95% confidence interval; we will use <span class="math inline">\(z^* = 1.96\)</span> many times when building CIs and running two-sided <span class="math inline">\(z\)</span>-tests at <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p>Area = 1 represents “the value is <em>somewhere</em>” — the total area under any density curve is 1 by definition. Area = 0 represents an event with probability 0, like “<span class="math inline">\(z\)</span> equals exactly 0.5” — continuous distributions assign probability 0 to single points; only intervals have positive probability.</p></li>
</ol>
</details></li>
<li><p><strong>Standardize, then read off the probability.</strong> SAT math scores are approximately <span class="math inline">\(N(\mu = 520, \sigma = 110)\)</span>.</p>
<ol type="a">
<li>Compute the <span class="math inline">\(z\)</span>-score for a student who scored 700.</li>
<li>Use <a href="https://learnlens.org/statlens/distribution/normal/?mu=520&amp;sigma=110&amp;tail=right" target="_blank">Normal at <span class="math inline">\(\mu = 520, \sigma = 110\)</span></a> to find the proportion of test-takers scoring above 700.</li>
<li>Now use <a href="https://learnlens.org/statlens/distribution/normal/?mu=0&amp;sigma=1&amp;tail=right" target="_blank">the <em>standardized</em> normal at <span class="math inline">\(\mu = 0, \sigma = 1\)</span></a> and set the boundary to your <span class="math inline">\(z\)</span>-score from (a). Same answer?</li>
<li>A counselor says: “About 5% of students score 700 or higher.” Explain in one sentence what is <em>probabilistic</em> about the 5% and what is <em>not</em>.</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p><span class="math inline">\(z = (700 - 520)/110 \approx 1.64\)</span>.</p></li>
<li><p>About 0.05 (5%).</p></li>
<li><p><strong>Yes</strong> — standardizing to <span class="math inline">\(z\)</span> is just a re-expression. The two routes give the same probability because the standard normal at <span class="math inline">\(z = 1.64\)</span> has the same right-tail area as the original normal at <span class="math inline">\(x = 700\)</span>.</p></li>
<li><p>The 5% is probabilistic in the sense that <em>across all test-takers</em>, about 5% score 700+. It is <strong>not</strong> the probability that any individual student “would have scored 700” — their score is what it is. The 5% is a <strong>long-run frequency</strong> across the population, not a probability statement about one person.</p></li>
</ol>
</details></li>
<li><p><strong>The sampling distribution of <span class="math inline">\(\bar{x}\)</span> is also normal — with different <span class="math inline">\(\sigma\)</span>.</strong> Continuing the SAT example: a school selects a random sample of <span class="math inline">\(n = 25\)</span> students and computes their mean math score <span class="math inline">\(\bar{x}\)</span>.</p>
<ol type="a">
<li>What is the sampling distribution of <span class="math inline">\(\bar{x}\)</span>? Give its mean, standard error, and shape.</li>
<li>Use <a href="https://learnlens.org/statlens/distribution/normal/?mu=520&amp;sigma=22&amp;tail=right" target="_blank">the appropriate normal tool</a> (pre-loaded with <span class="math inline">\(\mu = 520\)</span>, <span class="math inline">\(\sigma = 110/\sqrt{25} = 22\)</span>) to find the probability that <span class="math inline">\(\bar{x} \ge 550\)</span>.</li>
<li>Compare this to the probability that an <strong>individual student</strong> scores <span class="math inline">\(\ge 550\)</span>. Which is bigger and why?</li>
<li>The school doubles <span class="math inline">\(n\)</span> to 50. Will the probability in (b) get bigger or smaller? Why?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>Mean = 520, SE = <span class="math inline">\(110/\sqrt{25} = 22\)</span>, shape = approximately normal (the population is itself near-normal, and the CLT kicks in regardless).</p></li>
<li><p><span class="math inline">\(z = (550 - 520)/22 \approx 1.36\)</span> → <span class="math inline">\(P(\bar{x} \ge 550) \approx 0.087\)</span>.</p></li>
<li><p>For an individual, <span class="math inline">\(z = (550 - 520)/110 \approx 0.27\)</span> → <span class="math inline">\(P(X \ge 550) \approx 0.39\)</span> — much bigger. Individual scores vary a lot; sample means vary less because averaging dampens individual variability. The same gap from <span class="math inline">\(\mu\)</span> is “less surprising” for an individual than for a mean.</p></li>
<li><p><strong>Smaller.</strong> Doubling <span class="math inline">\(n\)</span> shrinks the SE to <span class="math inline">\(110/\sqrt{50} \approx 15.6\)</span>. The same gap of 30 points is now <span class="math inline">\(z \approx 1.93\)</span> instead of 1.36 — farther in the tail, lower probability.</p></li>
</ol>
</details></li>
<li><p><strong>Normal approximation to a proportion — when does the formula work?</strong> Open the <a href="https://learnlens.org/statlens/inference/one-prop/" target="_blank">One-Proportion <span class="math inline">\(z\)</span>-Test tool</a>.</p>
<ol type="a">
<li>Enter a scenario where <span class="math inline">\(\hat{p}\)</span> is close to 0.5 and <span class="math inline">\(n\)</span> is large (say <span class="math inline">\(\hat{p} = 0.45\)</span>, <span class="math inline">\(n = 200\)</span>). Run a test. The tool reports the success–failure counts. Does the normal approximation apply?</li>
<li>Now enter a scenario with small <span class="math inline">\(\hat{p}\)</span>: <span class="math inline">\(\hat{p} = 0.05\)</span>, <span class="math inline">\(n = 40\)</span>. Does the normal approximation apply? Why or why not?</li>
<li>For the small-<span class="math inline">\(\hat{p}\)</span> scenario in (b), if the test gives a small p-value, should you trust it? What should you do instead?</li>
<li>Why is the success–failure rule based on <span class="math inline">\(np_0\)</span> and <span class="math inline">\(n(1 - p_0)\)</span> (using the <strong>null</strong> <span class="math inline">\(p_0\)</span>) rather than <span class="math inline">\(n\hat{p}\)</span> and <span class="math inline">\(n(1 - \hat{p})\)</span> for a hypothesis test?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p><span class="math inline">\(np = 200 \cdot 0.45 = 90\)</span>, <span class="math inline">\(n(1-p) = 110\)</span> — both well above 10. <strong>Normal approximation applies.</strong></p></li>
<li><p><span class="math inline">\(np = 40 \cdot 0.05 = 2\)</span>, <span class="math inline">\(n(1-p) = 38\)</span>. The first one is far below 10. <strong>Normal approximation fails.</strong></p></li>
<li><p>Don’t trust the <span class="math inline">\(z\)</span>-test p-value here. Use a <strong>bootstrap</strong> confidence interval for <span class="math inline">\(p\)</span> or a <strong>randomization</strong> (Bernoulli null) test instead — both make no normal-approximation assumption.</p></li>
<li><p>Under <span class="math inline">\(H_0\)</span>, the test statistic’s null distribution depends on <span class="math inline">\(p_0\)</span> (the hypothesized population value), not on the observed <span class="math inline">\(\hat{p}\)</span>. Using <span class="math inline">\(p_0\)</span> is consistent with “assume <span class="math inline">\(H_0\)</span> is true and see how surprising the data are.” Confidence intervals, which are <em>not</em> tied to a null, use <span class="math inline">\(\hat{p}\)</span> in the condition check.</p></li>
</ol>
</details></li>
<li><p><strong>Simulation vs.&nbsp;analytic — when does the normal model agree with the bootstrap?</strong> Pair the <a href="https://learnlens.org/statlens/inference/one-prop/" target="_blank">One-Proportion <span class="math inline">\(z\)</span>-Test</a> with the <a href="https://learnlens.org/statlens/simulate/bootstrap-prop/" target="_blank">Bootstrap CI for One Proportion</a> on two datasets.</p>
<p>First a well-behaved case: any dataset with <span class="math inline">\(\hat{p}\)</span> near 0.5 and <span class="math inline">\(n \ge 100\)</span>.</p>
<ol type="a">
<li>Compare the 95% intervals from the two tools. How close are they?</li>
</ol>
<p>Now a troublesome case: a dataset with small <span class="math inline">\(\hat{p}\)</span> (e.g., the medical consultant data, <span class="math inline">\(\hat{p} \approx 0.05\)</span>).</p>
<ol start="2" type="a">
<li>Compare the 95% intervals again. Where do they disagree — in the midpoint, the width, or both?</li>
<li>Look at the <strong>bootstrap distribution</strong> of <span class="math inline">\(\hat{p}\)</span>. Is it symmetric or skewed? How does that explain the disagreement with the symmetric <span class="math inline">\(z\)</span>-interval?</li>
<li>A student says: “Both intervals are ‘right’ — they’re just approximations.” What’s a more accurate framing? Which interval is more honest in the troublesome case, and what does “honest” mean for an interval?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>For well-behaved data the two intervals are very close (typically agreeing to within a fraction of a percentage point).</p></li>
<li><p>They differ noticeably. The <span class="math inline">\(z\)</span>-interval is <strong>symmetric</strong> about <span class="math inline">\(\hat{p}\)</span> (same width on each side); the bootstrap interval is <strong>asymmetric</strong>, following the actual skew of the bootstrap distribution.</p></li>
<li><p>At small <span class="math inline">\(\hat{p}\)</span> the bootstrap distribution is <strong>right-skewed</strong>: <span class="math inline">\(\hat{p}\)</span> has a hard floor at 0, so resamples can’t go negative, but can drift upward. The <span class="math inline">\(z\)</span>-interval forces a symmetric shape that doesn’t match.</p></li>
<li><p>The two intervals are not both “right” — the <span class="math inline">\(z\)</span>-interval <strong>under-covers</strong> in the troublesome case because its symmetry assumption fails. The bootstrap is more <strong>honest</strong>: it conveys the actual shape of the uncertainty, including the asymmetry. “Honest” for an interval means its long-run coverage matches the advertised level (95%); the <span class="math inline">\(z\)</span>-interval’s coverage falls below 95% when the normal approximation breaks down.</p></li>
</ol>
</details></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-data:pewdiagnosis:2013" class="csl-entry" role="listitem">
Pew Research Center. 2013. <span>“The Diagnosis Difference.”</span> <a href="https://www.openintro.org/go?id=textbook-pew-2013-diagnosis-difference">https://www.openintro.org/go?id=textbook-pew-2013-diagnosis-difference</a>.
</div>
<div id="ref-data:socialmedianews:2022" class="csl-entry" role="listitem">
———. 2022. <span>“News Consumption Across Digital Platforms.”</span> <a href="https://www.pewresearch.org/journalism/fact-sheet/news-platform-fact-sheet/pj_2022-09-20_news-platforms_0-03b/">https://www.pewresearch.org/journalism/fact-sheet/news-platform-fact-sheet/pj_2022-09-20_news-platforms_0-03b/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../parts/part-iii.html" class="pagination-link" aria-label="Unit 3: Compute">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Unit 3: Compute</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/inference-proportions.html" class="pagination-link" aria-label="Inference for Proportions">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>