<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Randomization Tests – Introduction to Statistics: A Simulation-First Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/decision-errors.html" rel="next">
<link href="../chapters/sampling-variability.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-16f0be44cf0b9c8dc4714857273be9e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-c76bc2edb0e532e390ad582fcbf98d52.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-09dcc980c20c1404022130b7c091a889.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-8c3813bde4f24d5fe6df4dbcf9b16457.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-ii.html">Unit 2: Simulate</a></li><li class="breadcrumb-item"><a href="../chapters/randomization-tests.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to Statistics: A Simulation-First Approach</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../technology-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Technology Setup</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 1: Explore</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/study-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Collection and Study Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Explore</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Exploring a Distribution</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 2: Simulate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/randomization-tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decision-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bootstrap-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distributions via Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-simulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulate — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-simulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Simulate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 3: Compute</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Normal Approximation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference for Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ci-for-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Confidence Intervals for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/hypothesis-tests-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Hypothesis Tests for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-calculate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-calculate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Compute</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Inference for Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Two Means</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 4: Apply</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chi-Square Goodness of Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chisq-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/prediction-model-fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Prediction and Model Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/anova-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">ANOVA for Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-apply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apply — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-apply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Apply</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Comparing Several Means (ANOVA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-chisq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Association Between Two Categorical Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-chisq-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Association Between Two Categorical Variables (AI version)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projects/project-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project: Fitting and Testing a Regression Line</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 5: Foundations</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Expected Value and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Binomial Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">More About the Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/type-ii-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Type II Error and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Sample Size Planning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviews/review-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations — Unit Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tech/tech-tutorial-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tech Tutorial: Foundations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/statlens-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">StatLens Quick Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-hypothesis-framework" id="toc-sec-hypothesis-framework" class="nav-link active" data-scroll-target="#sec-hypothesis-framework"><span class="header-section-number">8.1</span> The hypothesis testing framework</a></li>
  <li><a href="#sec-null-alternative" id="toc-sec-null-alternative" class="nav-link" data-scroll-target="#sec-null-alternative"><span class="header-section-number">8.2</span> Null and alternative hypotheses</a></li>
  <li><a href="#sec-sex-discrimination" id="toc-sec-sex-discrimination" class="nav-link" data-scroll-target="#sec-sex-discrimination"><span class="header-section-number">8.3</span> Case study: sex discrimination</a>
  <ul class="collapse">
  <li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">8.3.1</span> Observed data</a></li>
  </ul></li>
  <li><a href="#sec-randomization-distribution" id="toc-sec-randomization-distribution" class="nav-link" data-scroll-target="#sec-randomization-distribution"><span class="header-section-number">8.4</span> Building a randomization distribution</a>
  <ul class="collapse">
  <li><a href="#the-card-shuffling-metaphor" id="toc-the-card-shuffling-metaphor" class="nav-link" data-scroll-target="#the-card-shuffling-metaphor"><span class="header-section-number">8.4.1</span> The card-shuffling metaphor</a></li>
  <li><a href="#one-simulation" id="toc-one-simulation" class="nav-link" data-scroll-target="#one-simulation"><span class="header-section-number">8.4.2</span> One simulation</a></li>
  <li><a href="#many-simulations" id="toc-many-simulations" class="nav-link" data-scroll-target="#many-simulations"><span class="header-section-number">8.4.3</span> Many simulations</a></li>
  <li><a href="#the-conclusion" id="toc-the-conclusion" class="nav-link" data-scroll-target="#the-conclusion"><span class="header-section-number">8.4.4</span> The conclusion</a></li>
  </ul></li>
  <li><a href="#sec-opportunity-cost" id="toc-sec-opportunity-cost" class="nav-link" data-scroll-target="#sec-opportunity-cost"><span class="header-section-number">8.5</span> Case study: opportunity cost</a>
  <ul class="collapse">
  <li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">8.5.1</span> Observed data</a></li>
  <li><a href="#simulating-under-the-null" id="toc-simulating-under-the-null" class="nav-link" data-scroll-target="#simulating-under-the-null"><span class="header-section-number">8.5.2</span> Simulating under the null</a></li>
  </ul></li>
  <li><a href="#sec-p-values" id="toc-sec-p-values" class="nav-link" data-scroll-target="#sec-p-values"><span class="header-section-number">8.6</span> P-values</a></li>
  <li><a href="#sec-statistical-significance" id="toc-sec-statistical-significance" class="nav-link" data-scroll-target="#sec-statistical-significance"><span class="header-section-number">8.7</span> Statistical discernibility</a>
  <ul class="collapse">
  <li><a href="#decision-framework" id="toc-decision-framework" class="nav-link" data-scroll-target="#decision-framework"><span class="header-section-number">8.7.1</span> Decision framework</a></li>
  </ul></li>
  <li><a href="#sec-two-sided-tests" id="toc-sec-two-sided-tests" class="nav-link" data-scroll-target="#sec-two-sided-tests"><span class="header-section-number">8.8</span> Two-sided tests</a></li>
  <li><a href="#sec-randomization-summary" id="toc-sec-randomization-summary" class="nav-link" data-scroll-target="#sec-randomization-summary"><span class="header-section-number">8.9</span> The randomization test procedure: a summary</a></li>
  <li><a href="#sec-randomization-tests-review" id="toc-sec-randomization-tests-review" class="nav-link" data-scroll-target="#sec-randomization-tests-review"><span class="header-section-number">8.10</span> Chapter review</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.10.1</span> Summary</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">8.10.2</span> Key terms</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">8.11</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#statlens-exercises" id="toc-statlens-exercises" class="nav-link" data-scroll-target="#statlens-exercises">StatLens Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-ii.html">Unit 2: Simulate</a></li><li class="breadcrumb-item"><a href="../chapters/randomization-tests.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Randomization Tests</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>Statistical inference is primarily concerned with understanding and quantifying the uncertainty of parameter estimates. While the equations and details change depending on the setting, the foundations for inference are the same throughout all of statistics. In this chapter, we introduce the <strong>hypothesis testing framework</strong> — a formal method for evaluating competing claims about a population using data. We learn how to build <strong>randomization distributions</strong> by shuffling data under the assumption that there is no effect, and we use these distributions to compute <strong>p-values</strong> that quantify the strength of the evidence.</p>
</div>
<section id="sec-hypothesis-framework" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-hypothesis-framework"><span class="header-section-number">8.1</span> The hypothesis testing framework</h2>
<p>Throughout this course so far, you have worked with data in a variety of contexts. You have learned how to summarize and visualize data as well as how to describe relationships between variables. But more often than not, data have been collected to answer a research question about a larger group — and the data are a (hopefully) representative subset.</p>
<p>There is almost always variability in data — one dataset will not be identical to a second dataset even if they are both collected from the same population using the same methods. However, quantifying the variability in the data is neither obvious nor easy. Answering the question “<em>how</em> different is one dataset from another?” is not trivial.</p>
<div class="workedexample">
<p>Suppose your professor splits the students in your class into two groups: students who sit on the left side of the classroom and students who sit on the right side. If <span class="math inline">\(\hat{p}_{L}\)</span> represents the proportion of left-side students who prefer reading on a screen and <span class="math inline">\(\hat{p}_{R}\)</span> represents the proportion of right-side students who prefer reading on a screen, would you be surprised if <span class="math inline">\(\hat{p}_{L}\)</span> did not <em>exactly</em> equal <span class="math inline">\(\hat{p}_{R}\)</span>?</p>
<hr>
<p>While the proportions <span class="math inline">\(\hat{p}_{L}\)</span> and <span class="math inline">\(\hat{p}_{R}\)</span> would probably be close to each other, it would be unusual for them to be exactly the same. We would probably observe a small difference due to <em>chance</em>.</p>
</div>
<div class="guidedpractice">
<p>If we do not think the side of the room a person sits on in class is related to whether they prefer to read books on a screen, what assumption are we making about the relationship between these two variables?</p>
<details>
<summary>
Show answer
</summary>
We would be assuming that these two variables are <strong>independent</strong> — knowing which side of the room someone sits on tells us nothing about their reading preference.
</details>
</div>
<p>The question at the heart of hypothesis testing is: <em>Could the pattern we observe in the data have arisen from chance alone, or is there something real going on?</em></p>
<div class="important">
<p><strong>Hypothesis testing.</strong></p>
<p>A <strong>hypothesis test</strong> is a statistical technique used to evaluate competing claims using data. The process involves:</p>
<ol type="1">
<li><strong>State the hypotheses</strong>: Define a null hypothesis (<span class="math inline">\(H_0\)</span>) and an alternative hypothesis (<span class="math inline">\(H_A\)</span>).</li>
<li><strong>Collect data</strong>: Gather evidence that bears on the hypotheses.</li>
<li><strong>Assess the evidence</strong>: Determine how likely the observed data would be if the null hypothesis were true.</li>
<li><strong>Draw a conclusion</strong>: Decide whether the evidence is strong enough to reject the null hypothesis.</li>
</ol>
<p>If the null hypothesis and the data notably disagree, then we reject the null hypothesis in favor of the alternative hypothesis. There are many nuances to hypothesis testing, and we will discuss these ideas throughout this chapter and those that follow.</p>
</div>
</section>
<section id="sec-null-alternative" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-null-alternative"><span class="header-section-number">8.2</span> Null and alternative hypotheses</h2>
<div class="definition">
<p>The <strong>null hypothesis</strong> (<span class="math inline">\(H_0\)</span>) often represents a skeptical perspective or a claim of “no difference” or “no effect.” It assumes that any observed pattern in the data is due to chance alone.</p>
<p>The <strong>alternative hypothesis</strong> (<span class="math inline">\(H_A\)</span>) represents the claim under investigation — typically that there <em>is</em> a real difference, a real effect, or a real relationship. The alternative hypothesis is usually the reason the research was conducted in the first place.</p>
</div>
<div class="workedexample">
<p>The US court system considers two possible claims about a defendant: they are either innocent or guilty. If we set these claims up in a hypothesis framework, which would be the null hypothesis and which the alternative?</p>
<hr>
<p>The jury considers whether the evidence is so convincing that there is no reasonable doubt regarding the person’s guilt. The skeptical perspective (null hypothesis) is that the person is innocent until evidence is presented that convinces the jury the person is guilty (alternative hypothesis).</p>
<p><span class="math display">\[H_0: \text{The defendant is innocent.}\]</span> <span class="math display">\[H_A: \text{The defendant is guilty.}\]</span></p>
</div>
<div class="caution">
<p>Notice that if a jury finds a defendant <em>not guilty</em>, this does not necessarily mean the jury is confident in the person’s innocence. They are simply not convinced of the alternative. This is also the case with hypothesis testing: <strong>even if we fail to reject the null hypothesis, we do not accept the null hypothesis as truth.</strong> Failing to find evidence in favor of the alternative is not the same as finding evidence that the null hypothesis is true.</p>
</div>
</section>
<section id="sec-sex-discrimination" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-sex-discrimination"><span class="header-section-number">8.3</span> Case study: sex discrimination</h2>
<p>We consider a study investigating sex discrimination in the 1970s, set in the context of personnel decisions within a bank. The research question: “Are individuals who identify as female discriminated against in promotion decisions made by their managers who identify as male?”</p>
<div class="caution">
<p><strong>A note on the data.</strong> This 1972 study recorded each participant’s sex as one of two categories, male or female, as was standard practice at the time. We keep that framing here to stay faithful to the original data. Sex and gender are now understood to be more varied than a single binary variable, and a study designed today might record them differently.</p>
</div>
<section id="observed-data" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="observed-data"><span class="header-section-number">8.3.1</span> Observed data</h3>
<p>The participants were 48 bank supervisors who identified as male, attending a management institute at the University of North Carolina in 1972. They were asked to assume the role of personnel director of a bank and were given a personnel file to judge whether the person should be promoted to a branch manager position. The files were identical, except that half indicated the candidate identified as male and the other half indicated the candidate identified as female. These files were randomly assigned to the bank managers.</p>
<div class="guidedpractice">
<p>Is this an observational study or an experiment? How does the type of study impact what can be inferred from the results?</p>
<details>
<summary>
Show answer
</summary>
The study is an experiment, as subjects were randomly assigned a “male” file or a “female” file (remember, all the files were actually identical in content). Since this is an experiment, the results can be used to evaluate a causal relationship between the sex of a candidate and the promotion decision.
</details>
</div>
<p>The results are summarized in the table below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Promoted</th>
<th style="text-align: center;">Not promoted</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">48</td>
</tr>
</tbody>
</table>
<div class="workedexample">
<p>When looking at the rates of promotion in this study, why might we be tempted to immediately conclude that individuals identifying as female are being discriminated against?</p>
<hr>
<p>The large difference in promotion rates (58.3% for female personnel versus 87.5% for male personnel) suggests there might be discrimination against women in promotion decisions. However, we cannot yet be sure if the observed difference represents discrimination or is just due to random chance when there is no discrimination occurring. Since we wouldn’t expect the sample proportions to be <em>exactly</em> equal, even if the truth was that the promotion decisions were independent of sex, we can’t rule out random chance as a possible explanation.</p>
</div>
<p>The observed difference in promotion rates is:</p>
<p><span class="math display">\[\hat{p}_M - \hat{p}_F = \frac{21}{24} - \frac{14}{24} = 0.875 - 0.583 = 0.292\]</span></p>
<p>This is 29.2 percentage points. The point estimate is large, but the sample size is small, making it unclear if this represents real discrimination or simply chance variation. We label two competing claims:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <strong>Null hypothesis.</strong> The variables <code>sex</code> and <code>decision</code> are independent. The difference in promotion rates of 29.2% was due to natural variability inherent in the random assignment.</li>
<li><span class="math inline">\(H_A\)</span>: <strong>Alternative hypothesis.</strong> The variables <code>sex</code> and <code>decision</code> are <em>not</em> independent. The difference in promotion rates of 29.2% was not due to natural variability, and equally qualified female personnel are less likely to be promoted than male personnel.</li>
</ul>
</section>
</section>
<section id="sec-randomization-distribution" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-randomization-distribution"><span class="header-section-number">8.4</span> Building a randomization distribution</h2>
<p>What would it mean if the null hypothesis were true? It would mean each banker would decide whether to promote the candidate without regard to the sex indicated on the file. The 35 promotions and 13 non-promotions were determined by factors <em>other than sex</em>, and the difference we observed was just bad luck in how the files happened to be assigned.</p>
<p>We can test this by performing a <strong>randomization</strong> — simulating what the results would look like if sex and the promotion decision were independent, as the null hypothesis claims.</p>
<section id="the-card-shuffling-metaphor" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="the-card-shuffling-metaphor"><span class="header-section-number">8.4.1</span> The card-shuffling metaphor</h3>
<p>Think of the data as 48 cards:</p>
<ul>
<li>35 red cards (promoted)</li>
<li>13 white cards (not promoted)</li>
</ul>
<p>In the actual study, 24 cards were dealt to the “male” pile and 24 to the “female” pile. Under the null hypothesis, the color of each card (the promotion decision) has nothing to do with which pile it lands in.</p>
<p>To simulate what the null hypothesis looks like, we:</p>
<ol type="1">
<li><strong>Thoroughly shuffle</strong> all 48 cards together.</li>
<li><strong>Deal</strong> 24 into a “male” pile and 24 into a “female” pile.</li>
<li><strong>Count</strong> the number of red (promoted) cards in each pile and compute the difference in proportions.</li>
</ol>
<p>This gives us one simulated difference <em>under the null hypothesis</em> — a difference that arose purely from the random shuffle, not from any real discrimination.</p>
</section>
<section id="one-simulation" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="one-simulation"><span class="header-section-number">8.4.2</span> One simulation</h3>
<p>Suppose after shuffling and dealing, we get the following result:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Promoted</th>
<th style="text-align: center;">Not promoted</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">48</td>
</tr>
</tbody>
</table>
<p>The simulated difference is <span class="math inline">\(18/24 - 17/24 = 0.042\)</span>, or about 4.2% — much smaller than the observed 29.2%.</p>
<div class="guidedpractice">
<p>What is the difference in promotion rates in the simulated data above? How does this compare to the observed difference of 29.2% from the actual study?</p>
<details>
<summary>
Show answer
</summary>
The simulated difference is <span class="math inline">\(18/24 - 17/24 = 0.042\)</span> or about 4.2% in favor of male personnel. This difference due to chance is much smaller than the 29.2% difference observed in the actual groups.
</details>
</div>
</section>
<section id="many-simulations" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="many-simulations"><span class="header-section-number">8.4.3</span> Many simulations</h3>
<p>One simulation is not enough. We need to repeat the shuffle-and-deal process many times to build up a picture of what <em>chance alone</em> looks like. Using a computer, we can do this hundreds or thousands of times.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sex-discrim-rand-dist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A histogram of 100 simulated differences in promotion rates between male and female candidates. The distribution is centered at zero. A small number of simulations at or beyond 0.292 are highlighted, showing they are rare under the null hypothesis.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sex-discrim-rand-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="randomization-tests_files/figure-html/fig-sex-discrim-rand-dist-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;8.1: A histogram of differences from 100 simulations produced under the null hypothesis. The simulated sex and decision are independent. Differences at least as large as the observed 0.292 are highlighted in red. ↗ Try this live — shuffle the labels yourself and rebuild the null distribution."><img src="randomization-tests_files/figure-html/fig-sex-discrim-rand-dist-1.png" class="img-fluid figure-img" alt="A histogram of 100 simulated differences in promotion rates between male and female candidates. The distribution is centered at zero. A small number of simulations at or beyond 0.292 are highlighted, showing they are rare under the null hypothesis." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sex-discrim-rand-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: A histogram of differences from 100 simulations produced under the null hypothesis. The simulated sex and decision are independent. Differences at least as large as the observed 0.292 are highlighted in red. <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/">↗ Try this live</a> — shuffle the labels yourself and rebuild the null distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The distribution of these simulated differences is centered around 0. This makes sense: under the null hypothesis, which makes no distinction between male and female files, we would expect the difference to be near zero with some random fluctuation.</p>
<div class="workedexample">
<p>How often would you observe a difference of at least 29.2% according to the randomization distribution? Often, sometimes, rarely, or never?</p>
<hr>
<p>It appears that a difference of at least 29.2% under the null hypothesis would only happen about 2% of the time. Such a low probability indicates that observing such a large difference from chance alone is rare.</p>
</div>
</section>
<section id="the-conclusion" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="the-conclusion"><span class="header-section-number">8.4.4</span> The conclusion</h3>
<p>The difference of 29.2% is a rare event if there really is no effect of sex on promotion decisions. This provides us with two possible interpretations:</p>
<ul>
<li>If <span class="math inline">\(H_0\)</span> is true: Sex has no effect on promotion decisions, and we observed a difference that is so large it would only happen rarely by chance.</li>
<li>If <span class="math inline">\(H_A\)</span> is true: Sex has an effect on promotion decisions, and what we observed was actually due to equally qualified female candidates being discriminated against.</li>
</ul>
<p>When we conduct formal studies, we reject a null position if the data strongly conflict with it. Since there was only about a 2% probability of obtaining a difference at least as large as 29.2% under the null hypothesis, we conclude that the data provide strong evidence of sex discrimination. We reject the null hypothesis in favor of the alternative.</p>
<div class="statlens">
<p><strong>Predict → Do → Explain.</strong> Open the <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/?activity=randomization-test-gated.json" target="_blank">Randomization Test Walkthrough</a> — a gated activity that loads the sex-discrimination data and walks you through the permutation logic with a cards-shuffling mechanism strip alongside the resampled dotplot. The activity opens with a <strong>Predict</strong> step (commit to the center, shape, and where you expect the observed 0.292 to fall in the shuffle distribution), walks you through 1,000 shuffles with a reality-check gate at each stage, and closes with an <strong>Explain</strong> step where you articulate why the shuffle centers at zero and why the tail fraction <em>is</em> the p-value. Your predictions and explanation save locally in the tool, so you can return to your work on the same device.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Open sandbox</strong> (no scaffolding). Prefer to run the test yourself with your own data? Launch the <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/" target="_blank">Randomization Test: Difference in Proportions</a> directly, enter the sex-discrimination table (or your own), generate 1,000 shuffled differences, and read off the tail fraction as the p-value.</p>
</div>
</div>
</section>
</section>
<section id="sec-opportunity-cost" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-opportunity-cost"><span class="header-section-number">8.5</span> Case study: opportunity cost</h2>
<p>How rational and consistent is the behavior of the typical American college student? Here, we explore whether reminding students that money not spent now can be spent later causes them to be thriftier.</p>
<p>One hundred and fifty students were recruited for the study. All were given a scenario about purchasing a video on sale for $14.99. Half (the control group) were given these options:</p>
<blockquote class="blockquote">
<ol type="A">
<li>Buy this entertaining video.</li>
<li>Not buy this entertaining video.</li>
</ol>
</blockquote>
<p>The other half (the treatment group) saw a slightly modified option (B):</p>
<blockquote class="blockquote">
<ol type="A">
<li>Buy this entertaining video.</li>
<li>Not buy this entertaining video. Keep the $14.99 for other purchases.</li>
</ol>
</blockquote>
<p>The hypotheses are:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Reminding students that they can save money for later purchases will not have any impact on their spending decisions.</li>
<li><span class="math inline">\(H_A\)</span>: Reminding students that they can save money for later purchases will reduce the chance they will continue with a purchase.</li>
</ul>
<section id="observed-data-1" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="observed-data-1"><span class="header-section-number">8.5.1</span> Observed data</h3>
<p>The results are summarized below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Buy video</th>
<th style="text-align: center;">Not buy video</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">97</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">150</td>
</tr>
</tbody>
</table>
<p>We define a “success” as a student who chooses <em>not</em> to buy the video. The difference in the proportion choosing not to buy is:</p>
<p><span class="math display">\[\hat{p}_{T} - \hat{p}_{C} = \frac{34}{75} - \frac{19}{75} = 0.453 - 0.253 = 0.200\]</span></p>
<p>The proportion of students who chose not to buy was 20 percentage points higher in the treatment group. Is this 20% difference so prominent that it is unlikely to have occurred from chance alone?</p>
</section>
<section id="simulating-under-the-null" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="simulating-under-the-null"><span class="header-section-number">8.5.2</span> Simulating under the null</h3>
<p>Using the same randomization technique, we start with 150 index cards: 53 labeled “not buy video” and 97 labeled “buy video.” We shuffle all cards together and deal them into two stacks of 75.</p>
<div class="workedexample">
<p>If we randomly assign the cards into simulated treatment and control groups, how many “not buy video” cards would we expect in each group? What would be the expected difference in proportions?</p>
<hr>
<p>Since the groups are equal in size, we would expect about <span class="math inline">\(53/2 \approx 26\)</span> or 27 “not buy video” cards in each group, yielding a difference of roughly 0%. Due to random chance, we might sometimes observe a little more or fewer than 26–27.</p>
</div>
<p>After running 1,000 simulations, the results show that the distribution of simulated differences is centered at 0, as expected under the null hypothesis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-opportunity-cost-rand-dist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A histogram of 1000 simulated differences between the proportion of students choosing not to buy the video in the treatment and control groups. The distribution is centered at zero. A small number of simulations at or beyond 0.20 are highlighted in red.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-opportunity-cost-rand-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="randomization-tests_files/figure-html/fig-opportunity-cost-rand-dist-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;8.2: A histogram of 1,000 simulated differences produced under the null hypothesis. Differences at least as large as the observed 0.20 are highlighted in red. ↗ Try this live — run the randomization on your own data — vary reps and watch it settle."><img src="randomization-tests_files/figure-html/fig-opportunity-cost-rand-dist-1.png" class="img-fluid figure-img" alt="A histogram of 1000 simulated differences between the proportion of students choosing not to buy the video in the treatment and control groups. The distribution is centered at zero. A small number of simulations at or beyond 0.20 are highlighted in red." width="2100"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-opportunity-cost-rand-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: A histogram of 1,000 simulated differences produced under the null hypothesis. Differences at least as large as the observed 0.20 are highlighted in red. <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/">↗ Try this live</a> — run the randomization on your own data — vary reps and watch it settle.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Under the null hypothesis, we would observe a difference of at least +20% about 0.6% of the time. That is very rare! We conclude the data provide strong evidence there is a treatment effect: reminding students that they could spend money later lowers their chance of making a purchase. Because this is an experiment (with random assignment), we can make a causal claim.</p>
</section>
</section>
<section id="sec-p-values" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="sec-p-values"><span class="header-section-number">8.6</span> P-values</h2>
<p>The probability we computed in the previous sections — the chance of observing a result as extreme as or more extreme than the one actually observed, <em>if the null hypothesis were true</em> — has a name.</p>
<div class="definition">
<p>The <strong>p-value</strong> is the probability of observing data at least as favorable to the alternative hypothesis as our current dataset, if the null hypothesis were true. We typically use a summary statistic of the data, such as a difference in proportions, to compute the p-value. This summary value is called the <strong>test statistic</strong>.</p>
</div>
<div class="workedexample">
<p>In the sex discrimination study, the test statistic was the difference in promotion rates. What was the test statistic in the opportunity cost study?</p>
<hr>
<p>The test statistic in the opportunity cost study was the difference in the proportion of students who decided against the video purchase in the treatment and control groups: <span class="math inline">\(\hat{p}_T - \hat{p}_C = 0.200\)</span>.</p>
</div>
<div class="important">
<p><strong>Interpreting the p-value.</strong></p>
<ul>
<li>A <strong>small p-value</strong> (e.g., below 0.05) means that the observed result would be rare if the null hypothesis were true. This is evidence <em>against</em> the null hypothesis.</li>
<li>A <strong>large p-value</strong> (e.g., above 0.10) means that the observed result is not particularly unusual under the null hypothesis. The data do not provide strong evidence against the null hypothesis.</li>
<li>The p-value is <strong>not</strong> the probability that the null hypothesis is true. It is the probability of the observed data (or more extreme data) <em>given that</em> the null hypothesis is true.</li>
</ul>
</div>
<div class="caution">
<p>A common mistake is to interpret the p-value as the probability that the null hypothesis is true (e.g., “there is a 2% chance that sex has no effect on promotions”). This is incorrect. The p-value tells us how <em>surprising</em> the data would be <em>if</em> the null hypothesis were true, not how likely the null hypothesis is to be true.</p>
</div>
</section>
<section id="sec-statistical-significance" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sec-statistical-significance"><span class="header-section-number">8.7</span> Statistical discernibility</h2>
<div class="definition">
<p>We say that the data provide <strong>statistically discernible</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> evidence against the null hypothesis if the p-value is less than a predetermined threshold called the <strong>discernibility level</strong>, denoted <span class="math inline">\(\alpha\)</span> (the Greek letter alpha).</p>
</div>
<p>The most commonly used discernibility level is <span class="math inline">\(\alpha = 0.05\)</span>, meaning we reject the null hypothesis when the p-value is less than 5%. However, there is nothing magical about 0.05 — it is a convention, and in some fields or applications a stricter (e.g., 0.01) or more lenient (e.g., 0.10) threshold may be appropriate.</p>
<div class="workedexample">
<p>In the opportunity cost study, we found that a difference of at least 20% would occur only about 6-in-1,000 times if the reminder had no influence on student decisions. The p-value is approximately 0.006. Would you classify this as statistically discernible?</p>
<hr>
<p>Yes. Since <span class="math inline">\(p\text{-value} = 0.006 &lt; 0.05 = \alpha\)</span>, the data provide statistically discernible evidence that US college students were actually influenced by the reminder.</p>
</div>
<div class="important">
<p><strong>What “statistically discernible” does and does not mean.</strong></p>
<p>“Statistically discernible” means the p-value fell below the chosen discernibility level. It does <strong>not</strong> necessarily mean the effect is large or practically important. A very large sample can detect a tiny difference as “statistically discernible” even if the difference is too small to matter in practice.</p>
<p>Conversely, “not statistically discernible” does not mean there is no effect. It may simply mean the sample was too small to detect the effect.</p>
</div>
<section id="decision-framework" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="decision-framework"><span class="header-section-number">8.7.1</span> Decision framework</h3>
<p>The logic of hypothesis testing follows a consistent pattern:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">If the p-value is…</th>
<th style="text-align: left;">Then we…</th>
<th style="text-align: left;">Because…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Less than <span class="math inline">\(\alpha\)</span></td>
<td style="text-align: left;"><strong>Reject</strong> <span class="math inline">\(H_0\)</span></td>
<td style="text-align: left;">The data are unlikely under <span class="math inline">\(H_0\)</span>; evidence supports <span class="math inline">\(H_A\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Greater than or equal to <span class="math inline">\(\alpha\)</span></td>
<td style="text-align: left;"><strong>Fail to reject</strong> <span class="math inline">\(H_0\)</span></td>
<td style="text-align: left;">The data are not sufficiently unusual under <span class="math inline">\(H_0\)</span></td>
</tr>
</tbody>
</table>
<div class="guidedpractice">
<p>A researcher tests whether a new teaching method improves exam scores compared to the standard method. The p-value from the randomization test is 0.12. Using <span class="math inline">\(\alpha = 0.05\)</span>, what conclusion should the researcher draw?</p>
<details>
<summary>
Show answer
</summary>
Since <span class="math inline">\(p\text{-value} = 0.12 &gt; 0.05 = \alpha\)</span>, the researcher fails to reject the null hypothesis. The data do not provide sufficient evidence that the new teaching method improves exam scores. This does not mean the new method is ineffective — only that this study did not produce enough evidence to conclude it is effective.
</details>
</div>
</section>
</section>
<section id="sec-two-sided-tests" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="sec-two-sided-tests"><span class="header-section-number">8.8</span> Two-sided tests</h2>
<p>In the sex discrimination study, we looked for differences in <em>one direction only</em> — whether female candidates were promoted at a lower rate. This is called a <strong>one-sided</strong> (or one-tailed) test. The alternative hypothesis specified a direction:</p>
<p><span class="math display">\[H_A: p_M - p_F &gt; 0 \quad \text{(males promoted at a higher rate)}\]</span></p>
<p>Sometimes, however, we are interested in detecting a difference in <em>either direction</em>. For example, if we are studying whether a new drug changes blood pressure (it could increase it <em>or</em> decrease it), we would use a <strong>two-sided</strong> (or two-tailed) test:</p>
<p><span class="math display">\[H_A: p_1 \neq p_2 \quad \text{(the proportions are different, in either direction)}\]</span></p>
<div class="definition">
<p>In a <strong>one-sided test</strong>, the alternative hypothesis specifies a direction (greater than or less than). The p-value is computed as the proportion of the randomization distribution in one tail.</p>
<p>In a <strong>two-sided test</strong>, the alternative hypothesis does not specify a direction (just “different”). The p-value is computed as the proportion of the randomization distribution in <em>both</em> tails — values at least as extreme as the observed statistic in either direction.</p>
</div>
<div class="workedexample">
<p>Suppose we are testing whether a coin is fair. We flip it 100 times and get 60 heads.</p>
<ul>
<li><strong>One-sided</strong> (<span class="math inline">\(H_A: p &gt; 0.5\)</span>): The p-value counts only simulations with 60 or more heads.</li>
<li><strong>Two-sided</strong> (<span class="math inline">\(H_A: p \neq 0.5\)</span>): The p-value counts simulations with 60 or more heads <em>and</em> simulations with 40 or fewer heads (equally extreme in the other direction).</li>
</ul>
<hr>
<p>For a symmetric randomization distribution, the two-sided p-value is approximately twice the one-sided p-value. If the one-sided p-value is 0.03, the two-sided p-value is approximately 0.06.</p>
</div>
<div class="guidedpractice">
<p>A researcher wants to know if a new fertilizer changes plant growth compared to no fertilizer. Should this be a one-sided or two-sided test? Write the hypotheses using appropriate notation, where <span class="math inline">\(\mu_T\)</span> is the mean growth with fertilizer and <span class="math inline">\(\mu_C\)</span> is the mean growth without.</p>
<details>
<summary>
Show answer
</summary>
This should be a two-sided test because the fertilizer could either increase or decrease growth (perhaps it has a toxic effect in some soils). The hypotheses are: <span class="math inline">\(H_0: \mu_T - \mu_C = 0\)</span> (no difference in mean growth) and <span class="math inline">\(H_A: \mu_T - \mu_C \neq 0\)</span> (the fertilizer changes mean growth, in either direction).
</details>
</div>
<div class="important">
<p><strong>Choosing one-sided vs.&nbsp;two-sided.</strong></p>
<ul>
<li>Use a <strong>one-sided test</strong> when you have a specific directional hypothesis <em>before looking at the data</em>. For example, “we believe this drug <em>lowers</em> blood pressure.”</li>
<li>Use a <strong>two-sided test</strong> when you want to detect a difference in either direction, or when you are not sure which direction the difference might go.</li>
<li>When in doubt, use a two-sided test. It is the more conservative choice and is less susceptible to bias from choosing the direction after seeing the data.</li>
</ul>
</div>
</section>
<section id="sec-randomization-summary" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="sec-randomization-summary"><span class="header-section-number">8.9</span> The randomization test procedure: a summary</h2>
<p>We can summarize the randomization test procedure as follows:</p>
<ol type="1">
<li><p><strong>Frame the research question in terms of hypotheses.</strong> The null hypothesis (<span class="math inline">\(H_0\)</span>) usually represents no difference or no effect. The alternative hypothesis (<span class="math inline">\(H_A\)</span>) represents the claim of interest.</p></li>
<li><p><strong>Collect data.</strong> If the research question focuses on associations but not causation, use an observational study. If you want to establish a causal connection, use an experiment with random assignment.</p></li>
<li><p><strong>Model what would happen under the null hypothesis.</strong> Shuffle (randomize) the data to break any association between the explanatory and response variables. Compute the test statistic for each shuffle. Repeat many times to build the <strong>randomization distribution</strong> (also called the null distribution).</p></li>
<li><p><strong>Compute the p-value.</strong> Determine what proportion of the randomization distribution is at least as extreme as the observed test statistic.</p></li>
<li><p><strong>Draw a conclusion.</strong> If the p-value is small (less than <span class="math inline">\(\alpha\)</span>), reject <span class="math inline">\(H_0\)</span> and conclude there is evidence for <span class="math inline">\(H_A\)</span>. If the p-value is not small, fail to reject <span class="math inline">\(H_0\)</span>. Write the conclusion in context, in plain language.</p></li>
</ol>
<div class="statlens">
<p><strong>See it in action.</strong> Open the <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/" target="_blank">Randomization Test: Difference in Proportions</a> to run the full procedure on your own data — and watch how the p-value shifts when you change the sample size or the magnitude of the observed difference.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Testing a single proportion by simulation
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter focused on comparing two groups because that is the most common use of a randomization test. The same simulate-under-<span class="math inline">\(H_0\)</span> logic also works for a <em>single</em> sample against a claimed proportion — instead of shuffling group labels, you draw new samples from a modeled null population. That one-sample simulation test is developed in the <a href="../chapters/inference-proportions.html">inference for proportions chapter</a> (see the “Building the null distribution by simulation” section).</p>
</div>
</div>
</section>
<section id="sec-randomization-tests-review" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="sec-randomization-tests-review"><span class="header-section-number">8.10</span> Chapter review</h2>
<section id="summary" class="level3" data-number="8.10.1">
<h3 data-number="8.10.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.10.1</span> Summary</h3>
<ul>
<li>A <strong>hypothesis test</strong> evaluates two competing claims: the null hypothesis (<span class="math inline">\(H_0\)</span>), which represents no effect or no difference, and the alternative hypothesis (<span class="math inline">\(H_A\)</span>), which represents the claim under investigation.</li>
<li>A <strong>randomization test</strong> (or permutation test) assesses the null hypothesis by shuffling the data to simulate what would happen if there were truly no effect. The collection of simulated test statistics forms the <strong>randomization distribution</strong>.</li>
<li>The <strong>test statistic</strong> is the summary value computed from the data (e.g., a difference in proportions) that we use to evaluate the hypotheses.</li>
<li>The <strong>p-value</strong> is the probability of observing a test statistic at least as extreme as the one observed, assuming the null hypothesis is true. It quantifies the strength of the evidence against <span class="math inline">\(H_0\)</span>.</li>
<li>We reject <span class="math inline">\(H_0\)</span> when the p-value is less than the <strong>discernibility level</strong> <span class="math inline">\(\alpha\)</span> (commonly 0.05). This is called a <strong>statistically discernible</strong> result.</li>
<li>A <strong>one-sided test</strong> looks for effects in a specified direction; a <strong>two-sided test</strong> looks for effects in either direction.</li>
<li>Failing to reject <span class="math inline">\(H_0\)</span> is not the same as proving <span class="math inline">\(H_0\)</span> is true.</li>
<li>Statistical discernibility does not imply practical importance.</li>
</ul>
</section>
<section id="key-terms" class="level3" data-number="8.10.2">
<h3 data-number="8.10.2" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">8.10.2</span> Key terms</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hypothesis test</td>
<td style="text-align: left;">A formal procedure for evaluating competing claims using data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Null hypothesis (<span class="math inline">\(H_0\)</span>)</td>
<td style="text-align: left;">The claim of no effect or no difference; the skeptical position</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alternative hypothesis (<span class="math inline">\(H_A\)</span>)</td>
<td style="text-align: left;">The claim that there is an effect or difference</td>
</tr>
<tr class="even">
<td style="text-align: left;">Randomization test</td>
<td style="text-align: left;">A hypothesis test that builds a null distribution by shuffling data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Randomization distribution</td>
<td style="text-align: left;">The distribution of the test statistic under repeated randomizations</td>
</tr>
<tr class="even">
<td style="text-align: left;">Test statistic</td>
<td style="text-align: left;">The summary value (e.g., difference in proportions) used to evaluate hypotheses</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P-value</td>
<td style="text-align: left;">Probability of observing a result as extreme as or more extreme than the data, if <span class="math inline">\(H_0\)</span> is true</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discernibility level (<span class="math inline">\(\alpha\)</span>)</td>
<td style="text-align: left;">The threshold below which the p-value leads us to reject <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Statistically discernible</td>
<td style="text-align: left;">A result whose p-value falls below <span class="math inline">\(\alpha\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">One-sided test</td>
<td style="text-align: left;">Alternative hypothesis specifies a direction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Two-sided test</td>
<td style="text-align: left;">Alternative hypothesis does not specify a direction</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="exercises" class="level2 exercises" data-number="8.11">
<h2 class="exercises anchored" data-number="8.11" data-anchor-id="exercises"><span class="header-section-number">8.11</span> Exercises</h2>
<p>Answers to odd-numbered exercises are provided in the <a href="../appendices/exercise-solutions.html">Exercise Solutions appendix</a> at the back of the book.</p>
<!-- Generated by build_textbook_exercises.py — DO NOT EDIT -->
<!-- Sources: _11-ex-foundations-randomization -->
<ol type="1">
<li><strong>Hypotheses.</strong> For each of the research statements below, note whether it represents a null hypothesis claim or an alternative hypothesis claim.</li>
</ol>
<ol type="a">
<li><p>The number of hours that grade-school children spend doing homework predicts their future success on standardized tests.</p></li>
<li><p>King cheetahs on average run the same speed as standard spotted cheetahs.</p></li>
<li><p>For a particular student, the probability of correctly answering a 5-option multiple choice test is larger than 0.2 (i.e., better than guessing).</p></li>
<li><p>The mean length of African elephant tusks has changed over the last 100 years.</p></li>
<li><p>The risk of facial clefts is equal for babies born to mothers who take folic acid supplements compared with those from mothers who do not.</p></li>
<li><p>Caffeine intake during pregnancy affects mean birth weight.</p></li>
<li><p>The probability of getting in a car accident is the same if using a cell phone than if not using a cell phone.</p></li>
</ol>
<ol start="2" type="1">
<li><strong>True null hypothesis.</strong> Unbeknownst to you, let’s say that the null hypothesis is actually true in the population. You plan to run a study anyway.</li>
</ol>
<ol type="a">
<li><p>If the level of discernibility you choose (i.e., the cutoff for your p-value) is 0.05, how likely is it that you will mistakenly reject the null hypothesis?</p></li>
<li><p>If the level of discernibility you choose (i.e., the cutoff for your p-value) is 0.01, how likely is it that you will mistakenly reject the null hypothesis?</p></li>
<li><p>If the level of discernibility you choose (i.e., the cutoff for your p-value) is 0.10, how likely is it that you will mistakenly reject the null hypothesis? </p></li>
</ol>
<ol start="3" type="1">
<li><strong>Identify hypotheses, I.</strong> Write the null and alternative hypotheses in words and then symbols for each of the following situations.</li>
</ol>
<ol type="a">
<li><p>New York is known as “the city that never sleeps”. A random sample of 25 New Yorkers were asked how much sleep they get per night. Do these data provide convincing evidence that New Yorkers on average sleep less than 8 hours a night?</p></li>
<li><p>Employers at a firm are worried about the effect of March Madness, a basketball championship held each spring in the US, on employee productivity. They estimate that on a regular business day employees spend on average 15 minutes of company time checking personal email, making personal phone calls, etc. They also collect data on how much company time employees spend on such non- business activities during March Madness. They want to determine if these data provide convincing evidence that employee productivity decreases during March Madness. </p></li>
</ol>
<ol start="4" type="1">
<li><strong>Identify hypotheses, II.</strong> Write the null and alternative hypotheses in words and using symbols for each of the following situations.</li>
</ol>
<ol type="a">
<li><p>Since 2008, chain restaurants in California have been required to display calorie counts of each menu item. Prior to menus displaying calorie counts, the average calorie intake of diners at a restaurant was 1100 calories. After calorie counts started to be displayed on menus, a nutritionist collected data on the number of calories consumed at this restaurant from a random sample of diners. Do these data provide convincing evidence of a difference in the average calorie intake of a diners at this restaurant?</p></li>
<li><p>Based on the performance of those who took the GRE exam between July 1, 2004 and June 30, 2007, the average Verbal Reasoning score was calculated to be 462. In 2021 the average verbal score was slightly higher. Do these data provide convincing evidence that the average GRE Verbal Reasoning score has changed since 2021? </p></li>
</ol>
<ol start="5" type="1">
<li><strong>Side effects of Avandia.</strong> Rosiglitazone is the active ingredient in the controversial type&nbsp;2 diabetes medicine Avandia and has been linked to an increased risk of serious cardiovascular problems such as stroke, heart failure, and death. A common alternative treatment is Pioglitazone, the active ingredient in a diabetes medicine called Actos. In a nationwide retrospective observational study of 227,571 Medicare beneficiaries aged 65 years or older, it was found that 2,593 of the 67,593 patients using Rosiglitazone and 5,386 of the 159,978 using Pioglitazone had serious cardiovascular problems. These data are summarized in the contingency table below. <span class="citation" data-cites="Graham:2010">(<a href="#ref-Graham:2010" role="doc-biblioref">Graham et al. 2010</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Treatment</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Pioglitazone</td>
<td style="text-align: right; width: 7em;">154,592</td>
<td style="text-align: right; width: 7em;">5,386</td>
<td style="text-align: right; width: 7em;">159,978</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Rosiglitazone</td>
<td style="text-align: right; width: 7em;">65,000</td>
<td style="text-align: right; width: 7em;">2,593</td>
<td style="text-align: right; width: 7em;">67,593</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 7em;">219,592</td>
<td style="text-align: right; width: 7em;">7,979</td>
<td style="text-align: right; width: 7em;">227,571</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li><p>Determine if each of the following statements is true or false. If false, explain why. <em>Be careful:</em> The reasoning may be wrong even if the statement’s conclusion is correct. In such cases, the statement should be considered false.</p>
<ol type="i">
<li><p>Since more patients on Pioglitazone had cardiovascular problems (5,386 vs.&nbsp;2,593), we can conclude that the rate of cardiovascular problems for those on a Pioglitazone treatment is higher.</p></li>
<li><p>The data suggest that diabetic patients who are taking Rosiglitazone are more likely to have cardiovascular problems since the rate of incidence was (2,593 / 67,593 = 0.038) 3.8% for patients on this treatment, while it was only (5,386 / 159,978 = 0.034) 3.4% for patients on Pioglitazone.</p></li>
<li><p>The fact that the rate of incidence is higher for the Rosiglitazone group proves that Rosiglitazone causes serious cardiovascular problems.</p></li>
<li><p>Based on the information provided so far, we cannot tell if the difference between the rates of incidences is due to a relationship between the two variables or due to chance.</p></li>
</ol></li>
<li><p>What proportion of all patients had cardiovascular problems?</p></li>
<li><p>If the type of treatment and having cardiovascular problems were independent, how many patients in the Rosiglitazone group would we expect to have had cardiovascular problems?</p></li>
<li><p>We can investigate the relationship between outcome and treatment in this study using a randomization technique. While in reality we would carry out the simulations required for randomization using statistical software, suppose we actually simulate using index cards. In order to simulate from the independence model, which states that the outcomes were independent of the treatment, we write whether each patient had a cardiovascular problem on cards, shuffled all the cards together, then deal them into two groups of size 67,593 and 159,978. We repeat this simulation 100 times and each time record the difference between the proportions of cards that say “Yes” in the Rosiglitazone and Pioglitazone groups. Use the histogram of these differences in proportions to answer the following questions.</p>
<ol type="i">
<li><p>What are the claims being tested?</p></li>
<li><p>Compared to the number calculated in part (b), which would provide more support for the alternative hypothesis, <em>higher</em> or <em>lower</em> proportion of patients with cardiovascular problems in the Rosiglitazone group?</p></li>
<li><p>What do the simulation results suggest about the relationship between taking Rosiglitazone and having cardiovascular problems in diabetic patients?</p></li>
</ol></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="randomization-tests_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="randomization-tests_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol start="6" type="1">
<li><strong>Heart transplants.</strong> The Stanford University Heart Transplant Study was conducted to determine whether an experimental heart transplant program increased lifespan. Each patient entering the program was designated an official heart transplant candidate, meaning that they were gravely ill and would most likely benefit from a new heart. Some patients got a transplant and some did not. The variable <code>transplant</code> indicates which group the patients were in; patients in the treatment group got a transplant and those in the control group did not. Of the 34 patients in the control group, 30 died. Of the 69 people in the treatment group, 45 died. Another variable called <code>survived</code> was used to indicate whether the patient was alive at the end of the study. <span class="citation" data-cites="Turnbull+Brown+Hu:1974">(<a href="#ref-Turnbull+Brown+Hu:1974" role="doc-biblioref">Turnbull, Brown, and Hu 1974</a>)</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="randomization-tests_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="randomization-tests_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:70.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Does the stacked bar plot indicate that survival is independent of whether the patient got a transplant? Explain your reasoning.</p></li>
<li><p>What do the box plots suggest about the efficacy of heart transplants.</p></li>
<li><p>What proportions of patients in the treatment and control groups died?</p></li>
<li><p>One approach for investigating whether the treatment is discernably effective is randomization testing.</p>
<ol type="i">
<li><p>What are the claims being tested?</p></li>
<li><p>The paragraph below describes the set up for a randomization test, if we were to do it without using statistical software. Fill in the blanks with a number or phrase.</p></li>
</ol>
<blockquote class="blockquote">
<p>We write <em>alive</em> on <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span> cards representing patients who were alive at the end of the study, and <em>deceased</em> on <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span> cards representing patients who were not. Then, we shuffle these cards and split them into two groups: one group of size <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span> representing treatment, and another group of size <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span> representing control. We calculate the difference between the proportion of cards in the treatment and control groups (treatment - control) and record this value. We repeat this 100 times to build a distribution centered at <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span>. Lastly, we calculate the proportion of simulations where the simulated differences in proportions are <span class="math inline">\(\rule{1.25cm}{0.5pt}\)</span>. If this proportion is low, we conclude that it is unlikely to have observed such an outcome by chance and that the null hypothesis should be rejected in favor of the alternative.</p>
</blockquote>
<ol start="3" type="i">
<li>What do the simulation results shown below suggest about the effectiveness of heart transplants?</li>
</ol></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="randomization-tests_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="randomization-tests_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></a></p>
</figure>
</div>
</div>
</div>
<details class="dataset-sources">
<summary>
Dataset sources
</summary>
<small><a href="http://openintrostat.github.io/openintro/reference/avandia.html"><code>avandia</code></a> (openintro) | <a href="http://openintrostat.github.io/openintro/reference/heart_transplant.html"><code>heart_transplant</code></a> (openintro)</small>
</details>
<!-- StatLens Interactive Exercises — Randomization Tests -->
<!-- HAND-AUTHORED (not generated). Pedagogy: problem framing, choosing the -->
<!-- right procedure, checking conditions, and interpreting tool output —     -->
<!-- the reasoning a calculator can't do for you. Answers are reasoning-based -->
<!-- on purpose; the numbers come from StatLens.                              -->
<section id="statlens-exercises" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="statlens-exercises">StatLens Exercises</h3>
<p>These exercises focus on the parts of a randomization test a calculator <em>can’t</em> do for you: <strong>framing the question</strong>, <strong>picking the right shuffling scheme</strong>, <strong>reading the null distribution</strong>, and <strong>interpreting a p-value</strong> without falling into the standard traps. Let <a href="https://learnlens.org/statlens" target="_blank">StatLens</a> do the arithmetic.</p>
<ol type="1">
<li><p><strong>Frame the question.</strong> A trial randomly assigns 90 students to either an online tutoring program or a control group, then measures their final exam scores. The mean score in the tutoring group is 4.2 points higher than in the control group.</p>
<ol type="a">
<li>What is the parameter of interest? Describe it in words.</li>
<li>Write <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span> for testing whether tutoring <em>improves</em> exam scores. Is the test one-sided or two-sided, and why?</li>
<li>The randomization test will simulate the “no effect” world by <strong>shuffling group labels</strong> across students. <em>Why is shuffling labels the right way to simulate <span class="math inline">\(H_0\)</span> here, and what feature of the study design makes shuffling labels valid?</em></li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>The parameter is <span class="math inline">\(\mu_T - \mu_C\)</span>, the difference in <strong>population</strong> mean exam scores between students who would receive the tutoring program and those who would not. The observed 4.2-point difference is the sample estimate.</p></li>
<li><p><span class="math inline">\(H_0: \mu_T - \mu_C = 0\)</span> vs.&nbsp;<span class="math inline">\(H_A: \mu_T - \mu_C &gt; 0\)</span> — <strong>one-sided</strong>, because the question is whether tutoring <em>improves</em> scores (a directional claim stated in advance).</p></li>
<li><p>Under <span class="math inline">\(H_0\)</span> (“tutoring does nothing”) every student’s exam score would be the same regardless of group label. So the group labels are interchangeable: a student who scored 87 in the tutoring group would have scored 87 in the control group anyway. Shuffling labels generates new datasets that are consistent with this “exchangeable” world. <strong>Random assignment</strong> is what makes this valid — the students were assigned to groups by a coin flip, not self-selected, so under <span class="math inline">\(H_0\)</span> the labels really are arbitrary.</p></li>
</ol>
</details></li>
<li><p><strong>Choose the procedure.</strong> For each scenario, name the randomization shuffle you would use — <strong>shuffle group labels</strong> (independent groups), <strong>shuffle paired-difference signs</strong> (paired data), <strong>shuffle the values of one variable</strong> (correlation/independence), or <strong>a Bernoulli null simulation</strong> (one proportion vs.&nbsp;a fixed value).</p>
<ol type="a">
<li>Did a coin biased toward heads come up “heads” more than 50% of the time in 100 tosses?</li>
<li>Are male and female job applicants offered different mean starting salaries?</li>
<li>Do students score higher on a test taken <strong>after</strong> a study skills workshop compared to <strong>before</strong>?</li>
<li>Is hours of TV per week associated with hours of sleep per night?</li>
<li>Do four different fertilizer brands produce different mean yields?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><strong>Bernoulli null simulation</strong> — simulate 100 coin flips with <span class="math inline">\(p = 0.5\)</span> many times and ask how often you get the observed count or more. b. <strong>Shuffle group labels</strong> (sex) — a two-group independent-samples randomization test for means. c.&nbsp;<strong>Shuffle paired-difference signs</strong> — for each student you have a “before” and “after”; randomly flipping the sign of each within-student difference simulates the world where the workshop did nothing. d.&nbsp;<strong>Shuffle the values of one variable</strong> — e.g., shuffle the sleep values to break the pairing with TV hours; this generates a null distribution of the correlation under “no association.” e. <strong>Shuffle group labels</strong> with <strong>four</strong> groups; the test statistic is the <span class="math inline">\(F\)</span> statistic (one-way ANOVA on the shuffled labels), not a difference of two means.</li>
</ol>
</details></li>
<li><p><strong>Read the null distribution.</strong> Open the <a href="https://learnlens.org/statlens/simulate/randomization-diff-props/?activity=randomization-test-gated.json" target="_blank">Randomization Test — Difference in Proportions</a> (the gated sex-discrimination walkthrough). Step through it until you have the null distribution of 1000 shuffled differences in front of you.</p>
<ol type="a">
<li>Where is the null distribution centered? Why does it have to be centered there, by construction?</li>
<li>The observed sample difference is marked on the dotplot. Roughly what proportion of the <em>shuffled</em> differences are at least as extreme as the observed one (one-sided)? That proportion <em>is</em> the p-value.</li>
<li>Suppose the observed difference had landed <em>near</em> the middle of the null distribution instead. What would the p-value be approximately, and what would you conclude?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>The null distribution is centered at <strong>0</strong> (the value <span class="math inline">\(H_0\)</span> asserts). It has to be, because the shuffling procedure breaks any real association between group label and outcome — on average, shuffled differences cancel out.</p></li>
<li><p>The p-value is (number of shuffles at least as extreme as the observed difference) / 1000. The activity reports it directly; for the sex-discrimination data it is around 0.02–0.03 one-sided. A small p-value means the observed result is rare under “no effect.”</p></li>
<li><p>The p-value would be near 0.5 (most shuffles would be at least as far from center as the observed value, when “the observed value” sits in the middle of the distribution). Conclusion: no evidence against <span class="math inline">\(H_0\)</span> — the observed difference is exactly the kind of fluctuation we expect under chance alone.</p></li>
</ol>
</details></li>
<li><p><strong>Run it and interpret it (means).</strong> Open the <a href="https://learnlens.org/statlens/simulate/randomization-diff-means/" target="_blank">Randomization Test for Difference in Means</a> with any two-group numeric dataset.</p>
<ol type="a">
<li><p>Run 1000 shuffles and read off the p-value. State your decision at <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p>Write a one-sentence conclusion <strong>in context</strong>.</p></li>
<li><p>Re-run the test with only 100 shuffles, then with 10000 shuffles. How does the p-value change? Why do we usually report a number that comes from “more shuffles, not fewer”?</p></li>
<li><p>Which statement is the correct interpretation of a p-value of 0.03?</p>
<ol type="i">
<li>There is a 3% probability that the null hypothesis is true.</li>
<li>If the two groups really had the same mean, we would see a difference at least as extreme as ours in about 3% of randomly assigned studies.</li>
<li>The probability that the alternative hypothesis is true is 0.97.</li>
</ol></li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>&amp; b. Read what StatLens reports; the in-context conclusion should name the groups and the strength of evidence (“strong evidence that the mean [response] in group A differs from group B,” etc.).</p></li>
<li><p>With more shuffles the p-value stabilizes (the Monte Carlo error shrinks like <span class="math inline">\(1/\sqrt{N}\)</span>). With only 100 shuffles the p-value can wobble by several percentage points between runs; with 10000 it is reliable to two decimal places. We want a number that does not depend on the random seed.</p></li>
<li><p><strong>(ii).</strong> The p-value is the probability of the <em>data</em> (or something more extreme) <em>given</em> <span class="math inline">\(H_0\)</span> — not the probability of <span class="math inline">\(H_0\)</span> given the data. Statements (i) and (iii) would require a prior probability for the hypotheses, which the test does not give us.</p></li>
</ol>
</details></li>
<li><p><strong>Simulation as a sanity check on the normal approximation.</strong> A textbook says: “When the sample sizes are large and the data are not too skewed, the randomization distribution of <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span> is approximately normal.” You will check this by eye.</p>
<ol type="a">
<li>Open any moderate-<span class="math inline">\(n\)</span> two-group numeric dataset in the <a href="https://learnlens.org/statlens/simulate/randomization-diff-means/" target="_blank">randomization test tool</a> and run 5000 shuffles. Describe the <strong>shape</strong>, <strong>center</strong>, and <strong>spread</strong> of the resulting null distribution.</li>
<li>Why does the <em>spread</em> of the null distribution tell you the <em>standard error</em> of <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span> — and why does that mean a randomization test essentially “discovers” the same SE the <span class="math inline">\(t\)</span>-formula computes from <span class="math inline">\(s_1\)</span>, <span class="math inline">\(s_2\)</span>, <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span>?</li>
<li>Now try the same on a <em>small</em>, skewed dataset (say <span class="math inline">\(n_1 = n_2 = 6\)</span>, with one outlier). Is the null distribution still approximately normal? If you ran a two-sample <span class="math inline">\(t\)</span>-test on this same data, would the <span class="math inline">\(t\)</span> distribution be a good match for the randomization distribution? Where would they disagree?</li>
<li>A student claims that the randomization test “only works for large samples.” Why is this exactly backwards — which test works <em>better</em> in small samples, the <span class="math inline">\(t\)</span>-test or the randomization test, and why?</li>
</ol>
<details>
<summary>
<p>Show answer</p>
</summary>
<ol type="a">
<li><p>The null distribution is roughly <strong>bell-shaped</strong> (with enough shuffles), <strong>centered at 0</strong> (by construction), and the <strong>spread</strong> matches the standard error of the difference.</p></li>
<li><p>The standard deviation of the null distribution <em>is</em> the simulated standard error of <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>. The formula <span class="math inline">\(\text{SE}(\bar{x}_1 - \bar{x}_2) = \sqrt{s_1^2/n_1 + s_2^2/n_2}\)</span> is an analytical <em>estimate</em> of the same quantity, derived under independence and large-sample assumptions. When both work, they should agree.</p></li>
<li><p>With small <span class="math inline">\(n\)</span> and an outlier, the null distribution is <strong>discrete</strong> (only a finite number of label permutations exist), often visibly <strong>non-normal</strong> in the tails, and may show “spikes” or “gaps.” The <span class="math inline">\(t\)</span> distribution is a smooth approximation that may underestimate or overestimate the tail probability, depending on where the outlier ends up under the permutations. The two p-values can differ substantially.</p></li>
<li><p>The randomization test makes no normality assumption — it just enumerates the label-shuffling distribution that <em>actually applies</em> under random assignment. It works best in <strong>small</strong> samples because the <span class="math inline">\(t\)</span>-distribution approximation is <em>worst</em> there. The <span class="math inline">\(t\)</span>-test relies on the CLT to make <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span> approximately normal; the randomization test does not need the CLT at all. So if anything, the rule should be: “use the randomization test in small samples <em>because</em> the <span class="math inline">\(t\)</span>-test’s assumptions are most likely to fail there.”</p></li>
</ol>
</details></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Graham:2010" class="csl-entry" role="listitem">
Graham, D. J., R. Ouellet-Hellstrom, T. E. MaCurdy, F. Ali, C. Sholley, C. Worrall, and J. A. Kelman. 2010. <span>“Risk of Acute Myocardial Infarction, Stroke, Heart Failure, and Death in Elderly Medicare Patients Treated with Rosiglitazone or Pioglitazone.”</span> <em>JAMA</em> 304 (4): 411. <a href="https://doi.org/10.1001/jama.2010.920">https://doi.org/10.1001/jama.2010.920</a>.
</div>
<div id="ref-Turnbull+Brown+Hu:1974" class="csl-entry" role="listitem">
Turnbull, B., B. Brown, and M. Hu. 1974. <span>“Survivorship of Heart Transplant Data.”</span> <em>Journal of the American Statistical Association</em> 69: 74–80. <a href="https://doi.org/10.1080/01621459.1974.10480130">https://doi.org/10.1080/01621459.1974.10480130</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Traditionally this result has been called <em>statistically significant</em>, and the threshold <span class="math inline">\(\alpha\)</span> the <em>significance level</em> — terms you will still see in most other books. Because <em>significant</em> in everyday English suggests <em>large</em> or <em>important</em>, which a small but genuinely detectable effect may not be, we follow <em>Introduction to Modern Statistics</em> and instead call the result <strong>statistically discernible</strong> and the threshold the <strong>discernibility level</strong>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/sampling-variability.html" class="pagination-link" aria-label="Sampling Variability">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/decision-errors.html" class="pagination-link" aria-label="Decision Errors">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Decision Errors</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to Statistics: A Simulation-First Approach</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>